import type { AddressFormLabels } from '@lfd/b2b-ui/address';
import type { AccountCopy } from './account.copy';

const ADDRESS_FORM: AddressFormLabels = {
  label: 'Address name',
  labelHint: 'e.g. Head office, Bastille shop',
  line1: 'Address',
  line1Placeholder: 'number and street',
  line2: 'Address line 2',
  line2Hint: 'building, floor, door code…',
  postalCode: 'Postcode',
  city: 'City',
  country: 'Country',
  countryPlaceholder: 'Choose a country…',
  optional: 'optional',
  noteLabel: 'Access instructions',
  notePlaceholder: 'Door code, floor, where to leave it…',
  coordinatesLabel: 'GPS point',
  coordinatesHint: 'for places an address is not enough to find',
  entryModeAria: 'How to enter the point',
  entryModePair: 'Two fields',
  entryModePasted: 'Pasted point',
  latitude: 'Latitude',
  latitudePlaceholder: '48.8566',
  longitude: 'Longitude',
  longitudePlaceholder: '2.3522',
  point: 'Point',
  pointHint: 'paste “48.8566, 2.3522” from a map',
  pointPlaceholder: '48.8566, 2.3522',
};

export const ACCOUNT_EN: AccountCopy = {
  title: 'My account',
  lead: 'Your file as we keep it: identity, access, paperwork, addresses, payment terms.',
  states: {
    incomplete: 'File to complete',
    pending: 'File in progress',
    active: 'Account active',
    suspended: 'Account suspended',
    terminated: 'Account closed',
  },
  loadFailedTitle: 'Your account could not be loaded',
  loadFailedBody: 'The service is not responding right now. Please try again in a moment.',
  loadRetry: 'Try again',
  loading: 'Loading your account…',
  signedOutTitle: 'Sign in to see your account',
  signedOutBody: 'Your file, access and paperwork are waiting for you here.',
  signIn: 'Sign in',
  cardKicker: 'Trade account',
  cardReference: 'My customer reference: {ref}',
  panelDot: 'Go to section {n}',
  cardPaymentHead: 'Payment methods',
  cardPaymentOnOrder: 'On order',
  cardPaymentOnAccount: 'On account / periodic',
  cardPaymentPending: 'Waiting for your details',
  cardUnknown: 'Account not recognised',
  cardUnknownNote: 'Sign in to find your company.',
  identityUnknown: '—',
  summaryHead: 'The file',
  edit: 'Edit',
  details: 'See details',
  save: 'Save',
  cancel: 'Cancel',
  sections: {
    identity: 'Legal identity',
    users: 'Users',
    kbis: 'Registry extract',
    addresses: 'Addresses',
    bank: 'Bank details',
    mandate: 'SEPA mandate',
    payment: 'Payment',
    preferences: 'Preferences',
    data: 'My data',
  },
  identityBrand: 'Trading name',
  identityCompany: 'Registered name',
  identityForm: 'Legal form',
  identitySiret: 'SIRET',
  identitySiren: 'SIREN',
  identityVat: 'VAT number',
  identityNote:
    'The trading name changes here. Registry details go through us: we check, then we update — these are the mentions that appear on your invoices.',
  identityPanelSubtitle: 'Trading name and VAT change here; registry details are filled in once.',
  identityVatField: 'Intra-EU VAT number',
  identityLegalHint:
    'Fill in once: after saving, this detail can only be corrected through our sales team.',
  identityFormPlaceholder: 'Choose',
  identityVatRequiredHint: 'Required for this legal form.',
  identityVatOptionalHint: 'Optional for this legal form — VAT franchise.',
  identityVatUndecidedHint: 'Required or not depending on the legal form.',
  identityOptional: 'optional',
  identityLegalLocked:
    'These details come from the company registry. To correct them, contact our sales team.',
  identitySaveFailed: 'Your identity was not saved.',
  railPosition: 'Section {n} of {total}',
  usersHolder: 'Account holder · you',
  usersAllRights: 'All rights',
  usersNote:
    'A contact can exist without a workspace: a name and an e-mail are enough to receive the invoices. The invitation is decided case by case.',
  usersAdd: 'Add a user or a contact',
  usersAddShort: 'Add a user',
  usersAddSubtitle: 'Their details, and what they do for the company.',
  usersAddFailed: 'The contact was not added.',
  tagContact: 'Contact only',
  contactFields: {
    email: 'Email',
    emailHint: 'this is where an access would be sent',
    role: 'Role in the company',
    rolePlaceholder: 'Choose',
    roles: { admin: 'Administrator', orders: 'Orders', billing: 'Billing' },
    firstName: 'First name',
    lastName: 'Last name',
    fonction: 'Job title',
    fonctionPlaceholder: 'e.g. Purchasing manager',
    phone: 'Phone',
  },
  contactEditHolderTitle: 'Edit the holder',
  contactEditTitle: 'Edit the contact',
  contactEditHolderSubtitle:
    'The holder’s details on the company record. They do not change their sign-in address: that one is changed under “My details”.',
  contactEditSubtitle: 'Their details, and what they do for the company.',
  contactEditFailed: 'The contact was not saved.',
  contactRemove: 'Delete',
  contactRemoveMessage: 'This contact will be removed from the company.',
  contactRemoveConfirm: 'Yes, delete',
  contactRemoveBusy: 'Deleting…',
  contactRemoveGroup: 'Confirm deleting the contact',
  contactRemoveFailed: 'The contact was not deleted.',
  dangerZone: 'Danger zone',
  profileFirstName: 'First name',
  profileLastName: 'Last name',
  profileEmail: 'E-mail',
  profilePanelSubtitle: 'Your personal details, seen only by us.',
  profileEmailHint: 'Also used to sign in.',
  profileEmailChange:
    'Once saved, this address becomes your sign-in identifier. A verification e-mail is sent to it: open it to confirm.',
  profileSaveFailed: 'Your details were not saved.',
  kbisHead: 'The registry extract',
  kbisCertified: 'Certified',
  kbisPending: 'Awaiting verification',
  kbisNone: 'No extract on file',
  kbisUpload: 'Upload the KBIS',
  kbisFiled: 'Filed on {date}',
  kbisOpen: 'Open',
  kbisReplace: 'Replace',
  kbisView: 'View the KBIS',
  kbisDownload: 'Download',
  kbisDrop: 'Upload',
  kbisHint: 'PDF, 10 MB maximum',
  kbisUploading: 'Uploading the KBIS…',
  kbisSaveFailed: 'The KBIS was not uploaded.',
  kbisFetchFailed: 'The KBIS could not be retrieved. Please try again.',
  billingHead: 'Billing',
  billingNote:
    'One billing address only: it is the one on your invoices and on the direct-debit mandate.',
  deliveryHead: 'Delivery',
  deliveryCount: '{n} addresses',
  deliveryCountOne: '{n} address',
  addressNoZone: 'outside our zones',
  addressNone: 'No address on file.',
  addressDefault: 'Default',
  addressAdd: 'Add a delivery address',
  billingFill: 'Fill in the billing address',
  billingEdit: 'Edit the billing address',
  addressEdit: 'Edit the delivery address',
  addressSaveFailed: 'The address was not saved.',
  addressSavedToast: 'Address saved.',
  addressRemove: 'Remove',
  addressRemoveMessage: 'Remove this address from the book? Orders already placed keep theirs.',
  addressRemoveConfirm: 'Remove the address',
  addressRemoveBusy: 'Removing…',
  addressRemoveGroup: 'Confirm removing the address',
  addressRemovedToast: 'Address removed.',
  addressActionFailed: 'The address book was not changed.',
  deliveryDialogSubtitle: 'A full postal address, and how we deliver there.',
  deliveryAddSubmit: 'Add',
  addressForm: ADDRESS_FORM,
  deliveryForm: {
    defaultLabel: 'Default delivery address',
    defaultHint: 'used automatically for your next orders',
    legend: 'Postal address',
    address: {
      ...ADDRESS_FORM,
      labelHint: 'e.g. Chalet, Mountain restaurant',
      line2Hint: 'building, floor, delivery instructions…',
      noteLabel: 'Note for the drivers',
      notePlaceholder: 'Access code, floor, on-site contact, drop-off instructions…',
      coordinatesLabel: 'GPS point',
      coordinatesHint: 'for places that are hard to find',
    },
    specs: {
      detailLegend: 'Delivery details',
      slotsLegend: 'Preferred time slots',
      sameEveryDay: 'Same time slot every day',
      sameEveryDayHint: 'untick to set a time slot per day',
      everyDay: 'Every day',
      weekdays: {
        mon: 'Monday',
        tue: 'Tuesday',
        wed: 'Wednesday',
        thu: 'Thursday',
        fri: 'Friday',
        sat: 'Saturday',
        sun: 'Sunday',
      },
      slotStart: 'Start',
      slotEnd: 'End',
      contactLegend: 'On-site contact',
      noContact: 'No dedicated delivery contact',
      noContactHint: 'tick if the driver has nobody to call on site',
      knownContact: 'Use a known contact',
      knownContactPlaceholder: 'Choose a contact…',
      firstName: 'First name',
      lastName: 'Last name',
      phone: 'Phone',
      contactIncomplete: 'Enter first name, last name and phone, or tick “no contact”.',
      signature: 'Signature on delivery',
      signatureHint: 'prefills orders delivered here; can be changed in the cart',
      signatureInherit: 'Same as the company ({floor})',
      signatureFloorRequired: 'required',
      signatureFloorNotRequired: 'not required',
      signatureRequired: 'Required',
      signatureNotRequired: 'Not required',
      signatureNoContactHint: 'with nobody on site, nobody can sign on delivery',
    },
  },
  termMonthly: '30 days end of month',
  termGrantedSub: 'Granted by your sales contact: your orders are settled at month end.',
  termRequestedSub: 'Request sent: your sales contact will approve it.',
  termNoneSub: 'On request: your sales contact grants it company by company.',
  termOrder: 'At checkout',
  termOrderSub: 'Card or Apple Pay, without waiting for the invoice',
  stateActive: 'Active',
  stateAvailable: 'Available',
  stateRequested: 'Pending',
  paymentNote:
    'Two regimes, no more: end of month when credit is granted, at checkout otherwise — and everyone can order at checkout.',
  termRequest: 'Request monthly payment',
  termRequestNote: 'This is a request: nothing changes until your sales contact approves it.',
  termRequestFailed: 'The request was not saved.',
  prefPickup: 'Usual pickup',
  prefNone: 'Nothing set — we ask on each order.',
  prefPickupAt: 'Collection at',
  prefPickupAny: 'Collection',
  prefDeliveryTo: 'Delivery to',
  prefDeliveryAny: 'Delivery',
  stateUnavailable: 'Not granted',
  prefLang: 'Language',
  prefNote: 'A dated operation warns once a season. Deliveries and invoices are on by default.',
  prefMethod: 'Usual mode',
  prefMethodNone: 'None — choose on each order',
  prefMethodPickup: 'Collection',
  prefMethodDelivery: 'Delivery',
  prefPickupPoint: 'Collection point',
  prefPickupDefault: 'The default point',
  prefDeliveryAddress: 'Delivery address',
  prefDeliveryDefault: 'The company’s default address',
  prefDefaultTag: 'default',
  prefSaveFailed: 'The preference was not saved.',
  prefLangNote: 'The language changes right away, nothing to save.',
  dataExportOrders: 'Export my orders and my invoices',
  dataExportOrdersSub: 'CSV and PDF, by financial year',
  dataExportPersonal: 'Download my personal data',
  dataExportPersonalSub: 'Everything we hold, in one file',
  dataSummary: 'Retention, transfer and closing of the workspace',
  dataKeep:
    'Your invoices stay available for ten years after closing — that is an obligation, not a choice.',
  dangerHead: 'Sensitive area',
  transferHead: 'Transfer the company',
  transferBody:
    'You hand the holder role to a user of the workspace. They take over billing, payment terms and the right to invite. You keep your access, without administration.',
  transferCta: 'Transfer the account',
  closeHead: 'Close this workspace',
  closeBody:
    'Final, and specific to this workspace: access revoked for you and your users, discount and payment terms lost, recurring baskets deleted. Your other workspaces do not move. A live order must be collected or cancelled first.',
  closeCta: 'Close this workspace',
  panelPhone: 'Phone',
  bankLoading: 'Reading your bank details…',
  bankLoadFailedTitle: 'Your bank details could not be read',
  bankLoadFailedBody: 'The service is not responding right now. Try again in a moment.',
  bankNone: 'No bank details on file',
  bankRegistered: 'Bank details on file',
  bankLast4: '•••• {last4}',
  bankNotice:
    'The account holder and address are the ones your bank knows: they may differ from your registered company name. If a direct debit runs on this account, replacing it stops the debit: we will get back to you on what comes next.',
  bankForm: {
    holder: 'Account holder',
    holderLegalForm: 'Title (Mr, Ms) or legal form (SAS, SARL…)',
    holderLegalFormHint:
      'Required by the business-to-business mandate, whether the holder is a company or a person — 40 characters at most.',
    line1: 'Address',
    line2: 'Address line 2',
    postalCode: 'Postcode',
    city: 'City',
    country: 'Country',
    iban: 'IBAN',
    ibanHint: 'Entered once. It will never be shown again.',
    bic: 'BIC',
  },
  bankSave: 'Save bank details',
  bankReplace: 'Replace bank details',
  bankSavedToast: 'Bank details saved.',
  bankSaveFailed: 'Your bank details were not saved.',
  mandateLoading: 'Reading your mandate…',
  mandateLoadFailedTitle: 'Your mandate could not be read',
  mandateLoadFailedBody: 'The service is not responding right now. Try again in a moment.',
  mandateNone: 'No mandate in progress',
  mandateAwaiting: 'Send back the mandate, dated and signed',
  mandateInReview: 'Mandate received — being checked',
  mandateActive: 'Mandate active',
  mandateReference: 'UMR · {reference}',
  mandateSignedOn: 'Signed on {date}',
  mandateProofFile: 'File on record: {fileName}',
  mandateGenerate: 'Generate my mandate',
  mandateSend: 'Send back the signed mandate',
  mandateView: 'View the mandate',
  mandateDownload: 'Download the mandate',
  mandateNoneBody: {
    CORE: 'The SEPA direct debit mandate authorises us to debit your invoices from the account in your bank details. Generate it: you can then print it, date it, sign it and send it back here.',
    B2B: 'The SEPA business-to-business direct debit mandate authorises us to debit your invoices from the account in your bank details. Generate it: you can then print it, date it, sign it and send it back here.',
  },
  mandateAwaitingBody: {
    CORE: 'Print the mandate, date and sign it, then upload a scan or photo here.',
    B2B: 'Print the mandate, date and sign it, then upload a scan or photo here. Also register it with your bank: a business-to-business direct debit is only accepted once your bank has the mandate on record.',
  },
  mandateInReviewBody:
    'We are checking the signed mandate: it becomes active once our team has reviewed it. You can still replace the uploaded file.',
  mandateActiveBody:
    'Your direct debits rely on this mandate. To change bank account, contact the sales team.',
  mandateDrop: 'Upload the signed mandate',
  mandateDropReplace: 'Replace the uploaded file',
  mandateDropHint: 'PDF or photo (JPEG, PNG, HEIC), 10 MB max.',
  mandateUploading: 'Uploading the mandate…',
  mandateUploadedToast: 'Signed mandate received.',
  mandateBlockedLead: 'To generate your mandate, we still need:',
  mandateBlockers: {
    bank_account_missing: 'your bank details',
    issuer_missing: 'our creditor details — we are taking care of it',
    company_name_missing: 'your company’s registered name',
    siren_missing: 'your company’s SIREN number',
    holder_legal_form_missing: 'the account holder’s title or legal form',
  },
  mandateBlockersIdentity: 'Complete legal identity',
  mandateBlockersBank: 'Complete bank details',
  mandateGenerateFailed: 'The mandate was not generated.',
  mandateUploadFailed: 'The signed mandate was not uploaded.',
  mandateFetchFailed: 'The mandate could not be opened. Try again in a moment.',
  mandateEsign: 'Use electronic signature',
  mandateEsignSoon: 'Coming soon',
  mandateOptions: 'Mandate options',
  mandateOptionsSubtitle: 'Debtor code and contract number',
  mandateOptionsNotice:
    'Both fields are optional: neither affects the validity of the mandate, and leaving them empty is perfectly normal.',
  mandateOptionsDraftWarning:
    'Changing these fields cancels the mandate awaiting signature: you will need to generate it again.',
  mandateOptionsForm: {
    debtorReference: 'Debtor identification code',
    debtorReferenceHint: 'The reference you want to see on your bank statements.',
    contractNumber: 'Contract number',
    contractNumberHint: 'Optional.',
  },
  mandateOptionsLoading: 'Reading the mandate options…',
  mandateOptionsLoadFailedTitle: 'The mandate options could not be read',
  mandateOptionsNoBank: 'Save your bank details first: these fields belong to them.',
  mandateOptionsSave: 'Save the options',
  mandateOptionsSavedToast: 'Mandate options saved.',
  mandateOptionsSaveFailed: 'The mandate options were not saved.',
  completion: {
    countOne: '1 item to complete',
    count: '{n} items to complete',
    blocksActivation: 'Prevents activation: {detail}',
    optionalNote: 'does not prevent activation',
    cardLead: 'To complete:',
    mandateFields: 'To generate your SEPA mandate: {fields}.',
    items: {
      identity: {
        title: 'Legal identity',
        detail: 'The company name, legal form or SIRET is missing.',
        action: 'Complete the identity',
      },
      vat: {
        title: 'VAT number',
        detail: 'Your intra-community VAT number is required.',
        action: 'Enter the VAT number',
      },
      telephone: {
        title: 'Phone number',
        detail: 'A driver must be able to call: enter a phone number, yours or a contact’s.',
        action: 'Add a number',
      },
      billing: {
        title: 'Billing address',
        detail: 'Your invoices need an address.',
        action: 'Add the billing address',
      },
      delivery: {
        title: 'Delivery address',
        detail: 'You prefer delivery: add at least one delivery address.',
        action: 'Add a delivery address',
      },
      kbis: {
        title: 'KBIS extract',
        detail: 'Upload your company’s KBIS extract.',
        action: 'Upload the KBIS',
      },
      bank: {
        title: 'Bank details',
        detail: 'Your bank details are incomplete.',
        action: 'Complete the bank details',
      },
    },
  },
  supportTitle: 'Contact our sales team',
  supportPanelTitle: 'Sales team',
  supportBody: 'A question about your account, an order or an invoice: we will get back to you.',
};
