import type { AddressFormLabels } from '@lfd/b2b-ui/address';
import type { AccountCopy } from './account.copy';

const ADDRESS_FORM: AddressFormLabels = {
  label: "Nome dell'indirizzo",
  labelHint: 'es. Sede, Negozio Bastille',
  line1: 'Indirizzo',
  line1Placeholder: 'numero e via',
  line2: 'Complemento',
  line2Hint: 'edificio, piano, citofono…',
  postalCode: 'CAP',
  city: 'Città',
  country: 'Paese',
  countryPlaceholder: 'Scegli un paese…',
  optional: 'facoltativo',
  noteLabel: 'Istruzioni di accesso',
  notePlaceholder: 'Citofono, piano, dove lasciare…',
  coordinatesLabel: 'Punto GPS',
  coordinatesHint: 'per i luoghi che un indirizzo non basta a trovare',
  entryModeAria: 'Modalità di inserimento del punto',
  entryModePair: 'Due campi',
  entryModePasted: 'Punto incollato',
  latitude: 'Latitudine',
  latitudePlaceholder: '48.8566',
  longitude: 'Longitudine',
  longitudePlaceholder: '2.3522',
  point: 'Punto',
  pointHint: 'incollate «48.8566, 2.3522» da una mappa',
  pointPlaceholder: '48.8566, 2.3522',
};

export const ACCOUNT_IT: AccountCopy = {
  title: 'Il mio account',
  lead: 'Il vostro fascicolo così come lo teniamo: identità, accessi, documenti, indirizzi, condizioni di pagamento.',
  states: {
    incomplete: 'Fascicolo da completare',
    pending: 'Fascicolo in corso',
    active: 'Account attivo',
    suspended: 'Account sospeso',
    terminated: 'Account chiuso',
  },
  loadFailedTitle: 'Non è stato possibile leggere il suo account',
  loadFailedBody: 'Il servizio non risponde al momento. Riprovi tra un istante.',
  loadRetry: 'Riprova',
  loading: 'Lettura del suo account…',
  signedOutTitle: 'Acceda per vedere il suo account',
  signedOutBody: 'Il suo fascicolo, gli accessi e i documenti la aspettano qui.',
  signIn: 'Accedi',
  cardKicker: 'Account professionale',
  cardReference: 'Il mio codice cliente: {ref}',
  panelDot: 'Vai alla sezione {n}',
  cardPaymentHead: 'Modalità di pagamento',
  cardPaymentOnOrder: 'All’ordine',
  cardPaymentOnAccount: 'Su conto / periodico',
  cardPaymentPending: 'In attesa dei tuoi dati',
  cardUnknown: 'Account non riconosciuto',
  cardUnknownNote: 'Acceda per ritrovare la sua azienda.',
  identityUnknown: '—',
  summaryHead: 'Il fascicolo',
  edit: 'Modificare',
  details: 'Vedere il dettaglio',
  save: 'Registra',
  cancel: 'Annulla',
  sections: {
    identity: 'Identità legale',
    users: 'Utenti',
    kbis: 'Visura',
    addresses: 'Indirizzi',
    bank: 'Coordinate bancarie',
    mandate: 'Mandato SEPA',
    payment: 'Pagamento',
    preferences: 'Preferenze',
    data: 'I miei dati',
  },
  identityBrand: 'Insegna',
  identityCompany: 'Ragione sociale',
  identityForm: 'Forma giuridica',
  identitySiret: 'SIRET',
  identitySiren: 'SIREN',
  identityVat: 'Partita IVA intracom.',
  identityNote:
    'L’insegna si cambia qui. Le menzioni del registro passano da noi: verifichiamo, poi aggiorniamo — sono quelle che figurano sulle vostre fatture.',
  identityPanelSubtitle:
    'Insegna e partita IVA si cambiano qui; le menzioni del registro si completano una volta.',
  identityVatField: 'Partita IVA intracomunitaria',
  identityLegalHint:
    'Da completare una sola volta: una volta registrata, questa menzione si corregge solo tramite il nostro servizio commerciale.',
  identityFormPlaceholder: 'Da scegliere',
  identityVatRequiredHint: 'Obbligatoria per questa forma giuridica.',
  identityVatOptionalHint: 'Facoltativa per questa forma giuridica — franchigia IVA.',
  identityVatUndecidedHint: 'Obbligatoria o no a seconda della forma giuridica.',
  identityOptional: 'facoltativo',
  identityLegalLocked:
    'Queste menzioni provengono dal registro delle imprese. Per correggerle, passate dal nostro servizio commerciale.',
  identitySaveFailed: 'L’identità non è stata registrata.',
  railPosition: 'Sezione {n} di {total}',
  usersHolder: 'Titolare dell’account · voi',
  usersAllRights: 'Tutti i diritti',
  usersNote:
    'Un contatto può esistere senza spazio: un nome e un’e-mail bastano per ricevere le fatture. L’invito, invece, si decide caso per caso.',
  usersAdd: 'Aggiungere un utente o un contatto',
  usersAddShort: 'Aggiungere un utente',
  usersAddSubtitle: 'I suoi recapiti, e che cosa fa per l’azienda.',
  usersAddFailed: 'Il contatto non è stato aggiunto.',
  tagContact: 'Solo contatto',
  contactFields: {
    email: 'E-mail',
    emailHint: 'è a questo indirizzo che verrebbe inviato un accesso',
    role: 'Ruolo nella società',
    rolePlaceholder: 'Da scegliere',
    roles: { admin: 'Amministratore', orders: 'Ordini', billing: 'Fatturazione' },
    firstName: 'Nome',
    lastName: 'Cognome',
    fonction: 'Funzione',
    fonctionPlaceholder: 'es. Responsabile acquisti',
    phone: 'Telefono',
  },
  contactEditHolderTitle: 'Modificare il titolare',
  contactEditTitle: 'Modificare il contatto',
  contactEditHolderSubtitle:
    'I recapiti del titolare sulla scheda della società. Non cambiano il suo indirizzo di accesso: quello si cambia in «I miei dati personali».',
  contactEditSubtitle: 'I suoi recapiti, e che cosa fa per la società.',
  contactEditFailed: 'Il contatto non è stato registrato.',
  contactRemove: 'Eliminare',
  contactRemoveMessage: 'Questo contatto sarà tolto dalla società.',
  contactRemoveConfirm: 'Sì, eliminare',
  contactRemoveBusy: 'Eliminazione…',
  contactRemoveGroup: 'Confermare l’eliminazione del contatto',
  contactRemoveFailed: 'Il contatto non è stato eliminato.',
  dangerZone: 'Zona pericolosa',
  profilePageLead: 'Chi siete e come accedete al vostro account.',
  profileIdentityTitle: 'Identità',
  profileFirstName: 'Nome',
  profileLastName: 'Cognome',
  profileEmail: 'E-mail',
  profileIdentitySubtitle: 'I vostri recapiti personali, visibili solo a noi.',
  profileEmailChange:
    'Dopo la registrazione, questo indirizzo diventa il vostro identificativo di accesso. Vi parte un’e-mail di verifica: apritela per confermarlo.',
  profileSaveFailed: 'I vostri dati non sono stati registrati.',
  loginMethodsTitle: 'Metodi di accesso',
  loginMethodsSubtitle: 'Ciò con cui entrate nel vostro account.',
  loginMethodsLoading: 'Lettura dei vostri metodi di accesso…',
  loginMethodsFailed: 'Impossibile leggere i vostri metodi di accesso.',
  loginMethodsRetry: 'Riprovare',
  loginMethodsEmpty: 'Nessun metodo di accesso',
  loginMethodsEmptyHint: 'Aggiungetene uno per entrare più in fretta la prossima volta.',
  loginMethodPrimary: 'Metodo principale',
  loginMethodsAdd: 'Aggiungerne uno',
  loginMethodAdd: 'Aggiungere {provider}',
  loginMethodsPromise: 'Accederete allo stesso account, con gli stessi ordini.',
  loginMethodRemove: 'Rimuovere',
  loginMethodRemoveMessage:
    'Non potrete più entrare con questo metodo. Nulla viene eliminato presso il fornitore: quell’account vi torna autonomo.',
  loginMethodRemoveConfirm: 'Sì, rimuovere',
  loginMethodRemoveBusy: 'Rimozione…',
  loginMethodRemoveGroup: 'Confermare la rimozione di questo metodo di accesso',
  loginMethodAuthFailed: 'L’autorizzazione non è andata a buon fine. Riprovate.',
  loginMethodRetry: 'Ricominciare',
  loginMethodEmail: 'E-mail',
  loginMethodGoogle: 'Google',
  loginMethodFacebook: 'Facebook',
  loginMethodEmailChange: 'Cambiare il mio indirizzo',
  loginMethodEmailChangeTitle: 'Cambiare il mio indirizzo di accesso',
  loginMethodEmailCurrent: 'Indirizzo attuale',
  loginMethodEmailNew: 'Nuovo indirizzo e-mail',
  loginMethodEmailConfirm: 'Conferma il nuovo indirizzo',
  loginMethodEmailMismatch: 'I due indirizzi non coincidono.',
  loginMethodEmailSame: 'È già il tuo indirizzo di accesso.',
  loginMethodPasswordChange: 'Cambiare la mia password',
  loginMethodPasswordSent: 'Vi è stato inviato un link.',
  loginMethodPasswordFailed: 'Il link non è stato inviato.',
  proAccountTitle: 'Aprire un account professionale',
  proAccountLead:
    'Ordinate a nome della vostra attività, a tariffe professionali, con fattura intestata a lei.',
  proAccountLink: 'Aprire un account pro',
  proAccountsTitle: 'I miei account professionali',
  proAccountsLead: 'Le aziende a cui sei collegato. Passa a una di esse dal menu dell’account.',
  proAccountAnother: 'Aprire un altro account pro',
  kbisHead: 'La visura camerale',
  kbisCertified: 'Certificato',
  kbisPending: 'In attesa di verifica',
  kbisNone: 'Nessun estratto depositato',
  kbisUpload: 'Depositare il KBIS',
  kbisFiled: 'Depositato il {date}',
  kbisOpen: 'Aprire',
  kbisReplace: 'Sostituire',
  kbisView: 'Vedere il KBIS',
  kbisDownload: 'Scaricare',
  kbisDrop: 'Depositare',
  kbisHint: 'PDF, 10 MB al massimo',
  kbisUploading: 'Invio del KBIS…',
  kbisSaveFailed: 'Il KBIS non è stato depositato.',
  kbisFetchFailed: 'Non è stato possibile recuperare il KBIS. Riprovate.',
  billingHead: 'Fatturazione',
  billingNote:
    'Un solo indirizzo di fatturazione: è quello che figura sulle fatture e sul mandato.',
  deliveryHead: 'Consegna',
  deliveryCount: '{n} indirizzi',
  deliveryCountOne: '{n} indirizzo',
  addressNoZone: 'fuori zona',
  addressNone: 'Nessun indirizzo registrato.',
  addressDefault: 'Predefinito',
  addressAdd: 'Aggiungere un indirizzo di consegna',
  billingFill: 'Indicare la fatturazione',
  billingEdit: 'Modificare la fatturazione',
  addressEdit: 'Modificare l’indirizzo di consegna',
  addressSaveFailed: 'L’indirizzo non è stato registrato.',
  addressSavedToast: 'Indirizzo registrato.',
  addressRemove: 'Eliminare',
  addressRemoveMessage:
    'Togliere questo indirizzo dalla rubrica? Gli ordini già passati conservano il loro.',
  addressRemoveConfirm: 'Eliminare l’indirizzo',
  addressRemoveBusy: 'Eliminazione…',
  addressRemoveGroup: 'Confermare l’eliminazione dell’indirizzo',
  addressRemovedToast: 'Indirizzo eliminato.',
  addressActionFailed: 'La rubrica non è stata modificata.',
  deliveryDialogSubtitle: 'Un indirizzo postale completo, e come vi consegniamo.',
  deliveryAddSubmit: 'Aggiungi',
  addressForm: ADDRESS_FORM,
  deliveryForm: {
    defaultLabel: 'Indirizzo di consegna predefinito',
    defaultHint: 'usato automaticamente per i prossimi ordini',
    legend: 'Indirizzo postale',
    address: {
      ...ADDRESS_FORM,
      labelHint: 'es. Chalet, Ristorante in quota',
      line2Hint: 'edificio, piano, istruzioni di consegna…',
      noteLabel: 'Nota per i corrieri',
      notePlaceholder: 'Codice di accesso, piano, contatto sul posto, istruzioni di consegna…',
      coordinatesLabel: 'Punto GPS',
      coordinatesHint: 'per i luoghi difficili da trovare',
    },
    specs: {
      detailLegend: 'Dettagli di consegna',
      slotsLegend: 'Fasce orarie preferite',
      sameEveryDay: 'La stessa fascia oraria ogni giorno',
      sameEveryDayHint: 'deselezionate per impostare una fascia per giorno',
      everyDay: 'Tutti i giorni',
      weekdays: {
        mon: 'Lunedì',
        tue: 'Martedì',
        wed: 'Mercoledì',
        thu: 'Giovedì',
        fri: 'Venerdì',
        sat: 'Sabato',
        sun: 'Domenica',
      },
      slotStart: 'Inizio',
      slotEnd: 'Fine',
      contactLegend: 'Contatto sul posto',
      noContact: 'Nessun contatto di consegna dedicato',
      noContactHint: 'selezionate se il corriere non ha nessuno da avvisare sul posto',
      knownContact: 'Riprendi un contatto noto',
      knownContactPlaceholder: 'Scegli un contatto…',
      firstName: 'Nome',
      lastName: 'Cognome',
      phone: 'Telefono',
      contactIncomplete: 'Inserite nome, cognome e telefono, oppure selezionate «nessun contatto».',
      signature: 'Firma alla consegna',
      signatureHint: 'precompila gli ordini consegnati qui; modificabile nel carrello',
      signatureInherit: 'Come la società ({floor})',
      signatureFloorRequired: 'richiesta',
      signatureFloorNotRequired: 'non richiesta',
      signatureRequired: 'Richiesta',
      signatureNotRequired: 'Non richiesta',
      signatureNoContactHint: 'senza un contatto sul posto, nessuno può firmare alla consegna',
    },
  },
  termMonthly: 'Pagamento a 30 giorni fine mese',
  termGrantedSub: 'Concesso dal vostro commerciale: gli ordini si saldano a fine mese.',
  termRequestedSub: 'Richiesta inviata: il vostro commerciale la convalida.',
  termNoneSub: 'Su richiesta: il vostro commerciale lo concede società per società.',
  termSuspendedSub: 'Addebito mensile sospeso — gli ordini si pagano con carta.',
  termOrder: 'All’ordine',
  termOrderSub: 'Carta o Apple Pay, senza aspettare la fattura',
  stateActive: 'Attivo',
  stateAvailable: 'Disponibile',
  stateRequested: 'In attesa',
  stateSuspended: 'Sospeso',
  paymentNote:
    'Due regimi, non di più: fine mese quando un credito è concesso, all’ordine altrimenti — e tutti possono ordinare all’ordine.',
  termRequest: 'Richiedere il pagamento mensile',
  termRequestNote:
    'È una richiesta: nulla cambia finché il vostro commerciale non l’ha convalidata.',
  termRequestFailed: 'La richiesta non è stata registrata.',
  prefPickup: 'Ritiro abituale',
  prefNone: 'Nulla impostato — la domanda torna a ogni ordine.',
  prefPickupAt: 'Ritiro al',
  prefPickupAny: 'Ritiro',
  prefDeliveryTo: 'Consegna',
  prefDeliveryAny: 'Consegna',
  stateUnavailable: 'Non concesso',
  prefLang: 'Lingua',
  prefNote:
    'Un’operazione a data avvisa una volta per stagione. Consegne e fatture, invece, sono attive di default.',
  prefMethod: 'Modalità abituale',
  prefMethodNone: 'Nessuna — scegliere a ogni ordine',
  prefMethodPickup: 'Ritiro',
  prefMethodDelivery: 'Consegna',
  prefPickupPoint: 'Punto di ritiro',
  prefPickupDefault: 'Il punto predefinito',
  prefDeliveryAddress: 'Indirizzo di consegna',
  prefDeliveryDefault: 'L’indirizzo predefinito della società',
  prefDefaultTag: 'predefinito',
  prefSaveFailed: 'La preferenza non è stata registrata.',
  prefLangNote: 'La lingua cambia subito, senza registrare nulla.',
  dataExportOrders: 'Esportare i miei ordini e le mie fatture',
  dataExportOrdersSub: 'CSV e PDF, per esercizio',
  dataExportPersonal: 'Scaricare i miei dati personali',
  dataExportPersonalSub: 'Tutto quello che abbiamo, in un file',
  dataSummary: 'Conservazione, trasferimento e chiusura dello spazio',
  dataKeep:
    'Le vostre fatture restano disponibili dieci anni dopo la chiusura — è un obbligo, non una scelta.',
  dangerHead: 'Zona sensibile',
  transferHead: 'Trasferire l’azienda',
  transferBody:
    'Cedete il ruolo di titolare a un utente dello spazio. Riprende la fatturazione, le condizioni di pagamento e il diritto di invitare. Voi mantenete il vostro accesso, senza l’amministrazione.',
  transferCta: 'Trasferire l’account',
  closeHead: 'Chiudere questo spazio',
  closeBody:
    'Definitivo, e proprio di questo spazio: accesso revocato per voi e per i vostri utenti, sconto e condizioni di pagamento persi, carrelli ricorrenti eliminati. Gli altri spazi non si muovono. Un ordine in corso va ritirato o annullato prima.',
  closeCta: 'Chiudere questo spazio',
  panelPhone: 'Telefono',
  bankLoading: 'Lettura delle coordinate bancarie…',
  bankLoadFailedTitle: 'Le coordinate bancarie non sono state lette',
  bankLoadFailedBody: 'Il servizio non risponde al momento. Riprovate tra un istante.',
  bankNone: 'Nessuna coordinata bancaria registrata',
  bankRegistered: 'Coordinate bancarie registrate',
  bankLast4: '•••• {last4}',
  bankNotice:
    'Il titolare e l’indirizzo sono quelli noti alla vostra banca: possono differire dalla ragione sociale. Se su questo conto è attivo un addebito, sostituirlo lo interrompe: vi ricontatteremo per il seguito.',
  bankForm: {
    holder: 'Titolare del conto',
    holderLegalForm: 'Titolo (Sig., Sig.ra) o forma giuridica (SAS, SARL…)',
    holderLegalFormHint:
      'Richiesto dal mandato tra imprese, che il titolare sia una società o una persona — al massimo 40 caratteri.',
    line1: 'Indirizzo',
    line2: 'Complemento',
    postalCode: 'CAP',
    city: 'Città',
    country: 'Paese',
    iban: 'IBAN',
    ibanHint: 'Inserito una volta. Non sarà mai più mostrato.',
    bic: 'BIC',
  },
  bankSave: 'Registra le coordinate',
  bankReplace: 'Sostituisci le coordinate',
  bankSavedToast: 'Coordinate bancarie registrate.',
  bankSaveFailed: 'Le coordinate bancarie non sono state registrate.',
  mandateLoading: 'Lettura del mandato…',
  mandateLoadFailedTitle: 'Il mandato non è stato letto',
  mandateLoadFailedBody: 'Il servizio non risponde al momento. Riprovate tra un istante.',
  mandateNone: 'Nessun mandato in corso',
  mandateAwaiting: 'Rinviate il mandato datato e firmato',
  mandateInReview: 'Mandato ricevuto — in verifica',
  mandateActive: 'Mandato attivo',
  mandateReference: 'Riferimento · {reference}',
  mandateSignedOn: 'Firmato il {date}',
  mandateProofFile: 'File caricato: {fileName}',
  mandateGenerate: 'Genera il mio mandato',
  mandateSend: 'Rinvia il mandato firmato',
  mandateView: 'Vedi il mandato',
  mandateDownload: 'Scarica il mandato',
  mandateNoneBody: {
    CORE: 'Il mandato di addebito diretto SEPA autorizza l’addebito delle vostre fatture sul conto delle vostre coordinate bancarie. Generatelo: potrete poi stamparlo, datarlo, firmarlo e rinviarcelo qui.',
    B2B: 'Il mandato di addebito diretto SEPA B2B autorizza l’addebito delle vostre fatture sul conto delle vostre coordinate bancarie. Generatelo: potrete poi stamparlo, datarlo, firmarlo e rinviarcelo qui.',
  },
  mandateAwaitingBody: {
    CORE: 'Stampate il mandato, datatelo e firmatelo, poi caricate qui la scansione o la foto.',
    B2B: 'Stampate il mandato, datatelo e firmatelo, poi caricate qui la scansione o la foto. Registratelo anche presso la vostra banca: un addebito B2B è accettato solo quando la banca ha registrato il mandato.',
  },
  mandateInReviewBody:
    'Stiamo verificando il mandato firmato: sarà attivo appena il nostro servizio lo avrà controllato. Potete ancora sostituire il file caricato.',
  mandateActiveBody:
    'I vostri addebiti si basano su questo mandato. Per cambiare conto bancario, contattate il servizio commerciale.',
  mandateDrop: 'Carica il mandato firmato',
  mandateDropReplace: 'Sostituisci il file caricato',
  mandateDropHint: 'PDF o foto (JPEG, PNG, HEIC), massimo 10 MB.',
  mandateUploading: 'Invio del mandato…',
  mandateUploadedToast: 'Mandato firmato ricevuto.',
  mandateBlockedLead: 'Per generare il mandato manca:',
  mandateBlockers: {
    bank_account_missing: 'le coordinate bancarie',
    issuer_missing: 'i nostri dati di creditore — ce ne occupiamo noi',
    company_name_missing: 'la ragione sociale della sua impresa',
    siren_missing: 'il numero SIREN della sua impresa',
    holder_legal_form_missing: 'il titolo o la forma giuridica del titolare del conto',
  },
  mandateBlockersIdentity: 'Completa l’identità legale',
  mandateBlockersBank: 'Completa le coordinate bancarie',
  mandateGenerateFailed: 'Il mandato non è stato generato.',
  mandateUploadFailed: 'Il mandato firmato non è stato caricato.',
  mandateFetchFailed: 'Il mandato non è stato aperto. Riprovate tra un istante.',
  mandateEsign: 'Usa la firma elettronica',
  mandateEsignSoon: 'Presto disponibile',
  mandateOptions: 'Opzioni del mandato',
  mandateOptionsSubtitle: 'Codice debitore e numero di contratto',
  mandateOptionsNotice:
    'Questi due campi sono facoltativi: nessuno condiziona la validità del mandato, e lasciarli vuoti è del tutto normale.',
  mandateOptionsDraftWarning:
    'Modificare questi campi annulla il mandato in attesa di firma: bisognerà generarlo di nuovo.',
  mandateOptionsForm: {
    debtorReference: 'Codice identificativo del debitore',
    debtorReferenceHint: 'Il riferimento che volete ritrovare sui vostri estratti conto.',
    contractNumber: 'Numero del contratto',
    contractNumberHint: 'Facoltativo.',
  },
  mandateOptionsLoading: 'Lettura delle opzioni del mandato…',
  mandateOptionsLoadFailedTitle: 'Le opzioni del mandato non sono state lette',
  mandateOptionsNoBank: 'Registrate prima le coordinate bancarie: questi campi vi si collegano.',
  mandateOptionsSave: 'Registra le opzioni',
  mandateOptionsSavedToast: 'Opzioni del mandato registrate.',
  mandateOptionsSaveFailed: 'Le opzioni del mandato non sono state registrate.',
  completion: {
    countOne: '1 elemento da completare',
    count: '{n} elementi da completare',
    blocksActivation: 'Impedisce l’attivazione: {detail}',
    optionalNote: 'non impedisce l’attivazione',
    cardLead: 'Da completare:',
    mandateFields: 'Per generare il vostro mandato SEPA: {fields}.',
    items: {
      identity: {
        title: 'Identità legale',
        detail: 'Mancano la ragione sociale, la forma giuridica o il SIRET.',
        action: 'Completare l’identità',
      },
      vat: {
        title: 'Partita IVA',
        detail: 'È richiesta la vostra partita IVA intracomunitaria.',
        action: 'Indicare la partita IVA',
      },
      telephone: {
        title: 'Numero di telefono',
        detail:
          'Un corriere deve poter chiamare: indicate un telefono, il vostro o quello di un contatto.',
        action: 'Aggiungere un numero',
      },
      billing: {
        title: 'Indirizzo di fatturazione',
        detail: 'Le vostre fatture hanno bisogno di un indirizzo.',
        action: 'Aggiungere la fatturazione',
      },
      delivery: {
        title: 'Indirizzo di consegna',
        detail: 'Preferite la consegna: aggiungete almeno un indirizzo di consegna.',
        action: 'Aggiungere una consegna',
      },
      kbis: {
        title: 'Visura KBIS',
        detail: 'Caricate la visura KBIS della vostra impresa.',
        action: 'Caricare il KBIS',
      },
      bank: {
        title: 'Coordinate bancarie',
        detail: 'Le vostre coordinate bancarie sono incomplete.',
        action: 'Completare le coordinate',
      },
    },
  },
  supportTitle: 'Contattare il servizio commerciale',
  supportPanelTitle: 'Servizio commerciale',
  supportBody: 'Una domanda sul vostro conto, un ordine o una fattura: vi rispondiamo.',
};
