import {
  DELIVERY_PROCEDURE_MAX_STEPS,
  DELIVERY_STEP_BODY_MAX,
  DELIVERY_STEP_TITLE_MAX,
} from '@lfd/contracts';

import type { DeliveryProcedureCopy } from './delivery-procedure.copy';

export const DELIVERY_PROCEDURE_EN: DeliveryProcedureCopy = {
  entry: 'Delivery procedure',
  toWrite: 'to be written',
  stepsNone: 'no steps',
  stepsOne: '1 step',
  steps: '{n} steps',
  removeBusy: 'Deleting…',
  removeGroup: 'Confirm deleting the step',
  editor: {
    loading: 'Loading the procedure…',
    loadError: 'The delivery procedure could not be loaded.',
    retry: 'Try again',
    emptyTitle: 'No delivery procedure',
    emptySubtitleEditable:
      'Describe, step by step, how the driver drops off the goods at this address.',
    emptySubtitleReadOnly: 'No steps have been described for this address.',
    addStep: 'Add a step',
    limitReached: `A procedure has at most ${DELIVERY_PROCEDURE_MAX_STEPS} steps.`,
    stepNumber: (n) => `Step ${n}`,
    moveUp: 'Move step up',
    moveDown: 'Move step down',
    revise: 'Redo',
    photoAlt: (title) => `Photo of the step “${title}”`,
    conflict: 'The procedure changed in the meantime: it has just been reloaded.',
    writeFailed: 'Saving failed. Please try again.',
    newStepHeading: 'New step',
    reviseHeading: (n) => `Redo step ${n}`,
    save: 'Save',
    add: 'Add the step',
    cancel: 'Cancel',
    removeTitle: 'Delete this step',
    removeAction: 'Delete the step',
    removeExplanation:
      'The step is deleted permanently, photo included. The following steps move up one place.',
    removeConfirm: 'Permanently delete this step?',
    form: {
      title: 'Title',
      titleHint: `${DELIVERY_STEP_TITLE_MAX} characters at most — what you read at a glance.`,
      body: 'Text',
      bodyHint: `${DELIVERY_STEP_BODY_MAX} characters at most.`,
      optional: 'optional',
      photoLegend: 'Photo',
      photoHint: 'A photo of the door, the gate or the passage. It is made lighter before sending.',
      choosePhoto: 'Choose a photo',
      replacePhoto: 'Replace the photo',
      removePhoto: 'Remove the photo',
      photoPreviewAlt: 'Preview of the step photo',
      photoReducing: 'Making the photo lighter…',
      photoTooHeavy: 'This photo is still too heavy, even made lighter. Choose another or crop it.',
      photoUnreadable: 'This file is not a readable image. Choose a JPEG or PNG photo.',
      titleRequired: 'The title is required.',
      titleTooLong: `The title exceeds ${DELIVERY_STEP_TITLE_MAX} characters.`,
      bodyTooLong: `The text exceeds ${DELIVERY_STEP_BODY_MAX} characters.`,
    },
  },
};
