
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `B2bChannelBinding` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model B2bChannelBinding
 * L'**appartenance d'un produit au canal B2B** : sa présence dit « vendu aux
 * pros », son absence dit le contraire. Un état de publication (`published`)
 * ne suffirait pas — il confondrait « publié chez Shopify » et « vendu aux
 * pros », et les deux catalogues ne pourraient jamais diverger.
 * 
 * Dépublier **supprime la ligne**. Le produit disparaîtra du prochain snapshot,
 * et le récepteur le nommera dans son rapport (`removedSkus`) : la nouvelle est
 * portée par le push, pas par un drapeau qu'il faudrait penser à relire.
 */
export type B2bChannelBindingModel = runtime.Types.Result.DefaultSelection<Prisma.$B2bChannelBindingPayload>

export type AggregateB2bChannelBinding = {
  _count: B2bChannelBindingCountAggregateOutputType | null
  _min: B2bChannelBindingMinAggregateOutputType | null
  _max: B2bChannelBindingMaxAggregateOutputType | null
}

export type B2bChannelBindingMinAggregateOutputType = {
  productId: string | null
  publishedAt: Date | null
  publishedBy: string | null
  lastPushedAt: Date | null
}

export type B2bChannelBindingMaxAggregateOutputType = {
  productId: string | null
  publishedAt: Date | null
  publishedBy: string | null
  lastPushedAt: Date | null
}

export type B2bChannelBindingCountAggregateOutputType = {
  productId: number
  publishedAt: number
  publishedBy: number
  lastPushedAt: number
  _all: number
}


export type B2bChannelBindingMinAggregateInputType = {
  productId?: true
  publishedAt?: true
  publishedBy?: true
  lastPushedAt?: true
}

export type B2bChannelBindingMaxAggregateInputType = {
  productId?: true
  publishedAt?: true
  publishedBy?: true
  lastPushedAt?: true
}

export type B2bChannelBindingCountAggregateInputType = {
  productId?: true
  publishedAt?: true
  publishedBy?: true
  lastPushedAt?: true
  _all?: true
}

export type B2bChannelBindingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which B2bChannelBinding to aggregate.
   */
  where?: Prisma.B2bChannelBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of B2bChannelBindings to fetch.
   */
  orderBy?: Prisma.B2bChannelBindingOrderByWithRelationInput | Prisma.B2bChannelBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.B2bChannelBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` B2bChannelBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` B2bChannelBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned B2bChannelBindings
  **/
  _count?: true | B2bChannelBindingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: B2bChannelBindingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: B2bChannelBindingMaxAggregateInputType
}

export type GetB2bChannelBindingAggregateType<T extends B2bChannelBindingAggregateArgs> = {
      [P in keyof T & keyof AggregateB2bChannelBinding]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateB2bChannelBinding[P]>
    : Prisma.GetScalarType<T[P], AggregateB2bChannelBinding[P]>
}




export type B2bChannelBindingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.B2bChannelBindingWhereInput
  orderBy?: Prisma.B2bChannelBindingOrderByWithAggregationInput | Prisma.B2bChannelBindingOrderByWithAggregationInput[]
  by: Prisma.B2bChannelBindingScalarFieldEnum[] | Prisma.B2bChannelBindingScalarFieldEnum
  having?: Prisma.B2bChannelBindingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: B2bChannelBindingCountAggregateInputType | true
  _min?: B2bChannelBindingMinAggregateInputType
  _max?: B2bChannelBindingMaxAggregateInputType
}

export type B2bChannelBindingGroupByOutputType = {
  productId: string
  publishedAt: Date
  publishedBy: string | null
  lastPushedAt: Date | null
  _count: B2bChannelBindingCountAggregateOutputType | null
  _min: B2bChannelBindingMinAggregateOutputType | null
  _max: B2bChannelBindingMaxAggregateOutputType | null
}

export type GetB2bChannelBindingGroupByPayload<T extends B2bChannelBindingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<B2bChannelBindingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof B2bChannelBindingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], B2bChannelBindingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], B2bChannelBindingGroupByOutputType[P]>
      }
    >
  >



export type B2bChannelBindingWhereInput = {
  AND?: Prisma.B2bChannelBindingWhereInput | Prisma.B2bChannelBindingWhereInput[]
  OR?: Prisma.B2bChannelBindingWhereInput[]
  NOT?: Prisma.B2bChannelBindingWhereInput | Prisma.B2bChannelBindingWhereInput[]
  productId?: Prisma.StringFilter<"B2bChannelBinding"> | string
  publishedAt?: Prisma.DateTimeFilter<"B2bChannelBinding"> | Date | string
  publishedBy?: Prisma.StringNullableFilter<"B2bChannelBinding"> | string | null
  lastPushedAt?: Prisma.DateTimeNullableFilter<"B2bChannelBinding"> | Date | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type B2bChannelBindingOrderByWithRelationInput = {
  productId?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  publishedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  lastPushedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type B2bChannelBindingWhereUniqueInput = Prisma.AtLeast<{
  productId?: string
  AND?: Prisma.B2bChannelBindingWhereInput | Prisma.B2bChannelBindingWhereInput[]
  OR?: Prisma.B2bChannelBindingWhereInput[]
  NOT?: Prisma.B2bChannelBindingWhereInput | Prisma.B2bChannelBindingWhereInput[]
  publishedAt?: Prisma.DateTimeFilter<"B2bChannelBinding"> | Date | string
  publishedBy?: Prisma.StringNullableFilter<"B2bChannelBinding"> | string | null
  lastPushedAt?: Prisma.DateTimeNullableFilter<"B2bChannelBinding"> | Date | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "productId">

export type B2bChannelBindingOrderByWithAggregationInput = {
  productId?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  publishedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  lastPushedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.B2bChannelBindingCountOrderByAggregateInput
  _max?: Prisma.B2bChannelBindingMaxOrderByAggregateInput
  _min?: Prisma.B2bChannelBindingMinOrderByAggregateInput
}

export type B2bChannelBindingScalarWhereWithAggregatesInput = {
  AND?: Prisma.B2bChannelBindingScalarWhereWithAggregatesInput | Prisma.B2bChannelBindingScalarWhereWithAggregatesInput[]
  OR?: Prisma.B2bChannelBindingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.B2bChannelBindingScalarWhereWithAggregatesInput | Prisma.B2bChannelBindingScalarWhereWithAggregatesInput[]
  productId?: Prisma.StringWithAggregatesFilter<"B2bChannelBinding"> | string
  publishedAt?: Prisma.DateTimeWithAggregatesFilter<"B2bChannelBinding"> | Date | string
  publishedBy?: Prisma.StringNullableWithAggregatesFilter<"B2bChannelBinding"> | string | null
  lastPushedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"B2bChannelBinding"> | Date | string | null
}

export type B2bChannelBindingCreateInput = {
  publishedAt?: Date | string
  publishedBy?: string | null
  lastPushedAt?: Date | string | null
  product: Prisma.ProductCreateNestedOneWithoutB2bBindingInput
}

export type B2bChannelBindingUncheckedCreateInput = {
  productId: string
  publishedAt?: Date | string
  publishedBy?: string | null
  lastPushedAt?: Date | string | null
}

export type B2bChannelBindingUpdateInput = {
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  product?: Prisma.ProductUpdateOneRequiredWithoutB2bBindingNestedInput
}

export type B2bChannelBindingUncheckedUpdateInput = {
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type B2bChannelBindingCreateManyInput = {
  productId: string
  publishedAt?: Date | string
  publishedBy?: string | null
  lastPushedAt?: Date | string | null
}

export type B2bChannelBindingUpdateManyMutationInput = {
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type B2bChannelBindingUncheckedUpdateManyInput = {
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type B2bChannelBindingNullableScalarRelationFilter = {
  is?: Prisma.B2bChannelBindingWhereInput | null
  isNot?: Prisma.B2bChannelBindingWhereInput | null
}

export type B2bChannelBindingCountOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  publishedBy?: Prisma.SortOrder
  lastPushedAt?: Prisma.SortOrder
}

export type B2bChannelBindingMaxOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  publishedBy?: Prisma.SortOrder
  lastPushedAt?: Prisma.SortOrder
}

export type B2bChannelBindingMinOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  publishedBy?: Prisma.SortOrder
  lastPushedAt?: Prisma.SortOrder
}

export type B2bChannelBindingCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.B2bChannelBindingCreateWithoutProductInput, Prisma.B2bChannelBindingUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.B2bChannelBindingCreateOrConnectWithoutProductInput
  connect?: Prisma.B2bChannelBindingWhereUniqueInput
}

export type B2bChannelBindingUncheckedCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.B2bChannelBindingCreateWithoutProductInput, Prisma.B2bChannelBindingUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.B2bChannelBindingCreateOrConnectWithoutProductInput
  connect?: Prisma.B2bChannelBindingWhereUniqueInput
}

export type B2bChannelBindingUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.B2bChannelBindingCreateWithoutProductInput, Prisma.B2bChannelBindingUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.B2bChannelBindingCreateOrConnectWithoutProductInput
  upsert?: Prisma.B2bChannelBindingUpsertWithoutProductInput
  disconnect?: Prisma.B2bChannelBindingWhereInput | boolean
  delete?: Prisma.B2bChannelBindingWhereInput | boolean
  connect?: Prisma.B2bChannelBindingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.B2bChannelBindingUpdateToOneWithWhereWithoutProductInput, Prisma.B2bChannelBindingUpdateWithoutProductInput>, Prisma.B2bChannelBindingUncheckedUpdateWithoutProductInput>
}

export type B2bChannelBindingUncheckedUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.B2bChannelBindingCreateWithoutProductInput, Prisma.B2bChannelBindingUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.B2bChannelBindingCreateOrConnectWithoutProductInput
  upsert?: Prisma.B2bChannelBindingUpsertWithoutProductInput
  disconnect?: Prisma.B2bChannelBindingWhereInput | boolean
  delete?: Prisma.B2bChannelBindingWhereInput | boolean
  connect?: Prisma.B2bChannelBindingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.B2bChannelBindingUpdateToOneWithWhereWithoutProductInput, Prisma.B2bChannelBindingUpdateWithoutProductInput>, Prisma.B2bChannelBindingUncheckedUpdateWithoutProductInput>
}

export type B2bChannelBindingCreateWithoutProductInput = {
  publishedAt?: Date | string
  publishedBy?: string | null
  lastPushedAt?: Date | string | null
}

export type B2bChannelBindingUncheckedCreateWithoutProductInput = {
  publishedAt?: Date | string
  publishedBy?: string | null
  lastPushedAt?: Date | string | null
}

export type B2bChannelBindingCreateOrConnectWithoutProductInput = {
  where: Prisma.B2bChannelBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.B2bChannelBindingCreateWithoutProductInput, Prisma.B2bChannelBindingUncheckedCreateWithoutProductInput>
}

export type B2bChannelBindingUpsertWithoutProductInput = {
  update: Prisma.XOR<Prisma.B2bChannelBindingUpdateWithoutProductInput, Prisma.B2bChannelBindingUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.B2bChannelBindingCreateWithoutProductInput, Prisma.B2bChannelBindingUncheckedCreateWithoutProductInput>
  where?: Prisma.B2bChannelBindingWhereInput
}

export type B2bChannelBindingUpdateToOneWithWhereWithoutProductInput = {
  where?: Prisma.B2bChannelBindingWhereInput
  data: Prisma.XOR<Prisma.B2bChannelBindingUpdateWithoutProductInput, Prisma.B2bChannelBindingUncheckedUpdateWithoutProductInput>
}

export type B2bChannelBindingUpdateWithoutProductInput = {
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type B2bChannelBindingUncheckedUpdateWithoutProductInput = {
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publishedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type B2bChannelBindingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productId?: boolean
  publishedAt?: boolean
  publishedBy?: boolean
  lastPushedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["b2bChannelBinding"]>

export type B2bChannelBindingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productId?: boolean
  publishedAt?: boolean
  publishedBy?: boolean
  lastPushedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["b2bChannelBinding"]>

export type B2bChannelBindingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productId?: boolean
  publishedAt?: boolean
  publishedBy?: boolean
  lastPushedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["b2bChannelBinding"]>

export type B2bChannelBindingSelectScalar = {
  productId?: boolean
  publishedAt?: boolean
  publishedBy?: boolean
  lastPushedAt?: boolean
}

export type B2bChannelBindingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"productId" | "publishedAt" | "publishedBy" | "lastPushedAt", ExtArgs["result"]["b2bChannelBinding"]>
export type B2bChannelBindingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type B2bChannelBindingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type B2bChannelBindingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $B2bChannelBindingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "B2bChannelBinding"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    productId: string
    /**
     * Quand ce produit a rejoint le canal, et par qui. La question posée six mois
     * plus tard est toujours « qui a mis ça en vente ».
     */
    publishedAt: Date
    publishedBy: string | null
    /**
     * Dernière poussée **réellement acceptée** par la plateforme. `NULL` = publié
     * mais jamais parti — l'écart que l'écran doit montrer.
     */
    lastPushedAt: Date | null
  }, ExtArgs["result"]["b2bChannelBinding"]>
  composites: {}
}

export type B2bChannelBindingGetPayload<S extends boolean | null | undefined | B2bChannelBindingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload, S>

export type B2bChannelBindingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<B2bChannelBindingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: B2bChannelBindingCountAggregateInputType | true
  }

export interface B2bChannelBindingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['B2bChannelBinding'], meta: { name: 'B2bChannelBinding' } }
  /**
   * Find zero or one B2bChannelBinding that matches the filter.
   * @param {B2bChannelBindingFindUniqueArgs} args - Arguments to find a B2bChannelBinding
   * @example
   * // Get one B2bChannelBinding
   * const b2bChannelBinding = await prisma.b2bChannelBinding.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends B2bChannelBindingFindUniqueArgs>(args: Prisma.SelectSubset<T, B2bChannelBindingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__B2bChannelBindingClient<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one B2bChannelBinding that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {B2bChannelBindingFindUniqueOrThrowArgs} args - Arguments to find a B2bChannelBinding
   * @example
   * // Get one B2bChannelBinding
   * const b2bChannelBinding = await prisma.b2bChannelBinding.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends B2bChannelBindingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, B2bChannelBindingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__B2bChannelBindingClient<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first B2bChannelBinding that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {B2bChannelBindingFindFirstArgs} args - Arguments to find a B2bChannelBinding
   * @example
   * // Get one B2bChannelBinding
   * const b2bChannelBinding = await prisma.b2bChannelBinding.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends B2bChannelBindingFindFirstArgs>(args?: Prisma.SelectSubset<T, B2bChannelBindingFindFirstArgs<ExtArgs>>): Prisma.Prisma__B2bChannelBindingClient<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first B2bChannelBinding that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {B2bChannelBindingFindFirstOrThrowArgs} args - Arguments to find a B2bChannelBinding
   * @example
   * // Get one B2bChannelBinding
   * const b2bChannelBinding = await prisma.b2bChannelBinding.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends B2bChannelBindingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, B2bChannelBindingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__B2bChannelBindingClient<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more B2bChannelBindings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {B2bChannelBindingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all B2bChannelBindings
   * const b2bChannelBindings = await prisma.b2bChannelBinding.findMany()
   * 
   * // Get first 10 B2bChannelBindings
   * const b2bChannelBindings = await prisma.b2bChannelBinding.findMany({ take: 10 })
   * 
   * // Only select the `productId`
   * const b2bChannelBindingWithProductIdOnly = await prisma.b2bChannelBinding.findMany({ select: { productId: true } })
   * 
   */
  findMany<T extends B2bChannelBindingFindManyArgs>(args?: Prisma.SelectSubset<T, B2bChannelBindingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a B2bChannelBinding.
   * @param {B2bChannelBindingCreateArgs} args - Arguments to create a B2bChannelBinding.
   * @example
   * // Create one B2bChannelBinding
   * const B2bChannelBinding = await prisma.b2bChannelBinding.create({
   *   data: {
   *     // ... data to create a B2bChannelBinding
   *   }
   * })
   * 
   */
  create<T extends B2bChannelBindingCreateArgs>(args: Prisma.SelectSubset<T, B2bChannelBindingCreateArgs<ExtArgs>>): Prisma.Prisma__B2bChannelBindingClient<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many B2bChannelBindings.
   * @param {B2bChannelBindingCreateManyArgs} args - Arguments to create many B2bChannelBindings.
   * @example
   * // Create many B2bChannelBindings
   * const b2bChannelBinding = await prisma.b2bChannelBinding.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends B2bChannelBindingCreateManyArgs>(args?: Prisma.SelectSubset<T, B2bChannelBindingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many B2bChannelBindings and returns the data saved in the database.
   * @param {B2bChannelBindingCreateManyAndReturnArgs} args - Arguments to create many B2bChannelBindings.
   * @example
   * // Create many B2bChannelBindings
   * const b2bChannelBinding = await prisma.b2bChannelBinding.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many B2bChannelBindings and only return the `productId`
   * const b2bChannelBindingWithProductIdOnly = await prisma.b2bChannelBinding.createManyAndReturn({
   *   select: { productId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends B2bChannelBindingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, B2bChannelBindingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a B2bChannelBinding.
   * @param {B2bChannelBindingDeleteArgs} args - Arguments to delete one B2bChannelBinding.
   * @example
   * // Delete one B2bChannelBinding
   * const B2bChannelBinding = await prisma.b2bChannelBinding.delete({
   *   where: {
   *     // ... filter to delete one B2bChannelBinding
   *   }
   * })
   * 
   */
  delete<T extends B2bChannelBindingDeleteArgs>(args: Prisma.SelectSubset<T, B2bChannelBindingDeleteArgs<ExtArgs>>): Prisma.Prisma__B2bChannelBindingClient<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one B2bChannelBinding.
   * @param {B2bChannelBindingUpdateArgs} args - Arguments to update one B2bChannelBinding.
   * @example
   * // Update one B2bChannelBinding
   * const b2bChannelBinding = await prisma.b2bChannelBinding.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends B2bChannelBindingUpdateArgs>(args: Prisma.SelectSubset<T, B2bChannelBindingUpdateArgs<ExtArgs>>): Prisma.Prisma__B2bChannelBindingClient<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more B2bChannelBindings.
   * @param {B2bChannelBindingDeleteManyArgs} args - Arguments to filter B2bChannelBindings to delete.
   * @example
   * // Delete a few B2bChannelBindings
   * const { count } = await prisma.b2bChannelBinding.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends B2bChannelBindingDeleteManyArgs>(args?: Prisma.SelectSubset<T, B2bChannelBindingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more B2bChannelBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {B2bChannelBindingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many B2bChannelBindings
   * const b2bChannelBinding = await prisma.b2bChannelBinding.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends B2bChannelBindingUpdateManyArgs>(args: Prisma.SelectSubset<T, B2bChannelBindingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more B2bChannelBindings and returns the data updated in the database.
   * @param {B2bChannelBindingUpdateManyAndReturnArgs} args - Arguments to update many B2bChannelBindings.
   * @example
   * // Update many B2bChannelBindings
   * const b2bChannelBinding = await prisma.b2bChannelBinding.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more B2bChannelBindings and only return the `productId`
   * const b2bChannelBindingWithProductIdOnly = await prisma.b2bChannelBinding.updateManyAndReturn({
   *   select: { productId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends B2bChannelBindingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, B2bChannelBindingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one B2bChannelBinding.
   * @param {B2bChannelBindingUpsertArgs} args - Arguments to update or create a B2bChannelBinding.
   * @example
   * // Update or create a B2bChannelBinding
   * const b2bChannelBinding = await prisma.b2bChannelBinding.upsert({
   *   create: {
   *     // ... data to create a B2bChannelBinding
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the B2bChannelBinding we want to update
   *   }
   * })
   */
  upsert<T extends B2bChannelBindingUpsertArgs>(args: Prisma.SelectSubset<T, B2bChannelBindingUpsertArgs<ExtArgs>>): Prisma.Prisma__B2bChannelBindingClient<runtime.Types.Result.GetResult<Prisma.$B2bChannelBindingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of B2bChannelBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {B2bChannelBindingCountArgs} args - Arguments to filter B2bChannelBindings to count.
   * @example
   * // Count the number of B2bChannelBindings
   * const count = await prisma.b2bChannelBinding.count({
   *   where: {
   *     // ... the filter for the B2bChannelBindings we want to count
   *   }
   * })
  **/
  count<T extends B2bChannelBindingCountArgs>(
    args?: Prisma.Subset<T, B2bChannelBindingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], B2bChannelBindingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a B2bChannelBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {B2bChannelBindingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends B2bChannelBindingAggregateArgs>(args: Prisma.Subset<T, B2bChannelBindingAggregateArgs>): Prisma.PrismaPromise<GetB2bChannelBindingAggregateType<T>>

  /**
   * Group by B2bChannelBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {B2bChannelBindingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends B2bChannelBindingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: B2bChannelBindingGroupByArgs['orderBy'] }
      : { orderBy?: B2bChannelBindingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, B2bChannelBindingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetB2bChannelBindingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the B2bChannelBinding model
 */
readonly fields: B2bChannelBindingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for B2bChannelBinding.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__B2bChannelBindingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the B2bChannelBinding model
 */
export interface B2bChannelBindingFieldRefs {
  readonly productId: Prisma.FieldRef<"B2bChannelBinding", 'String'>
  readonly publishedAt: Prisma.FieldRef<"B2bChannelBinding", 'DateTime'>
  readonly publishedBy: Prisma.FieldRef<"B2bChannelBinding", 'String'>
  readonly lastPushedAt: Prisma.FieldRef<"B2bChannelBinding", 'DateTime'>
}
    

// Custom InputTypes
/**
 * B2bChannelBinding findUnique
 */
export type B2bChannelBindingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingInclude<ExtArgs> | null
  /**
   * Filter, which B2bChannelBinding to fetch.
   */
  where: Prisma.B2bChannelBindingWhereUniqueInput
}

/**
 * B2bChannelBinding findUniqueOrThrow
 */
export type B2bChannelBindingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingInclude<ExtArgs> | null
  /**
   * Filter, which B2bChannelBinding to fetch.
   */
  where: Prisma.B2bChannelBindingWhereUniqueInput
}

/**
 * B2bChannelBinding findFirst
 */
export type B2bChannelBindingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingInclude<ExtArgs> | null
  /**
   * Filter, which B2bChannelBinding to fetch.
   */
  where?: Prisma.B2bChannelBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of B2bChannelBindings to fetch.
   */
  orderBy?: Prisma.B2bChannelBindingOrderByWithRelationInput | Prisma.B2bChannelBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for B2bChannelBindings.
   */
  cursor?: Prisma.B2bChannelBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` B2bChannelBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` B2bChannelBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of B2bChannelBindings.
   */
  distinct?: Prisma.B2bChannelBindingScalarFieldEnum | Prisma.B2bChannelBindingScalarFieldEnum[]
}

/**
 * B2bChannelBinding findFirstOrThrow
 */
export type B2bChannelBindingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingInclude<ExtArgs> | null
  /**
   * Filter, which B2bChannelBinding to fetch.
   */
  where?: Prisma.B2bChannelBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of B2bChannelBindings to fetch.
   */
  orderBy?: Prisma.B2bChannelBindingOrderByWithRelationInput | Prisma.B2bChannelBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for B2bChannelBindings.
   */
  cursor?: Prisma.B2bChannelBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` B2bChannelBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` B2bChannelBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of B2bChannelBindings.
   */
  distinct?: Prisma.B2bChannelBindingScalarFieldEnum | Prisma.B2bChannelBindingScalarFieldEnum[]
}

/**
 * B2bChannelBinding findMany
 */
export type B2bChannelBindingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingInclude<ExtArgs> | null
  /**
   * Filter, which B2bChannelBindings to fetch.
   */
  where?: Prisma.B2bChannelBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of B2bChannelBindings to fetch.
   */
  orderBy?: Prisma.B2bChannelBindingOrderByWithRelationInput | Prisma.B2bChannelBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing B2bChannelBindings.
   */
  cursor?: Prisma.B2bChannelBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` B2bChannelBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` B2bChannelBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of B2bChannelBindings.
   */
  distinct?: Prisma.B2bChannelBindingScalarFieldEnum | Prisma.B2bChannelBindingScalarFieldEnum[]
}

/**
 * B2bChannelBinding create
 */
export type B2bChannelBindingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingInclude<ExtArgs> | null
  /**
   * The data needed to create a B2bChannelBinding.
   */
  data: Prisma.XOR<Prisma.B2bChannelBindingCreateInput, Prisma.B2bChannelBindingUncheckedCreateInput>
}

/**
 * B2bChannelBinding createMany
 */
export type B2bChannelBindingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many B2bChannelBindings.
   */
  data: Prisma.B2bChannelBindingCreateManyInput | Prisma.B2bChannelBindingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * B2bChannelBinding createManyAndReturn
 */
export type B2bChannelBindingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * The data used to create many B2bChannelBindings.
   */
  data: Prisma.B2bChannelBindingCreateManyInput | Prisma.B2bChannelBindingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * B2bChannelBinding update
 */
export type B2bChannelBindingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingInclude<ExtArgs> | null
  /**
   * The data needed to update a B2bChannelBinding.
   */
  data: Prisma.XOR<Prisma.B2bChannelBindingUpdateInput, Prisma.B2bChannelBindingUncheckedUpdateInput>
  /**
   * Choose, which B2bChannelBinding to update.
   */
  where: Prisma.B2bChannelBindingWhereUniqueInput
}

/**
 * B2bChannelBinding updateMany
 */
export type B2bChannelBindingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update B2bChannelBindings.
   */
  data: Prisma.XOR<Prisma.B2bChannelBindingUpdateManyMutationInput, Prisma.B2bChannelBindingUncheckedUpdateManyInput>
  /**
   * Filter which B2bChannelBindings to update
   */
  where?: Prisma.B2bChannelBindingWhereInput
  /**
   * Limit how many B2bChannelBindings to update.
   */
  limit?: number
}

/**
 * B2bChannelBinding updateManyAndReturn
 */
export type B2bChannelBindingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * The data used to update B2bChannelBindings.
   */
  data: Prisma.XOR<Prisma.B2bChannelBindingUpdateManyMutationInput, Prisma.B2bChannelBindingUncheckedUpdateManyInput>
  /**
   * Filter which B2bChannelBindings to update
   */
  where?: Prisma.B2bChannelBindingWhereInput
  /**
   * Limit how many B2bChannelBindings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * B2bChannelBinding upsert
 */
export type B2bChannelBindingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingInclude<ExtArgs> | null
  /**
   * The filter to search for the B2bChannelBinding to update in case it exists.
   */
  where: Prisma.B2bChannelBindingWhereUniqueInput
  /**
   * In case the B2bChannelBinding found by the `where` argument doesn't exist, create a new B2bChannelBinding with this data.
   */
  create: Prisma.XOR<Prisma.B2bChannelBindingCreateInput, Prisma.B2bChannelBindingUncheckedCreateInput>
  /**
   * In case the B2bChannelBinding was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.B2bChannelBindingUpdateInput, Prisma.B2bChannelBindingUncheckedUpdateInput>
}

/**
 * B2bChannelBinding delete
 */
export type B2bChannelBindingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingInclude<ExtArgs> | null
  /**
   * Filter which B2bChannelBinding to delete.
   */
  where: Prisma.B2bChannelBindingWhereUniqueInput
}

/**
 * B2bChannelBinding deleteMany
 */
export type B2bChannelBindingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which B2bChannelBindings to delete
   */
  where?: Prisma.B2bChannelBindingWhereInput
  /**
   * Limit how many B2bChannelBindings to delete.
   */
  limit?: number
}

/**
 * B2bChannelBinding without action
 */
export type B2bChannelBindingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the B2bChannelBinding
   */
  select?: Prisma.B2bChannelBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the B2bChannelBinding
   */
  omit?: Prisma.B2bChannelBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.B2bChannelBindingInclude<ExtArgs> | null
}
