
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Emplacement` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Emplacement
 * Un **emplacement** (boutique / point de vente) et ses modes. S'il fait « sur
 * place », il ouvre une grille de tables click & collect (une URL + un QR par
 * table). Contexte `locations` — aucune dépendance au catalogue.
 */
export type EmplacementModel = runtime.Types.Result.DefaultSelection<Prisma.$EmplacementPayload>

export type AggregateEmplacement = {
  _count: EmplacementCountAggregateOutputType | null
  _min: EmplacementMinAggregateOutputType | null
  _max: EmplacementMaxAggregateOutputType | null
}

export type EmplacementMinAggregateOutputType = {
  id: string | null
  name: string | null
  clickCollect: boolean | null
  surPlace: boolean | null
  baseUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EmplacementMaxAggregateOutputType = {
  id: string | null
  name: string | null
  clickCollect: boolean | null
  surPlace: boolean | null
  baseUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EmplacementCountAggregateOutputType = {
  id: number
  name: number
  clickCollect: number
  surPlace: number
  baseUrl: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type EmplacementMinAggregateInputType = {
  id?: true
  name?: true
  clickCollect?: true
  surPlace?: true
  baseUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type EmplacementMaxAggregateInputType = {
  id?: true
  name?: true
  clickCollect?: true
  surPlace?: true
  baseUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type EmplacementCountAggregateInputType = {
  id?: true
  name?: true
  clickCollect?: true
  surPlace?: true
  baseUrl?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type EmplacementAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Emplacement to aggregate.
   */
  where?: Prisma.EmplacementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Emplacements to fetch.
   */
  orderBy?: Prisma.EmplacementOrderByWithRelationInput | Prisma.EmplacementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmplacementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Emplacements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Emplacements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Emplacements
  **/
  _count?: true | EmplacementCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmplacementMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmplacementMaxAggregateInputType
}

export type GetEmplacementAggregateType<T extends EmplacementAggregateArgs> = {
      [P in keyof T & keyof AggregateEmplacement]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmplacement[P]>
    : Prisma.GetScalarType<T[P], AggregateEmplacement[P]>
}




export type EmplacementGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmplacementWhereInput
  orderBy?: Prisma.EmplacementOrderByWithAggregationInput | Prisma.EmplacementOrderByWithAggregationInput[]
  by: Prisma.EmplacementScalarFieldEnum[] | Prisma.EmplacementScalarFieldEnum
  having?: Prisma.EmplacementScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmplacementCountAggregateInputType | true
  _min?: EmplacementMinAggregateInputType
  _max?: EmplacementMaxAggregateInputType
}

export type EmplacementGroupByOutputType = {
  id: string
  name: string
  clickCollect: boolean
  surPlace: boolean
  baseUrl: string
  createdAt: Date
  updatedAt: Date
  _count: EmplacementCountAggregateOutputType | null
  _min: EmplacementMinAggregateOutputType | null
  _max: EmplacementMaxAggregateOutputType | null
}

export type GetEmplacementGroupByPayload<T extends EmplacementGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmplacementGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmplacementGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmplacementGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmplacementGroupByOutputType[P]>
      }
    >
  >



export type EmplacementWhereInput = {
  AND?: Prisma.EmplacementWhereInput | Prisma.EmplacementWhereInput[]
  OR?: Prisma.EmplacementWhereInput[]
  NOT?: Prisma.EmplacementWhereInput | Prisma.EmplacementWhereInput[]
  id?: Prisma.StringFilter<"Emplacement"> | string
  name?: Prisma.StringFilter<"Emplacement"> | string
  clickCollect?: Prisma.BoolFilter<"Emplacement"> | boolean
  surPlace?: Prisma.BoolFilter<"Emplacement"> | boolean
  baseUrl?: Prisma.StringFilter<"Emplacement"> | string
  createdAt?: Prisma.DateTimeFilter<"Emplacement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Emplacement"> | Date | string
  tables?: Prisma.EmplacementTableListRelationFilter
}

export type EmplacementOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  clickCollect?: Prisma.SortOrder
  surPlace?: Prisma.SortOrder
  baseUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  tables?: Prisma.EmplacementTableOrderByRelationAggregateInput
}

export type EmplacementWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EmplacementWhereInput | Prisma.EmplacementWhereInput[]
  OR?: Prisma.EmplacementWhereInput[]
  NOT?: Prisma.EmplacementWhereInput | Prisma.EmplacementWhereInput[]
  name?: Prisma.StringFilter<"Emplacement"> | string
  clickCollect?: Prisma.BoolFilter<"Emplacement"> | boolean
  surPlace?: Prisma.BoolFilter<"Emplacement"> | boolean
  baseUrl?: Prisma.StringFilter<"Emplacement"> | string
  createdAt?: Prisma.DateTimeFilter<"Emplacement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Emplacement"> | Date | string
  tables?: Prisma.EmplacementTableListRelationFilter
}, "id">

export type EmplacementOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  clickCollect?: Prisma.SortOrder
  surPlace?: Prisma.SortOrder
  baseUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.EmplacementCountOrderByAggregateInput
  _max?: Prisma.EmplacementMaxOrderByAggregateInput
  _min?: Prisma.EmplacementMinOrderByAggregateInput
}

export type EmplacementScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmplacementScalarWhereWithAggregatesInput | Prisma.EmplacementScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmplacementScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmplacementScalarWhereWithAggregatesInput | Prisma.EmplacementScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Emplacement"> | string
  name?: Prisma.StringWithAggregatesFilter<"Emplacement"> | string
  clickCollect?: Prisma.BoolWithAggregatesFilter<"Emplacement"> | boolean
  surPlace?: Prisma.BoolWithAggregatesFilter<"Emplacement"> | boolean
  baseUrl?: Prisma.StringWithAggregatesFilter<"Emplacement"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Emplacement"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Emplacement"> | Date | string
}

export type EmplacementCreateInput = {
  id: string
  name: string
  clickCollect?: boolean
  surPlace?: boolean
  baseUrl?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  tables?: Prisma.EmplacementTableCreateNestedManyWithoutEmplacementInput
}

export type EmplacementUncheckedCreateInput = {
  id: string
  name: string
  clickCollect?: boolean
  surPlace?: boolean
  baseUrl?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  tables?: Prisma.EmplacementTableUncheckedCreateNestedManyWithoutEmplacementInput
}

export type EmplacementUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  clickCollect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  surPlace?: Prisma.BoolFieldUpdateOperationsInput | boolean
  baseUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tables?: Prisma.EmplacementTableUpdateManyWithoutEmplacementNestedInput
}

export type EmplacementUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  clickCollect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  surPlace?: Prisma.BoolFieldUpdateOperationsInput | boolean
  baseUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tables?: Prisma.EmplacementTableUncheckedUpdateManyWithoutEmplacementNestedInput
}

export type EmplacementCreateManyInput = {
  id: string
  name: string
  clickCollect?: boolean
  surPlace?: boolean
  baseUrl?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EmplacementUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  clickCollect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  surPlace?: Prisma.BoolFieldUpdateOperationsInput | boolean
  baseUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmplacementUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  clickCollect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  surPlace?: Prisma.BoolFieldUpdateOperationsInput | boolean
  baseUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmplacementCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  clickCollect?: Prisma.SortOrder
  surPlace?: Prisma.SortOrder
  baseUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EmplacementMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  clickCollect?: Prisma.SortOrder
  surPlace?: Prisma.SortOrder
  baseUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EmplacementMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  clickCollect?: Prisma.SortOrder
  surPlace?: Prisma.SortOrder
  baseUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EmplacementScalarRelationFilter = {
  is?: Prisma.EmplacementWhereInput
  isNot?: Prisma.EmplacementWhereInput
}

export type EmplacementCreateNestedOneWithoutTablesInput = {
  create?: Prisma.XOR<Prisma.EmplacementCreateWithoutTablesInput, Prisma.EmplacementUncheckedCreateWithoutTablesInput>
  connectOrCreate?: Prisma.EmplacementCreateOrConnectWithoutTablesInput
  connect?: Prisma.EmplacementWhereUniqueInput
}

export type EmplacementUpdateOneRequiredWithoutTablesNestedInput = {
  create?: Prisma.XOR<Prisma.EmplacementCreateWithoutTablesInput, Prisma.EmplacementUncheckedCreateWithoutTablesInput>
  connectOrCreate?: Prisma.EmplacementCreateOrConnectWithoutTablesInput
  upsert?: Prisma.EmplacementUpsertWithoutTablesInput
  connect?: Prisma.EmplacementWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EmplacementUpdateToOneWithWhereWithoutTablesInput, Prisma.EmplacementUpdateWithoutTablesInput>, Prisma.EmplacementUncheckedUpdateWithoutTablesInput>
}

export type EmplacementCreateWithoutTablesInput = {
  id: string
  name: string
  clickCollect?: boolean
  surPlace?: boolean
  baseUrl?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EmplacementUncheckedCreateWithoutTablesInput = {
  id: string
  name: string
  clickCollect?: boolean
  surPlace?: boolean
  baseUrl?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EmplacementCreateOrConnectWithoutTablesInput = {
  where: Prisma.EmplacementWhereUniqueInput
  create: Prisma.XOR<Prisma.EmplacementCreateWithoutTablesInput, Prisma.EmplacementUncheckedCreateWithoutTablesInput>
}

export type EmplacementUpsertWithoutTablesInput = {
  update: Prisma.XOR<Prisma.EmplacementUpdateWithoutTablesInput, Prisma.EmplacementUncheckedUpdateWithoutTablesInput>
  create: Prisma.XOR<Prisma.EmplacementCreateWithoutTablesInput, Prisma.EmplacementUncheckedCreateWithoutTablesInput>
  where?: Prisma.EmplacementWhereInput
}

export type EmplacementUpdateToOneWithWhereWithoutTablesInput = {
  where?: Prisma.EmplacementWhereInput
  data: Prisma.XOR<Prisma.EmplacementUpdateWithoutTablesInput, Prisma.EmplacementUncheckedUpdateWithoutTablesInput>
}

export type EmplacementUpdateWithoutTablesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  clickCollect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  surPlace?: Prisma.BoolFieldUpdateOperationsInput | boolean
  baseUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmplacementUncheckedUpdateWithoutTablesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  clickCollect?: Prisma.BoolFieldUpdateOperationsInput | boolean
  surPlace?: Prisma.BoolFieldUpdateOperationsInput | boolean
  baseUrl?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type EmplacementCountOutputType
 */

export type EmplacementCountOutputType = {
  tables: number
}

export type EmplacementCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tables?: boolean | EmplacementCountOutputTypeCountTablesArgs
}

/**
 * EmplacementCountOutputType without action
 */
export type EmplacementCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementCountOutputType
   */
  select?: Prisma.EmplacementCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EmplacementCountOutputType without action
 */
export type EmplacementCountOutputTypeCountTablesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmplacementTableWhereInput
}


export type EmplacementSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  clickCollect?: boolean
  surPlace?: boolean
  baseUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tables?: boolean | Prisma.Emplacement$tablesArgs<ExtArgs>
  _count?: boolean | Prisma.EmplacementCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emplacement"]>

export type EmplacementSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  clickCollect?: boolean
  surPlace?: boolean
  baseUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["emplacement"]>

export type EmplacementSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  clickCollect?: boolean
  surPlace?: boolean
  baseUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["emplacement"]>

export type EmplacementSelectScalar = {
  id?: boolean
  name?: boolean
  clickCollect?: boolean
  surPlace?: boolean
  baseUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type EmplacementOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "clickCollect" | "surPlace" | "baseUrl" | "createdAt" | "updatedAt", ExtArgs["result"]["emplacement"]>
export type EmplacementInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tables?: boolean | Prisma.Emplacement$tablesArgs<ExtArgs>
  _count?: boolean | Prisma.EmplacementCountOutputTypeDefaultArgs<ExtArgs>
}
export type EmplacementIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type EmplacementIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $EmplacementPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Emplacement"
  objects: {
    tables: Prisma.$EmplacementTablePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    /**
     * Vente à emporter en ligne.
     */
    clickCollect: boolean
    /**
     * Consommation sur place — ouvre les tables.
     */
    surPlace: boolean
    /**
     * URL de base du click & collect (`baseUrl?table=N&k=token`).
     */
    baseUrl: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["emplacement"]>
  composites: {}
}

export type EmplacementGetPayload<S extends boolean | null | undefined | EmplacementDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmplacementPayload, S>

export type EmplacementCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmplacementFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmplacementCountAggregateInputType | true
  }

export interface EmplacementDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Emplacement'], meta: { name: 'Emplacement' } }
  /**
   * Find zero or one Emplacement that matches the filter.
   * @param {EmplacementFindUniqueArgs} args - Arguments to find a Emplacement
   * @example
   * // Get one Emplacement
   * const emplacement = await prisma.emplacement.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmplacementFindUniqueArgs>(args: Prisma.SelectSubset<T, EmplacementFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmplacementClient<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Emplacement that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmplacementFindUniqueOrThrowArgs} args - Arguments to find a Emplacement
   * @example
   * // Get one Emplacement
   * const emplacement = await prisma.emplacement.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmplacementFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmplacementFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmplacementClient<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Emplacement that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementFindFirstArgs} args - Arguments to find a Emplacement
   * @example
   * // Get one Emplacement
   * const emplacement = await prisma.emplacement.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmplacementFindFirstArgs>(args?: Prisma.SelectSubset<T, EmplacementFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmplacementClient<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Emplacement that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementFindFirstOrThrowArgs} args - Arguments to find a Emplacement
   * @example
   * // Get one Emplacement
   * const emplacement = await prisma.emplacement.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmplacementFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmplacementFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmplacementClient<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Emplacements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Emplacements
   * const emplacements = await prisma.emplacement.findMany()
   * 
   * // Get first 10 Emplacements
   * const emplacements = await prisma.emplacement.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const emplacementWithIdOnly = await prisma.emplacement.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmplacementFindManyArgs>(args?: Prisma.SelectSubset<T, EmplacementFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Emplacement.
   * @param {EmplacementCreateArgs} args - Arguments to create a Emplacement.
   * @example
   * // Create one Emplacement
   * const Emplacement = await prisma.emplacement.create({
   *   data: {
   *     // ... data to create a Emplacement
   *   }
   * })
   * 
   */
  create<T extends EmplacementCreateArgs>(args: Prisma.SelectSubset<T, EmplacementCreateArgs<ExtArgs>>): Prisma.Prisma__EmplacementClient<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Emplacements.
   * @param {EmplacementCreateManyArgs} args - Arguments to create many Emplacements.
   * @example
   * // Create many Emplacements
   * const emplacement = await prisma.emplacement.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmplacementCreateManyArgs>(args?: Prisma.SelectSubset<T, EmplacementCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Emplacements and returns the data saved in the database.
   * @param {EmplacementCreateManyAndReturnArgs} args - Arguments to create many Emplacements.
   * @example
   * // Create many Emplacements
   * const emplacement = await prisma.emplacement.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Emplacements and only return the `id`
   * const emplacementWithIdOnly = await prisma.emplacement.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmplacementCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmplacementCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Emplacement.
   * @param {EmplacementDeleteArgs} args - Arguments to delete one Emplacement.
   * @example
   * // Delete one Emplacement
   * const Emplacement = await prisma.emplacement.delete({
   *   where: {
   *     // ... filter to delete one Emplacement
   *   }
   * })
   * 
   */
  delete<T extends EmplacementDeleteArgs>(args: Prisma.SelectSubset<T, EmplacementDeleteArgs<ExtArgs>>): Prisma.Prisma__EmplacementClient<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Emplacement.
   * @param {EmplacementUpdateArgs} args - Arguments to update one Emplacement.
   * @example
   * // Update one Emplacement
   * const emplacement = await prisma.emplacement.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmplacementUpdateArgs>(args: Prisma.SelectSubset<T, EmplacementUpdateArgs<ExtArgs>>): Prisma.Prisma__EmplacementClient<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Emplacements.
   * @param {EmplacementDeleteManyArgs} args - Arguments to filter Emplacements to delete.
   * @example
   * // Delete a few Emplacements
   * const { count } = await prisma.emplacement.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmplacementDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmplacementDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Emplacements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Emplacements
   * const emplacement = await prisma.emplacement.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmplacementUpdateManyArgs>(args: Prisma.SelectSubset<T, EmplacementUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Emplacements and returns the data updated in the database.
   * @param {EmplacementUpdateManyAndReturnArgs} args - Arguments to update many Emplacements.
   * @example
   * // Update many Emplacements
   * const emplacement = await prisma.emplacement.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Emplacements and only return the `id`
   * const emplacementWithIdOnly = await prisma.emplacement.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmplacementUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmplacementUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Emplacement.
   * @param {EmplacementUpsertArgs} args - Arguments to update or create a Emplacement.
   * @example
   * // Update or create a Emplacement
   * const emplacement = await prisma.emplacement.upsert({
   *   create: {
   *     // ... data to create a Emplacement
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Emplacement we want to update
   *   }
   * })
   */
  upsert<T extends EmplacementUpsertArgs>(args: Prisma.SelectSubset<T, EmplacementUpsertArgs<ExtArgs>>): Prisma.Prisma__EmplacementClient<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Emplacements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementCountArgs} args - Arguments to filter Emplacements to count.
   * @example
   * // Count the number of Emplacements
   * const count = await prisma.emplacement.count({
   *   where: {
   *     // ... the filter for the Emplacements we want to count
   *   }
   * })
  **/
  count<T extends EmplacementCountArgs>(
    args?: Prisma.Subset<T, EmplacementCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmplacementCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Emplacement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmplacementAggregateArgs>(args: Prisma.Subset<T, EmplacementAggregateArgs>): Prisma.PrismaPromise<GetEmplacementAggregateType<T>>

  /**
   * Group by Emplacement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmplacementGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmplacementGroupByArgs['orderBy'] }
      : { orderBy?: EmplacementGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmplacementGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmplacementGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Emplacement model
 */
readonly fields: EmplacementFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Emplacement.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmplacementClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tables<T extends Prisma.Emplacement$tablesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Emplacement$tablesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Emplacement model
 */
export interface EmplacementFieldRefs {
  readonly id: Prisma.FieldRef<"Emplacement", 'String'>
  readonly name: Prisma.FieldRef<"Emplacement", 'String'>
  readonly clickCollect: Prisma.FieldRef<"Emplacement", 'Boolean'>
  readonly surPlace: Prisma.FieldRef<"Emplacement", 'Boolean'>
  readonly baseUrl: Prisma.FieldRef<"Emplacement", 'String'>
  readonly createdAt: Prisma.FieldRef<"Emplacement", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Emplacement", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Emplacement findUnique
 */
export type EmplacementFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementInclude<ExtArgs> | null
  /**
   * Filter, which Emplacement to fetch.
   */
  where: Prisma.EmplacementWhereUniqueInput
}

/**
 * Emplacement findUniqueOrThrow
 */
export type EmplacementFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementInclude<ExtArgs> | null
  /**
   * Filter, which Emplacement to fetch.
   */
  where: Prisma.EmplacementWhereUniqueInput
}

/**
 * Emplacement findFirst
 */
export type EmplacementFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementInclude<ExtArgs> | null
  /**
   * Filter, which Emplacement to fetch.
   */
  where?: Prisma.EmplacementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Emplacements to fetch.
   */
  orderBy?: Prisma.EmplacementOrderByWithRelationInput | Prisma.EmplacementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Emplacements.
   */
  cursor?: Prisma.EmplacementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Emplacements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Emplacements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Emplacements.
   */
  distinct?: Prisma.EmplacementScalarFieldEnum | Prisma.EmplacementScalarFieldEnum[]
}

/**
 * Emplacement findFirstOrThrow
 */
export type EmplacementFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementInclude<ExtArgs> | null
  /**
   * Filter, which Emplacement to fetch.
   */
  where?: Prisma.EmplacementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Emplacements to fetch.
   */
  orderBy?: Prisma.EmplacementOrderByWithRelationInput | Prisma.EmplacementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Emplacements.
   */
  cursor?: Prisma.EmplacementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Emplacements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Emplacements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Emplacements.
   */
  distinct?: Prisma.EmplacementScalarFieldEnum | Prisma.EmplacementScalarFieldEnum[]
}

/**
 * Emplacement findMany
 */
export type EmplacementFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementInclude<ExtArgs> | null
  /**
   * Filter, which Emplacements to fetch.
   */
  where?: Prisma.EmplacementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Emplacements to fetch.
   */
  orderBy?: Prisma.EmplacementOrderByWithRelationInput | Prisma.EmplacementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Emplacements.
   */
  cursor?: Prisma.EmplacementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Emplacements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Emplacements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Emplacements.
   */
  distinct?: Prisma.EmplacementScalarFieldEnum | Prisma.EmplacementScalarFieldEnum[]
}

/**
 * Emplacement create
 */
export type EmplacementCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementInclude<ExtArgs> | null
  /**
   * The data needed to create a Emplacement.
   */
  data: Prisma.XOR<Prisma.EmplacementCreateInput, Prisma.EmplacementUncheckedCreateInput>
}

/**
 * Emplacement createMany
 */
export type EmplacementCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Emplacements.
   */
  data: Prisma.EmplacementCreateManyInput | Prisma.EmplacementCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Emplacement createManyAndReturn
 */
export type EmplacementCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * The data used to create many Emplacements.
   */
  data: Prisma.EmplacementCreateManyInput | Prisma.EmplacementCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Emplacement update
 */
export type EmplacementUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementInclude<ExtArgs> | null
  /**
   * The data needed to update a Emplacement.
   */
  data: Prisma.XOR<Prisma.EmplacementUpdateInput, Prisma.EmplacementUncheckedUpdateInput>
  /**
   * Choose, which Emplacement to update.
   */
  where: Prisma.EmplacementWhereUniqueInput
}

/**
 * Emplacement updateMany
 */
export type EmplacementUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Emplacements.
   */
  data: Prisma.XOR<Prisma.EmplacementUpdateManyMutationInput, Prisma.EmplacementUncheckedUpdateManyInput>
  /**
   * Filter which Emplacements to update
   */
  where?: Prisma.EmplacementWhereInput
  /**
   * Limit how many Emplacements to update.
   */
  limit?: number
}

/**
 * Emplacement updateManyAndReturn
 */
export type EmplacementUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * The data used to update Emplacements.
   */
  data: Prisma.XOR<Prisma.EmplacementUpdateManyMutationInput, Prisma.EmplacementUncheckedUpdateManyInput>
  /**
   * Filter which Emplacements to update
   */
  where?: Prisma.EmplacementWhereInput
  /**
   * Limit how many Emplacements to update.
   */
  limit?: number
}

/**
 * Emplacement upsert
 */
export type EmplacementUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementInclude<ExtArgs> | null
  /**
   * The filter to search for the Emplacement to update in case it exists.
   */
  where: Prisma.EmplacementWhereUniqueInput
  /**
   * In case the Emplacement found by the `where` argument doesn't exist, create a new Emplacement with this data.
   */
  create: Prisma.XOR<Prisma.EmplacementCreateInput, Prisma.EmplacementUncheckedCreateInput>
  /**
   * In case the Emplacement was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmplacementUpdateInput, Prisma.EmplacementUncheckedUpdateInput>
}

/**
 * Emplacement delete
 */
export type EmplacementDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementInclude<ExtArgs> | null
  /**
   * Filter which Emplacement to delete.
   */
  where: Prisma.EmplacementWhereUniqueInput
}

/**
 * Emplacement deleteMany
 */
export type EmplacementDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Emplacements to delete
   */
  where?: Prisma.EmplacementWhereInput
  /**
   * Limit how many Emplacements to delete.
   */
  limit?: number
}

/**
 * Emplacement.tables
 */
export type Emplacement$tablesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
  where?: Prisma.EmplacementTableWhereInput
  orderBy?: Prisma.EmplacementTableOrderByWithRelationInput | Prisma.EmplacementTableOrderByWithRelationInput[]
  cursor?: Prisma.EmplacementTableWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmplacementTableScalarFieldEnum | Prisma.EmplacementTableScalarFieldEnum[]
}

/**
 * Emplacement without action
 */
export type EmplacementDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Emplacement
   */
  select?: Prisma.EmplacementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Emplacement
   */
  omit?: Prisma.EmplacementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementInclude<ExtArgs> | null
}
