
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EmplacementTable` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model EmplacementTable
 * Une **table** d'un emplacement sur place. Le `number` est verrouillé (identité
 * de l'URL) : clé primaire composite `(emplacement, number)`. Suppression en
 * cascade avec l'emplacement.
 */
export type EmplacementTableModel = runtime.Types.Result.DefaultSelection<Prisma.$EmplacementTablePayload>

export type AggregateEmplacementTable = {
  _count: EmplacementTableCountAggregateOutputType | null
  _avg: EmplacementTableAvgAggregateOutputType | null
  _sum: EmplacementTableSumAggregateOutputType | null
  _min: EmplacementTableMinAggregateOutputType | null
  _max: EmplacementTableMaxAggregateOutputType | null
}

export type EmplacementTableAvgAggregateOutputType = {
  number: number | null
}

export type EmplacementTableSumAggregateOutputType = {
  number: number | null
}

export type EmplacementTableMinAggregateOutputType = {
  emplacementId: string | null
  number: number | null
  qrCreated: boolean | null
  token: string | null
}

export type EmplacementTableMaxAggregateOutputType = {
  emplacementId: string | null
  number: number | null
  qrCreated: boolean | null
  token: string | null
}

export type EmplacementTableCountAggregateOutputType = {
  emplacementId: number
  number: number
  qrCreated: number
  token: number
  _all: number
}


export type EmplacementTableAvgAggregateInputType = {
  number?: true
}

export type EmplacementTableSumAggregateInputType = {
  number?: true
}

export type EmplacementTableMinAggregateInputType = {
  emplacementId?: true
  number?: true
  qrCreated?: true
  token?: true
}

export type EmplacementTableMaxAggregateInputType = {
  emplacementId?: true
  number?: true
  qrCreated?: true
  token?: true
}

export type EmplacementTableCountAggregateInputType = {
  emplacementId?: true
  number?: true
  qrCreated?: true
  token?: true
  _all?: true
}

export type EmplacementTableAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmplacementTable to aggregate.
   */
  where?: Prisma.EmplacementTableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmplacementTables to fetch.
   */
  orderBy?: Prisma.EmplacementTableOrderByWithRelationInput | Prisma.EmplacementTableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmplacementTableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmplacementTables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmplacementTables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EmplacementTables
  **/
  _count?: true | EmplacementTableCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EmplacementTableAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EmplacementTableSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmplacementTableMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmplacementTableMaxAggregateInputType
}

export type GetEmplacementTableAggregateType<T extends EmplacementTableAggregateArgs> = {
      [P in keyof T & keyof AggregateEmplacementTable]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmplacementTable[P]>
    : Prisma.GetScalarType<T[P], AggregateEmplacementTable[P]>
}




export type EmplacementTableGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmplacementTableWhereInput
  orderBy?: Prisma.EmplacementTableOrderByWithAggregationInput | Prisma.EmplacementTableOrderByWithAggregationInput[]
  by: Prisma.EmplacementTableScalarFieldEnum[] | Prisma.EmplacementTableScalarFieldEnum
  having?: Prisma.EmplacementTableScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmplacementTableCountAggregateInputType | true
  _avg?: EmplacementTableAvgAggregateInputType
  _sum?: EmplacementTableSumAggregateInputType
  _min?: EmplacementTableMinAggregateInputType
  _max?: EmplacementTableMaxAggregateInputType
}

export type EmplacementTableGroupByOutputType = {
  emplacementId: string
  number: number
  qrCreated: boolean
  token: string | null
  _count: EmplacementTableCountAggregateOutputType | null
  _avg: EmplacementTableAvgAggregateOutputType | null
  _sum: EmplacementTableSumAggregateOutputType | null
  _min: EmplacementTableMinAggregateOutputType | null
  _max: EmplacementTableMaxAggregateOutputType | null
}

export type GetEmplacementTableGroupByPayload<T extends EmplacementTableGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmplacementTableGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmplacementTableGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmplacementTableGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmplacementTableGroupByOutputType[P]>
      }
    >
  >



export type EmplacementTableWhereInput = {
  AND?: Prisma.EmplacementTableWhereInput | Prisma.EmplacementTableWhereInput[]
  OR?: Prisma.EmplacementTableWhereInput[]
  NOT?: Prisma.EmplacementTableWhereInput | Prisma.EmplacementTableWhereInput[]
  emplacementId?: Prisma.StringFilter<"EmplacementTable"> | string
  number?: Prisma.IntFilter<"EmplacementTable"> | number
  qrCreated?: Prisma.BoolFilter<"EmplacementTable"> | boolean
  token?: Prisma.StringNullableFilter<"EmplacementTable"> | string | null
  emplacement?: Prisma.XOR<Prisma.EmplacementScalarRelationFilter, Prisma.EmplacementWhereInput>
}

export type EmplacementTableOrderByWithRelationInput = {
  emplacementId?: Prisma.SortOrder
  number?: Prisma.SortOrder
  qrCreated?: Prisma.SortOrder
  token?: Prisma.SortOrderInput | Prisma.SortOrder
  emplacement?: Prisma.EmplacementOrderByWithRelationInput
}

export type EmplacementTableWhereUniqueInput = Prisma.AtLeast<{
  emplacementId_number?: Prisma.EmplacementTableEmplacementIdNumberCompoundUniqueInput
  AND?: Prisma.EmplacementTableWhereInput | Prisma.EmplacementTableWhereInput[]
  OR?: Prisma.EmplacementTableWhereInput[]
  NOT?: Prisma.EmplacementTableWhereInput | Prisma.EmplacementTableWhereInput[]
  emplacementId?: Prisma.StringFilter<"EmplacementTable"> | string
  number?: Prisma.IntFilter<"EmplacementTable"> | number
  qrCreated?: Prisma.BoolFilter<"EmplacementTable"> | boolean
  token?: Prisma.StringNullableFilter<"EmplacementTable"> | string | null
  emplacement?: Prisma.XOR<Prisma.EmplacementScalarRelationFilter, Prisma.EmplacementWhereInput>
}, "emplacementId_number">

export type EmplacementTableOrderByWithAggregationInput = {
  emplacementId?: Prisma.SortOrder
  number?: Prisma.SortOrder
  qrCreated?: Prisma.SortOrder
  token?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EmplacementTableCountOrderByAggregateInput
  _avg?: Prisma.EmplacementTableAvgOrderByAggregateInput
  _max?: Prisma.EmplacementTableMaxOrderByAggregateInput
  _min?: Prisma.EmplacementTableMinOrderByAggregateInput
  _sum?: Prisma.EmplacementTableSumOrderByAggregateInput
}

export type EmplacementTableScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmplacementTableScalarWhereWithAggregatesInput | Prisma.EmplacementTableScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmplacementTableScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmplacementTableScalarWhereWithAggregatesInput | Prisma.EmplacementTableScalarWhereWithAggregatesInput[]
  emplacementId?: Prisma.StringWithAggregatesFilter<"EmplacementTable"> | string
  number?: Prisma.IntWithAggregatesFilter<"EmplacementTable"> | number
  qrCreated?: Prisma.BoolWithAggregatesFilter<"EmplacementTable"> | boolean
  token?: Prisma.StringNullableWithAggregatesFilter<"EmplacementTable"> | string | null
}

export type EmplacementTableCreateInput = {
  number: number
  qrCreated?: boolean
  token?: string | null
  emplacement: Prisma.EmplacementCreateNestedOneWithoutTablesInput
}

export type EmplacementTableUncheckedCreateInput = {
  emplacementId: string
  number: number
  qrCreated?: boolean
  token?: string | null
}

export type EmplacementTableUpdateInput = {
  number?: Prisma.IntFieldUpdateOperationsInput | number
  qrCreated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emplacement?: Prisma.EmplacementUpdateOneRequiredWithoutTablesNestedInput
}

export type EmplacementTableUncheckedUpdateInput = {
  emplacementId?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  qrCreated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EmplacementTableCreateManyInput = {
  emplacementId: string
  number: number
  qrCreated?: boolean
  token?: string | null
}

export type EmplacementTableUpdateManyMutationInput = {
  number?: Prisma.IntFieldUpdateOperationsInput | number
  qrCreated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EmplacementTableUncheckedUpdateManyInput = {
  emplacementId?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  qrCreated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EmplacementTableListRelationFilter = {
  every?: Prisma.EmplacementTableWhereInput
  some?: Prisma.EmplacementTableWhereInput
  none?: Prisma.EmplacementTableWhereInput
}

export type EmplacementTableOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EmplacementTableEmplacementIdNumberCompoundUniqueInput = {
  emplacementId: string
  number: number
}

export type EmplacementTableCountOrderByAggregateInput = {
  emplacementId?: Prisma.SortOrder
  number?: Prisma.SortOrder
  qrCreated?: Prisma.SortOrder
  token?: Prisma.SortOrder
}

export type EmplacementTableAvgOrderByAggregateInput = {
  number?: Prisma.SortOrder
}

export type EmplacementTableMaxOrderByAggregateInput = {
  emplacementId?: Prisma.SortOrder
  number?: Prisma.SortOrder
  qrCreated?: Prisma.SortOrder
  token?: Prisma.SortOrder
}

export type EmplacementTableMinOrderByAggregateInput = {
  emplacementId?: Prisma.SortOrder
  number?: Prisma.SortOrder
  qrCreated?: Prisma.SortOrder
  token?: Prisma.SortOrder
}

export type EmplacementTableSumOrderByAggregateInput = {
  number?: Prisma.SortOrder
}

export type EmplacementTableCreateNestedManyWithoutEmplacementInput = {
  create?: Prisma.XOR<Prisma.EmplacementTableCreateWithoutEmplacementInput, Prisma.EmplacementTableUncheckedCreateWithoutEmplacementInput> | Prisma.EmplacementTableCreateWithoutEmplacementInput[] | Prisma.EmplacementTableUncheckedCreateWithoutEmplacementInput[]
  connectOrCreate?: Prisma.EmplacementTableCreateOrConnectWithoutEmplacementInput | Prisma.EmplacementTableCreateOrConnectWithoutEmplacementInput[]
  createMany?: Prisma.EmplacementTableCreateManyEmplacementInputEnvelope
  connect?: Prisma.EmplacementTableWhereUniqueInput | Prisma.EmplacementTableWhereUniqueInput[]
}

export type EmplacementTableUncheckedCreateNestedManyWithoutEmplacementInput = {
  create?: Prisma.XOR<Prisma.EmplacementTableCreateWithoutEmplacementInput, Prisma.EmplacementTableUncheckedCreateWithoutEmplacementInput> | Prisma.EmplacementTableCreateWithoutEmplacementInput[] | Prisma.EmplacementTableUncheckedCreateWithoutEmplacementInput[]
  connectOrCreate?: Prisma.EmplacementTableCreateOrConnectWithoutEmplacementInput | Prisma.EmplacementTableCreateOrConnectWithoutEmplacementInput[]
  createMany?: Prisma.EmplacementTableCreateManyEmplacementInputEnvelope
  connect?: Prisma.EmplacementTableWhereUniqueInput | Prisma.EmplacementTableWhereUniqueInput[]
}

export type EmplacementTableUpdateManyWithoutEmplacementNestedInput = {
  create?: Prisma.XOR<Prisma.EmplacementTableCreateWithoutEmplacementInput, Prisma.EmplacementTableUncheckedCreateWithoutEmplacementInput> | Prisma.EmplacementTableCreateWithoutEmplacementInput[] | Prisma.EmplacementTableUncheckedCreateWithoutEmplacementInput[]
  connectOrCreate?: Prisma.EmplacementTableCreateOrConnectWithoutEmplacementInput | Prisma.EmplacementTableCreateOrConnectWithoutEmplacementInput[]
  upsert?: Prisma.EmplacementTableUpsertWithWhereUniqueWithoutEmplacementInput | Prisma.EmplacementTableUpsertWithWhereUniqueWithoutEmplacementInput[]
  createMany?: Prisma.EmplacementTableCreateManyEmplacementInputEnvelope
  set?: Prisma.EmplacementTableWhereUniqueInput | Prisma.EmplacementTableWhereUniqueInput[]
  disconnect?: Prisma.EmplacementTableWhereUniqueInput | Prisma.EmplacementTableWhereUniqueInput[]
  delete?: Prisma.EmplacementTableWhereUniqueInput | Prisma.EmplacementTableWhereUniqueInput[]
  connect?: Prisma.EmplacementTableWhereUniqueInput | Prisma.EmplacementTableWhereUniqueInput[]
  update?: Prisma.EmplacementTableUpdateWithWhereUniqueWithoutEmplacementInput | Prisma.EmplacementTableUpdateWithWhereUniqueWithoutEmplacementInput[]
  updateMany?: Prisma.EmplacementTableUpdateManyWithWhereWithoutEmplacementInput | Prisma.EmplacementTableUpdateManyWithWhereWithoutEmplacementInput[]
  deleteMany?: Prisma.EmplacementTableScalarWhereInput | Prisma.EmplacementTableScalarWhereInput[]
}

export type EmplacementTableUncheckedUpdateManyWithoutEmplacementNestedInput = {
  create?: Prisma.XOR<Prisma.EmplacementTableCreateWithoutEmplacementInput, Prisma.EmplacementTableUncheckedCreateWithoutEmplacementInput> | Prisma.EmplacementTableCreateWithoutEmplacementInput[] | Prisma.EmplacementTableUncheckedCreateWithoutEmplacementInput[]
  connectOrCreate?: Prisma.EmplacementTableCreateOrConnectWithoutEmplacementInput | Prisma.EmplacementTableCreateOrConnectWithoutEmplacementInput[]
  upsert?: Prisma.EmplacementTableUpsertWithWhereUniqueWithoutEmplacementInput | Prisma.EmplacementTableUpsertWithWhereUniqueWithoutEmplacementInput[]
  createMany?: Prisma.EmplacementTableCreateManyEmplacementInputEnvelope
  set?: Prisma.EmplacementTableWhereUniqueInput | Prisma.EmplacementTableWhereUniqueInput[]
  disconnect?: Prisma.EmplacementTableWhereUniqueInput | Prisma.EmplacementTableWhereUniqueInput[]
  delete?: Prisma.EmplacementTableWhereUniqueInput | Prisma.EmplacementTableWhereUniqueInput[]
  connect?: Prisma.EmplacementTableWhereUniqueInput | Prisma.EmplacementTableWhereUniqueInput[]
  update?: Prisma.EmplacementTableUpdateWithWhereUniqueWithoutEmplacementInput | Prisma.EmplacementTableUpdateWithWhereUniqueWithoutEmplacementInput[]
  updateMany?: Prisma.EmplacementTableUpdateManyWithWhereWithoutEmplacementInput | Prisma.EmplacementTableUpdateManyWithWhereWithoutEmplacementInput[]
  deleteMany?: Prisma.EmplacementTableScalarWhereInput | Prisma.EmplacementTableScalarWhereInput[]
}

export type EmplacementTableCreateWithoutEmplacementInput = {
  number: number
  qrCreated?: boolean
  token?: string | null
}

export type EmplacementTableUncheckedCreateWithoutEmplacementInput = {
  number: number
  qrCreated?: boolean
  token?: string | null
}

export type EmplacementTableCreateOrConnectWithoutEmplacementInput = {
  where: Prisma.EmplacementTableWhereUniqueInput
  create: Prisma.XOR<Prisma.EmplacementTableCreateWithoutEmplacementInput, Prisma.EmplacementTableUncheckedCreateWithoutEmplacementInput>
}

export type EmplacementTableCreateManyEmplacementInputEnvelope = {
  data: Prisma.EmplacementTableCreateManyEmplacementInput | Prisma.EmplacementTableCreateManyEmplacementInput[]
  skipDuplicates?: boolean
}

export type EmplacementTableUpsertWithWhereUniqueWithoutEmplacementInput = {
  where: Prisma.EmplacementTableWhereUniqueInput
  update: Prisma.XOR<Prisma.EmplacementTableUpdateWithoutEmplacementInput, Prisma.EmplacementTableUncheckedUpdateWithoutEmplacementInput>
  create: Prisma.XOR<Prisma.EmplacementTableCreateWithoutEmplacementInput, Prisma.EmplacementTableUncheckedCreateWithoutEmplacementInput>
}

export type EmplacementTableUpdateWithWhereUniqueWithoutEmplacementInput = {
  where: Prisma.EmplacementTableWhereUniqueInput
  data: Prisma.XOR<Prisma.EmplacementTableUpdateWithoutEmplacementInput, Prisma.EmplacementTableUncheckedUpdateWithoutEmplacementInput>
}

export type EmplacementTableUpdateManyWithWhereWithoutEmplacementInput = {
  where: Prisma.EmplacementTableScalarWhereInput
  data: Prisma.XOR<Prisma.EmplacementTableUpdateManyMutationInput, Prisma.EmplacementTableUncheckedUpdateManyWithoutEmplacementInput>
}

export type EmplacementTableScalarWhereInput = {
  AND?: Prisma.EmplacementTableScalarWhereInput | Prisma.EmplacementTableScalarWhereInput[]
  OR?: Prisma.EmplacementTableScalarWhereInput[]
  NOT?: Prisma.EmplacementTableScalarWhereInput | Prisma.EmplacementTableScalarWhereInput[]
  emplacementId?: Prisma.StringFilter<"EmplacementTable"> | string
  number?: Prisma.IntFilter<"EmplacementTable"> | number
  qrCreated?: Prisma.BoolFilter<"EmplacementTable"> | boolean
  token?: Prisma.StringNullableFilter<"EmplacementTable"> | string | null
}

export type EmplacementTableCreateManyEmplacementInput = {
  number: number
  qrCreated?: boolean
  token?: string | null
}

export type EmplacementTableUpdateWithoutEmplacementInput = {
  number?: Prisma.IntFieldUpdateOperationsInput | number
  qrCreated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EmplacementTableUncheckedUpdateWithoutEmplacementInput = {
  number?: Prisma.IntFieldUpdateOperationsInput | number
  qrCreated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EmplacementTableUncheckedUpdateManyWithoutEmplacementInput = {
  number?: Prisma.IntFieldUpdateOperationsInput | number
  qrCreated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type EmplacementTableSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  emplacementId?: boolean
  number?: boolean
  qrCreated?: boolean
  token?: boolean
  emplacement?: boolean | Prisma.EmplacementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emplacementTable"]>

export type EmplacementTableSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  emplacementId?: boolean
  number?: boolean
  qrCreated?: boolean
  token?: boolean
  emplacement?: boolean | Prisma.EmplacementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emplacementTable"]>

export type EmplacementTableSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  emplacementId?: boolean
  number?: boolean
  qrCreated?: boolean
  token?: boolean
  emplacement?: boolean | Prisma.EmplacementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emplacementTable"]>

export type EmplacementTableSelectScalar = {
  emplacementId?: boolean
  number?: boolean
  qrCreated?: boolean
  token?: boolean
}

export type EmplacementTableOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"emplacementId" | "number" | "qrCreated" | "token", ExtArgs["result"]["emplacementTable"]>
export type EmplacementTableInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  emplacement?: boolean | Prisma.EmplacementDefaultArgs<ExtArgs>
}
export type EmplacementTableIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  emplacement?: boolean | Prisma.EmplacementDefaultArgs<ExtArgs>
}
export type EmplacementTableIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  emplacement?: boolean | Prisma.EmplacementDefaultArgs<ExtArgs>
}

export type $EmplacementTablePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EmplacementTable"
  objects: {
    emplacement: Prisma.$EmplacementPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    emplacementId: string
    number: number
    qrCreated: boolean
    /**
     * Token rotatif du QR : le régénérer invalide l'ancien code imprimé.
     * `NULL` = aucun QR généré.
     */
    token: string | null
  }, ExtArgs["result"]["emplacementTable"]>
  composites: {}
}

export type EmplacementTableGetPayload<S extends boolean | null | undefined | EmplacementTableDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload, S>

export type EmplacementTableCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmplacementTableFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmplacementTableCountAggregateInputType | true
  }

export interface EmplacementTableDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EmplacementTable'], meta: { name: 'EmplacementTable' } }
  /**
   * Find zero or one EmplacementTable that matches the filter.
   * @param {EmplacementTableFindUniqueArgs} args - Arguments to find a EmplacementTable
   * @example
   * // Get one EmplacementTable
   * const emplacementTable = await prisma.emplacementTable.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmplacementTableFindUniqueArgs>(args: Prisma.SelectSubset<T, EmplacementTableFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmplacementTableClient<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EmplacementTable that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmplacementTableFindUniqueOrThrowArgs} args - Arguments to find a EmplacementTable
   * @example
   * // Get one EmplacementTable
   * const emplacementTable = await prisma.emplacementTable.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmplacementTableFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmplacementTableFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmplacementTableClient<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmplacementTable that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementTableFindFirstArgs} args - Arguments to find a EmplacementTable
   * @example
   * // Get one EmplacementTable
   * const emplacementTable = await prisma.emplacementTable.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmplacementTableFindFirstArgs>(args?: Prisma.SelectSubset<T, EmplacementTableFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmplacementTableClient<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmplacementTable that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementTableFindFirstOrThrowArgs} args - Arguments to find a EmplacementTable
   * @example
   * // Get one EmplacementTable
   * const emplacementTable = await prisma.emplacementTable.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmplacementTableFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmplacementTableFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmplacementTableClient<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EmplacementTables that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementTableFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EmplacementTables
   * const emplacementTables = await prisma.emplacementTable.findMany()
   * 
   * // Get first 10 EmplacementTables
   * const emplacementTables = await prisma.emplacementTable.findMany({ take: 10 })
   * 
   * // Only select the `emplacementId`
   * const emplacementTableWithEmplacementIdOnly = await prisma.emplacementTable.findMany({ select: { emplacementId: true } })
   * 
   */
  findMany<T extends EmplacementTableFindManyArgs>(args?: Prisma.SelectSubset<T, EmplacementTableFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EmplacementTable.
   * @param {EmplacementTableCreateArgs} args - Arguments to create a EmplacementTable.
   * @example
   * // Create one EmplacementTable
   * const EmplacementTable = await prisma.emplacementTable.create({
   *   data: {
   *     // ... data to create a EmplacementTable
   *   }
   * })
   * 
   */
  create<T extends EmplacementTableCreateArgs>(args: Prisma.SelectSubset<T, EmplacementTableCreateArgs<ExtArgs>>): Prisma.Prisma__EmplacementTableClient<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EmplacementTables.
   * @param {EmplacementTableCreateManyArgs} args - Arguments to create many EmplacementTables.
   * @example
   * // Create many EmplacementTables
   * const emplacementTable = await prisma.emplacementTable.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmplacementTableCreateManyArgs>(args?: Prisma.SelectSubset<T, EmplacementTableCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EmplacementTables and returns the data saved in the database.
   * @param {EmplacementTableCreateManyAndReturnArgs} args - Arguments to create many EmplacementTables.
   * @example
   * // Create many EmplacementTables
   * const emplacementTable = await prisma.emplacementTable.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EmplacementTables and only return the `emplacementId`
   * const emplacementTableWithEmplacementIdOnly = await prisma.emplacementTable.createManyAndReturn({
   *   select: { emplacementId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmplacementTableCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmplacementTableCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EmplacementTable.
   * @param {EmplacementTableDeleteArgs} args - Arguments to delete one EmplacementTable.
   * @example
   * // Delete one EmplacementTable
   * const EmplacementTable = await prisma.emplacementTable.delete({
   *   where: {
   *     // ... filter to delete one EmplacementTable
   *   }
   * })
   * 
   */
  delete<T extends EmplacementTableDeleteArgs>(args: Prisma.SelectSubset<T, EmplacementTableDeleteArgs<ExtArgs>>): Prisma.Prisma__EmplacementTableClient<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EmplacementTable.
   * @param {EmplacementTableUpdateArgs} args - Arguments to update one EmplacementTable.
   * @example
   * // Update one EmplacementTable
   * const emplacementTable = await prisma.emplacementTable.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmplacementTableUpdateArgs>(args: Prisma.SelectSubset<T, EmplacementTableUpdateArgs<ExtArgs>>): Prisma.Prisma__EmplacementTableClient<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EmplacementTables.
   * @param {EmplacementTableDeleteManyArgs} args - Arguments to filter EmplacementTables to delete.
   * @example
   * // Delete a few EmplacementTables
   * const { count } = await prisma.emplacementTable.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmplacementTableDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmplacementTableDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmplacementTables.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementTableUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EmplacementTables
   * const emplacementTable = await prisma.emplacementTable.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmplacementTableUpdateManyArgs>(args: Prisma.SelectSubset<T, EmplacementTableUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmplacementTables and returns the data updated in the database.
   * @param {EmplacementTableUpdateManyAndReturnArgs} args - Arguments to update many EmplacementTables.
   * @example
   * // Update many EmplacementTables
   * const emplacementTable = await prisma.emplacementTable.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EmplacementTables and only return the `emplacementId`
   * const emplacementTableWithEmplacementIdOnly = await prisma.emplacementTable.updateManyAndReturn({
   *   select: { emplacementId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmplacementTableUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmplacementTableUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EmplacementTable.
   * @param {EmplacementTableUpsertArgs} args - Arguments to update or create a EmplacementTable.
   * @example
   * // Update or create a EmplacementTable
   * const emplacementTable = await prisma.emplacementTable.upsert({
   *   create: {
   *     // ... data to create a EmplacementTable
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EmplacementTable we want to update
   *   }
   * })
   */
  upsert<T extends EmplacementTableUpsertArgs>(args: Prisma.SelectSubset<T, EmplacementTableUpsertArgs<ExtArgs>>): Prisma.Prisma__EmplacementTableClient<runtime.Types.Result.GetResult<Prisma.$EmplacementTablePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EmplacementTables.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementTableCountArgs} args - Arguments to filter EmplacementTables to count.
   * @example
   * // Count the number of EmplacementTables
   * const count = await prisma.emplacementTable.count({
   *   where: {
   *     // ... the filter for the EmplacementTables we want to count
   *   }
   * })
  **/
  count<T extends EmplacementTableCountArgs>(
    args?: Prisma.Subset<T, EmplacementTableCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmplacementTableCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EmplacementTable.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementTableAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmplacementTableAggregateArgs>(args: Prisma.Subset<T, EmplacementTableAggregateArgs>): Prisma.PrismaPromise<GetEmplacementTableAggregateType<T>>

  /**
   * Group by EmplacementTable.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmplacementTableGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmplacementTableGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmplacementTableGroupByArgs['orderBy'] }
      : { orderBy?: EmplacementTableGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmplacementTableGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmplacementTableGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EmplacementTable model
 */
readonly fields: EmplacementTableFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EmplacementTable.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmplacementTableClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  emplacement<T extends Prisma.EmplacementDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EmplacementDefaultArgs<ExtArgs>>): Prisma.Prisma__EmplacementClient<runtime.Types.Result.GetResult<Prisma.$EmplacementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EmplacementTable model
 */
export interface EmplacementTableFieldRefs {
  readonly emplacementId: Prisma.FieldRef<"EmplacementTable", 'String'>
  readonly number: Prisma.FieldRef<"EmplacementTable", 'Int'>
  readonly qrCreated: Prisma.FieldRef<"EmplacementTable", 'Boolean'>
  readonly token: Prisma.FieldRef<"EmplacementTable", 'String'>
}
    

// Custom InputTypes
/**
 * EmplacementTable findUnique
 */
export type EmplacementTableFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
  /**
   * Filter, which EmplacementTable to fetch.
   */
  where: Prisma.EmplacementTableWhereUniqueInput
}

/**
 * EmplacementTable findUniqueOrThrow
 */
export type EmplacementTableFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
  /**
   * Filter, which EmplacementTable to fetch.
   */
  where: Prisma.EmplacementTableWhereUniqueInput
}

/**
 * EmplacementTable findFirst
 */
export type EmplacementTableFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
  /**
   * Filter, which EmplacementTable to fetch.
   */
  where?: Prisma.EmplacementTableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmplacementTables to fetch.
   */
  orderBy?: Prisma.EmplacementTableOrderByWithRelationInput | Prisma.EmplacementTableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmplacementTables.
   */
  cursor?: Prisma.EmplacementTableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmplacementTables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmplacementTables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmplacementTables.
   */
  distinct?: Prisma.EmplacementTableScalarFieldEnum | Prisma.EmplacementTableScalarFieldEnum[]
}

/**
 * EmplacementTable findFirstOrThrow
 */
export type EmplacementTableFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
  /**
   * Filter, which EmplacementTable to fetch.
   */
  where?: Prisma.EmplacementTableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmplacementTables to fetch.
   */
  orderBy?: Prisma.EmplacementTableOrderByWithRelationInput | Prisma.EmplacementTableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmplacementTables.
   */
  cursor?: Prisma.EmplacementTableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmplacementTables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmplacementTables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmplacementTables.
   */
  distinct?: Prisma.EmplacementTableScalarFieldEnum | Prisma.EmplacementTableScalarFieldEnum[]
}

/**
 * EmplacementTable findMany
 */
export type EmplacementTableFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
  /**
   * Filter, which EmplacementTables to fetch.
   */
  where?: Prisma.EmplacementTableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmplacementTables to fetch.
   */
  orderBy?: Prisma.EmplacementTableOrderByWithRelationInput | Prisma.EmplacementTableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EmplacementTables.
   */
  cursor?: Prisma.EmplacementTableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmplacementTables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmplacementTables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmplacementTables.
   */
  distinct?: Prisma.EmplacementTableScalarFieldEnum | Prisma.EmplacementTableScalarFieldEnum[]
}

/**
 * EmplacementTable create
 */
export type EmplacementTableCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
  /**
   * The data needed to create a EmplacementTable.
   */
  data: Prisma.XOR<Prisma.EmplacementTableCreateInput, Prisma.EmplacementTableUncheckedCreateInput>
}

/**
 * EmplacementTable createMany
 */
export type EmplacementTableCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EmplacementTables.
   */
  data: Prisma.EmplacementTableCreateManyInput | Prisma.EmplacementTableCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EmplacementTable createManyAndReturn
 */
export type EmplacementTableCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * The data used to create many EmplacementTables.
   */
  data: Prisma.EmplacementTableCreateManyInput | Prisma.EmplacementTableCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EmplacementTable update
 */
export type EmplacementTableUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
  /**
   * The data needed to update a EmplacementTable.
   */
  data: Prisma.XOR<Prisma.EmplacementTableUpdateInput, Prisma.EmplacementTableUncheckedUpdateInput>
  /**
   * Choose, which EmplacementTable to update.
   */
  where: Prisma.EmplacementTableWhereUniqueInput
}

/**
 * EmplacementTable updateMany
 */
export type EmplacementTableUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EmplacementTables.
   */
  data: Prisma.XOR<Prisma.EmplacementTableUpdateManyMutationInput, Prisma.EmplacementTableUncheckedUpdateManyInput>
  /**
   * Filter which EmplacementTables to update
   */
  where?: Prisma.EmplacementTableWhereInput
  /**
   * Limit how many EmplacementTables to update.
   */
  limit?: number
}

/**
 * EmplacementTable updateManyAndReturn
 */
export type EmplacementTableUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * The data used to update EmplacementTables.
   */
  data: Prisma.XOR<Prisma.EmplacementTableUpdateManyMutationInput, Prisma.EmplacementTableUncheckedUpdateManyInput>
  /**
   * Filter which EmplacementTables to update
   */
  where?: Prisma.EmplacementTableWhereInput
  /**
   * Limit how many EmplacementTables to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EmplacementTable upsert
 */
export type EmplacementTableUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
  /**
   * The filter to search for the EmplacementTable to update in case it exists.
   */
  where: Prisma.EmplacementTableWhereUniqueInput
  /**
   * In case the EmplacementTable found by the `where` argument doesn't exist, create a new EmplacementTable with this data.
   */
  create: Prisma.XOR<Prisma.EmplacementTableCreateInput, Prisma.EmplacementTableUncheckedCreateInput>
  /**
   * In case the EmplacementTable was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmplacementTableUpdateInput, Prisma.EmplacementTableUncheckedUpdateInput>
}

/**
 * EmplacementTable delete
 */
export type EmplacementTableDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
  /**
   * Filter which EmplacementTable to delete.
   */
  where: Prisma.EmplacementTableWhereUniqueInput
}

/**
 * EmplacementTable deleteMany
 */
export type EmplacementTableDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmplacementTables to delete
   */
  where?: Prisma.EmplacementTableWhereInput
  /**
   * Limit how many EmplacementTables to delete.
   */
  limit?: number
}

/**
 * EmplacementTable without action
 */
export type EmplacementTableDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmplacementTable
   */
  select?: Prisma.EmplacementTableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmplacementTable
   */
  omit?: Prisma.EmplacementTableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmplacementTableInclude<ExtArgs> | null
}
