
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NutritionDeclaration` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model NutritionDeclaration
 * Fiche réglementaire d'une **déclinaison** — c'est elle qui est mise sur le
 * marché (doc 03). `variant_id` est PK **et** FK (*shared primary key*) : pas
 * d'identifiant de substitution, donc deux fiches sont structurellement
 * impossibles pour une même déclinaison.
 */
export type NutritionDeclarationModel = runtime.Types.Result.DefaultSelection<Prisma.$NutritionDeclarationPayload>

export type AggregateNutritionDeclaration = {
  _count: NutritionDeclarationCountAggregateOutputType | null
  _avg: NutritionDeclarationAvgAggregateOutputType | null
  _sum: NutritionDeclarationSumAggregateOutputType | null
  _min: NutritionDeclarationMinAggregateOutputType | null
  _max: NutritionDeclarationMaxAggregateOutputType | null
}

export type NutritionDeclarationAvgAggregateOutputType = {
  energyKcal: number | null
  carbsG: number | null
  fatG: number | null
  proteinG: number | null
  glycemicIndex: number | null
}

export type NutritionDeclarationSumAggregateOutputType = {
  energyKcal: number | null
  carbsG: number | null
  fatG: number | null
  proteinG: number | null
  glycemicIndex: number | null
}

export type NutritionDeclarationMinAggregateOutputType = {
  variantId: string | null
  energyKcal: number | null
  carbsG: number | null
  fatG: number | null
  proteinG: number | null
  glycemicIndex: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NutritionDeclarationMaxAggregateOutputType = {
  variantId: string | null
  energyKcal: number | null
  carbsG: number | null
  fatG: number | null
  proteinG: number | null
  glycemicIndex: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NutritionDeclarationCountAggregateOutputType = {
  variantId: number
  allergens: number
  mayContain: number
  energyKcal: number
  carbsG: number
  fatG: number
  proteinG: number
  glycemicIndex: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type NutritionDeclarationAvgAggregateInputType = {
  energyKcal?: true
  carbsG?: true
  fatG?: true
  proteinG?: true
  glycemicIndex?: true
}

export type NutritionDeclarationSumAggregateInputType = {
  energyKcal?: true
  carbsG?: true
  fatG?: true
  proteinG?: true
  glycemicIndex?: true
}

export type NutritionDeclarationMinAggregateInputType = {
  variantId?: true
  energyKcal?: true
  carbsG?: true
  fatG?: true
  proteinG?: true
  glycemicIndex?: true
  createdAt?: true
  updatedAt?: true
}

export type NutritionDeclarationMaxAggregateInputType = {
  variantId?: true
  energyKcal?: true
  carbsG?: true
  fatG?: true
  proteinG?: true
  glycemicIndex?: true
  createdAt?: true
  updatedAt?: true
}

export type NutritionDeclarationCountAggregateInputType = {
  variantId?: true
  allergens?: true
  mayContain?: true
  energyKcal?: true
  carbsG?: true
  fatG?: true
  proteinG?: true
  glycemicIndex?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type NutritionDeclarationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NutritionDeclaration to aggregate.
   */
  where?: Prisma.NutritionDeclarationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NutritionDeclarations to fetch.
   */
  orderBy?: Prisma.NutritionDeclarationOrderByWithRelationInput | Prisma.NutritionDeclarationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NutritionDeclarationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NutritionDeclarations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NutritionDeclarations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NutritionDeclarations
  **/
  _count?: true | NutritionDeclarationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NutritionDeclarationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NutritionDeclarationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NutritionDeclarationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NutritionDeclarationMaxAggregateInputType
}

export type GetNutritionDeclarationAggregateType<T extends NutritionDeclarationAggregateArgs> = {
      [P in keyof T & keyof AggregateNutritionDeclaration]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNutritionDeclaration[P]>
    : Prisma.GetScalarType<T[P], AggregateNutritionDeclaration[P]>
}




export type NutritionDeclarationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NutritionDeclarationWhereInput
  orderBy?: Prisma.NutritionDeclarationOrderByWithAggregationInput | Prisma.NutritionDeclarationOrderByWithAggregationInput[]
  by: Prisma.NutritionDeclarationScalarFieldEnum[] | Prisma.NutritionDeclarationScalarFieldEnum
  having?: Prisma.NutritionDeclarationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NutritionDeclarationCountAggregateInputType | true
  _avg?: NutritionDeclarationAvgAggregateInputType
  _sum?: NutritionDeclarationSumAggregateInputType
  _min?: NutritionDeclarationMinAggregateInputType
  _max?: NutritionDeclarationMaxAggregateInputType
}

export type NutritionDeclarationGroupByOutputType = {
  variantId: string
  allergens: runtime.JsonValue
  mayContain: runtime.JsonValue
  energyKcal: number | null
  carbsG: number | null
  fatG: number | null
  proteinG: number | null
  glycemicIndex: number | null
  createdAt: Date
  updatedAt: Date
  _count: NutritionDeclarationCountAggregateOutputType | null
  _avg: NutritionDeclarationAvgAggregateOutputType | null
  _sum: NutritionDeclarationSumAggregateOutputType | null
  _min: NutritionDeclarationMinAggregateOutputType | null
  _max: NutritionDeclarationMaxAggregateOutputType | null
}

export type GetNutritionDeclarationGroupByPayload<T extends NutritionDeclarationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NutritionDeclarationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NutritionDeclarationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NutritionDeclarationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NutritionDeclarationGroupByOutputType[P]>
      }
    >
  >



export type NutritionDeclarationWhereInput = {
  AND?: Prisma.NutritionDeclarationWhereInput | Prisma.NutritionDeclarationWhereInput[]
  OR?: Prisma.NutritionDeclarationWhereInput[]
  NOT?: Prisma.NutritionDeclarationWhereInput | Prisma.NutritionDeclarationWhereInput[]
  variantId?: Prisma.StringFilter<"NutritionDeclaration"> | string
  allergens?: Prisma.JsonFilter<"NutritionDeclaration">
  mayContain?: Prisma.JsonFilter<"NutritionDeclaration">
  energyKcal?: Prisma.FloatNullableFilter<"NutritionDeclaration"> | number | null
  carbsG?: Prisma.FloatNullableFilter<"NutritionDeclaration"> | number | null
  fatG?: Prisma.FloatNullableFilter<"NutritionDeclaration"> | number | null
  proteinG?: Prisma.FloatNullableFilter<"NutritionDeclaration"> | number | null
  glycemicIndex?: Prisma.FloatNullableFilter<"NutritionDeclaration"> | number | null
  createdAt?: Prisma.DateTimeFilter<"NutritionDeclaration"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NutritionDeclaration"> | Date | string
  variant?: Prisma.XOR<Prisma.ProductVariantScalarRelationFilter, Prisma.ProductVariantWhereInput>
}

export type NutritionDeclarationOrderByWithRelationInput = {
  variantId?: Prisma.SortOrder
  allergens?: Prisma.SortOrder
  mayContain?: Prisma.SortOrder
  energyKcal?: Prisma.SortOrderInput | Prisma.SortOrder
  carbsG?: Prisma.SortOrderInput | Prisma.SortOrder
  fatG?: Prisma.SortOrderInput | Prisma.SortOrder
  proteinG?: Prisma.SortOrderInput | Prisma.SortOrder
  glycemicIndex?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  variant?: Prisma.ProductVariantOrderByWithRelationInput
}

export type NutritionDeclarationWhereUniqueInput = Prisma.AtLeast<{
  variantId?: string
  AND?: Prisma.NutritionDeclarationWhereInput | Prisma.NutritionDeclarationWhereInput[]
  OR?: Prisma.NutritionDeclarationWhereInput[]
  NOT?: Prisma.NutritionDeclarationWhereInput | Prisma.NutritionDeclarationWhereInput[]
  allergens?: Prisma.JsonFilter<"NutritionDeclaration">
  mayContain?: Prisma.JsonFilter<"NutritionDeclaration">
  energyKcal?: Prisma.FloatNullableFilter<"NutritionDeclaration"> | number | null
  carbsG?: Prisma.FloatNullableFilter<"NutritionDeclaration"> | number | null
  fatG?: Prisma.FloatNullableFilter<"NutritionDeclaration"> | number | null
  proteinG?: Prisma.FloatNullableFilter<"NutritionDeclaration"> | number | null
  glycemicIndex?: Prisma.FloatNullableFilter<"NutritionDeclaration"> | number | null
  createdAt?: Prisma.DateTimeFilter<"NutritionDeclaration"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NutritionDeclaration"> | Date | string
  variant?: Prisma.XOR<Prisma.ProductVariantScalarRelationFilter, Prisma.ProductVariantWhereInput>
}, "variantId">

export type NutritionDeclarationOrderByWithAggregationInput = {
  variantId?: Prisma.SortOrder
  allergens?: Prisma.SortOrder
  mayContain?: Prisma.SortOrder
  energyKcal?: Prisma.SortOrderInput | Prisma.SortOrder
  carbsG?: Prisma.SortOrderInput | Prisma.SortOrder
  fatG?: Prisma.SortOrderInput | Prisma.SortOrder
  proteinG?: Prisma.SortOrderInput | Prisma.SortOrder
  glycemicIndex?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.NutritionDeclarationCountOrderByAggregateInput
  _avg?: Prisma.NutritionDeclarationAvgOrderByAggregateInput
  _max?: Prisma.NutritionDeclarationMaxOrderByAggregateInput
  _min?: Prisma.NutritionDeclarationMinOrderByAggregateInput
  _sum?: Prisma.NutritionDeclarationSumOrderByAggregateInput
}

export type NutritionDeclarationScalarWhereWithAggregatesInput = {
  AND?: Prisma.NutritionDeclarationScalarWhereWithAggregatesInput | Prisma.NutritionDeclarationScalarWhereWithAggregatesInput[]
  OR?: Prisma.NutritionDeclarationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NutritionDeclarationScalarWhereWithAggregatesInput | Prisma.NutritionDeclarationScalarWhereWithAggregatesInput[]
  variantId?: Prisma.StringWithAggregatesFilter<"NutritionDeclaration"> | string
  allergens?: Prisma.JsonWithAggregatesFilter<"NutritionDeclaration">
  mayContain?: Prisma.JsonWithAggregatesFilter<"NutritionDeclaration">
  energyKcal?: Prisma.FloatNullableWithAggregatesFilter<"NutritionDeclaration"> | number | null
  carbsG?: Prisma.FloatNullableWithAggregatesFilter<"NutritionDeclaration"> | number | null
  fatG?: Prisma.FloatNullableWithAggregatesFilter<"NutritionDeclaration"> | number | null
  proteinG?: Prisma.FloatNullableWithAggregatesFilter<"NutritionDeclaration"> | number | null
  glycemicIndex?: Prisma.FloatNullableWithAggregatesFilter<"NutritionDeclaration"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NutritionDeclaration"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"NutritionDeclaration"> | Date | string
}

export type NutritionDeclarationCreateInput = {
  allergens: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: number | null
  carbsG?: number | null
  fatG?: number | null
  proteinG?: number | null
  glycemicIndex?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
  variant: Prisma.ProductVariantCreateNestedOneWithoutNutritionInput
}

export type NutritionDeclarationUncheckedCreateInput = {
  variantId: string
  allergens: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: number | null
  carbsG?: number | null
  fatG?: number | null
  proteinG?: number | null
  glycemicIndex?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NutritionDeclarationUpdateInput = {
  allergens?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  carbsG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  fatG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  proteinG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  glycemicIndex?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  variant?: Prisma.ProductVariantUpdateOneRequiredWithoutNutritionNestedInput
}

export type NutritionDeclarationUncheckedUpdateInput = {
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  allergens?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  carbsG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  fatG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  proteinG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  glycemicIndex?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NutritionDeclarationCreateManyInput = {
  variantId: string
  allergens: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: number | null
  carbsG?: number | null
  fatG?: number | null
  proteinG?: number | null
  glycemicIndex?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NutritionDeclarationUpdateManyMutationInput = {
  allergens?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  carbsG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  fatG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  proteinG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  glycemicIndex?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NutritionDeclarationUncheckedUpdateManyInput = {
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  allergens?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  carbsG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  fatG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  proteinG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  glycemicIndex?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NutritionDeclarationNullableScalarRelationFilter = {
  is?: Prisma.NutritionDeclarationWhereInput | null
  isNot?: Prisma.NutritionDeclarationWhereInput | null
}

export type NutritionDeclarationCountOrderByAggregateInput = {
  variantId?: Prisma.SortOrder
  allergens?: Prisma.SortOrder
  mayContain?: Prisma.SortOrder
  energyKcal?: Prisma.SortOrder
  carbsG?: Prisma.SortOrder
  fatG?: Prisma.SortOrder
  proteinG?: Prisma.SortOrder
  glycemicIndex?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NutritionDeclarationAvgOrderByAggregateInput = {
  energyKcal?: Prisma.SortOrder
  carbsG?: Prisma.SortOrder
  fatG?: Prisma.SortOrder
  proteinG?: Prisma.SortOrder
  glycemicIndex?: Prisma.SortOrder
}

export type NutritionDeclarationMaxOrderByAggregateInput = {
  variantId?: Prisma.SortOrder
  energyKcal?: Prisma.SortOrder
  carbsG?: Prisma.SortOrder
  fatG?: Prisma.SortOrder
  proteinG?: Prisma.SortOrder
  glycemicIndex?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NutritionDeclarationMinOrderByAggregateInput = {
  variantId?: Prisma.SortOrder
  energyKcal?: Prisma.SortOrder
  carbsG?: Prisma.SortOrder
  fatG?: Prisma.SortOrder
  proteinG?: Prisma.SortOrder
  glycemicIndex?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NutritionDeclarationSumOrderByAggregateInput = {
  energyKcal?: Prisma.SortOrder
  carbsG?: Prisma.SortOrder
  fatG?: Prisma.SortOrder
  proteinG?: Prisma.SortOrder
  glycemicIndex?: Prisma.SortOrder
}

export type NutritionDeclarationCreateNestedOneWithoutVariantInput = {
  create?: Prisma.XOR<Prisma.NutritionDeclarationCreateWithoutVariantInput, Prisma.NutritionDeclarationUncheckedCreateWithoutVariantInput>
  connectOrCreate?: Prisma.NutritionDeclarationCreateOrConnectWithoutVariantInput
  connect?: Prisma.NutritionDeclarationWhereUniqueInput
}

export type NutritionDeclarationUncheckedCreateNestedOneWithoutVariantInput = {
  create?: Prisma.XOR<Prisma.NutritionDeclarationCreateWithoutVariantInput, Prisma.NutritionDeclarationUncheckedCreateWithoutVariantInput>
  connectOrCreate?: Prisma.NutritionDeclarationCreateOrConnectWithoutVariantInput
  connect?: Prisma.NutritionDeclarationWhereUniqueInput
}

export type NutritionDeclarationUpdateOneWithoutVariantNestedInput = {
  create?: Prisma.XOR<Prisma.NutritionDeclarationCreateWithoutVariantInput, Prisma.NutritionDeclarationUncheckedCreateWithoutVariantInput>
  connectOrCreate?: Prisma.NutritionDeclarationCreateOrConnectWithoutVariantInput
  upsert?: Prisma.NutritionDeclarationUpsertWithoutVariantInput
  disconnect?: Prisma.NutritionDeclarationWhereInput | boolean
  delete?: Prisma.NutritionDeclarationWhereInput | boolean
  connect?: Prisma.NutritionDeclarationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NutritionDeclarationUpdateToOneWithWhereWithoutVariantInput, Prisma.NutritionDeclarationUpdateWithoutVariantInput>, Prisma.NutritionDeclarationUncheckedUpdateWithoutVariantInput>
}

export type NutritionDeclarationUncheckedUpdateOneWithoutVariantNestedInput = {
  create?: Prisma.XOR<Prisma.NutritionDeclarationCreateWithoutVariantInput, Prisma.NutritionDeclarationUncheckedCreateWithoutVariantInput>
  connectOrCreate?: Prisma.NutritionDeclarationCreateOrConnectWithoutVariantInput
  upsert?: Prisma.NutritionDeclarationUpsertWithoutVariantInput
  disconnect?: Prisma.NutritionDeclarationWhereInput | boolean
  delete?: Prisma.NutritionDeclarationWhereInput | boolean
  connect?: Prisma.NutritionDeclarationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NutritionDeclarationUpdateToOneWithWhereWithoutVariantInput, Prisma.NutritionDeclarationUpdateWithoutVariantInput>, Prisma.NutritionDeclarationUncheckedUpdateWithoutVariantInput>
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NutritionDeclarationCreateWithoutVariantInput = {
  allergens: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: number | null
  carbsG?: number | null
  fatG?: number | null
  proteinG?: number | null
  glycemicIndex?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NutritionDeclarationUncheckedCreateWithoutVariantInput = {
  allergens: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: number | null
  carbsG?: number | null
  fatG?: number | null
  proteinG?: number | null
  glycemicIndex?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NutritionDeclarationCreateOrConnectWithoutVariantInput = {
  where: Prisma.NutritionDeclarationWhereUniqueInput
  create: Prisma.XOR<Prisma.NutritionDeclarationCreateWithoutVariantInput, Prisma.NutritionDeclarationUncheckedCreateWithoutVariantInput>
}

export type NutritionDeclarationUpsertWithoutVariantInput = {
  update: Prisma.XOR<Prisma.NutritionDeclarationUpdateWithoutVariantInput, Prisma.NutritionDeclarationUncheckedUpdateWithoutVariantInput>
  create: Prisma.XOR<Prisma.NutritionDeclarationCreateWithoutVariantInput, Prisma.NutritionDeclarationUncheckedCreateWithoutVariantInput>
  where?: Prisma.NutritionDeclarationWhereInput
}

export type NutritionDeclarationUpdateToOneWithWhereWithoutVariantInput = {
  where?: Prisma.NutritionDeclarationWhereInput
  data: Prisma.XOR<Prisma.NutritionDeclarationUpdateWithoutVariantInput, Prisma.NutritionDeclarationUncheckedUpdateWithoutVariantInput>
}

export type NutritionDeclarationUpdateWithoutVariantInput = {
  allergens?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  carbsG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  fatG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  proteinG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  glycemicIndex?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NutritionDeclarationUncheckedUpdateWithoutVariantInput = {
  allergens?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  mayContain?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  energyKcal?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  carbsG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  fatG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  proteinG?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  glycemicIndex?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type NutritionDeclarationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  variantId?: boolean
  allergens?: boolean
  mayContain?: boolean
  energyKcal?: boolean
  carbsG?: boolean
  fatG?: boolean
  proteinG?: boolean
  glycemicIndex?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["nutritionDeclaration"]>

export type NutritionDeclarationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  variantId?: boolean
  allergens?: boolean
  mayContain?: boolean
  energyKcal?: boolean
  carbsG?: boolean
  fatG?: boolean
  proteinG?: boolean
  glycemicIndex?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["nutritionDeclaration"]>

export type NutritionDeclarationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  variantId?: boolean
  allergens?: boolean
  mayContain?: boolean
  energyKcal?: boolean
  carbsG?: boolean
  fatG?: boolean
  proteinG?: boolean
  glycemicIndex?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["nutritionDeclaration"]>

export type NutritionDeclarationSelectScalar = {
  variantId?: boolean
  allergens?: boolean
  mayContain?: boolean
  energyKcal?: boolean
  carbsG?: boolean
  fatG?: boolean
  proteinG?: boolean
  glycemicIndex?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type NutritionDeclarationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"variantId" | "allergens" | "mayContain" | "energyKcal" | "carbsG" | "fatG" | "proteinG" | "glycemicIndex" | "createdAt" | "updatedAt", ExtArgs["result"]["nutritionDeclaration"]>
export type NutritionDeclarationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}
export type NutritionDeclarationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}
export type NutritionDeclarationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}

export type $NutritionDeclarationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NutritionDeclaration"
  objects: {
    variant: Prisma.$ProductVariantPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    variantId: string
    /**
     * Codes GS1 canoniques. `[]` = déclaration positive « aucun allergène »,
     * à ne pas confondre avec l'absence de ligne (= non renseigné).
     */
    allergens: runtime.JsonValue
    mayContain: runtime.JsonValue
    energyKcal: number | null
    carbsG: number | null
    fatG: number | null
    proteinG: number | null
    glycemicIndex: number | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["nutritionDeclaration"]>
  composites: {}
}

export type NutritionDeclarationGetPayload<S extends boolean | null | undefined | NutritionDeclarationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload, S>

export type NutritionDeclarationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NutritionDeclarationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NutritionDeclarationCountAggregateInputType | true
  }

export interface NutritionDeclarationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NutritionDeclaration'], meta: { name: 'NutritionDeclaration' } }
  /**
   * Find zero or one NutritionDeclaration that matches the filter.
   * @param {NutritionDeclarationFindUniqueArgs} args - Arguments to find a NutritionDeclaration
   * @example
   * // Get one NutritionDeclaration
   * const nutritionDeclaration = await prisma.nutritionDeclaration.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NutritionDeclarationFindUniqueArgs>(args: Prisma.SelectSubset<T, NutritionDeclarationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NutritionDeclarationClient<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NutritionDeclaration that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NutritionDeclarationFindUniqueOrThrowArgs} args - Arguments to find a NutritionDeclaration
   * @example
   * // Get one NutritionDeclaration
   * const nutritionDeclaration = await prisma.nutritionDeclaration.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NutritionDeclarationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NutritionDeclarationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NutritionDeclarationClient<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NutritionDeclaration that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionDeclarationFindFirstArgs} args - Arguments to find a NutritionDeclaration
   * @example
   * // Get one NutritionDeclaration
   * const nutritionDeclaration = await prisma.nutritionDeclaration.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NutritionDeclarationFindFirstArgs>(args?: Prisma.SelectSubset<T, NutritionDeclarationFindFirstArgs<ExtArgs>>): Prisma.Prisma__NutritionDeclarationClient<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NutritionDeclaration that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionDeclarationFindFirstOrThrowArgs} args - Arguments to find a NutritionDeclaration
   * @example
   * // Get one NutritionDeclaration
   * const nutritionDeclaration = await prisma.nutritionDeclaration.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NutritionDeclarationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NutritionDeclarationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NutritionDeclarationClient<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NutritionDeclarations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionDeclarationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NutritionDeclarations
   * const nutritionDeclarations = await prisma.nutritionDeclaration.findMany()
   * 
   * // Get first 10 NutritionDeclarations
   * const nutritionDeclarations = await prisma.nutritionDeclaration.findMany({ take: 10 })
   * 
   * // Only select the `variantId`
   * const nutritionDeclarationWithVariantIdOnly = await prisma.nutritionDeclaration.findMany({ select: { variantId: true } })
   * 
   */
  findMany<T extends NutritionDeclarationFindManyArgs>(args?: Prisma.SelectSubset<T, NutritionDeclarationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NutritionDeclaration.
   * @param {NutritionDeclarationCreateArgs} args - Arguments to create a NutritionDeclaration.
   * @example
   * // Create one NutritionDeclaration
   * const NutritionDeclaration = await prisma.nutritionDeclaration.create({
   *   data: {
   *     // ... data to create a NutritionDeclaration
   *   }
   * })
   * 
   */
  create<T extends NutritionDeclarationCreateArgs>(args: Prisma.SelectSubset<T, NutritionDeclarationCreateArgs<ExtArgs>>): Prisma.Prisma__NutritionDeclarationClient<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NutritionDeclarations.
   * @param {NutritionDeclarationCreateManyArgs} args - Arguments to create many NutritionDeclarations.
   * @example
   * // Create many NutritionDeclarations
   * const nutritionDeclaration = await prisma.nutritionDeclaration.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NutritionDeclarationCreateManyArgs>(args?: Prisma.SelectSubset<T, NutritionDeclarationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NutritionDeclarations and returns the data saved in the database.
   * @param {NutritionDeclarationCreateManyAndReturnArgs} args - Arguments to create many NutritionDeclarations.
   * @example
   * // Create many NutritionDeclarations
   * const nutritionDeclaration = await prisma.nutritionDeclaration.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NutritionDeclarations and only return the `variantId`
   * const nutritionDeclarationWithVariantIdOnly = await prisma.nutritionDeclaration.createManyAndReturn({
   *   select: { variantId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NutritionDeclarationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NutritionDeclarationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NutritionDeclaration.
   * @param {NutritionDeclarationDeleteArgs} args - Arguments to delete one NutritionDeclaration.
   * @example
   * // Delete one NutritionDeclaration
   * const NutritionDeclaration = await prisma.nutritionDeclaration.delete({
   *   where: {
   *     // ... filter to delete one NutritionDeclaration
   *   }
   * })
   * 
   */
  delete<T extends NutritionDeclarationDeleteArgs>(args: Prisma.SelectSubset<T, NutritionDeclarationDeleteArgs<ExtArgs>>): Prisma.Prisma__NutritionDeclarationClient<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NutritionDeclaration.
   * @param {NutritionDeclarationUpdateArgs} args - Arguments to update one NutritionDeclaration.
   * @example
   * // Update one NutritionDeclaration
   * const nutritionDeclaration = await prisma.nutritionDeclaration.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NutritionDeclarationUpdateArgs>(args: Prisma.SelectSubset<T, NutritionDeclarationUpdateArgs<ExtArgs>>): Prisma.Prisma__NutritionDeclarationClient<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NutritionDeclarations.
   * @param {NutritionDeclarationDeleteManyArgs} args - Arguments to filter NutritionDeclarations to delete.
   * @example
   * // Delete a few NutritionDeclarations
   * const { count } = await prisma.nutritionDeclaration.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NutritionDeclarationDeleteManyArgs>(args?: Prisma.SelectSubset<T, NutritionDeclarationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NutritionDeclarations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionDeclarationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NutritionDeclarations
   * const nutritionDeclaration = await prisma.nutritionDeclaration.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NutritionDeclarationUpdateManyArgs>(args: Prisma.SelectSubset<T, NutritionDeclarationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NutritionDeclarations and returns the data updated in the database.
   * @param {NutritionDeclarationUpdateManyAndReturnArgs} args - Arguments to update many NutritionDeclarations.
   * @example
   * // Update many NutritionDeclarations
   * const nutritionDeclaration = await prisma.nutritionDeclaration.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NutritionDeclarations and only return the `variantId`
   * const nutritionDeclarationWithVariantIdOnly = await prisma.nutritionDeclaration.updateManyAndReturn({
   *   select: { variantId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NutritionDeclarationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NutritionDeclarationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NutritionDeclaration.
   * @param {NutritionDeclarationUpsertArgs} args - Arguments to update or create a NutritionDeclaration.
   * @example
   * // Update or create a NutritionDeclaration
   * const nutritionDeclaration = await prisma.nutritionDeclaration.upsert({
   *   create: {
   *     // ... data to create a NutritionDeclaration
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NutritionDeclaration we want to update
   *   }
   * })
   */
  upsert<T extends NutritionDeclarationUpsertArgs>(args: Prisma.SelectSubset<T, NutritionDeclarationUpsertArgs<ExtArgs>>): Prisma.Prisma__NutritionDeclarationClient<runtime.Types.Result.GetResult<Prisma.$NutritionDeclarationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NutritionDeclarations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionDeclarationCountArgs} args - Arguments to filter NutritionDeclarations to count.
   * @example
   * // Count the number of NutritionDeclarations
   * const count = await prisma.nutritionDeclaration.count({
   *   where: {
   *     // ... the filter for the NutritionDeclarations we want to count
   *   }
   * })
  **/
  count<T extends NutritionDeclarationCountArgs>(
    args?: Prisma.Subset<T, NutritionDeclarationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NutritionDeclarationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NutritionDeclaration.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionDeclarationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NutritionDeclarationAggregateArgs>(args: Prisma.Subset<T, NutritionDeclarationAggregateArgs>): Prisma.PrismaPromise<GetNutritionDeclarationAggregateType<T>>

  /**
   * Group by NutritionDeclaration.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NutritionDeclarationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NutritionDeclarationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NutritionDeclarationGroupByArgs['orderBy'] }
      : { orderBy?: NutritionDeclarationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NutritionDeclarationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNutritionDeclarationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NutritionDeclaration model
 */
readonly fields: NutritionDeclarationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NutritionDeclaration.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NutritionDeclarationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  variant<T extends Prisma.ProductVariantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductVariantDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductVariantClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NutritionDeclaration model
 */
export interface NutritionDeclarationFieldRefs {
  readonly variantId: Prisma.FieldRef<"NutritionDeclaration", 'String'>
  readonly allergens: Prisma.FieldRef<"NutritionDeclaration", 'Json'>
  readonly mayContain: Prisma.FieldRef<"NutritionDeclaration", 'Json'>
  readonly energyKcal: Prisma.FieldRef<"NutritionDeclaration", 'Float'>
  readonly carbsG: Prisma.FieldRef<"NutritionDeclaration", 'Float'>
  readonly fatG: Prisma.FieldRef<"NutritionDeclaration", 'Float'>
  readonly proteinG: Prisma.FieldRef<"NutritionDeclaration", 'Float'>
  readonly glycemicIndex: Prisma.FieldRef<"NutritionDeclaration", 'Float'>
  readonly createdAt: Prisma.FieldRef<"NutritionDeclaration", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"NutritionDeclaration", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NutritionDeclaration findUnique
 */
export type NutritionDeclarationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationInclude<ExtArgs> | null
  /**
   * Filter, which NutritionDeclaration to fetch.
   */
  where: Prisma.NutritionDeclarationWhereUniqueInput
}

/**
 * NutritionDeclaration findUniqueOrThrow
 */
export type NutritionDeclarationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationInclude<ExtArgs> | null
  /**
   * Filter, which NutritionDeclaration to fetch.
   */
  where: Prisma.NutritionDeclarationWhereUniqueInput
}

/**
 * NutritionDeclaration findFirst
 */
export type NutritionDeclarationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationInclude<ExtArgs> | null
  /**
   * Filter, which NutritionDeclaration to fetch.
   */
  where?: Prisma.NutritionDeclarationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NutritionDeclarations to fetch.
   */
  orderBy?: Prisma.NutritionDeclarationOrderByWithRelationInput | Prisma.NutritionDeclarationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NutritionDeclarations.
   */
  cursor?: Prisma.NutritionDeclarationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NutritionDeclarations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NutritionDeclarations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NutritionDeclarations.
   */
  distinct?: Prisma.NutritionDeclarationScalarFieldEnum | Prisma.NutritionDeclarationScalarFieldEnum[]
}

/**
 * NutritionDeclaration findFirstOrThrow
 */
export type NutritionDeclarationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationInclude<ExtArgs> | null
  /**
   * Filter, which NutritionDeclaration to fetch.
   */
  where?: Prisma.NutritionDeclarationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NutritionDeclarations to fetch.
   */
  orderBy?: Prisma.NutritionDeclarationOrderByWithRelationInput | Prisma.NutritionDeclarationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NutritionDeclarations.
   */
  cursor?: Prisma.NutritionDeclarationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NutritionDeclarations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NutritionDeclarations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NutritionDeclarations.
   */
  distinct?: Prisma.NutritionDeclarationScalarFieldEnum | Prisma.NutritionDeclarationScalarFieldEnum[]
}

/**
 * NutritionDeclaration findMany
 */
export type NutritionDeclarationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationInclude<ExtArgs> | null
  /**
   * Filter, which NutritionDeclarations to fetch.
   */
  where?: Prisma.NutritionDeclarationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NutritionDeclarations to fetch.
   */
  orderBy?: Prisma.NutritionDeclarationOrderByWithRelationInput | Prisma.NutritionDeclarationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NutritionDeclarations.
   */
  cursor?: Prisma.NutritionDeclarationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NutritionDeclarations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NutritionDeclarations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NutritionDeclarations.
   */
  distinct?: Prisma.NutritionDeclarationScalarFieldEnum | Prisma.NutritionDeclarationScalarFieldEnum[]
}

/**
 * NutritionDeclaration create
 */
export type NutritionDeclarationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationInclude<ExtArgs> | null
  /**
   * The data needed to create a NutritionDeclaration.
   */
  data: Prisma.XOR<Prisma.NutritionDeclarationCreateInput, Prisma.NutritionDeclarationUncheckedCreateInput>
}

/**
 * NutritionDeclaration createMany
 */
export type NutritionDeclarationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NutritionDeclarations.
   */
  data: Prisma.NutritionDeclarationCreateManyInput | Prisma.NutritionDeclarationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NutritionDeclaration createManyAndReturn
 */
export type NutritionDeclarationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * The data used to create many NutritionDeclarations.
   */
  data: Prisma.NutritionDeclarationCreateManyInput | Prisma.NutritionDeclarationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * NutritionDeclaration update
 */
export type NutritionDeclarationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationInclude<ExtArgs> | null
  /**
   * The data needed to update a NutritionDeclaration.
   */
  data: Prisma.XOR<Prisma.NutritionDeclarationUpdateInput, Prisma.NutritionDeclarationUncheckedUpdateInput>
  /**
   * Choose, which NutritionDeclaration to update.
   */
  where: Prisma.NutritionDeclarationWhereUniqueInput
}

/**
 * NutritionDeclaration updateMany
 */
export type NutritionDeclarationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NutritionDeclarations.
   */
  data: Prisma.XOR<Prisma.NutritionDeclarationUpdateManyMutationInput, Prisma.NutritionDeclarationUncheckedUpdateManyInput>
  /**
   * Filter which NutritionDeclarations to update
   */
  where?: Prisma.NutritionDeclarationWhereInput
  /**
   * Limit how many NutritionDeclarations to update.
   */
  limit?: number
}

/**
 * NutritionDeclaration updateManyAndReturn
 */
export type NutritionDeclarationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * The data used to update NutritionDeclarations.
   */
  data: Prisma.XOR<Prisma.NutritionDeclarationUpdateManyMutationInput, Prisma.NutritionDeclarationUncheckedUpdateManyInput>
  /**
   * Filter which NutritionDeclarations to update
   */
  where?: Prisma.NutritionDeclarationWhereInput
  /**
   * Limit how many NutritionDeclarations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * NutritionDeclaration upsert
 */
export type NutritionDeclarationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationInclude<ExtArgs> | null
  /**
   * The filter to search for the NutritionDeclaration to update in case it exists.
   */
  where: Prisma.NutritionDeclarationWhereUniqueInput
  /**
   * In case the NutritionDeclaration found by the `where` argument doesn't exist, create a new NutritionDeclaration with this data.
   */
  create: Prisma.XOR<Prisma.NutritionDeclarationCreateInput, Prisma.NutritionDeclarationUncheckedCreateInput>
  /**
   * In case the NutritionDeclaration was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NutritionDeclarationUpdateInput, Prisma.NutritionDeclarationUncheckedUpdateInput>
}

/**
 * NutritionDeclaration delete
 */
export type NutritionDeclarationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationInclude<ExtArgs> | null
  /**
   * Filter which NutritionDeclaration to delete.
   */
  where: Prisma.NutritionDeclarationWhereUniqueInput
}

/**
 * NutritionDeclaration deleteMany
 */
export type NutritionDeclarationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NutritionDeclarations to delete
   */
  where?: Prisma.NutritionDeclarationWhereInput
  /**
   * Limit how many NutritionDeclarations to delete.
   */
  limit?: number
}

/**
 * NutritionDeclaration without action
 */
export type NutritionDeclarationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NutritionDeclaration
   */
  select?: Prisma.NutritionDeclarationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NutritionDeclaration
   */
  omit?: Prisma.NutritionDeclarationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NutritionDeclarationInclude<ExtArgs> | null
}
