
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductEditorial` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ProductEditorial
 * 
 */
export type ProductEditorialModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductEditorialPayload>

export type AggregateProductEditorial = {
  _count: ProductEditorialCountAggregateOutputType | null
  _min: ProductEditorialMinAggregateOutputType | null
  _max: ProductEditorialMaxAggregateOutputType | null
}

export type ProductEditorialMinAggregateOutputType = {
  productId: string | null
  brand: string | null
  updatedAt: Date | null
}

export type ProductEditorialMaxAggregateOutputType = {
  productId: string | null
  brand: string | null
  updatedAt: Date | null
}

export type ProductEditorialCountAggregateOutputType = {
  productId: number
  descriptionShort: number
  descriptionLong: number
  story: number
  pairing: number
  brand: number
  seoTitle: number
  seoDescription: number
  updatedAt: number
  _all: number
}


export type ProductEditorialMinAggregateInputType = {
  productId?: true
  brand?: true
  updatedAt?: true
}

export type ProductEditorialMaxAggregateInputType = {
  productId?: true
  brand?: true
  updatedAt?: true
}

export type ProductEditorialCountAggregateInputType = {
  productId?: true
  descriptionShort?: true
  descriptionLong?: true
  story?: true
  pairing?: true
  brand?: true
  seoTitle?: true
  seoDescription?: true
  updatedAt?: true
  _all?: true
}

export type ProductEditorialAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductEditorial to aggregate.
   */
  where?: Prisma.ProductEditorialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductEditorials to fetch.
   */
  orderBy?: Prisma.ProductEditorialOrderByWithRelationInput | Prisma.ProductEditorialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductEditorialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductEditorials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductEditorials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductEditorials
  **/
  _count?: true | ProductEditorialCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductEditorialMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductEditorialMaxAggregateInputType
}

export type GetProductEditorialAggregateType<T extends ProductEditorialAggregateArgs> = {
      [P in keyof T & keyof AggregateProductEditorial]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductEditorial[P]>
    : Prisma.GetScalarType<T[P], AggregateProductEditorial[P]>
}




export type ProductEditorialGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductEditorialWhereInput
  orderBy?: Prisma.ProductEditorialOrderByWithAggregationInput | Prisma.ProductEditorialOrderByWithAggregationInput[]
  by: Prisma.ProductEditorialScalarFieldEnum[] | Prisma.ProductEditorialScalarFieldEnum
  having?: Prisma.ProductEditorialScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductEditorialCountAggregateInputType | true
  _min?: ProductEditorialMinAggregateInputType
  _max?: ProductEditorialMaxAggregateInputType
}

export type ProductEditorialGroupByOutputType = {
  productId: string
  descriptionShort: runtime.JsonValue | null
  descriptionLong: runtime.JsonValue | null
  story: runtime.JsonValue | null
  pairing: runtime.JsonValue | null
  brand: string | null
  seoTitle: runtime.JsonValue | null
  seoDescription: runtime.JsonValue | null
  updatedAt: Date
  _count: ProductEditorialCountAggregateOutputType | null
  _min: ProductEditorialMinAggregateOutputType | null
  _max: ProductEditorialMaxAggregateOutputType | null
}

export type GetProductEditorialGroupByPayload<T extends ProductEditorialGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductEditorialGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductEditorialGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductEditorialGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductEditorialGroupByOutputType[P]>
      }
    >
  >



export type ProductEditorialWhereInput = {
  AND?: Prisma.ProductEditorialWhereInput | Prisma.ProductEditorialWhereInput[]
  OR?: Prisma.ProductEditorialWhereInput[]
  NOT?: Prisma.ProductEditorialWhereInput | Prisma.ProductEditorialWhereInput[]
  productId?: Prisma.StringFilter<"ProductEditorial"> | string
  descriptionShort?: Prisma.JsonNullableFilter<"ProductEditorial">
  descriptionLong?: Prisma.JsonNullableFilter<"ProductEditorial">
  story?: Prisma.JsonNullableFilter<"ProductEditorial">
  pairing?: Prisma.JsonNullableFilter<"ProductEditorial">
  brand?: Prisma.StringNullableFilter<"ProductEditorial"> | string | null
  seoTitle?: Prisma.JsonNullableFilter<"ProductEditorial">
  seoDescription?: Prisma.JsonNullableFilter<"ProductEditorial">
  updatedAt?: Prisma.DateTimeFilter<"ProductEditorial"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type ProductEditorialOrderByWithRelationInput = {
  productId?: Prisma.SortOrder
  descriptionShort?: Prisma.SortOrderInput | Prisma.SortOrder
  descriptionLong?: Prisma.SortOrderInput | Prisma.SortOrder
  story?: Prisma.SortOrderInput | Prisma.SortOrder
  pairing?: Prisma.SortOrderInput | Prisma.SortOrder
  brand?: Prisma.SortOrderInput | Prisma.SortOrder
  seoTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  seoDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type ProductEditorialWhereUniqueInput = Prisma.AtLeast<{
  productId?: string
  AND?: Prisma.ProductEditorialWhereInput | Prisma.ProductEditorialWhereInput[]
  OR?: Prisma.ProductEditorialWhereInput[]
  NOT?: Prisma.ProductEditorialWhereInput | Prisma.ProductEditorialWhereInput[]
  descriptionShort?: Prisma.JsonNullableFilter<"ProductEditorial">
  descriptionLong?: Prisma.JsonNullableFilter<"ProductEditorial">
  story?: Prisma.JsonNullableFilter<"ProductEditorial">
  pairing?: Prisma.JsonNullableFilter<"ProductEditorial">
  brand?: Prisma.StringNullableFilter<"ProductEditorial"> | string | null
  seoTitle?: Prisma.JsonNullableFilter<"ProductEditorial">
  seoDescription?: Prisma.JsonNullableFilter<"ProductEditorial">
  updatedAt?: Prisma.DateTimeFilter<"ProductEditorial"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "productId">

export type ProductEditorialOrderByWithAggregationInput = {
  productId?: Prisma.SortOrder
  descriptionShort?: Prisma.SortOrderInput | Prisma.SortOrder
  descriptionLong?: Prisma.SortOrderInput | Prisma.SortOrder
  story?: Prisma.SortOrderInput | Prisma.SortOrder
  pairing?: Prisma.SortOrderInput | Prisma.SortOrder
  brand?: Prisma.SortOrderInput | Prisma.SortOrder
  seoTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  seoDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProductEditorialCountOrderByAggregateInput
  _max?: Prisma.ProductEditorialMaxOrderByAggregateInput
  _min?: Prisma.ProductEditorialMinOrderByAggregateInput
}

export type ProductEditorialScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductEditorialScalarWhereWithAggregatesInput | Prisma.ProductEditorialScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductEditorialScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductEditorialScalarWhereWithAggregatesInput | Prisma.ProductEditorialScalarWhereWithAggregatesInput[]
  productId?: Prisma.StringWithAggregatesFilter<"ProductEditorial"> | string
  descriptionShort?: Prisma.JsonNullableWithAggregatesFilter<"ProductEditorial">
  descriptionLong?: Prisma.JsonNullableWithAggregatesFilter<"ProductEditorial">
  story?: Prisma.JsonNullableWithAggregatesFilter<"ProductEditorial">
  pairing?: Prisma.JsonNullableWithAggregatesFilter<"ProductEditorial">
  brand?: Prisma.StringNullableWithAggregatesFilter<"ProductEditorial"> | string | null
  seoTitle?: Prisma.JsonNullableWithAggregatesFilter<"ProductEditorial">
  seoDescription?: Prisma.JsonNullableWithAggregatesFilter<"ProductEditorial">
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ProductEditorial"> | Date | string
}

export type ProductEditorialCreateInput = {
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutEditorialInput
}

export type ProductEditorialUncheckedCreateInput = {
  productId: string
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Date | string
}

export type ProductEditorialUpdateInput = {
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutEditorialNestedInput
}

export type ProductEditorialUncheckedUpdateInput = {
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductEditorialCreateManyInput = {
  productId: string
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Date | string
}

export type ProductEditorialUpdateManyMutationInput = {
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductEditorialUncheckedUpdateManyInput = {
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductEditorialNullableScalarRelationFilter = {
  is?: Prisma.ProductEditorialWhereInput | null
  isNot?: Prisma.ProductEditorialWhereInput | null
}

export type ProductEditorialCountOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  descriptionShort?: Prisma.SortOrder
  descriptionLong?: Prisma.SortOrder
  story?: Prisma.SortOrder
  pairing?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  seoTitle?: Prisma.SortOrder
  seoDescription?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProductEditorialMaxOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProductEditorialMinOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProductEditorialCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductEditorialCreateWithoutProductInput, Prisma.ProductEditorialUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ProductEditorialCreateOrConnectWithoutProductInput
  connect?: Prisma.ProductEditorialWhereUniqueInput
}

export type ProductEditorialUncheckedCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductEditorialCreateWithoutProductInput, Prisma.ProductEditorialUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ProductEditorialCreateOrConnectWithoutProductInput
  connect?: Prisma.ProductEditorialWhereUniqueInput
}

export type ProductEditorialUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductEditorialCreateWithoutProductInput, Prisma.ProductEditorialUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ProductEditorialCreateOrConnectWithoutProductInput
  upsert?: Prisma.ProductEditorialUpsertWithoutProductInput
  disconnect?: Prisma.ProductEditorialWhereInput | boolean
  delete?: Prisma.ProductEditorialWhereInput | boolean
  connect?: Prisma.ProductEditorialWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProductEditorialUpdateToOneWithWhereWithoutProductInput, Prisma.ProductEditorialUpdateWithoutProductInput>, Prisma.ProductEditorialUncheckedUpdateWithoutProductInput>
}

export type ProductEditorialUncheckedUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductEditorialCreateWithoutProductInput, Prisma.ProductEditorialUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ProductEditorialCreateOrConnectWithoutProductInput
  upsert?: Prisma.ProductEditorialUpsertWithoutProductInput
  disconnect?: Prisma.ProductEditorialWhereInput | boolean
  delete?: Prisma.ProductEditorialWhereInput | boolean
  connect?: Prisma.ProductEditorialWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProductEditorialUpdateToOneWithWhereWithoutProductInput, Prisma.ProductEditorialUpdateWithoutProductInput>, Prisma.ProductEditorialUncheckedUpdateWithoutProductInput>
}

export type ProductEditorialCreateWithoutProductInput = {
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Date | string
}

export type ProductEditorialUncheckedCreateWithoutProductInput = {
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Date | string
}

export type ProductEditorialCreateOrConnectWithoutProductInput = {
  where: Prisma.ProductEditorialWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductEditorialCreateWithoutProductInput, Prisma.ProductEditorialUncheckedCreateWithoutProductInput>
}

export type ProductEditorialUpsertWithoutProductInput = {
  update: Prisma.XOR<Prisma.ProductEditorialUpdateWithoutProductInput, Prisma.ProductEditorialUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ProductEditorialCreateWithoutProductInput, Prisma.ProductEditorialUncheckedCreateWithoutProductInput>
  where?: Prisma.ProductEditorialWhereInput
}

export type ProductEditorialUpdateToOneWithWhereWithoutProductInput = {
  where?: Prisma.ProductEditorialWhereInput
  data: Prisma.XOR<Prisma.ProductEditorialUpdateWithoutProductInput, Prisma.ProductEditorialUncheckedUpdateWithoutProductInput>
}

export type ProductEditorialUpdateWithoutProductInput = {
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductEditorialUncheckedUpdateWithoutProductInput = {
  descriptionShort?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  descriptionLong?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  story?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  pairing?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  brand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seoTitle?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  seoDescription?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ProductEditorialSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productId?: boolean
  descriptionShort?: boolean
  descriptionLong?: boolean
  story?: boolean
  pairing?: boolean
  brand?: boolean
  seoTitle?: boolean
  seoDescription?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productEditorial"]>

export type ProductEditorialSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productId?: boolean
  descriptionShort?: boolean
  descriptionLong?: boolean
  story?: boolean
  pairing?: boolean
  brand?: boolean
  seoTitle?: boolean
  seoDescription?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productEditorial"]>

export type ProductEditorialSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productId?: boolean
  descriptionShort?: boolean
  descriptionLong?: boolean
  story?: boolean
  pairing?: boolean
  brand?: boolean
  seoTitle?: boolean
  seoDescription?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productEditorial"]>

export type ProductEditorialSelectScalar = {
  productId?: boolean
  descriptionShort?: boolean
  descriptionLong?: boolean
  story?: boolean
  pairing?: boolean
  brand?: boolean
  seoTitle?: boolean
  seoDescription?: boolean
  updatedAt?: boolean
}

export type ProductEditorialOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"productId" | "descriptionShort" | "descriptionLong" | "story" | "pairing" | "brand" | "seoTitle" | "seoDescription" | "updatedAt", ExtArgs["result"]["productEditorial"]>
export type ProductEditorialInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductEditorialIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductEditorialIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $ProductEditorialPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductEditorial"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    productId: string
    descriptionShort: runtime.JsonValue | null
    descriptionLong: runtime.JsonValue | null
    story: runtime.JsonValue | null
    pairing: runtime.JsonValue | null
    brand: string | null
    seoTitle: runtime.JsonValue | null
    seoDescription: runtime.JsonValue | null
    updatedAt: Date
  }, ExtArgs["result"]["productEditorial"]>
  composites: {}
}

export type ProductEditorialGetPayload<S extends boolean | null | undefined | ProductEditorialDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload, S>

export type ProductEditorialCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductEditorialFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductEditorialCountAggregateInputType | true
  }

export interface ProductEditorialDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductEditorial'], meta: { name: 'ProductEditorial' } }
  /**
   * Find zero or one ProductEditorial that matches the filter.
   * @param {ProductEditorialFindUniqueArgs} args - Arguments to find a ProductEditorial
   * @example
   * // Get one ProductEditorial
   * const productEditorial = await prisma.productEditorial.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductEditorialFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductEditorialFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductEditorialClient<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductEditorial that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductEditorialFindUniqueOrThrowArgs} args - Arguments to find a ProductEditorial
   * @example
   * // Get one ProductEditorial
   * const productEditorial = await prisma.productEditorial.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductEditorialFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductEditorialFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductEditorialClient<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductEditorial that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductEditorialFindFirstArgs} args - Arguments to find a ProductEditorial
   * @example
   * // Get one ProductEditorial
   * const productEditorial = await prisma.productEditorial.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductEditorialFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductEditorialFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductEditorialClient<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductEditorial that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductEditorialFindFirstOrThrowArgs} args - Arguments to find a ProductEditorial
   * @example
   * // Get one ProductEditorial
   * const productEditorial = await prisma.productEditorial.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductEditorialFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductEditorialFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductEditorialClient<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductEditorials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductEditorialFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductEditorials
   * const productEditorials = await prisma.productEditorial.findMany()
   * 
   * // Get first 10 ProductEditorials
   * const productEditorials = await prisma.productEditorial.findMany({ take: 10 })
   * 
   * // Only select the `productId`
   * const productEditorialWithProductIdOnly = await prisma.productEditorial.findMany({ select: { productId: true } })
   * 
   */
  findMany<T extends ProductEditorialFindManyArgs>(args?: Prisma.SelectSubset<T, ProductEditorialFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductEditorial.
   * @param {ProductEditorialCreateArgs} args - Arguments to create a ProductEditorial.
   * @example
   * // Create one ProductEditorial
   * const ProductEditorial = await prisma.productEditorial.create({
   *   data: {
   *     // ... data to create a ProductEditorial
   *   }
   * })
   * 
   */
  create<T extends ProductEditorialCreateArgs>(args: Prisma.SelectSubset<T, ProductEditorialCreateArgs<ExtArgs>>): Prisma.Prisma__ProductEditorialClient<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductEditorials.
   * @param {ProductEditorialCreateManyArgs} args - Arguments to create many ProductEditorials.
   * @example
   * // Create many ProductEditorials
   * const productEditorial = await prisma.productEditorial.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductEditorialCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductEditorialCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductEditorials and returns the data saved in the database.
   * @param {ProductEditorialCreateManyAndReturnArgs} args - Arguments to create many ProductEditorials.
   * @example
   * // Create many ProductEditorials
   * const productEditorial = await prisma.productEditorial.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductEditorials and only return the `productId`
   * const productEditorialWithProductIdOnly = await prisma.productEditorial.createManyAndReturn({
   *   select: { productId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductEditorialCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductEditorialCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductEditorial.
   * @param {ProductEditorialDeleteArgs} args - Arguments to delete one ProductEditorial.
   * @example
   * // Delete one ProductEditorial
   * const ProductEditorial = await prisma.productEditorial.delete({
   *   where: {
   *     // ... filter to delete one ProductEditorial
   *   }
   * })
   * 
   */
  delete<T extends ProductEditorialDeleteArgs>(args: Prisma.SelectSubset<T, ProductEditorialDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductEditorialClient<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductEditorial.
   * @param {ProductEditorialUpdateArgs} args - Arguments to update one ProductEditorial.
   * @example
   * // Update one ProductEditorial
   * const productEditorial = await prisma.productEditorial.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductEditorialUpdateArgs>(args: Prisma.SelectSubset<T, ProductEditorialUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductEditorialClient<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductEditorials.
   * @param {ProductEditorialDeleteManyArgs} args - Arguments to filter ProductEditorials to delete.
   * @example
   * // Delete a few ProductEditorials
   * const { count } = await prisma.productEditorial.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductEditorialDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductEditorialDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductEditorials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductEditorialUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductEditorials
   * const productEditorial = await prisma.productEditorial.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductEditorialUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductEditorialUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductEditorials and returns the data updated in the database.
   * @param {ProductEditorialUpdateManyAndReturnArgs} args - Arguments to update many ProductEditorials.
   * @example
   * // Update many ProductEditorials
   * const productEditorial = await prisma.productEditorial.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductEditorials and only return the `productId`
   * const productEditorialWithProductIdOnly = await prisma.productEditorial.updateManyAndReturn({
   *   select: { productId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductEditorialUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductEditorialUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductEditorial.
   * @param {ProductEditorialUpsertArgs} args - Arguments to update or create a ProductEditorial.
   * @example
   * // Update or create a ProductEditorial
   * const productEditorial = await prisma.productEditorial.upsert({
   *   create: {
   *     // ... data to create a ProductEditorial
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductEditorial we want to update
   *   }
   * })
   */
  upsert<T extends ProductEditorialUpsertArgs>(args: Prisma.SelectSubset<T, ProductEditorialUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductEditorialClient<runtime.Types.Result.GetResult<Prisma.$ProductEditorialPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductEditorials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductEditorialCountArgs} args - Arguments to filter ProductEditorials to count.
   * @example
   * // Count the number of ProductEditorials
   * const count = await prisma.productEditorial.count({
   *   where: {
   *     // ... the filter for the ProductEditorials we want to count
   *   }
   * })
  **/
  count<T extends ProductEditorialCountArgs>(
    args?: Prisma.Subset<T, ProductEditorialCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductEditorialCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductEditorial.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductEditorialAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductEditorialAggregateArgs>(args: Prisma.Subset<T, ProductEditorialAggregateArgs>): Prisma.PrismaPromise<GetProductEditorialAggregateType<T>>

  /**
   * Group by ProductEditorial.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductEditorialGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductEditorialGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductEditorialGroupByArgs['orderBy'] }
      : { orderBy?: ProductEditorialGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductEditorialGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductEditorialGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductEditorial model
 */
readonly fields: ProductEditorialFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductEditorial.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductEditorialClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductEditorial model
 */
export interface ProductEditorialFieldRefs {
  readonly productId: Prisma.FieldRef<"ProductEditorial", 'String'>
  readonly descriptionShort: Prisma.FieldRef<"ProductEditorial", 'Json'>
  readonly descriptionLong: Prisma.FieldRef<"ProductEditorial", 'Json'>
  readonly story: Prisma.FieldRef<"ProductEditorial", 'Json'>
  readonly pairing: Prisma.FieldRef<"ProductEditorial", 'Json'>
  readonly brand: Prisma.FieldRef<"ProductEditorial", 'String'>
  readonly seoTitle: Prisma.FieldRef<"ProductEditorial", 'Json'>
  readonly seoDescription: Prisma.FieldRef<"ProductEditorial", 'Json'>
  readonly updatedAt: Prisma.FieldRef<"ProductEditorial", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ProductEditorial findUnique
 */
export type ProductEditorialFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialInclude<ExtArgs> | null
  /**
   * Filter, which ProductEditorial to fetch.
   */
  where: Prisma.ProductEditorialWhereUniqueInput
}

/**
 * ProductEditorial findUniqueOrThrow
 */
export type ProductEditorialFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialInclude<ExtArgs> | null
  /**
   * Filter, which ProductEditorial to fetch.
   */
  where: Prisma.ProductEditorialWhereUniqueInput
}

/**
 * ProductEditorial findFirst
 */
export type ProductEditorialFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialInclude<ExtArgs> | null
  /**
   * Filter, which ProductEditorial to fetch.
   */
  where?: Prisma.ProductEditorialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductEditorials to fetch.
   */
  orderBy?: Prisma.ProductEditorialOrderByWithRelationInput | Prisma.ProductEditorialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductEditorials.
   */
  cursor?: Prisma.ProductEditorialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductEditorials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductEditorials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductEditorials.
   */
  distinct?: Prisma.ProductEditorialScalarFieldEnum | Prisma.ProductEditorialScalarFieldEnum[]
}

/**
 * ProductEditorial findFirstOrThrow
 */
export type ProductEditorialFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialInclude<ExtArgs> | null
  /**
   * Filter, which ProductEditorial to fetch.
   */
  where?: Prisma.ProductEditorialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductEditorials to fetch.
   */
  orderBy?: Prisma.ProductEditorialOrderByWithRelationInput | Prisma.ProductEditorialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductEditorials.
   */
  cursor?: Prisma.ProductEditorialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductEditorials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductEditorials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductEditorials.
   */
  distinct?: Prisma.ProductEditorialScalarFieldEnum | Prisma.ProductEditorialScalarFieldEnum[]
}

/**
 * ProductEditorial findMany
 */
export type ProductEditorialFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialInclude<ExtArgs> | null
  /**
   * Filter, which ProductEditorials to fetch.
   */
  where?: Prisma.ProductEditorialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductEditorials to fetch.
   */
  orderBy?: Prisma.ProductEditorialOrderByWithRelationInput | Prisma.ProductEditorialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductEditorials.
   */
  cursor?: Prisma.ProductEditorialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductEditorials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductEditorials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductEditorials.
   */
  distinct?: Prisma.ProductEditorialScalarFieldEnum | Prisma.ProductEditorialScalarFieldEnum[]
}

/**
 * ProductEditorial create
 */
export type ProductEditorialCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductEditorial.
   */
  data: Prisma.XOR<Prisma.ProductEditorialCreateInput, Prisma.ProductEditorialUncheckedCreateInput>
}

/**
 * ProductEditorial createMany
 */
export type ProductEditorialCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductEditorials.
   */
  data: Prisma.ProductEditorialCreateManyInput | Prisma.ProductEditorialCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductEditorial createManyAndReturn
 */
export type ProductEditorialCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * The data used to create many ProductEditorials.
   */
  data: Prisma.ProductEditorialCreateManyInput | Prisma.ProductEditorialCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProductEditorial update
 */
export type ProductEditorialUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductEditorial.
   */
  data: Prisma.XOR<Prisma.ProductEditorialUpdateInput, Prisma.ProductEditorialUncheckedUpdateInput>
  /**
   * Choose, which ProductEditorial to update.
   */
  where: Prisma.ProductEditorialWhereUniqueInput
}

/**
 * ProductEditorial updateMany
 */
export type ProductEditorialUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductEditorials.
   */
  data: Prisma.XOR<Prisma.ProductEditorialUpdateManyMutationInput, Prisma.ProductEditorialUncheckedUpdateManyInput>
  /**
   * Filter which ProductEditorials to update
   */
  where?: Prisma.ProductEditorialWhereInput
  /**
   * Limit how many ProductEditorials to update.
   */
  limit?: number
}

/**
 * ProductEditorial updateManyAndReturn
 */
export type ProductEditorialUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * The data used to update ProductEditorials.
   */
  data: Prisma.XOR<Prisma.ProductEditorialUpdateManyMutationInput, Prisma.ProductEditorialUncheckedUpdateManyInput>
  /**
   * Filter which ProductEditorials to update
   */
  where?: Prisma.ProductEditorialWhereInput
  /**
   * Limit how many ProductEditorials to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProductEditorial upsert
 */
export type ProductEditorialUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductEditorial to update in case it exists.
   */
  where: Prisma.ProductEditorialWhereUniqueInput
  /**
   * In case the ProductEditorial found by the `where` argument doesn't exist, create a new ProductEditorial with this data.
   */
  create: Prisma.XOR<Prisma.ProductEditorialCreateInput, Prisma.ProductEditorialUncheckedCreateInput>
  /**
   * In case the ProductEditorial was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductEditorialUpdateInput, Prisma.ProductEditorialUncheckedUpdateInput>
}

/**
 * ProductEditorial delete
 */
export type ProductEditorialDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialInclude<ExtArgs> | null
  /**
   * Filter which ProductEditorial to delete.
   */
  where: Prisma.ProductEditorialWhereUniqueInput
}

/**
 * ProductEditorial deleteMany
 */
export type ProductEditorialDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductEditorials to delete
   */
  where?: Prisma.ProductEditorialWhereInput
  /**
   * Limit how many ProductEditorials to delete.
   */
  limit?: number
}

/**
 * ProductEditorial without action
 */
export type ProductEditorialDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductEditorial
   */
  select?: Prisma.ProductEditorialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductEditorial
   */
  omit?: Prisma.ProductEditorialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductEditorialInclude<ExtArgs> | null
}
