
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ShopifyProductBinding` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ShopifyProductBinding
 * État de synchro d'un **produit** — Shopify pousse un produit et ses variantes
 * ensemble, donc l'empreinte et le statut vivent à ce niveau. Les *références*,
 * elles, restent sur la déclinaison (R4) : ce sont deux choses différentes.
 */
export type ShopifyProductBindingModel = runtime.Types.Result.DefaultSelection<Prisma.$ShopifyProductBindingPayload>

export type AggregateShopifyProductBinding = {
  _count: ShopifyProductBindingCountAggregateOutputType | null
  _min: ShopifyProductBindingMinAggregateOutputType | null
  _max: ShopifyProductBindingMaxAggregateOutputType | null
}

export type ShopifyProductBindingMinAggregateOutputType = {
  productId: string | null
  shopifyProductGid: string | null
  lastPushedHash: string | null
  lastPushedAt: Date | null
  syncStatus: $Enums.ShopifySyncStatus | null
  lastError: string | null
  headSnapshotId: string | null
}

export type ShopifyProductBindingMaxAggregateOutputType = {
  productId: string | null
  shopifyProductGid: string | null
  lastPushedHash: string | null
  lastPushedAt: Date | null
  syncStatus: $Enums.ShopifySyncStatus | null
  lastError: string | null
  headSnapshotId: string | null
}

export type ShopifyProductBindingCountAggregateOutputType = {
  productId: number
  shopifyProductGid: number
  lastPushedHash: number
  lastPushedAt: number
  syncStatus: number
  lastError: number
  headSnapshotId: number
  _all: number
}


export type ShopifyProductBindingMinAggregateInputType = {
  productId?: true
  shopifyProductGid?: true
  lastPushedHash?: true
  lastPushedAt?: true
  syncStatus?: true
  lastError?: true
  headSnapshotId?: true
}

export type ShopifyProductBindingMaxAggregateInputType = {
  productId?: true
  shopifyProductGid?: true
  lastPushedHash?: true
  lastPushedAt?: true
  syncStatus?: true
  lastError?: true
  headSnapshotId?: true
}

export type ShopifyProductBindingCountAggregateInputType = {
  productId?: true
  shopifyProductGid?: true
  lastPushedHash?: true
  lastPushedAt?: true
  syncStatus?: true
  lastError?: true
  headSnapshotId?: true
  _all?: true
}

export type ShopifyProductBindingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShopifyProductBinding to aggregate.
   */
  where?: Prisma.ShopifyProductBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopifyProductBindings to fetch.
   */
  orderBy?: Prisma.ShopifyProductBindingOrderByWithRelationInput | Prisma.ShopifyProductBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ShopifyProductBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopifyProductBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopifyProductBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ShopifyProductBindings
  **/
  _count?: true | ShopifyProductBindingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ShopifyProductBindingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ShopifyProductBindingMaxAggregateInputType
}

export type GetShopifyProductBindingAggregateType<T extends ShopifyProductBindingAggregateArgs> = {
      [P in keyof T & keyof AggregateShopifyProductBinding]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateShopifyProductBinding[P]>
    : Prisma.GetScalarType<T[P], AggregateShopifyProductBinding[P]>
}




export type ShopifyProductBindingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShopifyProductBindingWhereInput
  orderBy?: Prisma.ShopifyProductBindingOrderByWithAggregationInput | Prisma.ShopifyProductBindingOrderByWithAggregationInput[]
  by: Prisma.ShopifyProductBindingScalarFieldEnum[] | Prisma.ShopifyProductBindingScalarFieldEnum
  having?: Prisma.ShopifyProductBindingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ShopifyProductBindingCountAggregateInputType | true
  _min?: ShopifyProductBindingMinAggregateInputType
  _max?: ShopifyProductBindingMaxAggregateInputType
}

export type ShopifyProductBindingGroupByOutputType = {
  productId: string
  shopifyProductGid: string | null
  lastPushedHash: string | null
  lastPushedAt: Date | null
  syncStatus: $Enums.ShopifySyncStatus
  lastError: string | null
  headSnapshotId: string | null
  _count: ShopifyProductBindingCountAggregateOutputType | null
  _min: ShopifyProductBindingMinAggregateOutputType | null
  _max: ShopifyProductBindingMaxAggregateOutputType | null
}

export type GetShopifyProductBindingGroupByPayload<T extends ShopifyProductBindingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ShopifyProductBindingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ShopifyProductBindingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ShopifyProductBindingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ShopifyProductBindingGroupByOutputType[P]>
      }
    >
  >



export type ShopifyProductBindingWhereInput = {
  AND?: Prisma.ShopifyProductBindingWhereInput | Prisma.ShopifyProductBindingWhereInput[]
  OR?: Prisma.ShopifyProductBindingWhereInput[]
  NOT?: Prisma.ShopifyProductBindingWhereInput | Prisma.ShopifyProductBindingWhereInput[]
  productId?: Prisma.StringFilter<"ShopifyProductBinding"> | string
  shopifyProductGid?: Prisma.StringNullableFilter<"ShopifyProductBinding"> | string | null
  lastPushedHash?: Prisma.StringNullableFilter<"ShopifyProductBinding"> | string | null
  lastPushedAt?: Prisma.DateTimeNullableFilter<"ShopifyProductBinding"> | Date | string | null
  syncStatus?: Prisma.EnumShopifySyncStatusFilter<"ShopifyProductBinding"> | $Enums.ShopifySyncStatus
  lastError?: Prisma.StringNullableFilter<"ShopifyProductBinding"> | string | null
  headSnapshotId?: Prisma.StringNullableFilter<"ShopifyProductBinding"> | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type ShopifyProductBindingOrderByWithRelationInput = {
  productId?: Prisma.SortOrder
  shopifyProductGid?: Prisma.SortOrderInput | Prisma.SortOrder
  lastPushedHash?: Prisma.SortOrderInput | Prisma.SortOrder
  lastPushedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  syncStatus?: Prisma.SortOrder
  lastError?: Prisma.SortOrderInput | Prisma.SortOrder
  headSnapshotId?: Prisma.SortOrderInput | Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type ShopifyProductBindingWhereUniqueInput = Prisma.AtLeast<{
  productId?: string
  AND?: Prisma.ShopifyProductBindingWhereInput | Prisma.ShopifyProductBindingWhereInput[]
  OR?: Prisma.ShopifyProductBindingWhereInput[]
  NOT?: Prisma.ShopifyProductBindingWhereInput | Prisma.ShopifyProductBindingWhereInput[]
  shopifyProductGid?: Prisma.StringNullableFilter<"ShopifyProductBinding"> | string | null
  lastPushedHash?: Prisma.StringNullableFilter<"ShopifyProductBinding"> | string | null
  lastPushedAt?: Prisma.DateTimeNullableFilter<"ShopifyProductBinding"> | Date | string | null
  syncStatus?: Prisma.EnumShopifySyncStatusFilter<"ShopifyProductBinding"> | $Enums.ShopifySyncStatus
  lastError?: Prisma.StringNullableFilter<"ShopifyProductBinding"> | string | null
  headSnapshotId?: Prisma.StringNullableFilter<"ShopifyProductBinding"> | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "productId">

export type ShopifyProductBindingOrderByWithAggregationInput = {
  productId?: Prisma.SortOrder
  shopifyProductGid?: Prisma.SortOrderInput | Prisma.SortOrder
  lastPushedHash?: Prisma.SortOrderInput | Prisma.SortOrder
  lastPushedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  syncStatus?: Prisma.SortOrder
  lastError?: Prisma.SortOrderInput | Prisma.SortOrder
  headSnapshotId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ShopifyProductBindingCountOrderByAggregateInput
  _max?: Prisma.ShopifyProductBindingMaxOrderByAggregateInput
  _min?: Prisma.ShopifyProductBindingMinOrderByAggregateInput
}

export type ShopifyProductBindingScalarWhereWithAggregatesInput = {
  AND?: Prisma.ShopifyProductBindingScalarWhereWithAggregatesInput | Prisma.ShopifyProductBindingScalarWhereWithAggregatesInput[]
  OR?: Prisma.ShopifyProductBindingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ShopifyProductBindingScalarWhereWithAggregatesInput | Prisma.ShopifyProductBindingScalarWhereWithAggregatesInput[]
  productId?: Prisma.StringWithAggregatesFilter<"ShopifyProductBinding"> | string
  shopifyProductGid?: Prisma.StringNullableWithAggregatesFilter<"ShopifyProductBinding"> | string | null
  lastPushedHash?: Prisma.StringNullableWithAggregatesFilter<"ShopifyProductBinding"> | string | null
  lastPushedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ShopifyProductBinding"> | Date | string | null
  syncStatus?: Prisma.EnumShopifySyncStatusWithAggregatesFilter<"ShopifyProductBinding"> | $Enums.ShopifySyncStatus
  lastError?: Prisma.StringNullableWithAggregatesFilter<"ShopifyProductBinding"> | string | null
  headSnapshotId?: Prisma.StringNullableWithAggregatesFilter<"ShopifyProductBinding"> | string | null
}

export type ShopifyProductBindingCreateInput = {
  shopifyProductGid?: string | null
  lastPushedHash?: string | null
  lastPushedAt?: Date | string | null
  syncStatus?: $Enums.ShopifySyncStatus
  lastError?: string | null
  headSnapshotId?: string | null
  product: Prisma.ProductCreateNestedOneWithoutShopifyBindingInput
}

export type ShopifyProductBindingUncheckedCreateInput = {
  productId: string
  shopifyProductGid?: string | null
  lastPushedHash?: string | null
  lastPushedAt?: Date | string | null
  syncStatus?: $Enums.ShopifySyncStatus
  lastError?: string | null
  headSnapshotId?: string | null
}

export type ShopifyProductBindingUpdateInput = {
  shopifyProductGid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  syncStatus?: Prisma.EnumShopifySyncStatusFieldUpdateOperationsInput | $Enums.ShopifySyncStatus
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headSnapshotId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  product?: Prisma.ProductUpdateOneRequiredWithoutShopifyBindingNestedInput
}

export type ShopifyProductBindingUncheckedUpdateInput = {
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  shopifyProductGid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  syncStatus?: Prisma.EnumShopifySyncStatusFieldUpdateOperationsInput | $Enums.ShopifySyncStatus
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headSnapshotId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ShopifyProductBindingCreateManyInput = {
  productId: string
  shopifyProductGid?: string | null
  lastPushedHash?: string | null
  lastPushedAt?: Date | string | null
  syncStatus?: $Enums.ShopifySyncStatus
  lastError?: string | null
  headSnapshotId?: string | null
}

export type ShopifyProductBindingUpdateManyMutationInput = {
  shopifyProductGid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  syncStatus?: Prisma.EnumShopifySyncStatusFieldUpdateOperationsInput | $Enums.ShopifySyncStatus
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headSnapshotId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ShopifyProductBindingUncheckedUpdateManyInput = {
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  shopifyProductGid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  syncStatus?: Prisma.EnumShopifySyncStatusFieldUpdateOperationsInput | $Enums.ShopifySyncStatus
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headSnapshotId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ShopifyProductBindingNullableScalarRelationFilter = {
  is?: Prisma.ShopifyProductBindingWhereInput | null
  isNot?: Prisma.ShopifyProductBindingWhereInput | null
}

export type ShopifyProductBindingCountOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  shopifyProductGid?: Prisma.SortOrder
  lastPushedHash?: Prisma.SortOrder
  lastPushedAt?: Prisma.SortOrder
  syncStatus?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  headSnapshotId?: Prisma.SortOrder
}

export type ShopifyProductBindingMaxOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  shopifyProductGid?: Prisma.SortOrder
  lastPushedHash?: Prisma.SortOrder
  lastPushedAt?: Prisma.SortOrder
  syncStatus?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  headSnapshotId?: Prisma.SortOrder
}

export type ShopifyProductBindingMinOrderByAggregateInput = {
  productId?: Prisma.SortOrder
  shopifyProductGid?: Prisma.SortOrder
  lastPushedHash?: Prisma.SortOrder
  lastPushedAt?: Prisma.SortOrder
  syncStatus?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  headSnapshotId?: Prisma.SortOrder
}

export type ShopifyProductBindingCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ShopifyProductBindingCreateWithoutProductInput, Prisma.ShopifyProductBindingUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ShopifyProductBindingCreateOrConnectWithoutProductInput
  connect?: Prisma.ShopifyProductBindingWhereUniqueInput
}

export type ShopifyProductBindingUncheckedCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ShopifyProductBindingCreateWithoutProductInput, Prisma.ShopifyProductBindingUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ShopifyProductBindingCreateOrConnectWithoutProductInput
  connect?: Prisma.ShopifyProductBindingWhereUniqueInput
}

export type ShopifyProductBindingUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ShopifyProductBindingCreateWithoutProductInput, Prisma.ShopifyProductBindingUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ShopifyProductBindingCreateOrConnectWithoutProductInput
  upsert?: Prisma.ShopifyProductBindingUpsertWithoutProductInput
  disconnect?: Prisma.ShopifyProductBindingWhereInput | boolean
  delete?: Prisma.ShopifyProductBindingWhereInput | boolean
  connect?: Prisma.ShopifyProductBindingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ShopifyProductBindingUpdateToOneWithWhereWithoutProductInput, Prisma.ShopifyProductBindingUpdateWithoutProductInput>, Prisma.ShopifyProductBindingUncheckedUpdateWithoutProductInput>
}

export type ShopifyProductBindingUncheckedUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ShopifyProductBindingCreateWithoutProductInput, Prisma.ShopifyProductBindingUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ShopifyProductBindingCreateOrConnectWithoutProductInput
  upsert?: Prisma.ShopifyProductBindingUpsertWithoutProductInput
  disconnect?: Prisma.ShopifyProductBindingWhereInput | boolean
  delete?: Prisma.ShopifyProductBindingWhereInput | boolean
  connect?: Prisma.ShopifyProductBindingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ShopifyProductBindingUpdateToOneWithWhereWithoutProductInput, Prisma.ShopifyProductBindingUpdateWithoutProductInput>, Prisma.ShopifyProductBindingUncheckedUpdateWithoutProductInput>
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type EnumShopifySyncStatusFieldUpdateOperationsInput = {
  set?: $Enums.ShopifySyncStatus
}

export type ShopifyProductBindingCreateWithoutProductInput = {
  shopifyProductGid?: string | null
  lastPushedHash?: string | null
  lastPushedAt?: Date | string | null
  syncStatus?: $Enums.ShopifySyncStatus
  lastError?: string | null
  headSnapshotId?: string | null
}

export type ShopifyProductBindingUncheckedCreateWithoutProductInput = {
  shopifyProductGid?: string | null
  lastPushedHash?: string | null
  lastPushedAt?: Date | string | null
  syncStatus?: $Enums.ShopifySyncStatus
  lastError?: string | null
  headSnapshotId?: string | null
}

export type ShopifyProductBindingCreateOrConnectWithoutProductInput = {
  where: Prisma.ShopifyProductBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.ShopifyProductBindingCreateWithoutProductInput, Prisma.ShopifyProductBindingUncheckedCreateWithoutProductInput>
}

export type ShopifyProductBindingUpsertWithoutProductInput = {
  update: Prisma.XOR<Prisma.ShopifyProductBindingUpdateWithoutProductInput, Prisma.ShopifyProductBindingUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ShopifyProductBindingCreateWithoutProductInput, Prisma.ShopifyProductBindingUncheckedCreateWithoutProductInput>
  where?: Prisma.ShopifyProductBindingWhereInput
}

export type ShopifyProductBindingUpdateToOneWithWhereWithoutProductInput = {
  where?: Prisma.ShopifyProductBindingWhereInput
  data: Prisma.XOR<Prisma.ShopifyProductBindingUpdateWithoutProductInput, Prisma.ShopifyProductBindingUncheckedUpdateWithoutProductInput>
}

export type ShopifyProductBindingUpdateWithoutProductInput = {
  shopifyProductGid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  syncStatus?: Prisma.EnumShopifySyncStatusFieldUpdateOperationsInput | $Enums.ShopifySyncStatus
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headSnapshotId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ShopifyProductBindingUncheckedUpdateWithoutProductInput = {
  shopifyProductGid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastPushedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  syncStatus?: Prisma.EnumShopifySyncStatusFieldUpdateOperationsInput | $Enums.ShopifySyncStatus
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headSnapshotId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type ShopifyProductBindingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productId?: boolean
  shopifyProductGid?: boolean
  lastPushedHash?: boolean
  lastPushedAt?: boolean
  syncStatus?: boolean
  lastError?: boolean
  headSnapshotId?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shopifyProductBinding"]>

export type ShopifyProductBindingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productId?: boolean
  shopifyProductGid?: boolean
  lastPushedHash?: boolean
  lastPushedAt?: boolean
  syncStatus?: boolean
  lastError?: boolean
  headSnapshotId?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shopifyProductBinding"]>

export type ShopifyProductBindingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  productId?: boolean
  shopifyProductGid?: boolean
  lastPushedHash?: boolean
  lastPushedAt?: boolean
  syncStatus?: boolean
  lastError?: boolean
  headSnapshotId?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shopifyProductBinding"]>

export type ShopifyProductBindingSelectScalar = {
  productId?: boolean
  shopifyProductGid?: boolean
  lastPushedHash?: boolean
  lastPushedAt?: boolean
  syncStatus?: boolean
  lastError?: boolean
  headSnapshotId?: boolean
}

export type ShopifyProductBindingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"productId" | "shopifyProductGid" | "lastPushedHash" | "lastPushedAt" | "syncStatus" | "lastError" | "headSnapshotId", ExtArgs["result"]["shopifyProductBinding"]>
export type ShopifyProductBindingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ShopifyProductBindingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ShopifyProductBindingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $ShopifyProductBindingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ShopifyProductBinding"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    productId: string
    shopifyProductGid: string | null
    lastPushedHash: string | null
    lastPushedAt: Date | null
    syncStatus: $Enums.ShopifySyncStatus
    lastError: string | null
    /**
     * Le snapshot **head** = le BASE de la réconciliation (la dernière poussée réelle).
     * `NULL` tant que rien n'a été poussé en `live`.
     */
    headSnapshotId: string | null
  }, ExtArgs["result"]["shopifyProductBinding"]>
  composites: {}
}

export type ShopifyProductBindingGetPayload<S extends boolean | null | undefined | ShopifyProductBindingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload, S>

export type ShopifyProductBindingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ShopifyProductBindingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ShopifyProductBindingCountAggregateInputType | true
  }

export interface ShopifyProductBindingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ShopifyProductBinding'], meta: { name: 'ShopifyProductBinding' } }
  /**
   * Find zero or one ShopifyProductBinding that matches the filter.
   * @param {ShopifyProductBindingFindUniqueArgs} args - Arguments to find a ShopifyProductBinding
   * @example
   * // Get one ShopifyProductBinding
   * const shopifyProductBinding = await prisma.shopifyProductBinding.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ShopifyProductBindingFindUniqueArgs>(args: Prisma.SelectSubset<T, ShopifyProductBindingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ShopifyProductBindingClient<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ShopifyProductBinding that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ShopifyProductBindingFindUniqueOrThrowArgs} args - Arguments to find a ShopifyProductBinding
   * @example
   * // Get one ShopifyProductBinding
   * const shopifyProductBinding = await prisma.shopifyProductBinding.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ShopifyProductBindingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ShopifyProductBindingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShopifyProductBindingClient<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShopifyProductBinding that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifyProductBindingFindFirstArgs} args - Arguments to find a ShopifyProductBinding
   * @example
   * // Get one ShopifyProductBinding
   * const shopifyProductBinding = await prisma.shopifyProductBinding.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ShopifyProductBindingFindFirstArgs>(args?: Prisma.SelectSubset<T, ShopifyProductBindingFindFirstArgs<ExtArgs>>): Prisma.Prisma__ShopifyProductBindingClient<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShopifyProductBinding that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifyProductBindingFindFirstOrThrowArgs} args - Arguments to find a ShopifyProductBinding
   * @example
   * // Get one ShopifyProductBinding
   * const shopifyProductBinding = await prisma.shopifyProductBinding.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ShopifyProductBindingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ShopifyProductBindingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShopifyProductBindingClient<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ShopifyProductBindings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifyProductBindingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ShopifyProductBindings
   * const shopifyProductBindings = await prisma.shopifyProductBinding.findMany()
   * 
   * // Get first 10 ShopifyProductBindings
   * const shopifyProductBindings = await prisma.shopifyProductBinding.findMany({ take: 10 })
   * 
   * // Only select the `productId`
   * const shopifyProductBindingWithProductIdOnly = await prisma.shopifyProductBinding.findMany({ select: { productId: true } })
   * 
   */
  findMany<T extends ShopifyProductBindingFindManyArgs>(args?: Prisma.SelectSubset<T, ShopifyProductBindingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ShopifyProductBinding.
   * @param {ShopifyProductBindingCreateArgs} args - Arguments to create a ShopifyProductBinding.
   * @example
   * // Create one ShopifyProductBinding
   * const ShopifyProductBinding = await prisma.shopifyProductBinding.create({
   *   data: {
   *     // ... data to create a ShopifyProductBinding
   *   }
   * })
   * 
   */
  create<T extends ShopifyProductBindingCreateArgs>(args: Prisma.SelectSubset<T, ShopifyProductBindingCreateArgs<ExtArgs>>): Prisma.Prisma__ShopifyProductBindingClient<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ShopifyProductBindings.
   * @param {ShopifyProductBindingCreateManyArgs} args - Arguments to create many ShopifyProductBindings.
   * @example
   * // Create many ShopifyProductBindings
   * const shopifyProductBinding = await prisma.shopifyProductBinding.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ShopifyProductBindingCreateManyArgs>(args?: Prisma.SelectSubset<T, ShopifyProductBindingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ShopifyProductBindings and returns the data saved in the database.
   * @param {ShopifyProductBindingCreateManyAndReturnArgs} args - Arguments to create many ShopifyProductBindings.
   * @example
   * // Create many ShopifyProductBindings
   * const shopifyProductBinding = await prisma.shopifyProductBinding.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ShopifyProductBindings and only return the `productId`
   * const shopifyProductBindingWithProductIdOnly = await prisma.shopifyProductBinding.createManyAndReturn({
   *   select: { productId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ShopifyProductBindingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ShopifyProductBindingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ShopifyProductBinding.
   * @param {ShopifyProductBindingDeleteArgs} args - Arguments to delete one ShopifyProductBinding.
   * @example
   * // Delete one ShopifyProductBinding
   * const ShopifyProductBinding = await prisma.shopifyProductBinding.delete({
   *   where: {
   *     // ... filter to delete one ShopifyProductBinding
   *   }
   * })
   * 
   */
  delete<T extends ShopifyProductBindingDeleteArgs>(args: Prisma.SelectSubset<T, ShopifyProductBindingDeleteArgs<ExtArgs>>): Prisma.Prisma__ShopifyProductBindingClient<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ShopifyProductBinding.
   * @param {ShopifyProductBindingUpdateArgs} args - Arguments to update one ShopifyProductBinding.
   * @example
   * // Update one ShopifyProductBinding
   * const shopifyProductBinding = await prisma.shopifyProductBinding.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ShopifyProductBindingUpdateArgs>(args: Prisma.SelectSubset<T, ShopifyProductBindingUpdateArgs<ExtArgs>>): Prisma.Prisma__ShopifyProductBindingClient<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ShopifyProductBindings.
   * @param {ShopifyProductBindingDeleteManyArgs} args - Arguments to filter ShopifyProductBindings to delete.
   * @example
   * // Delete a few ShopifyProductBindings
   * const { count } = await prisma.shopifyProductBinding.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ShopifyProductBindingDeleteManyArgs>(args?: Prisma.SelectSubset<T, ShopifyProductBindingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShopifyProductBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifyProductBindingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ShopifyProductBindings
   * const shopifyProductBinding = await prisma.shopifyProductBinding.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ShopifyProductBindingUpdateManyArgs>(args: Prisma.SelectSubset<T, ShopifyProductBindingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShopifyProductBindings and returns the data updated in the database.
   * @param {ShopifyProductBindingUpdateManyAndReturnArgs} args - Arguments to update many ShopifyProductBindings.
   * @example
   * // Update many ShopifyProductBindings
   * const shopifyProductBinding = await prisma.shopifyProductBinding.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ShopifyProductBindings and only return the `productId`
   * const shopifyProductBindingWithProductIdOnly = await prisma.shopifyProductBinding.updateManyAndReturn({
   *   select: { productId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ShopifyProductBindingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ShopifyProductBindingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ShopifyProductBinding.
   * @param {ShopifyProductBindingUpsertArgs} args - Arguments to update or create a ShopifyProductBinding.
   * @example
   * // Update or create a ShopifyProductBinding
   * const shopifyProductBinding = await prisma.shopifyProductBinding.upsert({
   *   create: {
   *     // ... data to create a ShopifyProductBinding
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ShopifyProductBinding we want to update
   *   }
   * })
   */
  upsert<T extends ShopifyProductBindingUpsertArgs>(args: Prisma.SelectSubset<T, ShopifyProductBindingUpsertArgs<ExtArgs>>): Prisma.Prisma__ShopifyProductBindingClient<runtime.Types.Result.GetResult<Prisma.$ShopifyProductBindingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ShopifyProductBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifyProductBindingCountArgs} args - Arguments to filter ShopifyProductBindings to count.
   * @example
   * // Count the number of ShopifyProductBindings
   * const count = await prisma.shopifyProductBinding.count({
   *   where: {
   *     // ... the filter for the ShopifyProductBindings we want to count
   *   }
   * })
  **/
  count<T extends ShopifyProductBindingCountArgs>(
    args?: Prisma.Subset<T, ShopifyProductBindingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ShopifyProductBindingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ShopifyProductBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifyProductBindingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ShopifyProductBindingAggregateArgs>(args: Prisma.Subset<T, ShopifyProductBindingAggregateArgs>): Prisma.PrismaPromise<GetShopifyProductBindingAggregateType<T>>

  /**
   * Group by ShopifyProductBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifyProductBindingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ShopifyProductBindingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ShopifyProductBindingGroupByArgs['orderBy'] }
      : { orderBy?: ShopifyProductBindingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ShopifyProductBindingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetShopifyProductBindingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ShopifyProductBinding model
 */
readonly fields: ShopifyProductBindingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ShopifyProductBinding.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ShopifyProductBindingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ShopifyProductBinding model
 */
export interface ShopifyProductBindingFieldRefs {
  readonly productId: Prisma.FieldRef<"ShopifyProductBinding", 'String'>
  readonly shopifyProductGid: Prisma.FieldRef<"ShopifyProductBinding", 'String'>
  readonly lastPushedHash: Prisma.FieldRef<"ShopifyProductBinding", 'String'>
  readonly lastPushedAt: Prisma.FieldRef<"ShopifyProductBinding", 'DateTime'>
  readonly syncStatus: Prisma.FieldRef<"ShopifyProductBinding", 'ShopifySyncStatus'>
  readonly lastError: Prisma.FieldRef<"ShopifyProductBinding", 'String'>
  readonly headSnapshotId: Prisma.FieldRef<"ShopifyProductBinding", 'String'>
}
    

// Custom InputTypes
/**
 * ShopifyProductBinding findUnique
 */
export type ShopifyProductBindingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingInclude<ExtArgs> | null
  /**
   * Filter, which ShopifyProductBinding to fetch.
   */
  where: Prisma.ShopifyProductBindingWhereUniqueInput
}

/**
 * ShopifyProductBinding findUniqueOrThrow
 */
export type ShopifyProductBindingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingInclude<ExtArgs> | null
  /**
   * Filter, which ShopifyProductBinding to fetch.
   */
  where: Prisma.ShopifyProductBindingWhereUniqueInput
}

/**
 * ShopifyProductBinding findFirst
 */
export type ShopifyProductBindingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingInclude<ExtArgs> | null
  /**
   * Filter, which ShopifyProductBinding to fetch.
   */
  where?: Prisma.ShopifyProductBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopifyProductBindings to fetch.
   */
  orderBy?: Prisma.ShopifyProductBindingOrderByWithRelationInput | Prisma.ShopifyProductBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShopifyProductBindings.
   */
  cursor?: Prisma.ShopifyProductBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopifyProductBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopifyProductBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShopifyProductBindings.
   */
  distinct?: Prisma.ShopifyProductBindingScalarFieldEnum | Prisma.ShopifyProductBindingScalarFieldEnum[]
}

/**
 * ShopifyProductBinding findFirstOrThrow
 */
export type ShopifyProductBindingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingInclude<ExtArgs> | null
  /**
   * Filter, which ShopifyProductBinding to fetch.
   */
  where?: Prisma.ShopifyProductBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopifyProductBindings to fetch.
   */
  orderBy?: Prisma.ShopifyProductBindingOrderByWithRelationInput | Prisma.ShopifyProductBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShopifyProductBindings.
   */
  cursor?: Prisma.ShopifyProductBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopifyProductBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopifyProductBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShopifyProductBindings.
   */
  distinct?: Prisma.ShopifyProductBindingScalarFieldEnum | Prisma.ShopifyProductBindingScalarFieldEnum[]
}

/**
 * ShopifyProductBinding findMany
 */
export type ShopifyProductBindingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingInclude<ExtArgs> | null
  /**
   * Filter, which ShopifyProductBindings to fetch.
   */
  where?: Prisma.ShopifyProductBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopifyProductBindings to fetch.
   */
  orderBy?: Prisma.ShopifyProductBindingOrderByWithRelationInput | Prisma.ShopifyProductBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ShopifyProductBindings.
   */
  cursor?: Prisma.ShopifyProductBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopifyProductBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopifyProductBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShopifyProductBindings.
   */
  distinct?: Prisma.ShopifyProductBindingScalarFieldEnum | Prisma.ShopifyProductBindingScalarFieldEnum[]
}

/**
 * ShopifyProductBinding create
 */
export type ShopifyProductBindingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingInclude<ExtArgs> | null
  /**
   * The data needed to create a ShopifyProductBinding.
   */
  data: Prisma.XOR<Prisma.ShopifyProductBindingCreateInput, Prisma.ShopifyProductBindingUncheckedCreateInput>
}

/**
 * ShopifyProductBinding createMany
 */
export type ShopifyProductBindingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ShopifyProductBindings.
   */
  data: Prisma.ShopifyProductBindingCreateManyInput | Prisma.ShopifyProductBindingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ShopifyProductBinding createManyAndReturn
 */
export type ShopifyProductBindingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * The data used to create many ShopifyProductBindings.
   */
  data: Prisma.ShopifyProductBindingCreateManyInput | Prisma.ShopifyProductBindingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ShopifyProductBinding update
 */
export type ShopifyProductBindingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingInclude<ExtArgs> | null
  /**
   * The data needed to update a ShopifyProductBinding.
   */
  data: Prisma.XOR<Prisma.ShopifyProductBindingUpdateInput, Prisma.ShopifyProductBindingUncheckedUpdateInput>
  /**
   * Choose, which ShopifyProductBinding to update.
   */
  where: Prisma.ShopifyProductBindingWhereUniqueInput
}

/**
 * ShopifyProductBinding updateMany
 */
export type ShopifyProductBindingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ShopifyProductBindings.
   */
  data: Prisma.XOR<Prisma.ShopifyProductBindingUpdateManyMutationInput, Prisma.ShopifyProductBindingUncheckedUpdateManyInput>
  /**
   * Filter which ShopifyProductBindings to update
   */
  where?: Prisma.ShopifyProductBindingWhereInput
  /**
   * Limit how many ShopifyProductBindings to update.
   */
  limit?: number
}

/**
 * ShopifyProductBinding updateManyAndReturn
 */
export type ShopifyProductBindingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * The data used to update ShopifyProductBindings.
   */
  data: Prisma.XOR<Prisma.ShopifyProductBindingUpdateManyMutationInput, Prisma.ShopifyProductBindingUncheckedUpdateManyInput>
  /**
   * Filter which ShopifyProductBindings to update
   */
  where?: Prisma.ShopifyProductBindingWhereInput
  /**
   * Limit how many ShopifyProductBindings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ShopifyProductBinding upsert
 */
export type ShopifyProductBindingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingInclude<ExtArgs> | null
  /**
   * The filter to search for the ShopifyProductBinding to update in case it exists.
   */
  where: Prisma.ShopifyProductBindingWhereUniqueInput
  /**
   * In case the ShopifyProductBinding found by the `where` argument doesn't exist, create a new ShopifyProductBinding with this data.
   */
  create: Prisma.XOR<Prisma.ShopifyProductBindingCreateInput, Prisma.ShopifyProductBindingUncheckedCreateInput>
  /**
   * In case the ShopifyProductBinding was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ShopifyProductBindingUpdateInput, Prisma.ShopifyProductBindingUncheckedUpdateInput>
}

/**
 * ShopifyProductBinding delete
 */
export type ShopifyProductBindingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingInclude<ExtArgs> | null
  /**
   * Filter which ShopifyProductBinding to delete.
   */
  where: Prisma.ShopifyProductBindingWhereUniqueInput
}

/**
 * ShopifyProductBinding deleteMany
 */
export type ShopifyProductBindingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShopifyProductBindings to delete
   */
  where?: Prisma.ShopifyProductBindingWhereInput
  /**
   * Limit how many ShopifyProductBindings to delete.
   */
  limit?: number
}

/**
 * ShopifyProductBinding without action
 */
export type ShopifyProductBindingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifyProductBinding
   */
  select?: Prisma.ShopifyProductBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifyProductBinding
   */
  omit?: Prisma.ShopifyProductBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShopifyProductBindingInclude<ExtArgs> | null
}
