
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ShopifySettings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ShopifySettings
 * Réglages de l'intégration — ligne unique.
 * ⚠️ Aucun secret ici : le jeton d'API vit dans l'environnement (`AppConfig`).
 */
export type ShopifySettingsModel = runtime.Types.Result.DefaultSelection<Prisma.$ShopifySettingsPayload>

export type AggregateShopifySettings = {
  _count: ShopifySettingsCountAggregateOutputType | null
  _min: ShopifySettingsMinAggregateOutputType | null
  _max: ShopifySettingsMaxAggregateOutputType | null
}

export type ShopifySettingsMinAggregateOutputType = {
  id: string | null
  shopDomain: string | null
  apiVersion: string | null
  isEnabled: boolean | null
  updatedAt: Date | null
}

export type ShopifySettingsMaxAggregateOutputType = {
  id: string | null
  shopDomain: string | null
  apiVersion: string | null
  isEnabled: boolean | null
  updatedAt: Date | null
}

export type ShopifySettingsCountAggregateOutputType = {
  id: number
  shopDomain: number
  apiVersion: number
  isEnabled: number
  updatedAt: number
  _all: number
}


export type ShopifySettingsMinAggregateInputType = {
  id?: true
  shopDomain?: true
  apiVersion?: true
  isEnabled?: true
  updatedAt?: true
}

export type ShopifySettingsMaxAggregateInputType = {
  id?: true
  shopDomain?: true
  apiVersion?: true
  isEnabled?: true
  updatedAt?: true
}

export type ShopifySettingsCountAggregateInputType = {
  id?: true
  shopDomain?: true
  apiVersion?: true
  isEnabled?: true
  updatedAt?: true
  _all?: true
}

export type ShopifySettingsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShopifySettings to aggregate.
   */
  where?: Prisma.ShopifySettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopifySettings to fetch.
   */
  orderBy?: Prisma.ShopifySettingsOrderByWithRelationInput | Prisma.ShopifySettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ShopifySettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopifySettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopifySettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ShopifySettings
  **/
  _count?: true | ShopifySettingsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ShopifySettingsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ShopifySettingsMaxAggregateInputType
}

export type GetShopifySettingsAggregateType<T extends ShopifySettingsAggregateArgs> = {
      [P in keyof T & keyof AggregateShopifySettings]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateShopifySettings[P]>
    : Prisma.GetScalarType<T[P], AggregateShopifySettings[P]>
}




export type ShopifySettingsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShopifySettingsWhereInput
  orderBy?: Prisma.ShopifySettingsOrderByWithAggregationInput | Prisma.ShopifySettingsOrderByWithAggregationInput[]
  by: Prisma.ShopifySettingsScalarFieldEnum[] | Prisma.ShopifySettingsScalarFieldEnum
  having?: Prisma.ShopifySettingsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ShopifySettingsCountAggregateInputType | true
  _min?: ShopifySettingsMinAggregateInputType
  _max?: ShopifySettingsMaxAggregateInputType
}

export type ShopifySettingsGroupByOutputType = {
  id: string
  shopDomain: string
  apiVersion: string
  isEnabled: boolean
  updatedAt: Date
  _count: ShopifySettingsCountAggregateOutputType | null
  _min: ShopifySettingsMinAggregateOutputType | null
  _max: ShopifySettingsMaxAggregateOutputType | null
}

export type GetShopifySettingsGroupByPayload<T extends ShopifySettingsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ShopifySettingsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ShopifySettingsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ShopifySettingsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ShopifySettingsGroupByOutputType[P]>
      }
    >
  >



export type ShopifySettingsWhereInput = {
  AND?: Prisma.ShopifySettingsWhereInput | Prisma.ShopifySettingsWhereInput[]
  OR?: Prisma.ShopifySettingsWhereInput[]
  NOT?: Prisma.ShopifySettingsWhereInput | Prisma.ShopifySettingsWhereInput[]
  id?: Prisma.StringFilter<"ShopifySettings"> | string
  shopDomain?: Prisma.StringFilter<"ShopifySettings"> | string
  apiVersion?: Prisma.StringFilter<"ShopifySettings"> | string
  isEnabled?: Prisma.BoolFilter<"ShopifySettings"> | boolean
  updatedAt?: Prisma.DateTimeFilter<"ShopifySettings"> | Date | string
}

export type ShopifySettingsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  shopDomain?: Prisma.SortOrder
  apiVersion?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShopifySettingsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ShopifySettingsWhereInput | Prisma.ShopifySettingsWhereInput[]
  OR?: Prisma.ShopifySettingsWhereInput[]
  NOT?: Prisma.ShopifySettingsWhereInput | Prisma.ShopifySettingsWhereInput[]
  shopDomain?: Prisma.StringFilter<"ShopifySettings"> | string
  apiVersion?: Prisma.StringFilter<"ShopifySettings"> | string
  isEnabled?: Prisma.BoolFilter<"ShopifySettings"> | boolean
  updatedAt?: Prisma.DateTimeFilter<"ShopifySettings"> | Date | string
}, "id">

export type ShopifySettingsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  shopDomain?: Prisma.SortOrder
  apiVersion?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ShopifySettingsCountOrderByAggregateInput
  _max?: Prisma.ShopifySettingsMaxOrderByAggregateInput
  _min?: Prisma.ShopifySettingsMinOrderByAggregateInput
}

export type ShopifySettingsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ShopifySettingsScalarWhereWithAggregatesInput | Prisma.ShopifySettingsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ShopifySettingsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ShopifySettingsScalarWhereWithAggregatesInput | Prisma.ShopifySettingsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ShopifySettings"> | string
  shopDomain?: Prisma.StringWithAggregatesFilter<"ShopifySettings"> | string
  apiVersion?: Prisma.StringWithAggregatesFilter<"ShopifySettings"> | string
  isEnabled?: Prisma.BoolWithAggregatesFilter<"ShopifySettings"> | boolean
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ShopifySettings"> | Date | string
}

export type ShopifySettingsCreateInput = {
  id: string
  shopDomain: string
  apiVersion: string
  isEnabled?: boolean
  updatedAt?: Date | string
}

export type ShopifySettingsUncheckedCreateInput = {
  id: string
  shopDomain: string
  apiVersion: string
  isEnabled?: boolean
  updatedAt?: Date | string
}

export type ShopifySettingsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shopDomain?: Prisma.StringFieldUpdateOperationsInput | string
  apiVersion?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShopifySettingsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shopDomain?: Prisma.StringFieldUpdateOperationsInput | string
  apiVersion?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShopifySettingsCreateManyInput = {
  id: string
  shopDomain: string
  apiVersion: string
  isEnabled?: boolean
  updatedAt?: Date | string
}

export type ShopifySettingsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shopDomain?: Prisma.StringFieldUpdateOperationsInput | string
  apiVersion?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShopifySettingsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shopDomain?: Prisma.StringFieldUpdateOperationsInput | string
  apiVersion?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShopifySettingsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shopDomain?: Prisma.SortOrder
  apiVersion?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShopifySettingsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shopDomain?: Prisma.SortOrder
  apiVersion?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShopifySettingsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shopDomain?: Prisma.SortOrder
  apiVersion?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type ShopifySettingsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shopDomain?: boolean
  apiVersion?: boolean
  isEnabled?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["shopifySettings"]>

export type ShopifySettingsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shopDomain?: boolean
  apiVersion?: boolean
  isEnabled?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["shopifySettings"]>

export type ShopifySettingsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shopDomain?: boolean
  apiVersion?: boolean
  isEnabled?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["shopifySettings"]>

export type ShopifySettingsSelectScalar = {
  id?: boolean
  shopDomain?: boolean
  apiVersion?: boolean
  isEnabled?: boolean
  updatedAt?: boolean
}

export type ShopifySettingsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "shopDomain" | "apiVersion" | "isEnabled" | "updatedAt", ExtArgs["result"]["shopifySettings"]>

export type $ShopifySettingsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ShopifySettings"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    shopDomain: string
    apiVersion: string
    isEnabled: boolean
    updatedAt: Date
  }, ExtArgs["result"]["shopifySettings"]>
  composites: {}
}

export type ShopifySettingsGetPayload<S extends boolean | null | undefined | ShopifySettingsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload, S>

export type ShopifySettingsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ShopifySettingsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ShopifySettingsCountAggregateInputType | true
  }

export interface ShopifySettingsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ShopifySettings'], meta: { name: 'ShopifySettings' } }
  /**
   * Find zero or one ShopifySettings that matches the filter.
   * @param {ShopifySettingsFindUniqueArgs} args - Arguments to find a ShopifySettings
   * @example
   * // Get one ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ShopifySettingsFindUniqueArgs>(args: Prisma.SelectSubset<T, ShopifySettingsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ShopifySettingsClient<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ShopifySettings that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ShopifySettingsFindUniqueOrThrowArgs} args - Arguments to find a ShopifySettings
   * @example
   * // Get one ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ShopifySettingsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ShopifySettingsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShopifySettingsClient<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShopifySettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifySettingsFindFirstArgs} args - Arguments to find a ShopifySettings
   * @example
   * // Get one ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ShopifySettingsFindFirstArgs>(args?: Prisma.SelectSubset<T, ShopifySettingsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ShopifySettingsClient<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShopifySettings that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifySettingsFindFirstOrThrowArgs} args - Arguments to find a ShopifySettings
   * @example
   * // Get one ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ShopifySettingsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ShopifySettingsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShopifySettingsClient<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ShopifySettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifySettingsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.findMany()
   * 
   * // Get first 10 ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const shopifySettingsWithIdOnly = await prisma.shopifySettings.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ShopifySettingsFindManyArgs>(args?: Prisma.SelectSubset<T, ShopifySettingsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ShopifySettings.
   * @param {ShopifySettingsCreateArgs} args - Arguments to create a ShopifySettings.
   * @example
   * // Create one ShopifySettings
   * const ShopifySettings = await prisma.shopifySettings.create({
   *   data: {
   *     // ... data to create a ShopifySettings
   *   }
   * })
   * 
   */
  create<T extends ShopifySettingsCreateArgs>(args: Prisma.SelectSubset<T, ShopifySettingsCreateArgs<ExtArgs>>): Prisma.Prisma__ShopifySettingsClient<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ShopifySettings.
   * @param {ShopifySettingsCreateManyArgs} args - Arguments to create many ShopifySettings.
   * @example
   * // Create many ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ShopifySettingsCreateManyArgs>(args?: Prisma.SelectSubset<T, ShopifySettingsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ShopifySettings and returns the data saved in the database.
   * @param {ShopifySettingsCreateManyAndReturnArgs} args - Arguments to create many ShopifySettings.
   * @example
   * // Create many ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ShopifySettings and only return the `id`
   * const shopifySettingsWithIdOnly = await prisma.shopifySettings.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ShopifySettingsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ShopifySettingsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ShopifySettings.
   * @param {ShopifySettingsDeleteArgs} args - Arguments to delete one ShopifySettings.
   * @example
   * // Delete one ShopifySettings
   * const ShopifySettings = await prisma.shopifySettings.delete({
   *   where: {
   *     // ... filter to delete one ShopifySettings
   *   }
   * })
   * 
   */
  delete<T extends ShopifySettingsDeleteArgs>(args: Prisma.SelectSubset<T, ShopifySettingsDeleteArgs<ExtArgs>>): Prisma.Prisma__ShopifySettingsClient<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ShopifySettings.
   * @param {ShopifySettingsUpdateArgs} args - Arguments to update one ShopifySettings.
   * @example
   * // Update one ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ShopifySettingsUpdateArgs>(args: Prisma.SelectSubset<T, ShopifySettingsUpdateArgs<ExtArgs>>): Prisma.Prisma__ShopifySettingsClient<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ShopifySettings.
   * @param {ShopifySettingsDeleteManyArgs} args - Arguments to filter ShopifySettings to delete.
   * @example
   * // Delete a few ShopifySettings
   * const { count } = await prisma.shopifySettings.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ShopifySettingsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ShopifySettingsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShopifySettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifySettingsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ShopifySettingsUpdateManyArgs>(args: Prisma.SelectSubset<T, ShopifySettingsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShopifySettings and returns the data updated in the database.
   * @param {ShopifySettingsUpdateManyAndReturnArgs} args - Arguments to update many ShopifySettings.
   * @example
   * // Update many ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ShopifySettings and only return the `id`
   * const shopifySettingsWithIdOnly = await prisma.shopifySettings.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ShopifySettingsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ShopifySettingsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ShopifySettings.
   * @param {ShopifySettingsUpsertArgs} args - Arguments to update or create a ShopifySettings.
   * @example
   * // Update or create a ShopifySettings
   * const shopifySettings = await prisma.shopifySettings.upsert({
   *   create: {
   *     // ... data to create a ShopifySettings
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ShopifySettings we want to update
   *   }
   * })
   */
  upsert<T extends ShopifySettingsUpsertArgs>(args: Prisma.SelectSubset<T, ShopifySettingsUpsertArgs<ExtArgs>>): Prisma.Prisma__ShopifySettingsClient<runtime.Types.Result.GetResult<Prisma.$ShopifySettingsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ShopifySettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifySettingsCountArgs} args - Arguments to filter ShopifySettings to count.
   * @example
   * // Count the number of ShopifySettings
   * const count = await prisma.shopifySettings.count({
   *   where: {
   *     // ... the filter for the ShopifySettings we want to count
   *   }
   * })
  **/
  count<T extends ShopifySettingsCountArgs>(
    args?: Prisma.Subset<T, ShopifySettingsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ShopifySettingsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ShopifySettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifySettingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ShopifySettingsAggregateArgs>(args: Prisma.Subset<T, ShopifySettingsAggregateArgs>): Prisma.PrismaPromise<GetShopifySettingsAggregateType<T>>

  /**
   * Group by ShopifySettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShopifySettingsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ShopifySettingsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ShopifySettingsGroupByArgs['orderBy'] }
      : { orderBy?: ShopifySettingsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ShopifySettingsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetShopifySettingsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ShopifySettings model
 */
readonly fields: ShopifySettingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ShopifySettings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ShopifySettingsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ShopifySettings model
 */
export interface ShopifySettingsFieldRefs {
  readonly id: Prisma.FieldRef<"ShopifySettings", 'String'>
  readonly shopDomain: Prisma.FieldRef<"ShopifySettings", 'String'>
  readonly apiVersion: Prisma.FieldRef<"ShopifySettings", 'String'>
  readonly isEnabled: Prisma.FieldRef<"ShopifySettings", 'Boolean'>
  readonly updatedAt: Prisma.FieldRef<"ShopifySettings", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ShopifySettings findUnique
 */
export type ShopifySettingsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * Filter, which ShopifySettings to fetch.
   */
  where: Prisma.ShopifySettingsWhereUniqueInput
}

/**
 * ShopifySettings findUniqueOrThrow
 */
export type ShopifySettingsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * Filter, which ShopifySettings to fetch.
   */
  where: Prisma.ShopifySettingsWhereUniqueInput
}

/**
 * ShopifySettings findFirst
 */
export type ShopifySettingsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * Filter, which ShopifySettings to fetch.
   */
  where?: Prisma.ShopifySettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopifySettings to fetch.
   */
  orderBy?: Prisma.ShopifySettingsOrderByWithRelationInput | Prisma.ShopifySettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShopifySettings.
   */
  cursor?: Prisma.ShopifySettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopifySettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopifySettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShopifySettings.
   */
  distinct?: Prisma.ShopifySettingsScalarFieldEnum | Prisma.ShopifySettingsScalarFieldEnum[]
}

/**
 * ShopifySettings findFirstOrThrow
 */
export type ShopifySettingsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * Filter, which ShopifySettings to fetch.
   */
  where?: Prisma.ShopifySettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopifySettings to fetch.
   */
  orderBy?: Prisma.ShopifySettingsOrderByWithRelationInput | Prisma.ShopifySettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShopifySettings.
   */
  cursor?: Prisma.ShopifySettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopifySettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopifySettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShopifySettings.
   */
  distinct?: Prisma.ShopifySettingsScalarFieldEnum | Prisma.ShopifySettingsScalarFieldEnum[]
}

/**
 * ShopifySettings findMany
 */
export type ShopifySettingsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * Filter, which ShopifySettings to fetch.
   */
  where?: Prisma.ShopifySettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShopifySettings to fetch.
   */
  orderBy?: Prisma.ShopifySettingsOrderByWithRelationInput | Prisma.ShopifySettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ShopifySettings.
   */
  cursor?: Prisma.ShopifySettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShopifySettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShopifySettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShopifySettings.
   */
  distinct?: Prisma.ShopifySettingsScalarFieldEnum | Prisma.ShopifySettingsScalarFieldEnum[]
}

/**
 * ShopifySettings create
 */
export type ShopifySettingsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * The data needed to create a ShopifySettings.
   */
  data: Prisma.XOR<Prisma.ShopifySettingsCreateInput, Prisma.ShopifySettingsUncheckedCreateInput>
}

/**
 * ShopifySettings createMany
 */
export type ShopifySettingsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ShopifySettings.
   */
  data: Prisma.ShopifySettingsCreateManyInput | Prisma.ShopifySettingsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ShopifySettings createManyAndReturn
 */
export type ShopifySettingsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * The data used to create many ShopifySettings.
   */
  data: Prisma.ShopifySettingsCreateManyInput | Prisma.ShopifySettingsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ShopifySettings update
 */
export type ShopifySettingsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * The data needed to update a ShopifySettings.
   */
  data: Prisma.XOR<Prisma.ShopifySettingsUpdateInput, Prisma.ShopifySettingsUncheckedUpdateInput>
  /**
   * Choose, which ShopifySettings to update.
   */
  where: Prisma.ShopifySettingsWhereUniqueInput
}

/**
 * ShopifySettings updateMany
 */
export type ShopifySettingsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ShopifySettings.
   */
  data: Prisma.XOR<Prisma.ShopifySettingsUpdateManyMutationInput, Prisma.ShopifySettingsUncheckedUpdateManyInput>
  /**
   * Filter which ShopifySettings to update
   */
  where?: Prisma.ShopifySettingsWhereInput
  /**
   * Limit how many ShopifySettings to update.
   */
  limit?: number
}

/**
 * ShopifySettings updateManyAndReturn
 */
export type ShopifySettingsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * The data used to update ShopifySettings.
   */
  data: Prisma.XOR<Prisma.ShopifySettingsUpdateManyMutationInput, Prisma.ShopifySettingsUncheckedUpdateManyInput>
  /**
   * Filter which ShopifySettings to update
   */
  where?: Prisma.ShopifySettingsWhereInput
  /**
   * Limit how many ShopifySettings to update.
   */
  limit?: number
}

/**
 * ShopifySettings upsert
 */
export type ShopifySettingsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * The filter to search for the ShopifySettings to update in case it exists.
   */
  where: Prisma.ShopifySettingsWhereUniqueInput
  /**
   * In case the ShopifySettings found by the `where` argument doesn't exist, create a new ShopifySettings with this data.
   */
  create: Prisma.XOR<Prisma.ShopifySettingsCreateInput, Prisma.ShopifySettingsUncheckedCreateInput>
  /**
   * In case the ShopifySettings was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ShopifySettingsUpdateInput, Prisma.ShopifySettingsUncheckedUpdateInput>
}

/**
 * ShopifySettings delete
 */
export type ShopifySettingsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
  /**
   * Filter which ShopifySettings to delete.
   */
  where: Prisma.ShopifySettingsWhereUniqueInput
}

/**
 * ShopifySettings deleteMany
 */
export type ShopifySettingsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShopifySettings to delete
   */
  where?: Prisma.ShopifySettingsWhereInput
  /**
   * Limit how many ShopifySettings to delete.
   */
  limit?: number
}

/**
 * ShopifySettings without action
 */
export type ShopifySettingsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShopifySettings
   */
  select?: Prisma.ShopifySettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShopifySettings
   */
  omit?: Prisma.ShopifySettingsOmit<ExtArgs> | null
}
