
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SkuRegistry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SkuRegistry
 * Registre des références — garantit l'unicité du SKU dans un espace de noms
 * GLOBAL (produits et déclinaisons confondus, doc 06 invariant 1).
 * Une contrainte d'unicité ne pouvant pas s'étendre à deux tables, c'est ce
 * registre qui porte la garantie : la violation de sa clé primaire est le
 * `23505` traduit en `SkuAlreadyUsedError` par l'adaptateur de dépôt.
 */
export type SkuRegistryModel = runtime.Types.Result.DefaultSelection<Prisma.$SkuRegistryPayload>

export type AggregateSkuRegistry = {
  _count: SkuRegistryCountAggregateOutputType | null
  _min: SkuRegistryMinAggregateOutputType | null
  _max: SkuRegistryMaxAggregateOutputType | null
}

export type SkuRegistryMinAggregateOutputType = {
  value: string | null
  ownerType: $Enums.SkuOwnerType | null
  ownerId: string | null
}

export type SkuRegistryMaxAggregateOutputType = {
  value: string | null
  ownerType: $Enums.SkuOwnerType | null
  ownerId: string | null
}

export type SkuRegistryCountAggregateOutputType = {
  value: number
  ownerType: number
  ownerId: number
  _all: number
}


export type SkuRegistryMinAggregateInputType = {
  value?: true
  ownerType?: true
  ownerId?: true
}

export type SkuRegistryMaxAggregateInputType = {
  value?: true
  ownerType?: true
  ownerId?: true
}

export type SkuRegistryCountAggregateInputType = {
  value?: true
  ownerType?: true
  ownerId?: true
  _all?: true
}

export type SkuRegistryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SkuRegistry to aggregate.
   */
  where?: Prisma.SkuRegistryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkuRegistries to fetch.
   */
  orderBy?: Prisma.SkuRegistryOrderByWithRelationInput | Prisma.SkuRegistryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SkuRegistryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkuRegistries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkuRegistries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SkuRegistries
  **/
  _count?: true | SkuRegistryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SkuRegistryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SkuRegistryMaxAggregateInputType
}

export type GetSkuRegistryAggregateType<T extends SkuRegistryAggregateArgs> = {
      [P in keyof T & keyof AggregateSkuRegistry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSkuRegistry[P]>
    : Prisma.GetScalarType<T[P], AggregateSkuRegistry[P]>
}




export type SkuRegistryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SkuRegistryWhereInput
  orderBy?: Prisma.SkuRegistryOrderByWithAggregationInput | Prisma.SkuRegistryOrderByWithAggregationInput[]
  by: Prisma.SkuRegistryScalarFieldEnum[] | Prisma.SkuRegistryScalarFieldEnum
  having?: Prisma.SkuRegistryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SkuRegistryCountAggregateInputType | true
  _min?: SkuRegistryMinAggregateInputType
  _max?: SkuRegistryMaxAggregateInputType
}

export type SkuRegistryGroupByOutputType = {
  value: string
  ownerType: $Enums.SkuOwnerType
  ownerId: string
  _count: SkuRegistryCountAggregateOutputType | null
  _min: SkuRegistryMinAggregateOutputType | null
  _max: SkuRegistryMaxAggregateOutputType | null
}

export type GetSkuRegistryGroupByPayload<T extends SkuRegistryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SkuRegistryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SkuRegistryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SkuRegistryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SkuRegistryGroupByOutputType[P]>
      }
    >
  >



export type SkuRegistryWhereInput = {
  AND?: Prisma.SkuRegistryWhereInput | Prisma.SkuRegistryWhereInput[]
  OR?: Prisma.SkuRegistryWhereInput[]
  NOT?: Prisma.SkuRegistryWhereInput | Prisma.SkuRegistryWhereInput[]
  value?: Prisma.StringFilter<"SkuRegistry"> | string
  ownerType?: Prisma.EnumSkuOwnerTypeFilter<"SkuRegistry"> | $Enums.SkuOwnerType
  ownerId?: Prisma.StringFilter<"SkuRegistry"> | string
}

export type SkuRegistryOrderByWithRelationInput = {
  value?: Prisma.SortOrder
  ownerType?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type SkuRegistryWhereUniqueInput = Prisma.AtLeast<{
  value?: string
  AND?: Prisma.SkuRegistryWhereInput | Prisma.SkuRegistryWhereInput[]
  OR?: Prisma.SkuRegistryWhereInput[]
  NOT?: Prisma.SkuRegistryWhereInput | Prisma.SkuRegistryWhereInput[]
  ownerType?: Prisma.EnumSkuOwnerTypeFilter<"SkuRegistry"> | $Enums.SkuOwnerType
  ownerId?: Prisma.StringFilter<"SkuRegistry"> | string
}, "value">

export type SkuRegistryOrderByWithAggregationInput = {
  value?: Prisma.SortOrder
  ownerType?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  _count?: Prisma.SkuRegistryCountOrderByAggregateInput
  _max?: Prisma.SkuRegistryMaxOrderByAggregateInput
  _min?: Prisma.SkuRegistryMinOrderByAggregateInput
}

export type SkuRegistryScalarWhereWithAggregatesInput = {
  AND?: Prisma.SkuRegistryScalarWhereWithAggregatesInput | Prisma.SkuRegistryScalarWhereWithAggregatesInput[]
  OR?: Prisma.SkuRegistryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SkuRegistryScalarWhereWithAggregatesInput | Prisma.SkuRegistryScalarWhereWithAggregatesInput[]
  value?: Prisma.StringWithAggregatesFilter<"SkuRegistry"> | string
  ownerType?: Prisma.EnumSkuOwnerTypeWithAggregatesFilter<"SkuRegistry"> | $Enums.SkuOwnerType
  ownerId?: Prisma.StringWithAggregatesFilter<"SkuRegistry"> | string
}

export type SkuRegistryCreateInput = {
  value: string
  ownerType: $Enums.SkuOwnerType
  ownerId: string
}

export type SkuRegistryUncheckedCreateInput = {
  value: string
  ownerType: $Enums.SkuOwnerType
  ownerId: string
}

export type SkuRegistryUpdateInput = {
  value?: Prisma.StringFieldUpdateOperationsInput | string
  ownerType?: Prisma.EnumSkuOwnerTypeFieldUpdateOperationsInput | $Enums.SkuOwnerType
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkuRegistryUncheckedUpdateInput = {
  value?: Prisma.StringFieldUpdateOperationsInput | string
  ownerType?: Prisma.EnumSkuOwnerTypeFieldUpdateOperationsInput | $Enums.SkuOwnerType
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkuRegistryCreateManyInput = {
  value: string
  ownerType: $Enums.SkuOwnerType
  ownerId: string
}

export type SkuRegistryUpdateManyMutationInput = {
  value?: Prisma.StringFieldUpdateOperationsInput | string
  ownerType?: Prisma.EnumSkuOwnerTypeFieldUpdateOperationsInput | $Enums.SkuOwnerType
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkuRegistryUncheckedUpdateManyInput = {
  value?: Prisma.StringFieldUpdateOperationsInput | string
  ownerType?: Prisma.EnumSkuOwnerTypeFieldUpdateOperationsInput | $Enums.SkuOwnerType
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkuRegistryCountOrderByAggregateInput = {
  value?: Prisma.SortOrder
  ownerType?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type SkuRegistryMaxOrderByAggregateInput = {
  value?: Prisma.SortOrder
  ownerType?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type SkuRegistryMinOrderByAggregateInput = {
  value?: Prisma.SortOrder
  ownerType?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type EnumSkuOwnerTypeFieldUpdateOperationsInput = {
  set?: $Enums.SkuOwnerType
}



export type SkuRegistrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  value?: boolean
  ownerType?: boolean
  ownerId?: boolean
}, ExtArgs["result"]["skuRegistry"]>

export type SkuRegistrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  value?: boolean
  ownerType?: boolean
  ownerId?: boolean
}, ExtArgs["result"]["skuRegistry"]>

export type SkuRegistrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  value?: boolean
  ownerType?: boolean
  ownerId?: boolean
}, ExtArgs["result"]["skuRegistry"]>

export type SkuRegistrySelectScalar = {
  value?: boolean
  ownerType?: boolean
  ownerId?: boolean
}

export type SkuRegistryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"value" | "ownerType" | "ownerId", ExtArgs["result"]["skuRegistry"]>

export type $SkuRegistryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SkuRegistry"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    value: string
    ownerType: $Enums.SkuOwnerType
    ownerId: string
  }, ExtArgs["result"]["skuRegistry"]>
  composites: {}
}

export type SkuRegistryGetPayload<S extends boolean | null | undefined | SkuRegistryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload, S>

export type SkuRegistryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SkuRegistryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SkuRegistryCountAggregateInputType | true
  }

export interface SkuRegistryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SkuRegistry'], meta: { name: 'SkuRegistry' } }
  /**
   * Find zero or one SkuRegistry that matches the filter.
   * @param {SkuRegistryFindUniqueArgs} args - Arguments to find a SkuRegistry
   * @example
   * // Get one SkuRegistry
   * const skuRegistry = await prisma.skuRegistry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SkuRegistryFindUniqueArgs>(args: Prisma.SelectSubset<T, SkuRegistryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SkuRegistryClient<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SkuRegistry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SkuRegistryFindUniqueOrThrowArgs} args - Arguments to find a SkuRegistry
   * @example
   * // Get one SkuRegistry
   * const skuRegistry = await prisma.skuRegistry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SkuRegistryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SkuRegistryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SkuRegistryClient<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SkuRegistry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkuRegistryFindFirstArgs} args - Arguments to find a SkuRegistry
   * @example
   * // Get one SkuRegistry
   * const skuRegistry = await prisma.skuRegistry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SkuRegistryFindFirstArgs>(args?: Prisma.SelectSubset<T, SkuRegistryFindFirstArgs<ExtArgs>>): Prisma.Prisma__SkuRegistryClient<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SkuRegistry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkuRegistryFindFirstOrThrowArgs} args - Arguments to find a SkuRegistry
   * @example
   * // Get one SkuRegistry
   * const skuRegistry = await prisma.skuRegistry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SkuRegistryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SkuRegistryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SkuRegistryClient<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SkuRegistries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkuRegistryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SkuRegistries
   * const skuRegistries = await prisma.skuRegistry.findMany()
   * 
   * // Get first 10 SkuRegistries
   * const skuRegistries = await prisma.skuRegistry.findMany({ take: 10 })
   * 
   * // Only select the `value`
   * const skuRegistryWithValueOnly = await prisma.skuRegistry.findMany({ select: { value: true } })
   * 
   */
  findMany<T extends SkuRegistryFindManyArgs>(args?: Prisma.SelectSubset<T, SkuRegistryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SkuRegistry.
   * @param {SkuRegistryCreateArgs} args - Arguments to create a SkuRegistry.
   * @example
   * // Create one SkuRegistry
   * const SkuRegistry = await prisma.skuRegistry.create({
   *   data: {
   *     // ... data to create a SkuRegistry
   *   }
   * })
   * 
   */
  create<T extends SkuRegistryCreateArgs>(args: Prisma.SelectSubset<T, SkuRegistryCreateArgs<ExtArgs>>): Prisma.Prisma__SkuRegistryClient<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SkuRegistries.
   * @param {SkuRegistryCreateManyArgs} args - Arguments to create many SkuRegistries.
   * @example
   * // Create many SkuRegistries
   * const skuRegistry = await prisma.skuRegistry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SkuRegistryCreateManyArgs>(args?: Prisma.SelectSubset<T, SkuRegistryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SkuRegistries and returns the data saved in the database.
   * @param {SkuRegistryCreateManyAndReturnArgs} args - Arguments to create many SkuRegistries.
   * @example
   * // Create many SkuRegistries
   * const skuRegistry = await prisma.skuRegistry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SkuRegistries and only return the `value`
   * const skuRegistryWithValueOnly = await prisma.skuRegistry.createManyAndReturn({
   *   select: { value: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SkuRegistryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SkuRegistryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SkuRegistry.
   * @param {SkuRegistryDeleteArgs} args - Arguments to delete one SkuRegistry.
   * @example
   * // Delete one SkuRegistry
   * const SkuRegistry = await prisma.skuRegistry.delete({
   *   where: {
   *     // ... filter to delete one SkuRegistry
   *   }
   * })
   * 
   */
  delete<T extends SkuRegistryDeleteArgs>(args: Prisma.SelectSubset<T, SkuRegistryDeleteArgs<ExtArgs>>): Prisma.Prisma__SkuRegistryClient<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SkuRegistry.
   * @param {SkuRegistryUpdateArgs} args - Arguments to update one SkuRegistry.
   * @example
   * // Update one SkuRegistry
   * const skuRegistry = await prisma.skuRegistry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SkuRegistryUpdateArgs>(args: Prisma.SelectSubset<T, SkuRegistryUpdateArgs<ExtArgs>>): Prisma.Prisma__SkuRegistryClient<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SkuRegistries.
   * @param {SkuRegistryDeleteManyArgs} args - Arguments to filter SkuRegistries to delete.
   * @example
   * // Delete a few SkuRegistries
   * const { count } = await prisma.skuRegistry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SkuRegistryDeleteManyArgs>(args?: Prisma.SelectSubset<T, SkuRegistryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SkuRegistries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkuRegistryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SkuRegistries
   * const skuRegistry = await prisma.skuRegistry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SkuRegistryUpdateManyArgs>(args: Prisma.SelectSubset<T, SkuRegistryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SkuRegistries and returns the data updated in the database.
   * @param {SkuRegistryUpdateManyAndReturnArgs} args - Arguments to update many SkuRegistries.
   * @example
   * // Update many SkuRegistries
   * const skuRegistry = await prisma.skuRegistry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SkuRegistries and only return the `value`
   * const skuRegistryWithValueOnly = await prisma.skuRegistry.updateManyAndReturn({
   *   select: { value: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SkuRegistryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SkuRegistryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SkuRegistry.
   * @param {SkuRegistryUpsertArgs} args - Arguments to update or create a SkuRegistry.
   * @example
   * // Update or create a SkuRegistry
   * const skuRegistry = await prisma.skuRegistry.upsert({
   *   create: {
   *     // ... data to create a SkuRegistry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SkuRegistry we want to update
   *   }
   * })
   */
  upsert<T extends SkuRegistryUpsertArgs>(args: Prisma.SelectSubset<T, SkuRegistryUpsertArgs<ExtArgs>>): Prisma.Prisma__SkuRegistryClient<runtime.Types.Result.GetResult<Prisma.$SkuRegistryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SkuRegistries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkuRegistryCountArgs} args - Arguments to filter SkuRegistries to count.
   * @example
   * // Count the number of SkuRegistries
   * const count = await prisma.skuRegistry.count({
   *   where: {
   *     // ... the filter for the SkuRegistries we want to count
   *   }
   * })
  **/
  count<T extends SkuRegistryCountArgs>(
    args?: Prisma.Subset<T, SkuRegistryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SkuRegistryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SkuRegistry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkuRegistryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SkuRegistryAggregateArgs>(args: Prisma.Subset<T, SkuRegistryAggregateArgs>): Prisma.PrismaPromise<GetSkuRegistryAggregateType<T>>

  /**
   * Group by SkuRegistry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkuRegistryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SkuRegistryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SkuRegistryGroupByArgs['orderBy'] }
      : { orderBy?: SkuRegistryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SkuRegistryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSkuRegistryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SkuRegistry model
 */
readonly fields: SkuRegistryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SkuRegistry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SkuRegistryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SkuRegistry model
 */
export interface SkuRegistryFieldRefs {
  readonly value: Prisma.FieldRef<"SkuRegistry", 'String'>
  readonly ownerType: Prisma.FieldRef<"SkuRegistry", 'SkuOwnerType'>
  readonly ownerId: Prisma.FieldRef<"SkuRegistry", 'String'>
}
    

// Custom InputTypes
/**
 * SkuRegistry findUnique
 */
export type SkuRegistryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * Filter, which SkuRegistry to fetch.
   */
  where: Prisma.SkuRegistryWhereUniqueInput
}

/**
 * SkuRegistry findUniqueOrThrow
 */
export type SkuRegistryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * Filter, which SkuRegistry to fetch.
   */
  where: Prisma.SkuRegistryWhereUniqueInput
}

/**
 * SkuRegistry findFirst
 */
export type SkuRegistryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * Filter, which SkuRegistry to fetch.
   */
  where?: Prisma.SkuRegistryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkuRegistries to fetch.
   */
  orderBy?: Prisma.SkuRegistryOrderByWithRelationInput | Prisma.SkuRegistryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SkuRegistries.
   */
  cursor?: Prisma.SkuRegistryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkuRegistries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkuRegistries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SkuRegistries.
   */
  distinct?: Prisma.SkuRegistryScalarFieldEnum | Prisma.SkuRegistryScalarFieldEnum[]
}

/**
 * SkuRegistry findFirstOrThrow
 */
export type SkuRegistryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * Filter, which SkuRegistry to fetch.
   */
  where?: Prisma.SkuRegistryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkuRegistries to fetch.
   */
  orderBy?: Prisma.SkuRegistryOrderByWithRelationInput | Prisma.SkuRegistryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SkuRegistries.
   */
  cursor?: Prisma.SkuRegistryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkuRegistries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkuRegistries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SkuRegistries.
   */
  distinct?: Prisma.SkuRegistryScalarFieldEnum | Prisma.SkuRegistryScalarFieldEnum[]
}

/**
 * SkuRegistry findMany
 */
export type SkuRegistryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * Filter, which SkuRegistries to fetch.
   */
  where?: Prisma.SkuRegistryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkuRegistries to fetch.
   */
  orderBy?: Prisma.SkuRegistryOrderByWithRelationInput | Prisma.SkuRegistryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SkuRegistries.
   */
  cursor?: Prisma.SkuRegistryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkuRegistries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkuRegistries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SkuRegistries.
   */
  distinct?: Prisma.SkuRegistryScalarFieldEnum | Prisma.SkuRegistryScalarFieldEnum[]
}

/**
 * SkuRegistry create
 */
export type SkuRegistryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * The data needed to create a SkuRegistry.
   */
  data: Prisma.XOR<Prisma.SkuRegistryCreateInput, Prisma.SkuRegistryUncheckedCreateInput>
}

/**
 * SkuRegistry createMany
 */
export type SkuRegistryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SkuRegistries.
   */
  data: Prisma.SkuRegistryCreateManyInput | Prisma.SkuRegistryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SkuRegistry createManyAndReturn
 */
export type SkuRegistryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * The data used to create many SkuRegistries.
   */
  data: Prisma.SkuRegistryCreateManyInput | Prisma.SkuRegistryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SkuRegistry update
 */
export type SkuRegistryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * The data needed to update a SkuRegistry.
   */
  data: Prisma.XOR<Prisma.SkuRegistryUpdateInput, Prisma.SkuRegistryUncheckedUpdateInput>
  /**
   * Choose, which SkuRegistry to update.
   */
  where: Prisma.SkuRegistryWhereUniqueInput
}

/**
 * SkuRegistry updateMany
 */
export type SkuRegistryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SkuRegistries.
   */
  data: Prisma.XOR<Prisma.SkuRegistryUpdateManyMutationInput, Prisma.SkuRegistryUncheckedUpdateManyInput>
  /**
   * Filter which SkuRegistries to update
   */
  where?: Prisma.SkuRegistryWhereInput
  /**
   * Limit how many SkuRegistries to update.
   */
  limit?: number
}

/**
 * SkuRegistry updateManyAndReturn
 */
export type SkuRegistryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * The data used to update SkuRegistries.
   */
  data: Prisma.XOR<Prisma.SkuRegistryUpdateManyMutationInput, Prisma.SkuRegistryUncheckedUpdateManyInput>
  /**
   * Filter which SkuRegistries to update
   */
  where?: Prisma.SkuRegistryWhereInput
  /**
   * Limit how many SkuRegistries to update.
   */
  limit?: number
}

/**
 * SkuRegistry upsert
 */
export type SkuRegistryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * The filter to search for the SkuRegistry to update in case it exists.
   */
  where: Prisma.SkuRegistryWhereUniqueInput
  /**
   * In case the SkuRegistry found by the `where` argument doesn't exist, create a new SkuRegistry with this data.
   */
  create: Prisma.XOR<Prisma.SkuRegistryCreateInput, Prisma.SkuRegistryUncheckedCreateInput>
  /**
   * In case the SkuRegistry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SkuRegistryUpdateInput, Prisma.SkuRegistryUncheckedUpdateInput>
}

/**
 * SkuRegistry delete
 */
export type SkuRegistryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
  /**
   * Filter which SkuRegistry to delete.
   */
  where: Prisma.SkuRegistryWhereUniqueInput
}

/**
 * SkuRegistry deleteMany
 */
export type SkuRegistryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SkuRegistries to delete
   */
  where?: Prisma.SkuRegistryWhereInput
  /**
   * Limit how many SkuRegistries to delete.
   */
  limit?: number
}

/**
 * SkuRegistry without action
 */
export type SkuRegistryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkuRegistry
   */
  select?: Prisma.SkuRegistrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkuRegistry
   */
  omit?: Prisma.SkuRegistryOmit<ExtArgs> | null
}
