// Données de seed du catalogue La Folie Coffee — PORTÉES depuis le POC frontend
// (lfc-PIM-frontend/src/app/data/{db,products}.seed.ts) au moment de la bascule
// LocalDb → Prisma. Le backend devient la source de vérité ; ce fichier en est
// le point de départ reproductible. Format compact `Row` = ce que portait le CSV.
//
// ⚠️ Slice 1 : seules catégories + produits étaient modélisés côté backend. Les
// régimes de TVA sont arrivés depuis (contexte commerce) et vivent plus bas ;
// les presets de canaux attendent toujours le contexte locations.

export interface SeedCategory {
  readonly id: string;
  readonly nameFr: string;
  readonly slug: string;
  readonly position: number;
}

export const SEED_CATEGORIES: readonly SeedCategory[] = [
  { id: "cat_vien", nameFr: "Viennoiseries", slug: "viennoiseries", position: 1 },
  { id: "cat_pains", nameFr: "Pains", slug: "pains", position: 2 },
  { id: "cat_patis", nameFr: "Pâtisseries", slug: "patisseries", position: 3 },
  { id: "cat_sale", nameFr: "Salé & traiteur", slug: "sale-traiteur", position: 4 },
  { id: "cat_choco", nameFr: "Chocolat & confiserie", slug: "chocolat-confiserie", position: 5 },
];

/** Un régime de TVA de départ : un nom et un taux, rien d'autre. */
export interface SeedTvaRegime {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly percent: number;
}

/**
 * Les trois taux français de la restauration et de l'alimentaire.
 *
 * 5,5 % est le taux de l'alimentaire à emporter ; 10 % celui de la consommation
 * sur place ; 20 % le taux normal, qui rattrape ce qui n'est pas alimentaire
 * (confiserie de luxe, boissons alcoolisées, marchandise revendue).
 *
 * Ils sont posés **sans être rattachés** à une famille : décider quelle gamme
 * relève de quel taux est une décision comptable, pas une donnée de départ. Le
 * seed installe le référentiel, il ne remplit pas la déclaration.
 */
export const SEED_TVA_REGIMES: readonly SeedTvaRegime[] = [
  {
    id: "tva_reduit",
    name: "Réduit",
    description: "Alimentaire à emporter.",
    percent: 5.5,
  },
  {
    id: "tva_intermediaire",
    name: "Intermédiaire",
    description: "Consommation sur place.",
    percent: 10,
  },
  {
    id: "tva_normal",
    name: "Normal",
    description: "Taux plein — non alimentaire, alcools, revente.",
    percent: 20,
  },
];

export type Row = readonly [
  sku: string,
  name: string,
  slug: string,
  priceEur: number,
  weightGrams: number | null,
  categoryId: string,
  descriptionFr: string,
  flags: string,
];

export const ROWS: readonly Row[] = [
  // Viennoiseries
  [
    "VIE-001",
    "Croissant",
    "croissant",
    2.0,
    null,
    "cat_vien",
    "Le pur beurre, le vrai : un tourage patient et un feuilletage qui craque à la première bouchée.",
    "",
  ],
  [
    "VIE-002",
    "Pain au chocolat",
    "pain-au-chocolat",
    2.2,
    null,
    "cat_vien",
    "Feuilletage généreux et deux barres de chocolat qui ne font pas semblant.",
    "",
  ],
  ["VIE-003", "Patte d'ours", "patte-d-ours", 3.0, null, "cat_vien", "", "a-decrire"],
  [
    "VIE-004",
    "Pain aux raisins",
    "pain-aux-raisins",
    2.5,
    null,
    "cat_vien",
    "Spirale de crème pâtissière et raisins moelleux, roulée à la main.",
    "",
  ],
  [
    "VIE-005",
    "Chausson aux pommes",
    "chausson-aux-pommes",
    3.0,
    null,
    "cat_vien",
    "Feuilletage doré et pommes fondantes, comme à la sortie du four.",
    "",
  ],
  [
    "VIE-006",
    "Brioche pralinée individuelle",
    "brioche-pralinee-individuelle",
    2.5,
    null,
    "cat_vien",
    "Brioche moelleuse et pralines roses, la gourmandise version alpine.",
    "",
  ],
  [
    "VIE-007",
    "Brioche pépites de chocolat",
    "brioche-pepites-de-chocolat",
    2.7,
    null,
    "cat_vien",
    "Mie filante et pépites de chocolat généreusement reparties.",
    "",
  ],
  [
    "VIE-008",
    "Brioche au sucre",
    "brioche-au-sucre",
    2.3,
    null,
    "cat_vien",
    "La brioche simple et bien faite, croustillante de sucre sur le dessus.",
    "",
  ],
  [
    "VIE-009",
    "Pain au lait",
    "pain-au-lait",
    2.0,
    null,
    "cat_vien",
    "Mie douce et moelleuse, le classique du goûter.",
    "",
  ],
  [
    "VIE-010",
    "Brioche a tete",
    "brioche-a-tete",
    2.5,
    null,
    "cat_vien",
    "La brioche parisienne traditionnelle, façonnée a la main.",
    "",
  ],
  [
    "VIE-011",
    "Grosse brioche 350 g",
    "grosse-brioche-350-g",
    10.0,
    350,
    "cat_vien",
    "Grande brioche à partager, mie filante et croûte dorée.",
    "",
  ],
  ["VIE-012", "Abricotin", "abricotin", 2.5, null, "cat_vien", "", "a-decrire"],
  [
    "VIE-013",
    "Pain chocolat-banane",
    "pain-chocolat-banane",
    2.5,
    null,
    "cat_vien",
    "Feuilletage garni de chocolat et de banane, une association qui claque.",
    "",
  ],
  [
    "VIE-014",
    "Pain de mie brioché 500 g cuit",
    "pain-de-mie-brioche-500-g-cuit",
    6.5,
    500,
    "cat_vien",
    "Pain de mie brioche, mie filante, idéal pour le petit-déjeuner et le goûter.",
    "",
  ],
  ["VIE-015", "Croix de Savoie", "croix-de-savoie", 3.0, null, "cat_vien", "", "a-decrire"],
  [
    "VIE-016",
    "Sablé suisse",
    "sable-suisse",
    3.8,
    null,
    "cat_vien",
    "Pâte sablée, crème pâtissière et pepites de chocolat.",
    "",
  ],
  [
    "VIE-017",
    "Croissant aux amandes",
    "croissant-aux-amandes",
    3.0,
    null,
    "cat_vien",
    "Croissant garni de crème d'amandes et repassé au four, amandes effilees dessus.",
    "",
  ],
  [
    "VIE-018",
    "Pain au chocolat aux amandes",
    "pain-au-chocolat-aux-amandes",
    3.0,
    null,
    "cat_vien",
    "Pain au chocolat garni de crème d'amandes, gratiné aux amandes effilees.",
    "",
  ],
  [
    "VIE-019",
    "Gros cookie",
    "gros-cookie",
    4.0,
    null,
    "cat_vien",
    "Cookie généreux, cœur moelleux et bords croustillants.",
    "",
  ],

  // Pains
  [
    "PAI-001",
    "Baguette tradition",
    "baguette-tradition",
    2.0,
    null,
    "cat_pains",
    "Farine française, levain nourri chaque jour, croûte qui chante a la sortie du four.",
    "",
  ],
  [
    "PAI-002",
    "Baguette artisane 200 g",
    "baguette-artisane-200-g",
    1.8,
    200,
    "cat_pains",
    "Baguette de fabrication artisanale, mie alvéolée et croûte fine.",
    "",
  ],
  [
    "PAI-003",
    "Baguette village plateau 200 g",
    "baguette-village-plateau-200-g",
    2.0,
    200,
    "cat_pains",
    "Baguette de plateau, format pratique pour la table.",
    "",
  ],
  [
    "PAI-004",
    "Pain Viking 300 g",
    "pain-viking-300-g",
    4.0,
    300,
    "cat_pains",
    "Pain aux céréales, dense et rustique, parfait avec les fromages.",
    "",
  ],
  [
    "PAI-005",
    "Petit pain Beaufort",
    "petit-pain-beaufort",
    2.1,
    null,
    "cat_pains",
    "Petit pain au Beaufort, un classique savoyard.",
    "",
  ],
  [
    "PAI-006",
    "Pain moisson 300 g",
    "pain-moisson-300-g",
    4.0,
    300,
    "cat_pains",
    "Pain aux graines, mie souple et gout de céréales grillees.",
    "",
  ],
  [
    "PAI-007",
    "Flûte village 450 g",
    "flute-village-450-g",
    2.5,
    450,
    "cat_pains",
    "Flûte de village, croûte dorée et mie moelleuse.",
    "",
  ],
  [
    "PAI-008",
    "Pain de campagne 300 g",
    "pain-de-campagne-300-g",
    4.0,
    300,
    "cat_pains",
    "Pain de campagne au levain, il tient toute la journée.",
    "",
  ],
  [
    "PAI-009",
    "Baguette campagrain 200 g",
    "baguette-campagrain-200-g",
    2.5,
    200,
    "cat_pains",
    "Baguette de campagne aux graines.",
    "",
  ],
  [
    "PAI-010",
    "Ficelle artisane 140 g",
    "ficelle-artisane-140-g",
    1.75,
    140,
    "cat_pains",
    "Petit format, beaucoup de croûte.",
    "",
  ],
  [
    "PAI-011",
    "Flûte artisane 420 g",
    "flute-artisane-420-g",
    3.5,
    420,
    "cat_pains",
    "Flûte artisanale, mie alvéolée.",
    "",
  ],
  [
    "PAI-012",
    "Flûte tradition 450 g",
    "flute-tradition-450-g",
    3.5,
    450,
    "cat_pains",
    "Flûte de tradition francaise, fermentation lente.",
    "",
  ],
  [
    "PAI-013",
    "Pain complet 300 g",
    "pain-complet-300-g",
    4.0,
    300,
    "cat_pains",
    "Pain complet à la farine française, riche en fibres.",
    "",
  ],
  [
    "PAI-014",
    "Pain de seigle 300 g",
    "pain-de-seigle-300-g",
    4.0,
    300,
    "cat_pains",
    "Pain de seigle dense, idéal avec les huîtres et les fromages.",
    "",
  ],
  [
    "PAI-015",
    "Pain sportif au kg",
    "pain-sportif-au-kg",
    16.0,
    1000,
    "cat_pains",
    "Pain aux graines et fruits secs, vendu au kilo.",
    "",
  ],
  [
    "PAI-016",
    "Campaillou au kg",
    "campaillou-au-kg",
    10.0,
    1000,
    "cat_pains",
    "Pain de campagne rustique, vendu au kilo.",
    "",
  ],
  [
    "PAI-017",
    "Pavé aux noix 300 g",
    "pave-aux-noix-300-g",
    5.0,
    300,
    "cat_pains",
    "Pavé garni de noix, le compagnon du plateau de fromages.",
    "",
  ],
  [
    "PAI-018",
    "Pain de mie carré frais 340 g",
    "pain-de-mie-carre-frais-340-g",
    5.5,
    340,
    "cat_pains",
    "Pain de mie frais en carré, mie régulière et moelleuse.",
    "",
  ],

  // Pâtisseries
  [
    "PAT-001",
    "Tartelette myrtilles",
    "tartelette-myrtilles",
    6.0,
    null,
    "cat_patis",
    "Myrtilles sauvages de nos alpages sur une pâte sablée.",
    "titre-a-verifier",
  ],
  [
    "PAT-002",
    "Flan nature (part)",
    "flan-nature-part",
    4.0,
    null,
    "cat_patis",
    "Le flan pâtissier à l'ancienne, vanille et texture fondante.",
    "prix-a-verifier",
  ],
  [
    "PAT-003",
    "Tartelette framboises",
    "tartelette-framboises",
    6.0,
    null,
    "cat_patis",
    "Framboises fraîches et crème pâtissière sur pâte sablée.",
    "",
  ],
  [
    "PAT-004",
    "Délice des neiges",
    "delice-des-neiges",
    4.0,
    null,
    "cat_patis",
    "",
    "a-decrire prix-a-verifier",
  ],
  [
    "PAT-005",
    "Éclair chocolat",
    "eclair-chocolat",
    6.0,
    null,
    "cat_patis",
    "Pâte à choux, crème pâtissière au chocolat et glacage brillant.",
    "",
  ],
  [
    "PAT-006",
    "Tartelette citron",
    "tartelette-citron",
    6.0,
    null,
    "cat_patis",
    "Creme au citron acidulée sur une pâte sablée croustillante.",
    "",
  ],
  [
    "PAT-007",
    "Éclair café",
    "eclair-cafe",
    6.0,
    null,
    "cat_patis",
    "Pâte à choux et crème au café, le classique intemporel.",
    "",
  ],
  [
    "PAT-008",
    "Éclair vanille",
    "eclair-vanille",
    6.0,
    null,
    "cat_patis",
    "Pâte à choux garnie de crème à la vanille.",
    "",
  ],
  [
    "PAT-009",
    "Tarte citron meringuée (part)",
    "tarte-citron-meringuee-part",
    6.0,
    null,
    "cat_patis",
    "Citron acidulé et meringue dorée au chalumeau.",
    "",
  ],
  [
    "PAT-010",
    "Crumble framboise",
    "crumble-framboise",
    7.5,
    null,
    "cat_patis",
    "Framboises et pâte à crumble beurrée, servi en part.",
    "",
  ],
  ["PAT-011", "Rose des sables", "rose-des-sables", 4.0, null, "cat_patis", "", "a-decrire"],
  ["PAT-012", "Pyramide", "pyramide", 5.0, null, "cat_patis", "", "a-decrire"],
  [
    "PAT-013",
    "Tartelette noix caramel",
    "tartelette-noix-caramel",
    6.0,
    null,
    "cat_patis",
    "Caramel tendre et noix torréfiées sur pâte sablée.",
    "",
  ],
  [
    "PAT-014",
    "Mousse chocolat",
    "mousse-chocolat",
    6.0,
    null,
    "cat_patis",
    "Mousse au chocolat aérienne, servie en part individuelle.",
    "",
  ],
  [
    "PAT-015",
    "Tarte myrtille T1 (4 personnes)",
    "tarte-myrtille-t1-4-personnes",
    30.0,
    null,
    "cat_patis",
    "La tarte aux myrtilles sauvages en format à partager, 4 personnes.",
    "",
  ],
  [
    "PAT-016",
    "Mont-Blanc individuel",
    "mont-blanc-individuel",
    7.0,
    null,
    "cat_patis",
    "Vermicelles de crème de marron, meringue et chantilly.",
    "",
  ],
  [
    "PAT-017",
    "Tarte poire fermière (part)",
    "tarte-poire-fermiere-part",
    5.0,
    null,
    "cat_patis",
    "Poires fondantes sur une base d'amandes.",
    "",
  ],
  [
    "PAT-018",
    "Tarte abricot fermière (part)",
    "tarte-abricot-fermiere-part",
    5.0,
    null,
    "cat_patis",
    "Abricots et pâte sablée, la tarte de saison à l'ancienne.",
    "",
  ],

  // Salé & traiteur
  [
    "SAL-001",
    "Sandwich jambon blanc Beaufort",
    "sandwich-jambon-blanc-beaufort",
    7.0,
    null,
    "cat_sale",
    "Jambon blanc et Beaufort sur pain maison.",
    "",
  ],
  [
    "SAL-002",
    "Tourte au Beaufort (part)",
    "tourte-au-beaufort-part",
    6.5,
    null,
    "cat_sale",
    "Tourte généreuse au Beaufort, servie en part.",
    "",
  ],
  [
    "SAL-003",
    "Quiche lorraine (part)",
    "quiche-lorraine-part",
    5.5,
    null,
    "cat_sale",
    "Quiche lorraine a l'appareil crème et lardons, part individuelle.",
    "",
  ],
  [
    "SAL-004",
    "Pan bagnat thon",
    "pan-bagnat-thon",
    7.0,
    null,
    "cat_sale",
    "Le pan bagnat garni au thon, version montagne.",
    "",
  ],
  [
    "SAL-005",
    "Pizza (part)",
    "pizza-part",
    5.5,
    null,
    "cat_sale",
    "Part de pizza maison, pâte levée sur place.",
    "",
  ],
  [
    "SAL-006",
    "Club poulet",
    "club-poulet",
    7.0,
    null,
    "cat_sale",
    "Club sandwich au poulet, en trois étages.",
    "",
  ],
  [
    "SAL-007",
    "Sandwich poulet graines",
    "sandwich-poulet-graines",
    7.0,
    null,
    "cat_sale",
    "Poulet et pain aux graines, croquant et rassasiant.",
    "",
  ],
  [
    "SAL-008",
    "Sandwich jambon cru tomme",
    "sandwich-jambon-cru-tomme",
    7.0,
    null,
    "cat_sale",
    "Jambon cru et tomme de Savoie sur pain maison.",
    "",
  ],
  ["SAL-009", "Sandwich persillé", "sandwich-persille", 7.0, null, "cat_sale", "", "a-decrire"],
  [
    "SAL-010",
    "Sandwich jambon beurre cornichons",
    "sandwich-jambon-beurre-cornichons",
    6.5,
    null,
    "cat_sale",
    "Le jambon-beurre, avec les cornichons qui vont avec.",
    "prix-a-verifier",
  ],
  [
    "SAL-011",
    "Quiche poireaux chèvre (part)",
    "quiche-poireaux-chevre-part",
    6.0,
    null,
    "cat_sale",
    "Poireaux fondants et chèvre, part individuelle.",
    "",
  ],
  [
    "SAL-012",
    "Salade César (barquette)",
    "salade-cesar-barquette",
    10.0,
    null,
    "cat_sale",
    "Salade Cesar en barquette, prête à emporter.",
    "",
  ],
  [
    "SAL-013",
    "Tranche tomate mozzarella",
    "tranche-tomate-mozzarella",
    7.0,
    null,
    "cat_sale",
    "Tranche garnie tomate et mozzarella.",
    "",
  ],
  [
    "SAL-014",
    "Quiche saumon épinards (part)",
    "quiche-saumon-epinards-part",
    7.0,
    null,
    "cat_sale",
    "Saumon et épinards dans un appareil crèmeux.",
    "",
  ],
  [
    "SAL-015",
    "Salade de lentilles (barquette)",
    "salade-de-lentilles-barquette",
    8.5,
    null,
    "cat_sale",
    "Lentilles vertes en barquette, assaisonnées maison.",
    "",
  ],
  [
    "SAL-016",
    "Tranche miel chèvre",
    "tranche-miel-chevre",
    6.5,
    null,
    "cat_sale",
    "Tranche garnie chèvre et miel.",
    "prix-a-verifier",
  ],
  [
    "SAL-017",
    "Quiche légumes (part)",
    "quiche-legumes-part",
    5.5,
    null,
    "cat_sale",
    "Quiche aux légumes de saison, part individuelle.",
    "",
  ],
  [
    "SAL-018",
    "Sandwich rosette",
    "sandwich-rosette",
    7.0,
    null,
    "cat_sale",
    "Rosette et beurre sur pain maison.",
    "",
  ],
  [
    "SAL-019",
    "Fougasse provençale",
    "fougasse-provencale",
    6.5,
    null,
    "cat_sale",
    "Fougasse aux saveurs du Sud.",
    "prix-a-verifier",
  ],
  [
    "SAL-020",
    "Croque courgette",
    "croque-courgette",
    6.5,
    null,
    "cat_sale",
    "Croque végétarien à la courgette.",
    "prix-a-verifier",
  ],
  [
    "SAL-021",
    "Croque monsieur rustique",
    "croque-monsieur-rustique",
    6.5,
    null,
    "cat_sale",
    "Croque-monsieur sur pain de campagne, jambon et fromage.",
    "prix-a-verifier",
  ],
  [
    "SAL-022",
    "Tranche légumes",
    "tranche-legumes",
    6.5,
    null,
    "cat_sale",
    "Tranche garnie de légumes de saison.",
    "prix-a-verifier",
  ],
  [
    "SAL-023",
    "Sandwich maraîcher",
    "sandwich-maraicher",
    7.0,
    null,
    "cat_sale",
    "Sandwich végétarien aux légumes croquants.",
    "",
  ],
  [
    "SAL-024",
    "Tartiflette (part)",
    "tartiflette-part",
    7.0,
    null,
    "cat_sale",
    "La tartiflette en part individuelle, pommes de terre et reblochon.",
    "titre-a-verifier",
  ],

  // Chocolat & confiserie
  [
    "CHO-001",
    "Gros florentin lait",
    "gros-florentin-lait",
    6.0,
    null,
    "cat_choco",
    "Amandes caramélisées et chocolat au lait, format généreux.",
    "",
  ],
  [
    "CHO-002",
    "Gros florentin noir",
    "gros-florentin-noir",
    6.0,
    null,
    "cat_choco",
    "Amandes caramélisées et chocolat noir, format généreux.",
    "",
  ],
  [
    "CHO-003",
    "Tablette chocolat maison lait 100 g",
    "tablette-chocolat-maison-lait-100-g",
    10.0,
    100,
    "cat_choco",
    "Tablette de chocolat au lait tempéré à l'atelier.",
    "",
  ],
  [
    "CHO-004",
    "Sablé Gianduja pièce 300 g",
    "sable-gianduja-piece-300-g",
    6.5,
    300,
    "cat_choco",
    "Sablé et gianduja, le duo noisette-chocolat.",
    "tva-a-valider",
  ],
  [
    "CHO-005",
    "Magalinettes sachet 150 g",
    "magalinettes-sachet-150-g",
    13.0,
    150,
    "cat_choco",
    "",
    "a-decrire tva-a-valider",
  ],
  [
    "CHO-006",
    "Sablés Gianduja 200 g",
    "sables-gianduja-200-g",
    17.0,
    200,
    "cat_choco",
    "Assortiment de sablés au gianduja.",
    "tva-a-valider",
  ],
  [
    "CHO-007",
    "Boîte de florentins 220 g",
    "boite-de-florentins-220-g",
    28.0,
    220,
    "cat_choco",
    "Florentins en boîte, à offrir ou à garder.",
    "",
  ],
  [
    "CHO-008",
    "Grignottines boîte 150 g",
    "grignottines-boite-150-g",
    17.0,
    150,
    "cat_choco",
    "",
    "a-decrire tva-a-valider",
  ],
  [
    "CHO-009",
    "Œufs praliné 150 g",
    "ufs-praline-150-g",
    15.0,
    150,
    "cat_choco",
    "Œufs en chocolat fourrés praliné.",
    "",
  ],
  [
    "CHO-010",
    "Meringuettes noisette 100 g",
    "meringuettes-noisette-100-g",
    10.0,
    100,
    "cat_choco",
    "Petites meringues à la noisette, croquantes et légères.",
    "tva-a-valider",
  ],
  [
    "CHO-011",
    "Oups 250 g - chocolat des montagnes",
    "oups-250-g-chocolat-des-montagnes",
    30.0,
    250,
    "cat_choco",
    "",
    "a-decrire",
  ],
  [
    "CHO-012",
    "Boîte de 6 pattes d'ourson",
    "boite-de-6-pattes-d-ourson",
    16.0,
    null,
    "cat_choco",
    "Guimauve maison enrobée de chocolat, la spécialité de la maison.",
    "",
  ],
  [
    "CHO-013",
    "Mendiants boîte 200 g",
    "mendiants-boite-200-g",
    16.0,
    200,
    "cat_choco",
    "Mendiants au chocolat et fruits secs.",
    "tva-a-valider",
  ],
];
