
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model SkuRegistry
 * Registre des références — garantit l'unicité du SKU dans un espace de noms
 * GLOBAL (produits et déclinaisons confondus, doc 06 invariant 1).
 * Une contrainte d'unicité ne pouvant pas s'étendre à deux tables, c'est ce
 * registre qui porte la garantie : la violation de sa clé primaire est le
 * `23505` traduit en `SkuAlreadyUsedError` par l'adaptateur de dépôt.
 */
export type SkuRegistry = Prisma.SkuRegistryModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model TvaRegime
 * Régime de TVA — référence commerciale partagée (catégories + collection Shopify).
 */
export type TvaRegime = Prisma.TvaRegimeModel
/**
 * Model Emplacement
 * Un **emplacement** (boutique / point de vente) et ses modes. S'il fait « sur
 * place », il ouvre une grille de tables click & collect (une URL + un QR par
 * table). Contexte `locations` — aucune dépendance au catalogue.
 */
export type Emplacement = Prisma.EmplacementModel
/**
 * Model EmplacementTable
 * Une **table** d'un emplacement sur place. Le `number` est verrouillé (identité
 * de l'URL) : clé primaire composite `(emplacement, number)`. Suppression en
 * cascade avec l'emplacement.
 */
export type EmplacementTable = Prisma.EmplacementTableModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductVariant
 * 
 */
export type ProductVariant = Prisma.ProductVariantModel
/**
 * Model ShopifySettings
 * Réglages de l'intégration — ligne unique.
 * ⚠️ Aucun secret ici : le jeton d'API vit dans l'environnement (`AppConfig`).
 */
export type ShopifySettings = Prisma.ShopifySettingsModel
/**
 * Model ShopifyProductBinding
 * État de synchro d'un **produit** — Shopify pousse un produit et ses variantes
 * ensemble, donc l'empreinte et le statut vivent à ce niveau. Les *références*,
 * elles, restent sur la déclinaison (R4) : ce sont deux choses différentes.
 */
export type ShopifyProductBinding = Prisma.ShopifyProductBindingModel
/**
 * Model ShopifyPushSnapshot
 * Historique **append-only** des poussées réelles d'un `handle` — l'ancêtre commun
 * (BASE) de la réconciliation à trois voies et la matière du rollback. Voir
 * [`publication-reconciliation-3way.md`](../../../documentation/lfc/publication-reconciliation-3way.md).
 * 
 * Contrairement aux bindings (états de synchro re-dérivables), ceci est un **journal** :
 * le perdre efface l'historique et le retour arrière. Jamais muté après écriture — un
 * rollback ré-écrit une **nouvelle** ligne (une copie d'une version antérieure).
 */
export type ShopifyPushSnapshot = Prisma.ShopifyPushSnapshotModel
/**
 * Model ShopifyVariantBinding
 * Ce que Shopify sait d'une **déclinaison** — l'unité réellement vendue (R4).
 */
export type ShopifyVariantBinding = Prisma.ShopifyVariantBindingModel
/**
 * Model NutritionDeclaration
 * Fiche réglementaire d'une **déclinaison** — c'est elle qui est mise sur le
 * marché (doc 03). `variant_id` est PK **et** FK (*shared primary key*) : pas
 * d'identifiant de substitution, donc deux fiches sont structurellement
 * impossibles pour une même déclinaison.
 */
export type NutritionDeclaration = Prisma.NutritionDeclarationModel
/**
 * Model ProductEditorial
 * 
 */
export type ProductEditorial = Prisma.ProductEditorialModel
/**
 * Model MediaAsset
 * Agrégat propre : un visuel a son cycle de vie (upload, CDN) et peut servir
 * plusieurs produits. On stocke le **master** + un point focal ; les tailles
 * dérivées sont calculées par chaque canal, jamais ressaisies.
 */
export type MediaAsset = Prisma.MediaAssetModel
/**
 * Model ProductMedia
 * Table de liaison dédiée — **pas** de FK polymorphe (`owner_type`/`owner_id`),
 * qui priverait Postgres de toute intégrité référentielle (doc 01).
 */
export type ProductMedia = Prisma.ProductMediaModel
/**
 * Model B2bChannelBinding
 * L'**appartenance d'un produit au canal B2B** : sa présence dit « vendu aux
 * pros », son absence dit le contraire. Un état de publication (`published`)
 * ne suffirait pas — il confondrait « publié chez Shopify » et « vendu aux
 * pros », et les deux catalogues ne pourraient jamais diverger.
 * 
 * Dépublier **supprime la ligne**. Le produit disparaîtra du prochain snapshot,
 * et le récepteur le nommera dans son rapport (`removedSkus`) : la nouvelle est
 * portée par le push, pas par un drapeau qu'il faudrait penser à relire.
 */
export type B2bChannelBinding = Prisma.B2bChannelBindingModel
