
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ProductKind = {
  daily: 'daily',
  made_to_order: 'made_to_order',
  resale: 'resale'
} as const

export type ProductKind = (typeof ProductKind)[keyof typeof ProductKind]


export const ProductStatus = {
  draft: 'draft',
  published: 'published',
  archived: 'archived'
} as const

export type ProductStatus = (typeof ProductStatus)[keyof typeof ProductStatus]


export const SkuOwnerType = {
  product: 'product',
  variant: 'variant'
} as const

export type SkuOwnerType = (typeof SkuOwnerType)[keyof typeof SkuOwnerType]


export const ShopifySyncStatus = {
  never_pushed: 'never_pushed',
  up_to_date: 'up_to_date',
  drifted: 'drifted',
  failed: 'failed'
} as const

export type ShopifySyncStatus = (typeof ShopifySyncStatus)[keyof typeof ShopifySyncStatus]


export const ShopifyChannelMode = {
  live: 'live',
  dry_run: 'dry_run'
} as const

export type ShopifyChannelMode = (typeof ShopifyChannelMode)[keyof typeof ShopifyChannelMode]


export const ShopifyPushOutcome = {
  pushed: 'pushed',
  failed: 'failed'
} as const

export type ShopifyPushOutcome = (typeof ShopifyPushOutcome)[keyof typeof ShopifyPushOutcome]


export const MediaRole = {
  hero: 'hero',
  gallery: 'gallery',
  lifestyle: 'lifestyle',
  thumbnail: 'thumbnail',
  print: 'print'
} as const

export type MediaRole = (typeof MediaRole)[keyof typeof MediaRole]
