import type { ClientCopy } from './client-copy.model';
import { ACCOUNT_EN } from './screens/account.en';
import { INVOICES_EN } from './screens/invoices.copy';
import { ORDERS_EN } from './screens/orders.copy';

/**
 * Anglais. Val d'Isère reçoit autant de britanniques que d'italiens ; laisser
 * `EN` cliquable et muet aurait été pire que de ne pas l'offrir.
 *
 * « Fournil » devient *bakery* (le lieu), « coursier » *courier* — pas *driver*,
 * qui laisserait croire à une plateforme de livraison.
 */
export const EN: ClientCopy = {
  chrome: {
    identityConflict: 'An account already uses this Google address. Sign in with your usual email.',
    identityConflictDismiss: 'Got it',
    back: 'Back',
    menu: 'Menu',
    notifications: 'Notifications',
    lang: 'Language',
    signIn: 'Sign in',
    createAccount: 'Create my account',
    kickerWelcome: 'Welcome',
    kickerRappel: 'Call back',
    kickerCommande: 'New order',
    kickerShop: 'Shop',
    kickerCart: 'The basket',
    kickerPay: 'Payment',
    kickerQr: 'Collection',
    kickerDone: 'Confirmed',
    deskKicker: 'Val d’Isère · order online',
    brandLine: 'Bakery · Val d’Isère',
    featureAccessFailed:
      'We couldn’t check what the shop offers right now, so some pages stay closed. Reload the page to try again.',
    accountMenu: 'My personal account',
    myProfile: 'My profile',
    workspaceChoice: 'Workspace',
    workspacePersonal: 'Personal',
    workspaceCurrentPersonal: 'Personal account',
    workspaceCurrentFor: 'Working for',
    workspaceSection: 'My workspaces',
    workspaceKindPro: 'Pro',
    workspaceKindPersonal: 'Personal',
    workspacePersonalNote: 'Orders in your own name',
    workspaceRolePro: 'Pro account',
    notificationsClose: 'Close',
    notificationsCount: '{unread} unread · {total} in total',
    notificationsMarkAll: 'Mark all as read',
    notificationsEmpty: 'Nothing to report.',
    cartOpen: 'View my basket',
  },

  nav: {
    destinations: {
      shop: 'Shop',
      orders: 'Orders',
      invoices: 'Invoices',
      baskets: 'Recurring baskets',
      account: 'My account',
    },
    invoicesDue: '{n} to settle',
    basketsCount: '{n} templates',
    cart: 'My basket',
    soon: 'Soon',
    close: 'Close the menu',
    newOrder: 'New order',
    newOrderSub: 'Pickup or courier, you choose',
    house: 'The bakery',
    houseLinks: [
      ['Our counters and our methods', '6 notes'],
      ['Le Labo — hours and access', 'Open'],
      ['Something urgent to add?', 'Call us'],
    ],
    logout: 'Sign out',
    address: 'Le Labo · route de la Balme, Val d’Isère — 7 am – 7 pm',
    hello: 'Hello {name}.',
    helloAnonymous: 'Hello.',
  },
  hero: {
    welcomeTitle: 'Your resort order, ready in two minutes.',
    welcomeIntro: 'You choose, we prepare.',
    rappelTitle: 'When shall we call ?',
    rappelIntro: 'We call from the bakery, never from a call centre.',
  },
  aside: {
    proof: [
      'Quick sign-up.',
      'Your account grows with what you need.',
      'Trade prices, resort delivery, monthly invoicing on request.',
    ],
    address: 'Le Labo · Route de la Balme — open 7am to 7pm.',
  },
  signup: {
    facebook: 'Continue with Facebook',
    orEmail: 'or by e-mail',
    google: 'Continue with Google',
    eyebrow: 'First time ? 3 details and you’re in',
    alreadyLead: 'Already a customer ?',
    alreadyLink: 'Sign in',
    pitch: 'A first name, an email, a number. That’s all — the rest can wait until you need it.',
    firstName: 'First name',
    firstNamePlaceholder: 'Your first name',
    tel: 'Phone',
    telPlaceholder: '06 00 00 00 00',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    open: 'Sign up',
    submit: 'Create my account',
    fine: 'A password to open the door, then your device recognises you.',
    fineInline: 'A password to open the door, then your device recognises you.',
    legal:
      'By continuing, you accept the terms of sale and our data policy. No payment is asked for at sign-up.',
  },
  rappel: {
    asapGroup: 'As soon as possible',
    asapTitle: 'Within 15 minutes',
    asapSub: 'The bakery picks up — that’s the fastest.',
    todayGroup: 'Today',
    note: 'Between noon and 2pm we’re at the oven : we don’t take calls, and we’d rather say so.',
    phone: 'We’ll call you on {phone}.',
    phoneUnknown: 'We call the number on your account.',
    ctaIdle: 'Pick a time',
    ctaReady: 'Request the call',
    slotFree: 'available',
    slotFull: 'full',
    slotOven: 'at the oven',
  },
  doors: {
    or: 'or',
    alreadyTitle: 'Already a customer ?',
    alreadySub: 'Password, or your device',
    firstTitle: 'First time ?',
    firstSub: 'First name, email, phone',
    signInLead: 'Continue the way you chose when you opened your account.',
    signInSubmit: 'Continue',
    switchLabel: 'Account type',
    persoLabel: 'Individual',
    persoSub: 'I order for myself',
    proLabel: 'Trade',
    proSub: 'I order for my venue',
    toPersoLead: 'Ordering for yourself ?',
    toPersoLink: 'Create a personal account',
    toProLead: 'Ordering for a venue ?',
  },
  event: {
    badge: 'Catering',
    title: 'An event,\nwe handle it all.',
    pitch: 'Seminar, birthday, club outing : the headcount, the time, the place — we do the rest.',
    cta: 'Get a quote ›',
    pending:
      'The quote request screen lands in the next batch — the card is wired, its sequel isn’t.',
  },
  commande: {
    title: 'Hello {name}.\nHow shall we serve you ?',
    titleAnonymous: 'Hello.\nHow can we serve you?',
    intro: 'You choose, we bake.',
    sectionsLabel: 'Sections',
    newOrderTitle: 'New order',
    newOrderSub: 'One question to start with : do you come, or do we ?',
    nowTitle: 'Right now',
    pickupBadge: 'Pickup',
    pickupTitle: 'I’ll come\nand get it',
    pickupDetail: 'At the Labo, or any of our resort shops.',
    pickupNote: 'Tomorrow from 6 am',
    pickupDetailWide: 'At the Labo or in the village, tomorrow at the hour I pick.',
    pickupCta: 'Choose a pickup point',
    pickupNoteWide: 'Up to −{value}',
    deliveryBadge: 'Courier',
    deliveryTitle: 'We bring it\nto you',
    deliveryDetail: 'Tomorrow, in the time slot you pick.',
    deliveryNote: 'Order before 6 pm',
    deliveryDetailWide: 'Tomorrow, in the slot you pick. Two addresses already saved.',
    deliveryCta: 'Choose an address',
    deliveryNoteWide: 'Before 6 pm',
    eventBadge: 'Christmas',
    eventTitle: 'Christmas is made\nat the bakehouse',
    eventDetail: 'Two yule logs, a calendar, the papillotes.',
    eventNote: '72 h notice · D-18',
    cateringBadge: 'Catering',
    cateringTitle: 'An event,\nwe handle it all',
    cateringDetail: 'Seminar, birthday, club outing.',
    cateringNote: 'Answer within 24 h',
    browseTitle: 'Show me the shop',
    browseSub: 'Browse the counter and decide afterwards',
    againTitle: 'Same as last Saturday ?',
    againSub: '2 traditions, 4 croissants, 1 praline ski · pickup at the Labo',
    againAction: 'Reorder',
    againLead: 'Or start again from',
    urgenceTitle: 'Something urgent, something extra ?',
    urgencePitch:
      'A forgotten item on a running order, one more batch : the phone sorts it out. We rarely say no.',
    urgenceCta: 'Call me back',
    pending:
      'The rest of the journey lands in the next batch — the card is wired, its screen is not.',
  },
  shop: {
    changeService: 'Change',
    pickService: 'Where are you served?',
    pickServiceHint: 'Price and time depend on it — say so before paying.',
    loading: 'Loading the shelves…',
    loadFailedTitle: 'The shop could not load',
    loadFailedHint: 'The network did not answer. Nothing is lost — your basket is waiting.',
    loadRetry: 'Try again',
    searchPlaceholder: 'Look for a baguette, an éclair…',
    clearSearch: 'Clear the search',
    allShelves: 'Everything',
    allShelvesTitle: 'The whole counter',
    resultsFor: 'Results for “{query}”',
    piecesUnit: 'items',
    emptyTitle: 'Nothing under that name.',
    emptyHint: 'Try “bread”, “tart”, or tap a shelf.',
    openFeatureShelf: 'Open the shelf',
    slidePrevious: 'Previous',
    slideNext: 'Next',
    slideGoTo: 'Item {n} of {count}',
    shelvesGroup: 'The shelves',
    priceHt: '{price} excl. VAT',
    htSuffix: 'excl. VAT',
    priceTtc: '{price} incl. VAT',
    ttcSuffix: 'incl. VAT',
    addAria: 'Add {name}',
    removeAria: 'Remove {name}',
    cartTitle: 'Your basket',
    cartEmpty:
      'Empty basket. The morning batch goes fast — the praline ski never sees the afternoon.',
    upsell: '{name} with that?',
    upsellLine: 'The treat you regret leaving behind.',
    orderingSoon: 'Online ordering opens soon.',
  },
  product: {
    bestSeller: 'Best-seller',
    oven: 'Baked',
    perPiece: '/ piece',
    proDiscount: 'Trade price −{pct}%',
    batch: '× {n}',
    batchAria: '{n} pieces',
    addCount: 'Add {n}',
    update: 'Update',
    inCart: 'Already in basket',
  },
  cart: {
    kicker: 'The basket',
    title: 'Your order',
    intro: 'Read it over, adjust, pay. The batch follows your slot.',
    pickupGroup: 'To collect',
    deliveryGroup: 'To deliver',
    slotNote: '{day} · chosen slot',
    dayToday: 'today',
    dayTomorrow: 'tomorrow',
    changeService: 'Change',
    subtotal: 'Subtotal excl. VAT',
    discount: 'Collection discount {at} −{value}',
    fee: 'Courier',
    vat: 'VAT {rate}',
    total: 'Total incl. VAT',
    clear: 'Empty the basket',
    payOnAccount: 'Charge to account',
    accountSoon:
      'Charging to account lands in the next batch — it is waiting on your payment term.',
    dropAria: 'Remove {name} from the basket',
    pay: 'Pay for my order · {total}',
    payHint: 'Paid online. You show your QR at the counter, nothing to settle there.',
    settleTitle: 'How are you paying?',
    settleCard: 'Pay now',
    settleAccount: 'Add to the account',
    browse: 'See the counter',
    whoTitle: 'Who is placing this order?',
    whoHint: 'We need a name and an address to send you your pickup QR.',
    whoRegister: 'This is my first order',
    whoSignIn: 'I already have an account',
    back: 'Back to the shop',
    guestTitle: 'Who is collecting?',
    guestSubtitle: 'No account to create. We just need a way to send you your QR.',
    guestFirstName: 'First name',
    guestFirstNameHint: 'This is the name we will call at the counter.',
    guestEmail: 'Email address',
    guestEmailHint: 'Your confirmation and pickup QR land there.',
    guestEmailAgain: 'Confirm your address',
    guestEmailMismatch: 'The two addresses are not the same.',
    guestPhone: 'Phone',
    guestPhoneHint: 'So we can reach you if something is wrong with your order.',
    guestCancel: 'Cancel',
    guestConfirm: 'Continue',
  },
  qr: {
    title: 'Your handover code',
    lead: 'Show this code. The team’s scan is what records the handover.',
    loading: 'Loading…',
    codeLabel: 'Handover QR code',
    when: 'For {day}',
    unavailable: 'This order has no code: it predates the handover code.',
    unknown: 'That order cannot be found.',
  },
  pay: {
    title: 'One thing left: paying.',
    lead: 'Your order {ref} is on file. It goes into production once paid.',
    amount: 'Amount due',
    loading: 'Loading secure payment…',
    submit: 'Pay {total}',
    submitting: 'Paying…',
    later: 'I will pay from “My orders”',
    unavailable:
      'Payment is unavailable right now. Your order is on file: you can pay it from “My orders”.',
    refused: 'The payment was declined.',
    failed: 'The payment could not be completed.',
    accepted: 'Payment accepted.',
  },
  done: {
    kicker: 'Confirmed',
    title: 'All paid.\nWe start at 4.15 am.',
    titleDue: 'Order on file.\nOne thing left: paying.',
    titleAccount: 'Order on file.\nIt goes on your account.',
    intro: 'Your order joins tomorrow morning’s batch.',
    keptTitle: 'Kept in your space',
    keptLine: 'Find it again, with its collection QR, under “My orders”.',
    recapPickup: 'Collection',
    recapDelivery: 'Delivery',
    recapContent: 'Contents',
    recapPieces: '{count} items',
    paidOnline: 'Paid online',
    toSettle: 'Left to pay',
    onAccount: 'Charged to your account',
    settleAction: 'Pay now',
    qr: 'View my handover code',
    changeNote: 'Need a change? Call the bakery — a placed order goes into production.',
  },
  dialog: {
    close: 'Close',
  },
  pickupDialog: {
    kicker: 'Pickup',
    title: 'Where are you coming ?',
    whenTitle: 'When are you coming ?',
    lead: 'We like having you over : collect at the Labo and get {value} off your order.',
    habit: 'your usual',
    readyFrom: 'Ready from {time}',
    discountTag: '−{value} on everything',
    proPrice: 'Trade price',
    shopPrice: 'Shop price',
    cta: 'Pick my time',
  },
  addressDialog: {
    kicker: 'Courier',
    title: 'Where do we deliver ?',
    bookGroup: 'Your addresses',
    defaultTag: 'Default',
    otherGroup: 'Another address',
    street: 'Street',
    streetPlaceholder: '12 rue du Coin Ferrand',
    postcode: 'Postcode',
    postcodePlaceholder: '73150',
    city: 'Town',
    cityUnknown: 'Derived from the postcode',
    outOfZone: 'Outside the delivery area',
    outOfZoneNote: 'We don’t ride down that far yet. Pickup is still open to you.',
    whoGroup: 'Who receives it',
    name: 'Name',
    fromAccount: 'Account',
    phone: 'Phone',
    edit: 'Edit',
    whyPhone: 'Prefilled from your account — the courier calls this number if the door hides.',
    saveToBook: 'Save this address to my book',
    saveOn: 'We’ll have it ready next time.',
    saveOff: 'Otherwise it only serves this order.',
    cta: 'Pick my slot · €{fee}',
    ctaBlocked: 'Choose an address',
  },
  slotStep: {
    pickupIntro: 'To collect {place}. The slot keeps the batch for you.',
    deliveryIntro: 'Delivered {place}. The courier leaves as the slot opens.',
    amGroup: 'Morning · out of the oven',
    pmGroup: 'Après-ski · second batch',
    free: 'open',
    proOnly: 'trade only',
    before: 'before',
    noneTitle: 'No hours declared',
    noneSubtitle: 'This place hasn’t published its hours yet. Call us and we’ll sort it out.',
    ctaIdle: 'Pick a slot',
    cta: 'Fill my basket',
  },
  orders: ORDERS_EN,
  invoices: INVOICES_EN,
  account: ACCOUNT_EN,
  pro: {
    title: 'Interested in a trade account ?',
    bookedTitle: 'Call requested',
    pitch: 'Negotiated prices, resort delivery, monthly invoicing. We’ll explain in two minutes.',
    cta: 'Ask us to call you',
    openAccount: 'Open my trade account',
    booked: 'Call requested · {slot}',
    at: 'On',
    cancel: 'Cancel',
  },
  legalDocument: {
    close: 'Close',
    loading: 'Loading the document…',
    errorTitle: 'Document unavailable',
    errorSubtitle: 'The document could not be loaded. Try again in a moment — or just ask us.',
    retry: 'Try again',
    emptyTitle: 'Not published yet',
    emptySubtitle: 'This notice does not carry any clause yet.',
  },
};
