import type { ClientCopy } from './client-copy.model';
import { ACCOUNT_IT } from './screens/account.it';
import { INVOICES_IT } from './screens/invoices.copy';
import { ORDERS_IT } from './screens/orders.copy';

/**
 * Italien. Val d'Isère est frontalière : la clientèle italienne n'est pas un
 * public de passage, c'est un public de saison.
 *
 * Deux partis pris de traduction : « fournil » devient *laboratorio* (le lieu,
 * pas le métier — c'est ainsi que la boutique se nomme, « Le Labo »), et
 * « coursier » devient *corriere*, qui dit la livraison en station sans laisser
 * croire à une messagerie.
 */
export const IT: ClientCopy = {
  chrome: {
    identityConflict:
      'Esiste già un account con questo indirizzo Google. Accedi con la tua email abituale.',
    identityConflictDismiss: 'Ho capito',
    back: 'Indietro',
    menu: 'Menu',
    notifications: 'Notifiche',
    lang: 'Lingua',
    signIn: 'Accedi',
    createAccount: 'Crea il mio account',
    kickerWelcome: 'Benvenuto',
    kickerRappel: 'Richiamo',
    kickerCommande: 'Nuovo ordine',
    kickerShop: 'Bottega',
    kickerCart: 'Il carrello',
    kickerPay: 'Pagamento',
    kickerQr: 'Ritiro',
    kickerDone: 'Confermato',
    deskKicker: 'Val d’Isère · ordina online',
    brandLine: 'Panetteria · Val d’Isère',
    featureAccessFailed:
      'Non siamo riusciti a verificare cosa offre il negozio in questo momento: alcune pagine restano chiuse. Ricarica la pagina per riprovare.',
    accountMenu: 'Il mio account personale',
    myProfile: 'Il mio profilo',
    workspaceChoice: 'Spazio di lavoro',
    workspacePersonal: 'Personale',
    workspaceCurrentPersonal: 'Account personale',
    workspaceCurrentFor: 'Lavori per',
    workspaceSection: 'I miei spazi',
    workspaceKindPro: 'Pro',
    workspaceKindPersonal: 'Personale',
    workspacePersonalNote: 'Ordini a suo nome',
    workspaceRolePro: 'Account pro',
    notificationsClose: 'Chiudi',
    notificationsCount: '{unread} non lette · {total} in totale',
    notificationsMarkAll: 'Segna tutto come letto',
    notificationsEmpty: 'Nulla da segnalare.',
    cartOpen: 'Vedi il mio carrello',
  },

  nav: {
    destinations: {
      shop: 'Negozio',
      orders: 'Ordini',
      invoices: 'Fatture',
      baskets: 'Carrelli ricorrenti',
      account: 'Il mio account',
    },
    invoicesDue: '{n} da saldare',
    basketsCount: '{n} modelli',
    cart: 'Il mio carrello',
    soon: 'Presto',
    close: 'Chiudi il menu',
    newOrder: 'Nuovo ordine',
    newOrderSub: 'Ritiro o corriere, scegliete voi',
    house: 'La casa',
    houseLinks: [
      ['I nostri banchi e i nostri metodi', '6 schede'],
      ['Le Labo — orari e accesso', 'Aperto'],
      ['Un imprevisto, un’aggiunta?', 'Chiamaci'],
    ],
    logout: 'Esci',
    address: 'Le Labo · route de la Balme, Val d’Isère — 7 – 19',
    hello: 'Ciao {name}.',
    helloAnonymous: 'Ciao.',
  },
  hero: {
    welcomeTitle: 'Il tuo ordine in stazione, pronto in due minuti.',
    welcomeIntro: 'Tu scegli, noi prepariamo.',
    rappelTitle: 'Quando ti richiamiamo ?',
    rappelIntro: 'Chiamiamo dal laboratorio, mai da un call center.',
  },
  aside: {
    proof: [
      'Iscrizione rapida.',
      'Il tuo spazio cresce insieme alle tue esigenze.',
      'Prezzi professionali, consegna in stazione, fatturazione mensile su richiesta.',
    ],
    address: 'Le Labo · Route de la Balme — aperto dalle 7 alle 19.',
  },
  signup: {
    facebook: 'Continua con Facebook',
    orEmail: 'oppure via e-mail',
    google: 'Continua con Google',
    eyebrow: 'Prima volta ? 3 informazioni e si parte',
    alreadyLead: 'Sei già cliente ?',
    alreadyLink: 'Accedere',
    pitch: 'Un nome, una e-mail, un numero. Tutto qui — il resto aspetterà che ti serva.',
    firstName: 'Nome',
    firstNamePlaceholder: 'Il tuo nome',
    tel: 'Telefono',
    telPlaceholder: '06 00 00 00 00',
    email: 'E-mail',
    emailPlaceholder: 'tu@esempio.it',
    open: 'Iscriviti',
    submit: 'Crea il mio account',
    fine: 'Una password per aprire, poi il suo dispositivo la riconosce.',
    fineInline: 'Una password per aprire, poi il suo dispositivo la riconosce.',
    legal:
      'Continuando, accettate le condizioni generali di vendita e la nostra politica sui dati. Nessun pagamento è richiesto all’iscrizione.',
  },
  rappel: {
    asapGroup: 'Prima possibile',
    asapTitle: 'Entro 15 minuti',
    asapSub: 'Risponde il laboratorio — è la via più rapida.',
    todayGroup: 'Oggi',
    note: 'Tra le 12 e le 14 siamo al forno : non rispondiamo al telefono, e preferiamo dirlo.',
    phone: 'Ti richiamiamo al {phone}.',
    phoneUnknown: 'La richiamiamo al numero del suo account.',
    ctaIdle: 'Scegli un momento',
    ctaReady: 'Richiedi il richiamo',
    slotFree: 'disponibile',
    slotFull: 'esaurito',
    slotOven: 'al forno',
  },
  doors: {
    or: 'oppure',
    alreadyTitle: 'Sei già cliente ?',
    alreadySub: 'Password, o il suo dispositivo',
    firstTitle: 'Prima volta ?',
    firstSub: 'Nome, e-mail, telefono',
    signInLead: 'Riprendi dal metodo che hai scelto aprendo il tuo account.',
    signInSubmit: 'Continua',
    switchLabel: 'Tipo di account',
    persoLabel: 'Privato',
    persoSub: 'Ordino per me',
    proLabel: 'Professionista',
    proSub: 'Ordino per il mio locale',
    toPersoLead: 'Ordina per sé ?',
    toPersoLink: 'Creare un account privato',
    toProLead: 'Ordina per un locale ?',
  },
  event: {
    badge: 'Catering',
    title: 'Un evento,\npensiamo a tutto.',
    pitch:
      'Seminario, compleanno, uscita di club : il numero, l’ora, il luogo — al resto pensiamo noi.',
    cta: 'Un preventivo ›',
    pending:
      'La schermata di richiesta preventivo arriva nel prossimo lotto — la scheda è collegata, il seguito no.',
  },
  commande: {
    title: 'Buongiorno {name}.\nCome glielo serviamo ?',
    titleAnonymous: 'Buongiorno.\nCome la serviamo?',
    intro: 'Lei sceglie, noi prepariamo.',
    sectionsLabel: 'Sezioni',
    newOrderTitle: 'Nuovo ordine',
    newOrderSub: 'Una sola domanda per iniziare : viene lei, o veniamo noi ?',
    nowTitle: 'In questo momento',
    pickupBadge: 'Ritiro',
    pickupTitle: 'Passo io\na prenderlo',
    pickupDetail: 'Al Labo o in una delle botteghe della stazione.',
    pickupNote: 'Domani dalle 6',
    pickupDetailWide: 'Al Labo o al villaggio, domani all’ora che scelgo io.',
    pickupCta: 'Scegliere un punto di ritiro',
    pickupNoteWide: 'Fino a −{value}',
    deliveryBadge: 'Corriere',
    deliveryTitle: 'Glielo\nportiamo noi',
    deliveryDetail: 'Domani, nella fascia oraria che sceglie lei.',
    deliveryNote: 'Ordini entro le 18',
    deliveryDetailWide: 'Domani, nella fascia che sceglie lei. Due indirizzi già salvati.',
    deliveryCta: 'Scegliere un indirizzo',
    deliveryNoteWide: 'Entro le 18',
    eventBadge: 'Natale',
    eventTitle: 'Il Natale si gioca\nal forno',
    eventDetail: 'Due tronchetti, un calendario, i papillotes.',
    eventNote: '72 h di preavviso · G-18',
    cateringBadge: 'Catering',
    cateringTitle: 'Un evento,\npensiamo a tutto',
    cateringDetail: 'Seminario, compleanno, uscita di club.',
    cateringNote: 'Risposta entro 24 h',
    browseTitle: 'Visito la bottega',
    browseSub: 'Per vedere i prodotti e decidere dopo',
    againTitle: 'Come sabato scorso ?',
    againSub: '2 traditions, 4 croissant, 1 ski al pralinato · ritiro al Labo',
    againAction: 'Rifare',
    againLead: 'Oppure riprenda',
    urgenceTitle: 'Un’urgenza, un’aggiunta ?',
    urgencePitch:
      'Una dimenticanza su un ordine in corso, una sfornata da allungare : si risolve al telefono. Diciamo di no di rado.',
    urgenceCta: 'Farsi richiamare',
    pending:
      'Il seguito del percorso arriva nel prossimo lotto — la scheda è collegata, la sua schermata no.',
  },
  shop: {
    changeService: 'Cambia',
    pickService: 'Dove viene servito?',
    pickServiceHint: 'Prezzo e orario dipendono da questo — lo dica prima di pagare.',
    loading: 'Il reparto sta arrivando…',
    loadFailedTitle: 'La bottega non si è caricata',
    loadFailedHint: 'La rete non ha risposto. Niente è perduto: il carrello ti aspetta.',
    loadRetry: 'Riprova',
    searchPlaceholder: 'Cerca una baguette, un éclair…',
    clearSearch: 'Cancella la ricerca',
    allShelves: 'Tutto',
    allShelvesTitle: 'Tutto il banco',
    resultsFor: 'Risultati per « {query} »',
    piecesUnit: 'pezzi',
    emptyTitle: 'Niente con questo nome.',
    emptyHint: 'Provi « pane », « torta », o tocchi un reparto.',
    openFeatureShelf: 'Apri il reparto',
    slidePrevious: 'Precedente',
    slideNext: 'Successivo',
    slideGoTo: 'Contenuto {n} di {count}',
    shelvesGroup: 'I reparti',
    priceHt: '{price} IVA escl.',
    htSuffix: 'IVA escl.',
    priceTtc: '{price} IVA incl.',
    ttcSuffix: 'IVA incl.',
    addAria: 'Aggiungi {name}',
    removeAria: 'Togli {name}',
    cartTitle: 'Il suo carrello',
    cartEmpty:
      'Carrello vuoto. L’infornata del mattino va via in fretta — lo sci al pralinato non arriva mai al pomeriggio.',
    upsell: '{name} insieme?',
    upsellLine: 'La golosità che si rimpiange di non aver preso.',
    orderingSoon: 'Gli ordini online aprono presto.',
    operationOpensOn: 'Apre il {date}',
    operationNotOpen: 'Non ancora aperto',
    operationClosed: 'Ordini chiusi',
    operationBadgeFrom: 'Dal {date}',
    operationBadgeDays: 'G‑{days}',
    operationBadgeLastDay: 'Ultimo giorno',
  },
  product: {
    bestSeller: 'Best-seller',
    oven: 'Sfornata',
    operationPickup: 'Ritiro',
    operationPickupSpan: 'dal {from} al {until}',
    operationPickupDay: 'il {day}',
    perPiece: '/ pezzo',
    proDiscount: 'Prezzo pro −{pct} %',
    batch: '× {n}',
    batchAria: '{n} pezzi',
    addCount: 'Aggiungi {n}',
    update: 'Aggiorna',
    inCart: 'Già nel carrello',
  },
  cart: {
    kicker: 'Il carrello',
    title: 'Il suo ordine',
    intro: 'Rilegga, corregga, paghi. L’infornata segue la sua fascia oraria.',
    pickupGroup: 'Da ritirare',
    deliveryGroup: 'Da consegnare',
    slotNote: '{day} · fascia scelta',
    dayToday: 'oggi',
    dayTomorrow: 'domani',
    changeService: 'Modifica',
    subtotal: 'Subtotale IVA escl.',
    discount: 'Sconto ritiro {at} −{value}',
    fee: 'Corriere',
    vat: 'IVA {rate}',
    total: 'Totale IVA incl.',
    clear: 'Svuota il carrello',
    payOnAccount: 'Addebita sul conto',
    accountSoon:
      'L’addebito sul conto arriva nel prossimo lotto — attende la vostra condizione di pagamento.',
    dropAria: 'Rimuovi {name} dal carrello',
    pay: 'Pago il mio ordine · {total}',
    payHint: 'Pagamento online. Mostri il QR al banco, non deve saldare nulla sul posto.',
    settleTitle: 'Come pagate ?',
    settleCard: 'Pagamento diretto',
    settleAccount: 'Aggiungi al conto',
    browse: 'Vedi il banco',
    whoTitle: 'Chi effettua questo ordine?',
    whoHint: 'Ci servono un nome e un indirizzo per inviarle il QR di ritiro.',
    whoRegister: 'È il mio primo ordine',
    whoSignIn: 'Ho già un account',
    back: 'Torna alla bottega',
    guestTitle: 'Chi viene a ritirare?',
    guestSubtitle: 'Nessun account da creare. Ci serve solo come inviarle il suo QR.',
    guestFirstName: 'Nome',
    guestFirstNameHint: 'È il nome che chiameremo al banco.',
    guestEmail: 'Indirizzo e-mail',
    guestEmailHint: 'La conferma e il QR di ritiro arrivano lì.',
    guestEmailAgain: 'Confermi il suo indirizzo',
    guestEmailMismatch: 'I due indirizzi non coincidono.',
    guestPhone: 'Telefono',
    guestPhoneHint: 'Per contattarla se qualcosa non va con il suo ordine.',
    guestCancel: 'Annulla',
    guestConfirm: 'Continua',
  },
  qr: {
    title: 'Il suo codice di consegna',
    lead: 'Mostri questo codice. È la scansione del team che attesta la consegna.',
    loading: 'Caricamento…',
    codeLabel: 'Codice QR di consegna',
    when: 'Per il {day}',
    unavailable: 'Questo ordine non ha codice: è anteriore al codice di consegna.',
    unknown: 'Ordine non trovato.',
  },
  pay: {
    title: 'Resta da pagare.',
    lead: 'Il suo ordine {ref} è registrato. Parte in produzione una volta pagato.',
    amount: 'Importo da pagare',
    loading: 'Caricamento del pagamento sicuro…',
    submit: 'Paga {total}',
    submitting: 'Pagamento…',
    later: 'Pago da « I miei ordini »',
    unavailable:
      'Il pagamento non è disponibile al momento. Il suo ordine è registrato: potrà pagarlo da « I miei ordini ».',
    refused: 'Il pagamento è stato rifiutato.',
    failed: 'Il pagamento non è andato a buon fine.',
    accepted: 'Pagamento accettato.',
  },
  done: {
    kicker: 'Confermato',
    title: 'È pagato.\nSi comincia alle 4.15.',
    titleDue: 'Ordine registrato.\nResta da pagare.',
    titleAccount: 'Ordine registrato.\nVa sul suo conto.',
    intro: 'Il suo ordine entra nell’infornata di domani mattina.',
    keptTitle: 'Conservato nel suo spazio',
    keptLine: 'Lo ritrova, col suo QR di ritiro, in « I miei ordini ».',
    recapPickup: 'Ritiro',
    recapDelivery: 'Consegna',
    recapContent: 'Contenuto',
    recapPieces: '{count} pezzi',
    paidOnline: 'Pagato online',
    toSettle: 'Resta da pagare',
    onAccount: 'Addebitato sul conto',
    settleAction: 'Paga adesso',
    qr: 'Vedere il mio codice di consegna',
    changeNote: 'Un cambiamento? Chiami il forno — un ordine inviato entra in produzione.',
  },
  dialog: {
    close: 'Chiudere',
  },
  pickupDialog: {
    kicker: 'Ritiro',
    title: 'Dove passa a prenderlo ?',
    whenTitle: 'Quando passa ?',
    lead: 'Ci fa piacere riceverla : ritiri al Labo e approfitti di uno sconto del {value} sull’ordine.',
    habit: 'la sua abitudine',
    readyFrom: 'Pronto dalle {time}',
    discountTag: '−{value} su tutto',
    proPrice: 'Prezzo pro',
    shopPrice: 'Prezzo bottega',
    cta: 'Scegliere l’ora',
  },
  addressDialog: {
    kicker: 'Corriere',
    title: 'Dove consegniamo ?',
    bookGroup: 'I suoi indirizzi',
    defaultTag: 'Predefinito',
    otherGroup: 'Un altro indirizzo',
    street: 'Via',
    streetPlaceholder: '12 rue du Coin Ferrand',
    postcode: 'Codice postale',
    postcodePlaceholder: '73150',
    city: 'Città',
    cityUnknown: 'Si deduce dal codice postale',
    outOfZone: 'Fuori zona di consegna',
    outOfZoneNote: 'Fin laggiù non scendiamo ancora. Il ritiro, invece, resta aperto.',
    whoGroup: 'Chi riceve',
    name: 'Nome',
    fromAccount: 'Account',
    phone: 'Telefono',
    edit: 'Modificare',
    whyPhone:
      'Precompilato dal suo account — il corriere chiama questo numero se non trova la porta.',
    saveToBook: 'Salvare questo indirizzo in rubrica',
    saveOn: 'Lo ritroveremo al prossimo ordine.',
    saveOff: 'Altrimenti serve solo per questo ordine.',
    cta: 'Scegliere la fascia · {fee} €',
    ctaBlocked: 'Scelga un indirizzo',
  },
  slotStep: {
    pickupIntro: 'Da ritirare {place}. La fascia le tiene la sfornata.',
    deliveryIntro: 'Consegnato {place}. Il corriere parte all’apertura della fascia.',
    amGroup: 'Mattina · appena sfornato',
    pmGroup: 'Après-ski · seconda sfornata',
    free: 'aperto',
    proOnly: 'riservato ai professionisti',
    before: 'entro le',
    noneTitle: 'Nessun orario dichiarato',
    noneSubtitle:
      'Questo punto non ha ancora pubblicato gli orari. Ci chiami, troviamo la soluzione.',
    ctaIdle: 'Scelga una fascia',
    cta: 'Riempire il carrello',
  },
  orders: ORDERS_IT,
  invoices: INVOICES_IT,
  account: ACCOUNT_IT,
  pro: {
    title: 'Ti interessa lo spazio professionale ?',
    bookedTitle: 'Richiamo richiesto',
    pitch:
      'Prezzi concordati, consegna in stazione, fatturazione mensile. Te lo spieghiamo in due minuti.',
    cta: 'Chiedi di essere richiamato',
    openAccount: 'Apri il mio account professionale',
    booked: 'Richiamo richiesto · {slot}',
    at: 'Al',
    cancel: 'Annulla',
  },
  legalDocument: {
    close: 'Chiudi',
    loading: 'Caricamento del documento…',
    errorTitle: 'Documento non disponibile',
    errorSubtitle:
      'Non è stato possibile caricare il documento. Riprova tra un istante — o scrivici.',
    retry: 'Riprova',
    emptyTitle: 'Documento non pubblicato',
    emptySubtitle: 'Questa informativa non contiene ancora alcun articolo.',
  },
};
