-- BASCULER — palier 2/3 de la bascule `AddressKind`.
--
-- Les lignes passent à `billing`/`delivery`. Ce qui rend l'opération inoffensive
-- n'est pas sa prudence, c'est le palier 1 : depuis lui, le code EN LIGNE lit
-- les deux encodages. L'ancien container relira donc sans broncher les lignes
-- que cette migration vient de réécrire.
--
-- ⚠️ **Cette migration ne doit PAS partir dans le même déploiement que
-- `20260825090000_address_kind_etendre`.** Si les deux s'appliquent à la suite,
-- le container qui sert encore le trafic est celui d'AVANT le palier 1 : il ne
-- connaît que `facturation`, et ne lèverait aucune erreur — il rendrait des
-- adresses absentes.
--
-- ## Pourquoi cette phrase est un commentaire et non un garde SQL
--
-- Ce fichier a d'abord porté un garde : « refuser si `étendre` a fini il y a
-- moins de cinq minutes ». Il a mordu à la première utilisation — sur une base
-- de DÉVELOPPEMENT, où les trois paliers arrivent forcément dans le même
-- `migrate deploy`, et où aucun container ne sert de trafic.
--
-- Le défaut est de conception, pas de réglage : depuis SQL, « dev rejoue toutes
-- les migrations » et « la prod a déployé les deux d'un coup » ont exactement la
-- même forme. Seul l'appelant sait lequel des deux il est. Un garde qui ne peut
-- pas faire la différence se déclenche sur chaque machine de développement, on
-- apprend à le contourner — et il ne protège plus rien le jour où il aurait
-- servi. L'ordre des déploiements est le travail de la chaîne de livraison
-- (`documentation/ops/pipelines.md`), pas d'une migration.
--
-- Le palier 3, lui, GARDE : sa question porte sur les données (« reste-t-il une
-- ligne dans l'ancien encodage ? »), et une question sur les données a la même
-- réponse partout.
UPDATE "public"."addresses" SET "kind" = 'billing' WHERE "kind" = 'facturation';
UPDATE "public"."addresses" SET "kind" = 'delivery' WHERE "kind" = 'livraison';
