import type { AccountCopy } from './account.copy';

export const ACCOUNT_EN: AccountCopy = {
  title: 'My account',
  lead: 'Your file as we keep it: identity, access, paperwork, addresses, payment terms.',
  states: {
    incomplete: 'File to complete',
    pending: 'File in progress',
    active: 'Account active',
    suspended: 'Account suspended',
    terminated: 'Account closed',
  },
  loadFailedTitle: 'Your account could not be loaded',
  loadFailedBody: 'The service is not responding right now. Please try again in a moment.',
  loadRetry: 'Try again',
  loading: 'Loading your account…',
  signedOutTitle: 'Sign in to see your account',
  signedOutBody: 'Your file, access and paperwork are waiting for you here.',
  signIn: 'Sign in',
  cardKicker: 'Trade account',
  cardReference: 'My customer reference: {ref}',
  panelDot: 'Go to section {n}',
  cardPaymentHead: 'Payment methods',
  cardPaymentOnOrder: 'On order',
  cardPaymentOnAccount: 'On account / periodic',
  cardPaymentPending: 'Waiting for your details',
  cardUnknown: 'Account not recognised',
  cardUnknownNote: 'Sign in to find your company.',
  identityUnknown: '—',
  summaryHead: 'The file',
  edit: 'Edit',
  details: 'See details',
  save: 'Save',
  cancel: 'Cancel',
  sections: {
    identity: 'Legal identity',
    users: 'Users',
    profile: 'My details',
    kbis: 'Registry extract',
    addresses: 'Addresses',
    bank: 'Bank details',
    payment: 'Payment',
    preferences: 'Preferences',
    data: 'My data',
  },
  identityBrand: 'Trading name',
  identityCompany: 'Registered name',
  identityForm: 'Legal form',
  identitySiret: 'SIRET',
  identityVat: 'VAT number',
  identityNote:
    'The trading name changes here. Registry details go through us: we check, then we update — these are the mentions that appear on your invoices.',
  identityPanelSubtitle: 'Trading name and VAT change here; registry details are filled in once.',
  identityVatField: 'Intra-EU VAT number',
  identityLegalHint:
    'Fill in once: after saving, this detail can only be corrected through our sales team.',
  identityLegalLocked:
    'These details come from the company registry. To correct them, contact our sales team.',
  identitySaveFailed: 'Your identity was not saved.',
  railPosition: 'Section {n} of {total}',
  usersHolder: 'Account holder · you',
  usersAllRights: 'All rights',
  usersNote:
    'A contact can exist without a workspace: a name and an e-mail are enough to receive the invoices. The invitation is decided case by case.',
  usersAdd: 'Add a user or a contact',
  usersAddShort: 'Add a user',
  usersAddSubtitle: 'Their details, and what they do for the company.',
  usersAddFailed: 'The contact was not added.',
  roleUnset: 'To be set',
  tagContact: 'Contact only',
  contactEditHolderTitle: 'Edit the holder',
  contactEditTitle: 'Edit the contact',
  contactEditHolderSubtitle:
    'The holder’s details on the company record. They do not change their sign-in address: that one is changed under “My details”.',
  contactEditSubtitle: 'Their details, and what they do for the company.',
  contactEditFailed: 'The contact was not saved.',
  contactRemove: 'Delete',
  contactRemoveMessage: 'This contact will be removed from the company.',
  contactRemoveConfirm: 'Yes, delete',
  contactRemoveBusy: 'Deleting…',
  contactRemoveGroup: 'Confirm deleting the contact',
  contactRemoveFailed: 'The contact was not deleted.',
  profileFirstName: 'First name',
  profileLastName: 'Last name',
  profileEmail: 'E-mail',
  profileNote:
    'Your own details, not the company’s. The e-mail address is also the one you sign in with.',
  profilePanelSubtitle: 'Your personal details, seen only by us.',
  profileEmailHint: 'Also used to sign in.',
  profileEmailChange:
    'Once saved, this address becomes your sign-in identifier. A verification e-mail is sent to it: open it to confirm.',
  profileSaveFailed: 'Your details were not saved.',
  kbisHead: 'The registry extract',
  kbisCertified: 'Certified',
  kbisPending: 'Awaiting verification',
  kbisNone: 'No extract on file',
  kbisUpload: 'Upload the KBIS',
  kbisFiled: 'Filed on {date}',
  kbisOpen: 'Open',
  kbisReplace: 'Replace',
  kbisView: 'View the KBIS',
  kbisDownload: 'Download',
  kbisDrop: 'Upload',
  kbisHint: 'PDF, 10 MB maximum',
  kbisUploading: 'Uploading the KBIS…',
  kbisSaveFailed: 'The KBIS was not uploaded.',
  kbisFetchFailed: 'The KBIS could not be retrieved. Please try again.',
  billingHead: 'Billing',
  billingNote:
    'One billing address only: it is the one on your invoices and on the direct-debit mandate.',
  deliveryHead: 'Delivery',
  deliveryCount: '{n} addresses',
  deliveryCountOne: '{n} address',
  addressNoZone: 'outside our zones',
  addressNone: 'No address on file.',
  addressDefault: 'Default',
  addressAdd: 'Add a delivery address',
  billingFill: 'Fill in the billing address',
  billingEdit: 'Edit the billing address',
  addressEdit: 'Edit the delivery address',
  deliveryNote: 'Note for the drivers',
  addressSaveFailed: 'The address was not saved.',
  addressSavedToast: 'Address saved.',
  addressMakeDefault: 'Make default',
  addressDefaultToast: 'Default address changed.',
  addressRemove: 'Remove',
  addressRemoveMessage: 'Remove this address from the book? Orders already placed keep theirs.',
  addressRemoveConfirm: 'Remove the address',
  addressRemoveBusy: 'Removing…',
  addressRemoveGroup: 'Confirm removing the address',
  addressRemovedToast: 'Address removed.',
  addressActionFailed: 'The address book was not changed.',
  termMonthly: '30 days end of month',
  termGrantedSub: 'Granted by your sales contact: your orders are settled at month end.',
  termRequestedSub: 'Request sent: your sales contact will approve it.',
  termNoneSub: 'On request: your sales contact grants it company by company.',
  termOrder: 'At checkout',
  termOrderSub: 'Card or Apple Pay, without waiting for the invoice',
  stateActive: 'Active',
  stateAvailable: 'Available',
  stateRequested: 'Pending',
  paymentNote:
    'Two regimes, no more: end of month when credit is granted, at checkout otherwise — and everyone can order at checkout.',
  termRequest: 'Request monthly payment',
  termRequestNote: 'This is a request: nothing changes until your sales contact approves it.',
  termRequestFailed: 'The request was not saved.',
  prefPickup: 'Usual pickup',
  prefNone: 'Nothing set — we ask on each order.',
  prefPickupAt: 'Collection at',
  prefPickupAny: 'Collection',
  prefDeliveryTo: 'Delivery to',
  prefDeliveryAny: 'Delivery',
  stateUnavailable: 'Not granted',
  prefLang: 'Language',
  prefNote: 'A dated operation warns once a season. Deliveries and invoices are on by default.',
  prefMethod: 'Usual mode',
  prefMethodNone: 'None — choose on each order',
  prefMethodPickup: 'Collection',
  prefMethodDelivery: 'Delivery',
  prefPickupPoint: 'Collection point',
  prefPickupDefault: 'The default point',
  prefDeliveryAddress: 'Delivery address',
  prefDeliveryDefault: 'The company’s default address',
  prefDefaultTag: 'default',
  prefSaveFailed: 'The preference was not saved.',
  prefLangNote: 'The language changes right away, nothing to save.',
  dataExportOrders: 'Export my orders and my invoices',
  dataExportOrdersSub: 'CSV and PDF, by financial year',
  dataExportPersonal: 'Download my personal data',
  dataExportPersonalSub: 'Everything we hold, in one file',
  dataSummary: 'Retention, transfer and closing of the workspace',
  dataKeep:
    'Your invoices stay available for ten years after closing — that is an obligation, not a choice.',
  dangerHead: 'Sensitive area',
  transferHead: 'Transfer the company',
  transferBody:
    'You hand the holder role to a user of the workspace. They take over billing, payment terms and the right to invite. You keep your access, without administration.',
  transferCta: 'Transfer the account',
  closeHead: 'Close this workspace',
  closeBody:
    'Final, and specific to this workspace: access revoked for you and your users, discount and payment terms lost, recurring baskets deleted. Your other workspaces do not move. A live order must be collected or cancelled first.',
  closeCta: 'Close this workspace',
  panelKicker: 'User',
  panelContact: 'Contact details',
  panelPhone: 'Phone',
  panelRole: 'Role',
  noPhone: 'not given',
  spaceContactHead: 'No workspace',
  spaceContactBody:
    'This contact exists only to receive the invoices by e-mail. No password, no basket, and nothing of the app is visible to them.',
  spaceActiveHead: 'Workspace active',
  spaceSelf: 'Your own access cannot be revoked here: hand over the holder role first.',
  bankLoading: 'Reading your bank details…',
  bankLoadFailedTitle: 'Your bank details could not be read',
  bankLoadFailedBody: 'The service is not responding right now. Try again in a moment.',
  bankNone: 'No bank details on file',
  bankRegistered: 'Bank details on file',
  bankLast4: '•••• {last4}',
  bankNotice:
    'The account holder and address are the ones your bank knows: they may differ from your registered company name. If a direct debit runs on this account, replacing it stops the debit: we will get back to you on what comes next.',
  bankHolder: 'Account holder',
  bankLine1: 'Address',
  bankLine2: 'Address line 2',
  bankPostalCode: 'Postcode',
  bankCity: 'City',
  bankCountry: 'Country',
  bankIbanHint: 'Entered once. It will never be shown again.',
  bankSave: 'Save bank details',
  bankReplace: 'Replace bank details',
  bankSavedToast: 'Bank details saved.',
  bankSaveFailed: 'Your bank details were not saved.',
  supportTitle: 'Contact our sales team',
  supportPanelTitle: 'Sales team',
  supportBody: 'A question about your account, an order or an invoice: we will get back to you.',
};
