import type { AccountCopy } from './account.copy';

export const ACCOUNT_EN: AccountCopy = {
  title: 'My account',
  lead: 'Your file as we keep it: identity, access, paperwork, addresses, payment terms.',
  state: 'Account active · file complete',
  cardKicker: 'Trade account',
  cardActive: 'Active',
  cardReference: 'Ref. {ref} — quote it on the phone',
  cardTermMonthly: 'End of month',
  cardTermOrder: 'On order',
  cardUnknown: 'Account not recognised',
  cardUnknownNote: 'Sign in to find your company.',
  identityUnknown: '—',
  cardTerm: 'End of month',
  summaryHead: 'The file',
  summaryNote: 'One page: the summary scrolls, it does not change screen.',
  edit: 'Edit',
  sections: {
    identity: 'Legal identity',
    users: 'Users',
    kbis: 'Registry extract',
    addresses: 'Addresses',
    payment: 'Payment',
    preferences: 'Preferences',
    data: 'My data',
  },
  identityBrand: 'Trading name',
  identityCompany: 'Registered name',
  identityForm: 'Legal form',
  identitySiret: 'SIRET',
  identityVat: 'VAT number',
  identityNote:
    'The trading name changes here. Registry details go through us: we check, then we update — these are the mentions that appear on your invoices.',
  usersHolder: 'Account holder · you',
  usersAllRights: 'All rights',
  usersAdd: 'Add a user or a contact',
  usersNote:
    'A contact can exist without a workspace: a name and an e-mail are enough to receive the invoices. The invitation is decided case by case.',
  roleUnset: 'To be set',
  tagContact: 'Contact only',
  kbisHead: 'The registry extract',
  kbisCertified: 'Certified extract',
  kbisPending: 'Awaiting verification',
  kbisNone: 'No extract on file.',
  kbisUpload: 'Upload an extract',
  kbisFiled: 'Filed on {date}',
  kbisOpen: 'Open',
  kbisReplace: 'Replace',
  kbisNote:
    'An extract less than three months old is asked for when credit is opened, never at sign-up. This one stays valid until 12/05 — we will warn you beforehand.',
  billingHead: 'Billing',
  billingNote:
    'One billing address only: it is the one on your invoices and on the direct-debit mandate.',
  deliveryHead: 'Delivery',
  deliveryCount: '{n} addresses',
  addressNoZone: 'outside our zones',
  addressNone: 'No address on file.',
  addressDefault: 'Default',
  addressAdd: 'Add an address',
  termMonthly: '30 days end of month',
  termMonthlySub: 'Granted on 14/02/2024 · limit €2,000',
  termOrder: 'At checkout',
  termOrderSub: 'Card or Apple Pay, without waiting for the invoice',
  stateActive: 'Active',
  stateAvailable: 'Available',
  paymentNote:
    'Two regimes, no more: end of month when credit is granted, at checkout otherwise — and everyone can order at checkout.',
  prefPickup: 'Usual pickup',
  prefNone: 'Nothing set — we ask on each order.',
  prefPickupAt: 'Collection at',
  prefPickupAny: 'Collection',
  prefDeliveryTo: 'Delivery to',
  prefDeliveryAny: 'Delivery',
  stateUnavailable: 'Not granted',
  prefLang: 'Language',
  prefNote: 'A dated operation warns once a season. Deliveries and invoices are on by default.',
  dataExportOrders: 'Export my orders and my invoices',
  dataExportOrdersSub: 'CSV and PDF, by financial year',
  dataExportPersonal: 'Download my personal data',
  dataExportPersonalSub: 'Everything we hold, in one file',
  dataKeep:
    'Your invoices stay available for ten years after closing — that is an obligation, not a choice.',
  dangerHead: 'Sensitive area',
  transferHead: 'Transfer the company',
  transferBody:
    'You hand the holder role to a user of the workspace. They take over billing, payment terms and the right to invite. You keep your access, without administration.',
  transferCta: 'Transfer the account',
  closeHead: 'Close this workspace',
  closeBody:
    'Final, and specific to this workspace: access revoked for you and your users, discount and payment terms lost, recurring baskets deleted. Your other workspaces do not move. A live order must be collected or cancelled first.',
  closeCta: 'Close this workspace',
  panelKicker: 'User',
  panelContact: 'Contact details',
  panelPhone: 'Phone',
  panelRole: 'Role',
  panelCan: 'What they can do',
  noPhone: 'not given',
  spaceContactHead: 'No workspace',
  spaceContactBody:
    'This contact exists only to receive the invoices by e-mail. No password, no basket, and nothing of the app is visible to them.',
  spaceInvite: 'Invite them to create a workspace',
  spaceInviteNote: 'The invitation goes by e-mail, without a password: a link, valid 14 days.',
  spaceActiveHead: 'Workspace active',
  spaceSelf: 'Your own access cannot be revoked here: hand over the holder role first.',
};
