import type { AccountCopy } from './account.copy';

export const ACCOUNT_FR: AccountCopy = {
  title: 'Mon compte',
  lead: 'Votre dossier tel que nous le tenons : identité, accès, papiers, adresses, conditions de paiement.',
  states: {
    incomplete: 'Dossier à compléter',
    pending: 'Dossier en cours',
    active: 'Compte actif',
    suspended: 'Compte suspendu',
    terminated: 'Compte clos',
  },
  loadFailedTitle: 'Votre compte n’a pas pu être lu',
  loadFailedBody: 'Le service ne répond pas pour le moment. Réessayez dans un instant.',
  loadRetry: 'Réessayer',
  loading: 'Lecture de votre compte…',
  signedOutTitle: 'Connectez-vous pour voir votre compte',
  signedOutBody: 'Votre dossier, vos accès et vos papiers vous attendent ici.',
  signIn: 'Se connecter',
  cardKicker: 'Compte professionnel',
  cardReference: 'Ma référence client : {ref}',
  panelDot: 'Aller à la section {n}',
  cardPaymentHead: 'Modes de paiement',
  cardPaymentOnOrder: 'À la commande',
  cardPaymentOnAccount: 'Au compte / périodique',
  cardPaymentPending: 'En attente de vos informations',
  cardUnknown: 'Compte non reconnu',
  cardUnknownNote: 'Connectez-vous pour retrouver votre entreprise.',
  identityUnknown: '—',
  summaryHead: 'Le dossier',
  summaryNote: 'Une seule page : le sommaire fait défiler, il ne change pas d’écran.',
  edit: 'Modifier',
  sections: {
    identity: 'Identité légale',
    users: 'Utilisateurs',
    kbis: 'KBIS',
    addresses: 'Adresses',
    bank: 'RIB',
    payment: 'Paiement',
    preferences: 'Préférences',
    data: 'Mes données',
  },
  identityBrand: 'Enseigne',
  identityCompany: 'Raison sociale',
  identityForm: 'Forme juridique',
  identitySiret: 'SIRET',
  identityVat: 'TVA intracom.',
  identityNote:
    'L’enseigne se change ici. Les mentions du greffe passent par nous : on vérifie, puis on met à jour — c’est ce qui figure sur vos factures.',
  identityPanelSubtitle:
    'L’enseigne et la TVA se changent ici ; les mentions du greffe se complètent une fois.',
  identityVatField: 'TVA intracommunautaire',
  identityLegalHint:
    'À compléter une seule fois : une fois enregistrée, cette mention ne se corrige plus qu’avec notre service commercial.',
  identityLegalLocked:
    'Ces mentions viennent du greffe. Pour les corriger, passez par notre service commercial.',
  identitySaveFailed: 'L’identité n’a pas été enregistrée.',
  identityCancel: 'Annuler',
  identitySave: 'Enregistrer',
  railPosition: 'Section {n} sur {total}',
  usersHolder: 'Détenteur du compte · vous',
  usersAllRights: 'Tous droits',
  usersAdd: 'Ajouter un utilisateur ou un contact',
  usersNote:
    'Un contact peut exister sans espace : un nom et un e-mail suffisent pour recevoir les factures. L’invitation, elle, se décide au cas par cas.',
  roleUnset: 'À préciser',
  tagContact: 'Contact seulement',
  kbisHead: 'L’extrait du greffe',
  kbisCertified: 'Extrait certifié',
  kbisPending: 'En attente de vérification',
  kbisNone: 'Aucun extrait déposé.',
  kbisUpload: 'Déposer un extrait',
  kbisFiled: 'Déposé le {date}',
  kbisOpen: 'Ouvrir',
  kbisReplace: 'Remplacer',
  kbisNote:
    'Un extrait de moins de trois mois est demandé à l’ouverture d’un crédit, jamais à l’inscription. Celui-ci reste valable jusqu’au 12/05 — nous vous préviendrons avant.',
  billingHead: 'Facturation',
  billingNote:
    'Une seule adresse de facturation : c’est elle qui figure sur les factures et sur le mandat.',
  deliveryHead: 'Livraison',
  deliveryCount: '{n} adresses',
  addressNoZone: 'hors zone',
  addressNone: 'Aucune adresse enregistrée.',
  addressDefault: 'Par défaut',
  addressAdd: 'Ajouter une adresse',
  termMonthly: 'Paiement à 30 jours fin de mois',
  termMonthlySub: 'Accordé le 14/02/2024 · plafond 2 000 €',
  termOrder: 'À la commande',
  termOrderSub: 'Carte ou Apple Pay, sans attendre la facture',
  stateActive: 'Actif',
  stateAvailable: 'Disponible',
  paymentNote:
    'Deux régimes, pas plus : fin de mois quand un crédit est accordé, à la commande sinon — et tout le monde peut commander à la commande.',
  prefPickup: 'Retrait habituel',
  prefNone: 'Rien de posé — la question se pose à chaque commande.',
  prefPickupAt: 'Retrait au',
  prefPickupAny: 'Retrait',
  prefDeliveryTo: 'Livraison',
  prefDeliveryAny: 'Livraison',
  stateUnavailable: 'Non accordé',
  prefLang: 'Langue',
  prefNote:
    'Une opération datée ne prévient qu’une fois par saison. Les livraisons et les factures, elles, sont actives par défaut.',
  dataExportOrders: 'Exporter mes commandes et mes factures',
  dataExportOrdersSub: 'CSV et PDF, par exercice',
  dataExportPersonal: 'Télécharger mes données personnelles',
  dataExportPersonalSub: 'Tout ce que nous avons, en un fichier',
  dataKeep:
    'Vos factures restent disponibles dix ans après la fermeture — c’est une obligation, pas un choix.',
  dangerHead: 'Zone sensible',
  transferHead: 'Transférer l’entreprise',
  transferBody:
    'Vous cédez le rôle de détenteur à un utilisateur de l’espace. Il reprend la facturation, les conditions de paiement et le droit d’inviter. Vous gardez votre accès, sans l’administration.',
  transferCta: 'Transférer le compte',
  closeHead: 'Fermer cet espace',
  closeBody:
    'Définitif, et propre à cet espace : accès révoqué pour vous et vos utilisateurs, remise et conditions de paiement perdues, paniers récurrents supprimés. Vos autres espaces ne bougent pas. Une commande en cours doit être retirée ou annulée avant.',
  closeCta: 'Fermer cet espace',
  panelKicker: 'Utilisateur',
  panelContact: 'Coordonnées',
  panelPhone: 'Téléphone',
  panelRole: 'Fonction',
  panelCan: 'Ce qu’il peut faire',
  noPhone: 'non renseigné',
  spaceContactHead: 'Pas d’espace',
  spaceContactBody:
    'Ce contact existe uniquement pour recevoir les factures par e-mail. Il n’a pas de mot de passe, pas de panier, et ne voit rien de l’application.',
  spaceInvite: 'Inviter à créer son espace',
  spaceInviteNote: 'L’invitation part par e-mail, sans mot de passe : un lien, valable 14 jours.',
  spaceActiveHead: 'Espace actif',
  spaceSelf:
    'Votre propre accès ne se retire pas d’ici : transmettez d’abord le rôle de détenteur.',
  bankLoading: 'Lecture de votre RIB…',
  bankLoadFailedTitle: 'Votre RIB n’a pas pu être lu',
  bankLoadFailedBody: 'Le service ne répond pas pour le moment. Réessayez dans un instant.',
  bankNone: 'Aucun RIB enregistré',
  bankSaved: '•••• {last4} · BIC {bic} · {holder}',
  bankNotice:
    'Le titulaire et l’adresse sont ceux que connaît votre banque : ils peuvent différer de votre raison sociale. Si un prélèvement est en place sur ce compte, le remplacer l’interrompt : nous revenons vers vous pour la suite.',
  bankHolder: 'Titulaire du compte',
  bankLine1: 'Adresse',
  bankLine2: 'Complément',
  bankPostalCode: 'Code postal',
  bankCity: 'Ville',
  bankCountry: 'Pays',
  bankIbanHint: 'Saisi une fois. Il ne sera plus jamais réaffiché.',
  bankSave: 'Enregistrer le RIB',
  bankReplace: 'Remplacer le RIB',
  bankSavedToast: 'RIB enregistré.',
  bankSaveFailed: 'Le RIB n’a pas été enregistré.',
  supportTitle: 'Contacter le service commercial',
  supportPanelTitle: 'Service commercial',
  supportBody: 'Une question sur votre compte, une commande ou une facture : nous vous répondons.',
};
