import type { AddressFormLabels } from '@lfd/b2b-ui/address';
import type { AccountCopy } from './account.copy';

const ADDRESS_FORM: AddressFormLabels = {
  label: "Nom de l'adresse",
  labelHint: 'ex. Siège, Boutique Bastille',
  line1: 'Adresse',
  line1Placeholder: 'n° et voie',
  line2: 'Complément',
  line2Hint: 'bâtiment, étage, digicode…',
  postalCode: 'Code postal',
  city: 'Ville',
  country: 'Pays',
  countryPlaceholder: 'Choisir un pays…',
  optional: 'optionnel',
  noteLabel: 'Consignes d’accès',
  notePlaceholder: 'Digicode, étage, où déposer…',
  coordinatesLabel: 'Point GPS',
  coordinatesHint: 'pour les lieux qu’une adresse ne suffit pas à trouver',
  entryModeAria: 'Mode de saisie du point',
  entryModePair: 'Deux champs',
  entryModePasted: 'Point collé',
  latitude: 'Latitude',
  latitudePlaceholder: '48.8566',
  longitude: 'Longitude',
  longitudePlaceholder: '2.3522',
  point: 'Point',
  pointHint: 'collez « 48.8566, 2.3522 » depuis une carte',
  pointPlaceholder: '48.8566, 2.3522',
};

export const ACCOUNT_FR: AccountCopy = {
  title: 'Mon compte',
  lead: 'Votre dossier tel que nous le tenons : identité, accès, papiers, adresses, conditions de paiement.',
  states: {
    incomplete: 'Dossier à compléter',
    pending: 'Dossier en cours',
    active: 'Compte actif',
    suspended: 'Compte suspendu',
    terminated: 'Compte clos',
  },
  loadFailedTitle: 'Votre compte n’a pas pu être lu',
  loadFailedBody: 'Le service ne répond pas pour le moment. Réessayez dans un instant.',
  loadRetry: 'Réessayer',
  loading: 'Lecture de votre compte…',
  signedOutTitle: 'Connectez-vous pour voir votre compte',
  signedOutBody: 'Votre dossier, vos accès et vos papiers vous attendent ici.',
  signIn: 'Se connecter',
  cardKicker: 'Compte professionnel',
  cardReference: 'Ma référence client : {ref}',
  panelDot: 'Aller à la section {n}',
  cardPaymentHead: 'Modes de paiement',
  cardPaymentOnOrder: 'À la commande',
  cardPaymentOnAccount: 'Au compte / périodique',
  cardPaymentPending: 'En attente de vos informations',
  cardUnknown: 'Compte non reconnu',
  cardUnknownNote: 'Connectez-vous pour retrouver votre entreprise.',
  identityUnknown: '—',
  summaryHead: 'Le dossier',
  edit: 'Modifier',
  details: 'Voir le détail',
  save: 'Enregistrer',
  cancel: 'Annuler',
  sections: {
    identity: 'Identité légale',
    users: 'Utilisateurs',
    profile: 'Mes informations',
    kbis: 'KBIS',
    addresses: 'Adresses',
    bank: 'RIB',
    mandate: 'Mandat SEPA',
    payment: 'Paiement',
    preferences: 'Préférences',
    data: 'Mes données',
  },
  identityBrand: 'Enseigne',
  identityCompany: 'Raison sociale',
  identityForm: 'Forme juridique',
  identitySiret: 'SIRET',
  identityVat: 'TVA intracom.',
  identityNote:
    'L’enseigne se change ici. Les mentions du greffe passent par nous : on vérifie, puis on met à jour — c’est ce qui figure sur vos factures.',
  identityPanelSubtitle:
    'L’enseigne et la TVA se changent ici ; les mentions du greffe se complètent une fois.',
  identityVatField: 'TVA intracommunautaire',
  identityLegalHint:
    'À compléter une seule fois : une fois enregistrée, cette mention ne se corrige plus qu’avec notre service commercial.',
  identityLegalLocked:
    'Ces mentions viennent du greffe. Pour les corriger, passez par notre service commercial.',
  identitySaveFailed: 'L’identité n’a pas été enregistrée.',
  railPosition: 'Section {n} sur {total}',
  usersHolder: 'Détenteur du compte · vous',
  usersAllRights: 'Tous droits',
  usersNote:
    'Un contact peut exister sans espace : un nom et un e-mail suffisent pour recevoir les factures. L’invitation, elle, se décide au cas par cas.',
  usersAdd: 'Ajouter un utilisateur ou un contact',
  usersAddShort: 'Ajouter un utilisateur',
  usersAddSubtitle: 'Ses coordonnées, et ce qu’il fait pour la société.',
  usersAddFailed: 'Le contact n’a pas été ajouté.',
  roleUnset: 'À préciser',
  tagContact: 'Contact seulement',
  contactEditHolderTitle: 'Modifier le détenteur',
  contactEditTitle: 'Modifier le contact',
  contactEditHolderSubtitle:
    'Les coordonnées du détenteur sur la fiche de la société. Elles ne changent pas son adresse de connexion : celle-ci se change dans « Mes informations ».',
  contactEditSubtitle: 'Ses coordonnées, et ce qu’il fait pour la société.',
  contactEditFailed: 'Le contact n’a pas été enregistré.',
  contactRemove: 'Supprimer',
  contactRemoveMessage: 'Ce contact sera retiré de la société.',
  contactRemoveConfirm: 'Oui, supprimer',
  contactRemoveBusy: 'Suppression…',
  contactRemoveGroup: 'Confirmer la suppression du contact',
  contactRemoveFailed: 'Le contact n’a pas été supprimé.',
  profileFirstName: 'Prénom',
  profileLastName: 'Nom',
  profileEmail: 'E-mail',
  profileNote:
    'Vos coordonnées à vous, pas celles de la société. L’adresse e-mail est aussi celle avec laquelle vous vous connectez.',
  profilePanelSubtitle: 'Vos coordonnées personnelles, visibles de nous seuls.',
  profileEmailHint: 'Sert aussi à vous connecter.',
  profileEmailChange:
    'Dès l’enregistrement, cette adresse devient votre identifiant de connexion. Un e-mail de vérification y part : ouvrez-le pour la confirmer.',
  profileSaveFailed: 'Vos informations n’ont pas été enregistrées.',
  kbisHead: 'L’extrait du greffe',
  kbisCertified: 'Certifié',
  kbisPending: 'En attente de vérification',
  kbisNone: 'Aucun extrait déposé',
  kbisUpload: 'Déposer le KBIS',
  kbisFiled: 'Déposé le {date}',
  kbisOpen: 'Ouvrir',
  kbisReplace: 'Remplacer',
  kbisView: 'Voir le KBIS',
  kbisDownload: 'Télécharger',
  kbisDrop: 'Déposer',
  kbisHint: 'PDF, 10 Mo maximum',
  kbisUploading: 'Envoi du KBIS…',
  kbisSaveFailed: 'Le KBIS n’a pas été déposé.',
  kbisFetchFailed: 'Le KBIS n’a pas pu être récupéré. Réessayez.',
  billingHead: 'Facturation',
  billingNote:
    'Une seule adresse de facturation : c’est elle qui figure sur les factures et sur le mandat.',
  deliveryHead: 'Livraison',
  deliveryCount: '{n} adresses',
  deliveryCountOne: '{n} adresse',
  addressNoZone: 'hors zone',
  addressNone: 'Aucune adresse enregistrée.',
  addressDefault: 'Par défaut',
  addressAdd: 'Ajouter une adresse de livraison',
  billingFill: 'Renseigner la facturation',
  billingEdit: 'Modifier la facturation',
  addressEdit: 'Modifier l’adresse de livraison',
  addressSaveFailed: 'L’adresse n’a pas été enregistrée.',
  addressSavedToast: 'Adresse enregistrée.',
  addressMakeDefault: 'Définir par défaut',
  addressDefaultToast: 'Adresse par défaut changée.',
  addressRemove: 'Supprimer',
  addressRemoveMessage:
    'Retirer cette adresse du carnet ? Les commandes déjà passées gardent la leur.',
  addressRemoveConfirm: 'Supprimer l’adresse',
  addressRemoveBusy: 'Suppression…',
  addressRemoveGroup: 'Confirmer la suppression de l’adresse',
  addressRemovedToast: 'Adresse supprimée.',
  addressActionFailed: 'Le carnet n’a pas été modifié.',
  deliveryDialogSubtitle: 'Une adresse postale complète, et comment on y livre.',
  deliveryAddSubmit: 'Ajouter',
  addressForm: ADDRESS_FORM,
  deliveryForm: {
    defaultLabel: 'Adresse de livraison par défaut',
    defaultHint: 'utilisée d’office pour les prochaines commandes',
    legend: 'Adresse postale',
    address: {
      ...ADDRESS_FORM,
      labelHint: 'ex. Chalet, Restaurant d’altitude',
      line2Hint: 'bâtiment, étage, instructions de livraison…',
      noteLabel: 'Note pour les livreurs',
      notePlaceholder: 'Code d’accès, étage, contact sur place, consignes de dépôt…',
      coordinatesLabel: 'Point GPS',
      coordinatesHint: 'lieux difficiles à localiser',
    },
    specs: {
      detailLegend: 'Détail de livraison',
      slotsLegend: 'Créneaux préférés',
      sameEveryDay: 'Le même créneau tous les jours',
      sameEveryDayHint: 'décochez pour définir un créneau par jour',
      everyDay: 'Tous les jours',
      weekdays: {
        mon: 'Lundi',
        tue: 'Mardi',
        wed: 'Mercredi',
        thu: 'Jeudi',
        fri: 'Vendredi',
        sat: 'Samedi',
        sun: 'Dimanche',
      },
      slotStart: 'Début',
      slotEnd: 'Fin',
      contactLegend: 'Contact sur place',
      noContact: 'Pas de contact de livraison dédié',
      noContactHint: 'cochez si le livreur n’a personne à prévenir sur place',
      knownContact: 'Reprendre un contact connu',
      knownContactPlaceholder: 'Choisir un contact…',
      firstName: 'Prénom',
      lastName: 'Nom',
      phone: 'Téléphone',
      contactIncomplete: 'Renseignez prénom, nom et téléphone, ou cochez « pas de contact ».',
      signature: 'Signature à la remise',
      signatureHint: 'préremplit les commandes livrées ici ; modifiable au panier',
      signatureInherit: 'Comme la société ({floor})',
      signatureFloorRequired: 'exigée',
      signatureFloorNotRequired: 'non exigée',
      signatureRequired: 'Exigée',
      signatureNotRequired: 'Non exigée',
      signatureNoContactHint: 'sans contact sur place, personne ne peut signer à la remise',
    },
  },
  termMonthly: 'Paiement à 30 jours fin de mois',
  termGrantedSub: 'Accordé par votre commercial : vos commandes se règlent en fin de mois.',
  termRequestedSub: 'Demande envoyée : votre commercial la valide.',
  termNoneSub: 'Sur demande : votre commercial l’accorde société par société.',
  termOrder: 'À la commande',
  termOrderSub: 'Carte ou Apple Pay, sans attendre la facture',
  stateActive: 'Actif',
  stateAvailable: 'Disponible',
  stateRequested: 'En attente',
  paymentNote:
    'Deux régimes, pas plus : fin de mois quand un crédit est accordé, à la commande sinon — et tout le monde peut commander à la commande.',
  termRequest: 'Demander le règlement mensuel',
  termRequestNote:
    'C’est une demande : rien ne change tant que votre commercial ne l’a pas validée.',
  termRequestFailed: 'La demande n’a pas été enregistrée.',
  prefPickup: 'Retrait habituel',
  prefNone: 'Rien de posé — la question se pose à chaque commande.',
  prefPickupAt: 'Retrait au',
  prefPickupAny: 'Retrait',
  prefDeliveryTo: 'Livraison',
  prefDeliveryAny: 'Livraison',
  stateUnavailable: 'Non accordé',
  prefLang: 'Langue',
  prefNote:
    'Une opération datée ne prévient qu’une fois par saison. Les livraisons et les factures, elles, sont actives par défaut.',
  prefMethod: 'Mode habituel',
  prefMethodNone: 'Aucun — choisir à chaque commande',
  prefMethodPickup: 'Retrait',
  prefMethodDelivery: 'Livraison',
  prefPickupPoint: 'Point de retrait',
  prefPickupDefault: 'Le point par défaut',
  prefDeliveryAddress: 'Adresse de livraison',
  prefDeliveryDefault: 'L’adresse par défaut de la société',
  prefDefaultTag: 'défaut',
  prefSaveFailed: 'La préférence n’a pas été enregistrée.',
  prefLangNote: 'La langue change tout de suite, sans rien enregistrer.',
  dataExportOrders: 'Exporter mes commandes et mes factures',
  dataExportOrdersSub: 'CSV et PDF, par exercice',
  dataExportPersonal: 'Télécharger mes données personnelles',
  dataExportPersonalSub: 'Tout ce que nous avons, en un fichier',
  dataSummary: 'Conservation, transfert et fermeture de l’espace',
  dataKeep:
    'Vos factures restent disponibles dix ans après la fermeture — c’est une obligation, pas un choix.',
  dangerHead: 'Zone sensible',
  transferHead: 'Transférer l’entreprise',
  transferBody:
    'Vous cédez le rôle de détenteur à un utilisateur de l’espace. Il reprend la facturation, les conditions de paiement et le droit d’inviter. Vous gardez votre accès, sans l’administration.',
  transferCta: 'Transférer le compte',
  closeHead: 'Fermer cet espace',
  closeBody:
    'Définitif, et propre à cet espace : accès révoqué pour vous et vos utilisateurs, remise et conditions de paiement perdues, paniers récurrents supprimés. Vos autres espaces ne bougent pas. Une commande en cours doit être retirée ou annulée avant.',
  closeCta: 'Fermer cet espace',
  panelKicker: 'Utilisateur',
  panelContact: 'Coordonnées',
  panelPhone: 'Téléphone',
  panelRole: 'Fonction',
  noPhone: 'non renseigné',
  spaceContactHead: 'Pas d’espace',
  spaceContactBody:
    'Ce contact existe uniquement pour recevoir les factures par e-mail. Il n’a pas de mot de passe, pas de panier, et ne voit rien de l’application.',
  spaceActiveHead: 'Espace actif',
  spaceSelf:
    'Votre propre accès ne se retire pas d’ici : transmettez d’abord le rôle de détenteur.',
  bankLoading: 'Lecture de votre RIB…',
  bankLoadFailedTitle: 'Votre RIB n’a pas pu être lu',
  bankLoadFailedBody: 'Le service ne répond pas pour le moment. Réessayez dans un instant.',
  bankNone: 'Aucun RIB enregistré',
  bankRegistered: 'RIB enregistré',
  bankLast4: '•••• {last4}',
  bankNotice:
    'Le titulaire et l’adresse sont ceux que connaît votre banque : ils peuvent différer de votre raison sociale. Si un prélèvement est en place sur ce compte, le remplacer l’interrompt : nous revenons vers vous pour la suite.',
  bankForm: {
    holder: 'Titulaire du compte',
    holderPlaceholder: '',
    line1: 'Adresse',
    line1Placeholder: '',
    line2: 'Complément',
    line2Placeholder: '',
    postalCode: 'Code postal',
    postalCodePlaceholder: '',
    city: 'Ville',
    cityPlaceholder: '',
    country: 'Pays',
    countryPlaceholder: '',
    iban: 'IBAN',
    ibanPlaceholder: '',
    ibanHint: 'Saisi une fois. Il ne sera plus jamais réaffiché.',
    bic: 'BIC',
    bicPlaceholder: '',
  },
  bankSave: 'Enregistrer le RIB',
  bankReplace: 'Remplacer le RIB',
  bankSavedToast: 'RIB enregistré.',
  bankSaveFailed: 'Le RIB n’a pas été enregistré.',
  mandateLoading: 'Lecture de votre mandat…',
  mandateLoadFailedTitle: 'Votre mandat n’a pas pu être lu',
  mandateLoadFailedBody: 'Le service ne répond pas pour le moment. Réessayez dans un instant.',
  mandateNone: 'Aucun mandat en cours',
  mandateAwaiting: 'Renvoyez le mandat daté et signé',
  mandateInReview: 'Mandat reçu — en vérification',
  mandateActive: 'Mandat actif',
  mandateReference: 'RUM · {reference}',
  mandateSignedOn: 'Signé le {date}',
  mandateProofFile: 'Fichier déposé : {fileName}',
  mandateGenerate: 'Générer mon mandat',
  mandateSend: 'Renvoyer le mandat signé',
  mandateView: 'Voir le mandat',
  mandateDownload: 'Télécharger le mandat',
  mandateNoneBody:
    'Le mandat de prélèvement SEPA interentreprises autorise le prélèvement de vos factures sur le compte de votre RIB. Générez-le : vous pourrez ensuite l’imprimer, le dater, le signer et nous le renvoyer ici.',
  mandateAwaitingBody:
    'Imprimez le mandat, datez-le et signez-le, puis déposez ici son scan ou sa photo. Déclarez-le aussi à votre banque : un prélèvement interentreprises n’est accepté qu’une fois le mandat enregistré chez elle.',
  mandateInReviewBody:
    'Nous vérifions le mandat signé : il sera actif dès que notre service l’aura relu. Vous pouvez encore remplacer le fichier déposé.',
  mandateActiveBody:
    'Vos prélèvements s’appuient sur ce mandat. Pour changer de compte bancaire, contactez le service commercial.',
  mandateDrop: 'Déposer le mandat signé',
  mandateDropReplace: 'Remplacer le fichier déposé',
  mandateDropHint: 'PDF ou photo (JPEG, PNG, HEIC), 10 Mo au plus.',
  mandateUploading: 'Envoi du mandat…',
  mandateUploadedToast: 'Mandat signé reçu.',
  mandateGenerateFailed: 'Le mandat n’a pas été généré.',
  mandateUploadFailed: 'Le mandat signé n’a pas été déposé.',
  mandateFetchFailed: 'Le mandat n’a pas pu être ouvert. Réessayez dans un instant.',
  mandateEsign: 'Utiliser la signature électronique',
  mandateEsignSoon: 'Bientôt disponible',
  mandateOptions: 'Options du mandat',
  mandateOptionsSubtitle: 'Code débiteur et numéro de contrat',
  mandateOptionsNotice:
    'Ces deux zones sont facultatives : aucune ne conditionne la validité du mandat, et les laisser vides est parfaitement normal.',
  mandateOptionsDraftWarning:
    'Modifier ces zones annule le mandat en attente de signature : il faudra le générer à nouveau.',
  mandateOptionsForm: {
    debtorReference: 'Code identifiant du débiteur',
    debtorReferenceHint: 'La référence que vous voulez voir revenir sur vos relevés bancaires.',
    debtorReferencePlaceholder: '',
    contractNumber: 'Numéro du contrat',
    contractNumberHint: 'Facultatif.',
    contractNumberPlaceholder: '',
  },
  mandateOptionsLoading: 'Lecture des options du mandat…',
  mandateOptionsLoadFailedTitle: 'Les options du mandat n’ont pas pu être lues',
  mandateOptionsNoBank: 'Enregistrez d’abord votre RIB : ces zones s’y rattachent.',
  mandateOptionsSave: 'Enregistrer les options',
  mandateOptionsSavedToast: 'Options du mandat enregistrées.',
  mandateOptionsSaveFailed: 'Les options du mandat n’ont pas été enregistrées.',
  supportTitle: 'Contacter le service commercial',
  supportPanelTitle: 'Service commercial',
  supportBody: 'Une question sur votre compte, une commande ou une facture : nous vous répondons.',
};
