import type { AccountCopy } from './account.copy';

export const ACCOUNT_IT: AccountCopy = {
  title: 'Il mio account',
  lead: 'Il vostro fascicolo così come lo teniamo: identità, accessi, documenti, indirizzi, condizioni di pagamento.',
  states: {
    incomplete: 'Fascicolo da completare',
    pending: 'Fascicolo in corso',
    active: 'Account attivo',
    suspended: 'Account sospeso',
    terminated: 'Account chiuso',
  },
  loadFailedTitle: 'Non è stato possibile leggere il suo account',
  loadFailedBody: 'Il servizio non risponde al momento. Riprovi tra un istante.',
  loadRetry: 'Riprova',
  loading: 'Lettura del suo account…',
  signedOutTitle: 'Acceda per vedere il suo account',
  signedOutBody: 'Il suo fascicolo, gli accessi e i documenti la aspettano qui.',
  signIn: 'Accedi',
  cardKicker: 'Account professionale',
  cardReference: 'Il mio codice cliente: {ref}',
  panelDot: 'Vai alla sezione {n}',
  cardPaymentHead: 'Modalità di pagamento',
  cardPaymentOnOrder: 'All’ordine',
  cardPaymentOnAccount: 'Su conto / periodico',
  cardPaymentPending: 'In attesa dei tuoi dati',
  cardUnknown: 'Account non riconosciuto',
  cardUnknownNote: 'Acceda per ritrovare la sua azienda.',
  identityUnknown: '—',
  summaryHead: 'Il fascicolo',
  edit: 'Modificare',
  details: 'Vedere il dettaglio',
  save: 'Registra',
  cancel: 'Annulla',
  sections: {
    identity: 'Identità legale',
    users: 'Utenti',
    kbis: 'Visura',
    addresses: 'Indirizzi',
    bank: 'Coordinate bancarie',
    payment: 'Pagamento',
    preferences: 'Preferenze',
    data: 'I miei dati',
  },
  identityBrand: 'Insegna',
  identityCompany: 'Ragione sociale',
  identityForm: 'Forma giuridica',
  identitySiret: 'SIRET',
  identityVat: 'Partita IVA intracom.',
  identityNote:
    'L’insegna si cambia qui. Le menzioni del registro passano da noi: verifichiamo, poi aggiorniamo — sono quelle che figurano sulle vostre fatture.',
  identityPanelSubtitle:
    'Insegna e partita IVA si cambiano qui; le menzioni del registro si completano una volta.',
  identityVatField: 'Partita IVA intracomunitaria',
  identityLegalHint:
    'Da completare una sola volta: una volta registrata, questa menzione si corregge solo tramite il nostro servizio commerciale.',
  identityLegalLocked:
    'Queste menzioni provengono dal registro delle imprese. Per correggerle, passate dal nostro servizio commerciale.',
  identitySaveFailed: 'L’identità non è stata registrata.',
  railPosition: 'Sezione {n} di {total}',
  usersHolder: 'Titolare dell’account · voi',
  usersAllRights: 'Tutti i diritti',
  usersNote:
    'Un contatto può esistere senza spazio: un nome e un’e-mail bastano per ricevere le fatture. L’invito, invece, si decide caso per caso.',
  usersAdd: 'Aggiungere un utente o un contatto',
  usersAddShort: 'Aggiungere un utente',
  usersAddSubtitle: 'I suoi recapiti, e che cosa fa per l’azienda.',
  usersAddFailed: 'Il contatto non è stato aggiunto.',
  roleUnset: 'Da precisare',
  tagContact: 'Solo contatto',
  kbisHead: 'La visura camerale',
  kbisCertified: 'Certificato',
  kbisPending: 'In attesa di verifica',
  kbisNone: 'Nessun estratto depositato',
  kbisUpload: 'Depositare il KBIS',
  kbisFiled: 'Depositato il {date}',
  kbisOpen: 'Aprire',
  kbisReplace: 'Sostituire',
  kbisView: 'Vedere il KBIS',
  kbisDownload: 'Scaricare',
  kbisDrop: 'Depositare',
  kbisHint: 'PDF, 10 MB al massimo',
  kbisUploading: 'Invio del KBIS…',
  kbisSaveFailed: 'Il KBIS non è stato depositato.',
  kbisFetchFailed: 'Non è stato possibile recuperare il KBIS. Riprovate.',
  billingHead: 'Fatturazione',
  billingNote:
    'Un solo indirizzo di fatturazione: è quello che figura sulle fatture e sul mandato.',
  deliveryHead: 'Consegna',
  deliveryCount: '{n} indirizzi',
  addressNoZone: 'fuori zona',
  addressNone: 'Nessun indirizzo registrato.',
  addressDefault: 'Predefinito',
  addressAdd: 'Aggiungere un indirizzo di consegna',
  billingFill: 'Indicare la fatturazione',
  billingEdit: 'Modificare la fatturazione',
  addressEdit: 'Modificare l’indirizzo di consegna',
  deliveryNote: 'Nota per i corrieri',
  addressSaveFailed: 'L’indirizzo non è stato registrato.',
  addressSavedToast: 'Indirizzo registrato.',
  termMonthly: 'Pagamento a 30 giorni fine mese',
  termMonthlySub: 'Concesso il 14/02/2024 · massimale 2 000 €',
  termOrder: 'All’ordine',
  termOrderSub: 'Carta o Apple Pay, senza aspettare la fattura',
  stateActive: 'Attivo',
  stateAvailable: 'Disponibile',
  paymentNote:
    'Due regimi, non di più: fine mese quando un credito è concesso, all’ordine altrimenti — e tutti possono ordinare all’ordine.',
  prefPickup: 'Ritiro abituale',
  prefNone: 'Nulla impostato — la domanda torna a ogni ordine.',
  prefPickupAt: 'Ritiro al',
  prefPickupAny: 'Ritiro',
  prefDeliveryTo: 'Consegna',
  prefDeliveryAny: 'Consegna',
  stateUnavailable: 'Non concesso',
  prefLang: 'Lingua',
  prefNote:
    'Un’operazione a data avvisa una volta per stagione. Consegne e fatture, invece, sono attive di default.',
  dataExportOrders: 'Esportare i miei ordini e le mie fatture',
  dataExportOrdersSub: 'CSV e PDF, per esercizio',
  dataExportPersonal: 'Scaricare i miei dati personali',
  dataExportPersonalSub: 'Tutto quello che abbiamo, in un file',
  dataSummary: 'Conservazione, trasferimento e chiusura dello spazio',
  dataKeep:
    'Le vostre fatture restano disponibili dieci anni dopo la chiusura — è un obbligo, non una scelta.',
  dangerHead: 'Zona sensibile',
  transferHead: 'Trasferire l’azienda',
  transferBody:
    'Cedete il ruolo di titolare a un utente dello spazio. Riprende la fatturazione, le condizioni di pagamento e il diritto di invitare. Voi mantenete il vostro accesso, senza l’amministrazione.',
  transferCta: 'Trasferire l’account',
  closeHead: 'Chiudere questo spazio',
  closeBody:
    'Definitivo, e proprio di questo spazio: accesso revocato per voi e per i vostri utenti, sconto e condizioni di pagamento persi, carrelli ricorrenti eliminati. Gli altri spazi non si muovono. Un ordine in corso va ritirato o annullato prima.',
  closeCta: 'Chiudere questo spazio',
  panelKicker: 'Utente',
  panelContact: 'Contatti',
  panelPhone: 'Telefono',
  panelRole: 'Funzione',
  panelCan: 'Che cosa può fare',
  noPhone: 'non indicato',
  spaceContactHead: 'Nessuno spazio',
  spaceContactBody:
    'Questo contatto esiste solo per ricevere le fatture per e-mail. Non ha password, non ha carrello e non vede nulla dell’applicazione.',
  spaceInvite: 'Invitare a creare il suo spazio',
  spaceInviteNote: 'L’invito parte per e-mail, senza password: un link, valido 14 giorni.',
  spaceActiveHead: 'Spazio attivo',
  spaceSelf: 'Il vostro accesso non si toglie da qui: trasmettete prima il ruolo di titolare.',
  bankLoading: 'Lettura delle coordinate bancarie…',
  bankLoadFailedTitle: 'Le coordinate bancarie non sono state lette',
  bankLoadFailedBody: 'Il servizio non risponde al momento. Riprovate tra un istante.',
  bankNone: 'Nessuna coordinata bancaria registrata',
  bankRegistered: 'Coordinate bancarie registrate',
  bankLast4: '•••• {last4}',
  bankNotice:
    'Il titolare e l’indirizzo sono quelli noti alla vostra banca: possono differire dalla ragione sociale. Se su questo conto è attivo un addebito, sostituirlo lo interrompe: vi ricontatteremo per il seguito.',
  bankHolder: 'Titolare del conto',
  bankLine1: 'Indirizzo',
  bankLine2: 'Complemento',
  bankPostalCode: 'CAP',
  bankCity: 'Città',
  bankCountry: 'Paese',
  bankIbanHint: 'Inserito una volta. Non sarà mai più mostrato.',
  bankSave: 'Registra le coordinate',
  bankReplace: 'Sostituisci le coordinate',
  bankSavedToast: 'Coordinate bancarie registrate.',
  bankSaveFailed: 'Le coordinate bancarie non sono state registrate.',
  supportTitle: 'Contattare il servizio commerciale',
  supportPanelTitle: 'Servizio commerciale',
  supportBody: 'Una domanda sul vostro conto, un ordine o una fattura: vi rispondiamo.',
};
