import type { AccountCopy } from './account.copy';

export const ACCOUNT_FR: AccountCopy = {
  title: 'Mon compte',
  lead: 'Votre dossier tel que nous le tenons : identité, accès, papiers, adresses, conditions de paiement.',
  state: 'Compte actif · dossier complet',
  cardKicker: 'Compte professionnel',
  cardSince: 'Membre depuis {month} · réf. {ref}',
  cardActive: 'Actif',
  cardDiscount: 'Remise pro',
  cardTerm: 'Fin de mois',
  cardCap: 'Plafond',
  summaryHead: 'Le dossier',
  summaryNote: 'Une seule page : le sommaire fait défiler, il ne change pas d’écran.',
  edit: 'Modifier',
  sections: {
    identity: 'Identité légale',
    users: 'Utilisateurs',
    kbis: 'KBIS',
    addresses: 'Adresses',
    payment: 'Paiement',
    preferences: 'Préférences',
    data: 'Mes données',
  },
  identityBrand: 'Enseigne',
  identityCompany: 'Raison sociale',
  identityForm: 'Forme juridique',
  identitySiret: 'SIRET',
  identityVat: 'TVA intracom.',
  identityNote:
    'L’enseigne se change ici. Les mentions du greffe passent par nous : on vérifie, puis on met à jour — c’est ce qui figure sur vos factures.',
  usersHolder: 'Détenteur du compte · vous',
  usersAllRights: 'Tous droits',
  usersAdd: 'Ajouter un utilisateur ou un contact',
  usersNote:
    'Un contact peut exister sans espace : un nom et un e-mail suffisent pour recevoir les factures. L’invitation, elle, se décide au cas par cas.',
  tagActive: 'Espace actif',
  tagInvited: 'Invitation envoyée',
  tagContact: 'Contact seulement',
  kbisHead: 'L’extrait du greffe',
  kbisVerified: 'Vérifié le {date} par {who}',
  kbisUpToDate: 'À jour',
  kbisFiled: 'Déposé le {date} · {size}',
  kbisOpen: 'Ouvrir',
  kbisReplace: 'Remplacer',
  kbisFreshness: 'Fraîcheur de l’extrait',
  kbisGauge: '1 mois sur 3',
  kbisNote:
    'Un extrait de moins de trois mois est demandé à l’ouverture d’un crédit, jamais à l’inscription. Celui-ci reste valable jusqu’au 12/05 — nous vous préviendrons avant.',
  billingHead: 'Facturation',
  billingNote:
    'Une seule adresse de facturation : c’est elle qui figure sur les factures et sur le mandat.',
  deliveryHead: 'Livraison',
  deliveryCount: '{n} adresses',
  addressDefault: 'Par défaut',
  addressAdd: 'Ajouter une adresse',
  termMonthly: 'Paiement à 30 jours fin de mois',
  termMonthlySub: 'Accordé le 14/02/2024 · plafond 2 000 €',
  termOrder: 'À la commande',
  termOrderSub: 'Carte ou Apple Pay, sans attendre la facture',
  stateActive: 'Actif',
  stateAvailable: 'Disponible',
  sepaHead: 'Prélèvement SEPA',
  cardHead: 'Carte enregistrée',
  change: 'Changer',
  paymentNote:
    'Deux régimes, pas plus : fin de mois quand un crédit est accordé, à la commande sinon — et tout le monde peut commander à la commande.',
  prefPickup: 'Retrait habituel',
  prefLang: 'Langue',
  prefNotify: 'Ce qui me prévient',
  prefDeliveries: 'Livraisons et retraits',
  prefInvoices: 'Factures et échéances',
  prefEvents: 'Opérations Pâques et Noël',
  prefNote:
    'Une opération datée ne prévient qu’une fois par saison. Les livraisons et les factures, elles, sont actives par défaut.',
  dataExportOrders: 'Exporter mes commandes et mes factures',
  dataExportOrdersSub: 'CSV et PDF, par exercice',
  dataExportPersonal: 'Télécharger mes données personnelles',
  dataExportPersonalSub: 'Tout ce que nous avons, en un fichier',
  dataKeep:
    'Vos factures restent disponibles dix ans après la fermeture — c’est une obligation, pas un choix.',
  dangerHead: 'Zone sensible',
  transferHead: 'Transférer l’entreprise',
  transferBody:
    'Vous cédez le rôle de détenteur à un utilisateur de l’espace. Il reprend la facturation, les conditions de paiement et le droit d’inviter. Vous gardez votre accès, sans l’administration.',
  transferCta: 'Transférer le compte',
  closeHead: 'Fermer cet espace',
  closeBody:
    'Définitif, et propre à cet espace : accès révoqué pour vous et vos utilisateurs, remise et conditions de paiement perdues, paniers récurrents supprimés. Vos autres espaces ne bougent pas. Une commande en cours doit être retirée ou annulée avant.',
  closeCta: 'Fermer cet espace',
  panelKicker: 'Utilisateur',
  panelContact: 'Coordonnées',
  panelPhone: 'Téléphone',
  panelRole: 'Fonction',
  panelCan: 'Ce qu’il peut faire',
  canOrder: 'Commander',
  canInvoices: 'Voir les factures',
  canAdmin: 'Administrer le compte',
  yes: 'Oui',
  no: 'Non',
  noPhone: 'non renseigné',
  spaceContactHead: 'Pas d’espace',
  spaceContactBody:
    'Ce contact existe uniquement pour recevoir les factures par e-mail. Il n’a pas de mot de passe, pas de panier, et ne voit rien de l’application.',
  spaceInvite: 'Inviter à créer son espace',
  spaceInviteNote: 'L’invitation part par e-mail, sans mot de passe : un lien, valable 14 jours.',
  spaceInvitedHead: 'Invitation envoyée',
  spaceInvitedBody: 'Envoyée le {date} · le lien reste valable 14 jours.',
  spaceResend: 'Relancer',
  spaceCancel: 'Annuler',
  spaceActiveHead: 'Espace actif',
  spaceActiveBody: 'Actif depuis le {date} · connexion par lien e-mail, sans mot de passe.',
  spaceRevoke: 'Retirer l’accès',
  spaceSelf:
    'Votre propre accès ne se retire pas d’ici : transmettez d’abord le rôle de détenteur.',
};
