import type { AccountCopy } from './account.copy';

export const ACCOUNT_IT: AccountCopy = {
  title: 'Il mio account',
  lead: 'Il vostro fascicolo così come lo teniamo: identità, accessi, documenti, indirizzi, condizioni di pagamento.',
  state: 'Account attivo · fascicolo completo',
  cardKicker: 'Account professionale',
  cardSince: 'Membro da {month} · rif. {ref}',
  cardActive: 'Attivo',
  cardDiscount: 'Sconto pro',
  cardTerm: 'Fine mese',
  cardCap: 'Massimale',
  summaryHead: 'Il fascicolo',
  summaryNote: 'Una sola pagina: il sommario fa scorrere, non cambia schermata.',
  edit: 'Modificare',
  sections: {
    identity: 'Identità legale',
    users: 'Utenti',
    kbis: 'Visura',
    addresses: 'Indirizzi',
    payment: 'Pagamento',
    preferences: 'Preferenze',
    data: 'I miei dati',
  },
  identityBrand: 'Insegna',
  identityCompany: 'Ragione sociale',
  identityForm: 'Forma giuridica',
  identitySiret: 'SIRET',
  identityVat: 'Partita IVA intracom.',
  identityNote:
    'L’insegna si cambia qui. Le menzioni del registro passano da noi: verifichiamo, poi aggiorniamo — sono quelle che figurano sulle vostre fatture.',
  usersHolder: 'Titolare dell’account · voi',
  usersAllRights: 'Tutti i diritti',
  usersAdd: 'Aggiungere un utente o un contatto',
  usersNote:
    'Un contatto può esistere senza spazio: un nome e un’e-mail bastano per ricevere le fatture. L’invito, invece, si decide caso per caso.',
  tagActive: 'Spazio attivo',
  tagInvited: 'Invito inviato',
  tagContact: 'Solo contatto',
  kbisHead: 'La visura camerale',
  kbisVerified: 'Verificata il {date} da {who}',
  kbisUpToDate: 'Aggiornata',
  kbisFiled: 'Depositata il {date} · {size}',
  kbisOpen: 'Aprire',
  kbisReplace: 'Sostituire',
  kbisFreshness: 'Freschezza della visura',
  kbisGauge: '1 mese su 3',
  kbisNote:
    'Una visura di meno di tre mesi è richiesta all’apertura di un credito, mai all’iscrizione. Questa resta valida fino al 12/05 — vi avviseremo prima.',
  billingHead: 'Fatturazione',
  billingNote:
    'Un solo indirizzo di fatturazione: è quello che figura sulle fatture e sul mandato.',
  deliveryHead: 'Consegna',
  deliveryCount: '{n} indirizzi',
  addressDefault: 'Predefinito',
  addressAdd: 'Aggiungere un indirizzo',
  termMonthly: 'Pagamento a 30 giorni fine mese',
  termMonthlySub: 'Concesso il 14/02/2024 · massimale 2 000 €',
  termOrder: 'All’ordine',
  termOrderSub: 'Carta o Apple Pay, senza aspettare la fattura',
  stateActive: 'Attivo',
  stateAvailable: 'Disponibile',
  sepaHead: 'Addebito SEPA',
  cardHead: 'Carta registrata',
  change: 'Cambiare',
  paymentNote:
    'Due regimi, non di più: fine mese quando un credito è concesso, all’ordine altrimenti — e tutti possono ordinare all’ordine.',
  prefPickup: 'Ritiro abituale',
  prefLang: 'Lingua',
  prefNotify: 'Che cosa mi avvisa',
  prefDeliveries: 'Consegne e ritiri',
  prefInvoices: 'Fatture e scadenze',
  prefEvents: 'Operazioni Pasqua e Natale',
  prefNote:
    'Un’operazione a data avvisa una volta per stagione. Consegne e fatture, invece, sono attive di default.',
  dataExportOrders: 'Esportare i miei ordini e le mie fatture',
  dataExportOrdersSub: 'CSV e PDF, per esercizio',
  dataExportPersonal: 'Scaricare i miei dati personali',
  dataExportPersonalSub: 'Tutto quello che abbiamo, in un file',
  dataKeep:
    'Le vostre fatture restano disponibili dieci anni dopo la chiusura — è un obbligo, non una scelta.',
  dangerHead: 'Zona sensibile',
  transferHead: 'Trasferire l’azienda',
  transferBody:
    'Cedete il ruolo di titolare a un utente dello spazio. Riprende la fatturazione, le condizioni di pagamento e il diritto di invitare. Voi mantenete il vostro accesso, senza l’amministrazione.',
  transferCta: 'Trasferire l’account',
  closeHead: 'Chiudere questo spazio',
  closeBody:
    'Definitivo, e proprio di questo spazio: accesso revocato per voi e per i vostri utenti, sconto e condizioni di pagamento persi, carrelli ricorrenti eliminati. Gli altri spazi non si muovono. Un ordine in corso va ritirato o annullato prima.',
  closeCta: 'Chiudere questo spazio',
  panelKicker: 'Utente',
  panelContact: 'Contatti',
  panelPhone: 'Telefono',
  panelRole: 'Funzione',
  panelCan: 'Che cosa può fare',
  canOrder: 'Ordinare',
  canInvoices: 'Vedere le fatture',
  canAdmin: 'Amministrare l’account',
  yes: 'Sì',
  no: 'No',
  noPhone: 'non indicato',
  spaceContactHead: 'Nessuno spazio',
  spaceContactBody:
    'Questo contatto esiste solo per ricevere le fatture per e-mail. Non ha password, non ha carrello e non vede nulla dell’applicazione.',
  spaceInvite: 'Invitare a creare il suo spazio',
  spaceInviteNote: 'L’invito parte per e-mail, senza password: un link, valido 14 giorni.',
  spaceInvitedHead: 'Invito inviato',
  spaceInvitedBody: 'Inviato il {date} · il link resta valido 14 giorni.',
  spaceResend: 'Sollecitare',
  spaceCancel: 'Annullare',
  spaceActiveHead: 'Spazio attivo',
  spaceActiveBody: 'Attivo dal {date} · accesso con link e-mail, senza password.',
  spaceRevoke: 'Togliere l’accesso',
  spaceSelf: 'Il vostro accesso non si toglie da qui: trasmettete prima il ruolo di titolare.',
};
