import { isJournalFactType, JOURNAL_FACT_TYPES } from '@lfd/contracts/journal-facts';
import { describe, expect, it } from 'vitest';

import { PHRASES } from '../phrases/phrase-registry';

/**
 * **Les types sans phrase — une liste qui ne peut que décroître** (plan des
 * phrases du journal, lot C, 2026-09-19).
 *
 * Le registre est un `Partial` pendant le lot C ; le lot D écrit les phrases
 * famille par famille et le passe en `Record` complet, ce qui rendra ce test
 * inutile — on le supprimera alors avec cette liste vide.
 *
 * D'ici là, la liste est FIGÉE : un type ajouté au catalogue sans phrase la
 * fait échouer (il faut l'écrire, ou l'inscrire ici en connaissance de cause),
 * et une phrase écrite sans retirer son type d'ici aussi — la liste reste le
 * relevé exact de ce qui manque.
 */
const WITHOUT_PHRASE: readonly string[] = [
  'product.created',
  'product.identity_saved',
  'product.reclassified',
  'product.pricing_saved',
  'product.declaration_saved',
  'product.editorial_saved',
  'product.media_saved',
  'product.channels_changed',
  'product.vat_changed',
  'product.declared_ready',
  'product.archived',
  'product.restored',
  'product.ingredients_saved',
  'variant.added',
  'variant.aligned',
  'variant.renamed',
  'variant.regulatory_aligned',
  'product_category.created',
  'product_category.renamed',
  'product_category.moved',
  'product_category.archived',
  'product_category.reordered',
  'product_category.channels_changed',
  'product_category.editorial_saved',
  'product_category.media_saved',
  'catalog_revision.taken',
  'catalog_revision.named',
  'catalog_revision.pushed',
  'accounting_rules.method_changed',
  'accounting_rules.pro_ratio_changed',
  'point_of_sale.created',
  'point_of_sale.updated',
  'point_of_sale.deleted',
  'point_of_sale.table_qr_generated',
  'point_of_sale.table_qr_removed',
  'sales_context.created',
  'sales_context.updated',
  'sales_context.deleted',
  'appellation.created',
  'appellation.updated',
  'appellation.deleted',
  'ingredient.created',
  'ingredient.updated',
  'ingredient.deleted',
  'ingredient.allergens_saved',
  'allergen_category.created',
  'allergen_category.renamed',
  'allergen_category.reordered',
  'allergen_category.archived',
  'allergen_category.restored',
  'allergen_entry.created',
  'allergen_entry.updated',
  'allergen_entry.archived',
  'allergen_entry.restored',
  'order_time_limit.set',
  'order_time_limit.removed',
  'catalog_item.b2b_price_set',
  'catalog_item.b2b_price_cleared',
  'catalog_item.hidden',
  'catalog_item.shown',
  'catalog_item.featured',
  'catalog_item.unfeatured',
  'catalog_delivery.accepted',
  'lead.captured',
  'lead.stage_changed',
  'lead.converted',
  'lead.lost',
  'appointment.requested',
  'appointment.confirmed',
  'appointment.cancelled',
  'appointment.honored',
  'appointment.no_show',
  'reco.shown',
  'company.declared',
  'company.step_reached',
  'company.activated',
  'company.kbis_certified',
  'company.kbis_revoked',
  'company.kbis_uploaded',
  'company.kbis_uploaded_by_staff',
  'company.identity_corrected',
  'company.identity_edited',
  'company.payment_terms_granted',
  'company.payment_term_requested',
  'company.status_changed',
  'company.billing_address_saved',
  'company.delivery_address_added',
  'company.delivery_address_updated',
  'company.delivery_address_removed',
  'company.default_delivery_set',
  'company.delivery_procedure_edited',
  'company.delivery_procedure_edited_by_staff',
  'company.fulfillment_preference_set',
  'company.contact_added',
  'company.contact_updated',
  'company.contact_removed',
  'company.primary_contact_changed',
  'company.access_opened',
  'company.bank_account_changed',
  'user.registered',
  'user.profile_updated',
  'user.password_link_issued',
  'subscription.created',
  'subscription.status_changed',
  'subscription.occurrence_overridden',
  'subscription.deleted',
  'support.requested',
  'support.handled',
  'feature_access.override_set',
  'feature_access.override_cleared',
  'feature_access.exemption_added',
  'feature_access.exemption_removed',
  'order.handed_over',
  'order_cutoff_waiver.granted',
  'order_cutoff_waiver.revoked',
  'order_late_fee.set',
  'order_late_fee.cleared',
  'production_day.closed',
  'production_day.retaken',
  'production_container.set',
  'production_container.removed',
  'company_mercuriale.posed',
  'company_mercuriale.archived',
  'company_mercuriale.renamed',
  'legal_entity.declared',
  'legal_entity.corrected',
  'legal_entity.creditor_identifier_assigned',
  'legal_entity.creditor_account_changed',
  'legal_entity.pre_notification_changed',
  'legal_entity.mandate_scheme_changed',
  'legal_entity.archived',
  'legal_entity.restored',
  'payment_mandate.minted',
  'payment_mandate.proof_attached',
  'payment_mandate.signed',
  'payment_mandate.sent',
  'payment_mandate.revoked',
  'payment_mandate.draft_voided',
  'payment_mandate.options_changed',
  'payment_mandate.proof_purged',
];

describe('le registre des phrases (lot C)', () => {
  it('ne laisse sans phrase que les types de la liste figée — ni plus, ni moins', () => {
    const without = JOURNAL_FACT_TYPES.filter((type) => PHRASES[type] === undefined);

    expect([...without].sort()).toEqual([...WITHOUT_PHRASE].sort());
  });

  it('ne donne de phrase qu’à des types du catalogue', () => {
    const unknown = Object.keys(PHRASES).filter((type) => !isJournalFactType(type));

    expect(unknown).toEqual([]);
  });
});
