import type { ClientCopy } from './client-copy.model';

/**
 * Anglais. Val d'Isère reçoit autant de britanniques que d'italiens ; laisser
 * `EN` cliquable et muet aurait été pire que de ne pas l'offrir.
 *
 * « Fournil » devient *bakery* (le lieu), « coursier » *courier* — pas *driver*,
 * qui laisserait croire à une plateforme de livraison.
 */
export const EN: ClientCopy = {
  chrome: {
    back: 'Back',
    menu: 'Menu',
    notifications: 'Notifications',
    lang: 'Language',
    kickerWelcome: 'Welcome',
    kickerRappel: 'Call back',
    kickerCommande: 'New order',
    kickerShop: 'Shop',
    kickerCart: 'The basket',
    kickerDone: 'Confirmed',
    deskKicker: 'Val d’Isère · order online',
  },
  foot: {
    tagline: 'Mountain bakery',
    pitch:
      'Sourdough bread, AOP-butter viennoiserie and resort pastry, baked every night at Le Labo, route de la Balme. Delivered around the resort before the lifts open.',
    housesHead: 'The bakeries',
    houses: [
      {
        name: 'Le Labo',
        street: 'Route de la Balme',
        city: '73150 Val d’Isère',
        hours: '7 am – 7 pm, every day',
      },
      {
        name: 'Le Village',
        street: '4 avenue Olympique',
        city: '73150 Val d’Isère',
        hours: '9 am – 8 pm, every day',
      },
    ],
    orderHead: 'Order',
    orderLinks: [
      'Pickup at Le Labo or Le Village',
      'Courier around the resort',
      'Catering and events',
      'Open a trade account',
      'Our counters and our methods',
      'Easter and Christmas operations',
    ],
    helpHead: 'Help and contact',
    phoneHours: '7 am – 7 pm · additions until 6 pm',
    helpLinks: ['Book an appointment', 'Track my order', 'Frequent questions', 'Report a problem'],
    legalPay: 'Secure card and Apple Pay payment, bank transfer for trade accounts.',
    legalVat: 'Prices include VAT, at 5.5% or 10% depending on the product.',
    legalLinks: ['Legal notice', 'Terms', 'Privacy', 'Cookies', 'Accessibility'],
  },
  nav: {
    destinations: {
      shop: 'The shop',
      cart: 'My basket',
      orders: 'My orders',
      invoices: 'My invoices',
      account: 'My account',
    },
    invoicesDue: '{n} to settle',
    soon: 'Soon',
    close: 'Close the menu',
    newOrder: 'New order',
    newOrderSub: 'Pickup or courier, you choose',
    house: 'The bakery',
    houseLinks: [
      ['Our counters and our methods', '6 notes'],
      ['Le Labo — hours and access', 'Open'],
      ['Something urgent to add?', 'Call us'],
    ],
    logout: 'Sign out',
    address: 'Le Labo · route de la Balme, Val d’Isère — 7 am – 7 pm',
    hello: 'Hello {name}.',
    helloAnonymous: 'Hello.',
  },
  espace: {
    today: ['One thing today.', 'Two things today.', 'Three things today.'],
    todayNone: 'Nothing is waiting.',
    lead: 'What needs doing, and nothing else.',
    leadNone: 'All settled. Whenever you want to start again.',
    wellTitle: 'Ready for you',
    wellNote: '— what needs an action, and nothing else.',
    pickupTitle: 'Collect my order',
    pickupRef: 'Order {ref}',
    pickupWhen: 'Ready {at}, from {slot}',
    pickupAction: 'My QR',
    cartTitle: 'Basket waiting',
    cartBadge: 'Before 6 pm',
    cartWhen: 'Started last night',
    cartAction: 'Finish',
    invoiceTitle: 'March invoice',
    invoiceDue: 'Due 15 April',
    invoiceAction: 'Settle',
    contactKicker: 'We answer',
    contactTitle: 'A question,\nsomething unexpected?',
    contactWho:
      'Camille and Malik, at Le Labo, 7 am to 7 pm. A late addition still goes through by phone until 6 pm.',
    call: 'Call',
    write: 'Write',
    habitsHead: 'Your habits',
    proHead: 'Your trade account',
    proDiscount: 'Pickup discount at Le Labo',
    proMonth: 'Outstanding this month',
    proKbis: 'KBIS verification',
    proKbisState: 'In progress',
  },
  hero: {
    welcomeTitle: 'Your resort order, ready in two minutes.',
    welcomeIntro: 'You choose, we prepare.',
    rappelTitle: 'When shall we call ?',
    rappelIntro: 'We call from the bakery, never from a call centre.',
  },
  aside: {
    proof: [
      'Quick sign-up.',
      'Your account grows with what you need.',
      'Trade prices, resort delivery, monthly invoicing on request.',
    ],
    address: 'Le Labo · Route de la Balme — open 7am to 7pm.',
  },
  signup: {
    eyebrow: 'First time ? 3 details and you’re in',
    alreadyLead: 'Already a customer ?',
    alreadyLink: 'Sign in',
    pitch: 'A first name, an email, a number. That’s all — the rest can wait until you need it.',
    firstName: 'First name',
    firstNamePlaceholder: 'Your first name',
    tel: 'Phone',
    telPlaceholder: '06 00 00 00 00',
    telHint: 'So a courier looking for your door can call you.',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    open: 'Sign up',
    submit: 'Create my account',
    fine: 'A password to open the door, then your device recognises you.',
    fineInline: 'A password to open the door, then your device recognises you.',
    legal:
      'By creating an account you accept our terms of sale. No company paperwork is required to sign up.',
  },
  rappel: {
    asapGroup: 'As soon as possible',
    asapTitle: 'Within 15 minutes',
    asapSub: 'The bakery picks up — that’s the fastest.',
    todayGroup: 'Today',
    note: 'Between noon and 2pm we’re at the oven : we don’t take calls, and we’d rather say so.',
    phone: 'We’ll call you on {phone}.',
    phoneUnknown: 'We call the number on your account.',
    ctaIdle: 'Pick a time',
    ctaReady: 'Request the call',
    slotFree: 'available',
    slotFull: 'full',
    slotOven: 'at the oven',
  },
  doors: {
    or: 'or',
    alreadyTitle: 'Already a customer ?',
    alreadySub: 'Password, or your device',
    firstTitle: 'First time ?',
    firstSub: 'First name, email, phone',
  },
  event: {
    badge: 'Catering',
    title: 'An event,\nwe handle it all.',
    pitch: 'Seminar, birthday, club outing : the headcount, the time, the place — we do the rest.',
    cta: 'Get a quote ›',
    pending:
      'The quote request screen lands in the next batch — the card is wired, its sequel isn’t.',
  },
  commande: {
    title: 'Hello {name}.\nHow shall we serve you ?',
    titleAnonymous: 'Hello.\nHow can we serve you?',
    intro: 'You choose, we bake.',
    sectionsLabel: 'Sections',
    newOrderTitle: 'New order',
    newOrderSub: 'One question to start with : do you come, or do we ?',
    nowTitle: 'Right now',
    pickupBadge: 'Pickup',
    pickupTitle: 'I’ll come\nand get it',
    pickupDetail: 'At the Labo, or any of our resort shops.',
    pickupNote: 'Tomorrow from 6 am',
    pickupDetailWide: 'At the Labo or in the village, tomorrow at the hour I pick.',
    pickupCta: 'Choose a pickup point',
    pickupNoteWide: 'Up to −10 %',
    deliveryBadge: 'Courier',
    deliveryTitle: 'We bring it\nto you',
    deliveryDetail: 'Tomorrow, in the time slot you pick.',
    deliveryNote: 'Order before 6 pm',
    deliveryDetailWide: 'Tomorrow, in the slot you pick. Two addresses already saved.',
    deliveryCta: 'Choose an address',
    deliveryNoteWide: 'Before 6 pm',
    eventBadge: 'Christmas',
    eventTitle: 'Christmas is made\nat the bakehouse',
    eventDetail: 'Two yule logs, a calendar, the papillotes.',
    eventNote: '72 h notice · D-18',
    cateringBadge: 'Catering',
    cateringTitle: 'An event,\nwe handle it all',
    cateringDetail: 'Seminar, birthday, club outing.',
    cateringNote: 'Answer within 24 h',
    browseTitle: 'Show me the shop',
    browseSub: 'Browse the counter and decide afterwards',
    againTitle: 'Same as last Saturday ?',
    againSub: '2 traditions, 4 croissants, 1 praline ski · pickup at the Labo',
    againAction: 'Reorder',
    againLead: 'Or start again from',
    urgenceTitle: 'Something urgent, something extra ?',
    urgencePitch:
      'A forgotten item on a running order, one more batch : the phone sorts it out. We rarely say no.',
    urgenceCta: 'Call me back',
    pending:
      'The rest of the journey lands in the next batch — the card is wired, its screen is not.',
  },
  shop: {
    changeService: 'Change',
    pickService: 'Where are you served?',
    pickServiceHint: 'Price and time depend on it — say so before paying.',
    searchPlaceholder: 'Look for a baguette, an éclair…',
    clearSearch: 'Clear the search',
    allShelves: 'Everything',
    allShelvesTitle: 'The whole counter',
    resultsFor: 'Results for “{query}”',
    pieces: '{count} items',
    learnMore: 'Find out more',
    emptyTitle: 'Nothing under that name.',
    emptyHint: 'Try “bread”, “tart”, or tap a shelf.',
    shelvesGroup: 'The shelves',
    add: 'Add',
    addAria: 'Add {name}',
    removeAria: 'Remove {name}',
    cartBar: '{count} items in the basket',
    cartTitle: 'Your basket',
    cartEmpty:
      'Empty basket. The morning batch goes fast — the praline ski never sees the afternoon.',
    upsell: '{name} with that?',
    upsellLine: 'The treat you regret leaving behind.',
  },
  product: {
    signature: 'Signature',
    unitPrice: 'Unit price',
    oven: 'Out of the oven',
    pickupAt: 'Collect at',
    deliverTo: 'Delivered',
    cta: 'Add · {price}',
  },
  cart: {
    kicker: 'The basket',
    title: 'Your order',
    intro: 'Read it over, adjust, pay. The batch follows your slot.',
    pickupGroup: 'To collect',
    deliveryGroup: 'To deliver',
    slotNote: 'tomorrow · chosen slot',
    subtotal: 'Subtotal',
    discount: 'Collection discount {at} −{pct} %',
    fee: 'Courier',
    vat: 'incl. VAT {rate}',
    vatSweet: 'bread, pastry, cakes',
    vatSale: 'savoury, catering',
    total: 'Total',
    pay: 'Pay for my order · {total}',
    payHint: 'Paid online. You show your QR at the counter, nothing to settle there.',
    browse: 'See the counter',
    back: 'Back to the shop',
  },
  done: {
    kicker: 'Confirmed',
    title: 'All paid.\nWe start at 4.15 am.',
    intro: 'Your order joins tomorrow morning’s batch.',
    mailTitle: 'Receipt sent by e-mail',
    mailLine: 'To {email} — the invoice and the collection QR are inside.',
    mailLineNoAddress: 'To your account address — the invoice and the collection QR are inside.',
    recapPickup: 'Collection',
    recapDelivery: 'Delivery',
    recapContent: 'Contents',
    recapPieces: '{count} items',
    paidOnline: 'Paid online',
    qr: 'Show my collection QR',
    edit: 'Change',
    cancel: 'Cancel',
    deadline: 'Changeable until 10 pm — refunded at once. After that, the dough is kneaded.',
    pending: 'That screen lands in the next batch.',
  },
  dialog: {
    close: 'Close',
  },
  pickupDialog: {
    kicker: 'Pickup',
    title: 'Where are you coming ?',
    lead: 'We like having you over : collect at the Labo and get {pct} % off your order.',
    habit: 'your usual',
    readyFrom: 'Ready from {time}',
    discountTag: '−{pct} % on everything',
    shopPrice: 'Shop price',
    cta: 'Pick my time',
    ctaDiscount: 'Pick my time · −{pct} %',
  },
  addressDialog: {
    kicker: 'Courier',
    title: 'Where do we deliver ?',
    bookGroup: 'Your addresses',
    defaultTag: 'Default',
    otherGroup: 'Another address',
    street: 'Street',
    streetPlaceholder: '12 rue du Coin Ferrand',
    postcode: 'Postcode',
    postcodePlaceholder: '73150',
    city: 'Town',
    cityUnknown: 'Derived from the postcode',
    outOfZone: 'Outside the delivery area',
    outOfZoneNote: 'We don’t ride down that far yet. Pickup is still open to you.',
    whoGroup: 'Who receives it',
    name: 'Name',
    fromAccount: 'Account',
    phone: 'Phone',
    edit: 'Edit',
    whyPhone: 'Prefilled from your account — the courier calls this number if the door hides.',
    saveToBook: 'Save this address to my book',
    saveOn: 'We’ll have it ready next time.',
    saveOff: 'Otherwise it only serves this order.',
    cta: 'Pick my slot · €{fee}',
    ctaBlocked: 'Choose an address',
  },
  slotStep: {
    pickupIntro: 'To collect {place}. The slot keeps the batch for you.',
    deliveryIntro: 'Delivered {place}. The courier leaves as the slot opens.',
    amGroup: 'Morning · out of the oven',
    pmGroup: 'Après-ski · second batch',
    firstBatch: 'out of the oven',
    free: 'available',
    full: 'full',
    secondBatch: 'second batch',
    laboOnly: 'Labo only',
    ctaIdle: 'Pick a slot',
    cta: 'Fill my basket',
  },
  pro: {
    title: 'Interested in a trade account ?',
    bookedTitle: 'Call requested',
    pitch: 'Negotiated prices, resort delivery, monthly invoicing. We’ll explain in two minutes.',
    cta: 'Ask us to call you',
    booked: 'Call requested · {slot}',
    at: 'On',
    cancel: 'Cancel',
  },
};
