import type { ClientCopy } from './client-copy.model';

/** La langue de référence : c'est elle que la maquette écrit. */
export const FR: ClientCopy = {
  chrome: {
    back: 'Retour',
    menu: 'Menu',
    notifications: 'Notifications',
    lang: 'Langue',
    kickerWelcome: 'Bienvenue',
    kickerRappel: 'Rappel',
    kickerCommande: 'Nouvelle commande',
    kickerShop: 'Boutique',
    kickerCart: 'Le panier',
    kickerDone: 'Confirmée',
    deskKicker: 'Val d’Isère · commande en ligne',
  },
  foot: {
    place: 'Le Labo · Route de la Balme, Val d’Isère',
    hours: 'Ouvert de 7 h à 19 h',
  },
  nav: {
    destinations: {
      shop: 'La boutique',
      cart: 'Mon panier',
      orders: 'Mes commandes',
      invoices: 'Mes factures',
      account: 'Mon compte',
    },
    invoicesDue: '{n} à régler',
    soon: 'Bientôt',
    close: 'Fermer le menu',
    newOrder: 'Nouvelle commande',
    newOrderSub: 'Retrait ou coursier · en deux touches',
    house: 'La maison',
    houseLinks: [
      ['Nos rayons et nos méthodes', '6 fiches'],
      ['Le Labo — horaires et accès', 'Ouvert'],
      ['Une urgence, un ajout ?', 'Nous appeler'],
    ],
    logout: 'Se déconnecter',
    address: 'Le Labo · route de la Balme, Val d’Isère — 7 h – 19 h',
    hello: 'Bonjour {name}.',
    helloAnonymous: 'Bonjour.',
  },
  hero: {
    welcomeTitle: 'Votre commande en station, réservée en deux minutes.',
    welcomeIntro: 'Vous choisissez, nous préparons.',
    rappelTitle: 'On vous rappelle quand ?',
    rappelIntro: 'On appelle depuis le fournil, jamais depuis un centre.',
  },
  aside: {
    proof: [
      'Inscription rapide.',
      'Votre espace évolue en fonction de vos besoins.',
      'Tarifs pro, livraison en station, facturation mensuelle sur demande.',
    ],
    address: 'Le Labo · Route de la Balme — ouvert de 7 h à 19 h.',
  },
  signup: {
    eyebrow: 'Première visite ? 3 infos et c’est parti',
    alreadyLead: 'Déjà client ?',
    alreadyLink: 'Se connecter',
    pitch:
      'Un prénom, un e-mail, un numéro. C’est tout — le reste attendra que vous en ayez besoin.',
    firstName: 'Prénom',
    firstNamePlaceholder: 'Votre prénom',
    tel: 'Téléphone',
    telPlaceholder: '06 00 00 00 00',
    telHint: 'Pour qu’un coursier qui cherche la porte puisse appeler.',
    email: 'E-mail',
    emailPlaceholder: 'vous@exemple.fr',
    open: 'S’inscrire',
    submit: 'Créer mon compte',
    fine: 'Un mot de passe pour ouvrir, puis votre appareil vous reconnaît.',
    fineInline: 'Un mot de passe pour ouvrir, puis votre appareil vous reconnaît.',
    legal:
      'En créant un compte, vous acceptez nos conditions de vente. Aucun document d’entreprise n’est demandé à l’inscription.',
  },
  rappel: {
    asapGroup: 'Dès que possible',
    asapTitle: 'Dans les 15 minutes',
    asapSub: 'Le fournil décroche — c’est le plus rapide.',
    todayGroup: 'Aujourd’hui',
    note: 'Entre 12 h et 14 h on est au four : on ne prend pas d’appel, et on préfère le dire.',
    phone: 'On vous rappellera au {phone}.',
    phoneUnknown: 'On vous rappelle au numéro de votre compte.',
    ctaIdle: 'Choisissez un moment',
    ctaReady: 'Demander le rappel',
    slotFree: 'disponible',
    slotFull: 'complet',
    slotOven: 'au four',
  },
  doors: {
    or: 'ou',
    alreadyTitle: 'Déjà client ?',
    alreadySub: 'Mot de passe, ou votre appareil',
    firstTitle: 'Première visite ?',
    firstSub: 'Prénom, e-mail, téléphone',
  },
  event: {
    badge: 'Traiteur',
    title: 'Un event,\non prépare tout.',
    pitch:
      'Séminaire, anniversaire, sortie de club : le nombre, l’heure, le lieu — on s’occupe du reste.',
    cta: 'Un devis ›',
    pending:
      'L’écran de demande de devis arrive au prochain lot — la carte est branchée, pas sa suite.',
  },
  commande: {
    title: 'Bonjour {name}.\nOn vous sert comment ?',
    titleAnonymous: 'Bonjour.\nOn vous sert comment ?',
    intro: 'Vous choisissez, nous préparons.',
    sectionsLabel: 'Sections',
    newOrderTitle: 'Nouvelle commande',
    newOrderSub: 'Une seule question pour démarrer : vous venez, ou on vient ?',
    nowTitle: 'En ce moment',
    pickupBadge: 'Retrait',
    pickupTitle: 'Je passe\nle prendre',
    pickupDetail: 'Au Labo ou dans une boutique de station.',
    pickupNote: 'Demain à partir de 6 h',
    pickupDetailWide: 'Au Labo ou au village, demain à l’heure de mon choix.',
    pickupCta: 'Choisir un point de retrait',
    pickupNoteWide: 'Jusqu’à −10 %',
    deliveryBadge: 'Coursier',
    deliveryTitle: 'On vous\nl’apporte',
    deliveryDetail: 'Demain, au créneau que vous choisissez.',
    deliveryNote: 'Commandez avant 18 h',
    deliveryDetailWide: 'Demain, au créneau que vous choisissez. Deux adresses déjà enregistrées.',
    deliveryCta: 'Choisir une adresse',
    deliveryNoteWide: 'Avant 18 h',
    eventBadge: 'Noël',
    eventTitle: 'Noël se joue\nau fournil',
    eventDetail: 'Deux bûches, un calendrier, les papillotes.',
    eventNote: '72 h de délai · J-18',
    cateringBadge: 'Traiteur',
    cateringTitle: 'Un event,\non prépare tout',
    cateringDetail: 'Séminaire, anniversaire, sortie de club.',
    cateringNote: 'Réponse sous 24 h',
    browseTitle: 'Je visite la boutique',
    browseSub: 'Pour voir les produits et décider ensuite',
    againTitle: 'Comme samedi dernier ?',
    againSub: '2 traditions, 4 croissants, 1 ski praliné · retrait au Labo',
    againAction: 'Refaire',
    againLead: 'Ou reprenez',
    urgenceTitle: 'Une urgence, un ajout ?',
    urgencePitch:
      'Un oubli sur une commande en cours, une fournée à rallonger : ça se règle au téléphone. On dit rarement non.',
    urgenceCta: 'Être rappelé',
    pending:
      'La suite du parcours arrive au prochain lot — la carte est branchée, pas encore son écran.',
  },
  shop: {
    changeService: 'Changer',
    pickService: 'Où êtes-vous servi ?',
    pickServiceHint: 'Le prix et l’heure en dépendent — dites-le avant de régler.',
    searchPlaceholder: 'Chercher une baguette, un éclair…',
    clearSearch: 'Effacer la recherche',
    allShelves: 'Tout',
    allShelvesTitle: 'Tout le rayon',
    resultsFor: 'Résultats pour « {query} »',
    pieces: '{count} pièces',
    learnMore: 'En savoir plus',
    emptyTitle: 'Rien sous ce nom.',
    emptyHint: 'Essayez « pain », « tarte », ou touchez un rayon.',
    shelvesGroup: 'Les rayons',
    add: 'Ajouter',
    addAria: 'Ajouter {name}',
    removeAria: 'Retirer {name}',
    cartBar: '{count} pièces au panier',
    cartTitle: 'Votre panier',
    cartEmpty:
      'Panier vide. La fournée du matin part vite — le ski praliné ne fait jamais l’après-midi.',
    upsell: '{name} avec ça ?',
    upsellLine: 'La gourmandise qu’on regrette de ne pas avoir prise.',
  },
  product: {
    signature: 'Signature',
    unitPrice: 'Prix unitaire',
    oven: 'Sortie du four',
    pickupAt: 'À retirer',
    deliverTo: 'Livré',
    cta: 'Au panier · {price}',
  },
  cart: {
    kicker: 'Le panier',
    title: 'Votre commande',
    intro: 'Relisez, ajustez, réglez. La fournée se cale sur votre créneau.',
    pickupGroup: 'À retirer',
    deliveryGroup: 'À livrer',
    slotNote: 'demain · créneau choisi',
    subtotal: 'Sous-total',
    discount: 'Remise retrait {at} −{pct} %',
    fee: 'Coursier',
    vat: 'dont TVA {rate}',
    vatSweet: 'pain, viennoiserie, pâtisserie',
    vatSale: 'salé, traiteur',
    total: 'Total',
    pay: 'Régler ma commande · {total}',
    payHint: 'Paiement en ligne. Vous présentez votre QR au comptoir, rien à régler sur place.',
    browse: 'Voir le rayon',
    back: 'Retour à la boutique',
  },
  done: {
    kicker: 'Confirmée',
    title: 'C’est réglé.\nOn s’y met à 4 h 15.',
    intro: 'Votre commande entre dans la fournée de demain matin.',
    mailTitle: 'Reçu envoyé par e-mail',
    mailLine: 'À {email} — la facture et le QR de retrait sont dedans.',
    mailLineNoAddress: 'À l’adresse de votre compte — la facture et le QR de retrait sont dedans.',
    recapPickup: 'Retrait',
    recapDelivery: 'Livraison',
    recapContent: 'Contenu',
    recapPieces: '{count} pièces',
    paidOnline: 'Réglé en ligne',
    qr: 'Voir mon QR de retrait',
    edit: 'Modifier',
    cancel: 'Annuler',
    deadline: 'Modifiable jusqu’à 22 h — remboursement immédiat. Après, la pâte est pétrie.',
    pending: 'Cet écran arrive au prochain lot.',
  },
  dialog: {
    close: 'Fermer',
  },
  pickupDialog: {
    kicker: 'Retrait',
    title: 'Vous venez où ?',
    lead: 'On aime vous recevoir : retirez au Labo et profitez d’une remise de {pct} % sur votre commande.',
    habit: 'votre habitude',
    readyFrom: 'Prêt dès {time}',
    discountTag: '−{pct} % sur tout',
    shopPrice: 'Prix boutique',
    cta: 'Choisir mon heure',
    ctaDiscount: 'Choisir mon heure · −{pct} %',
  },
  addressDialog: {
    kicker: 'Coursier',
    title: 'On livre où ?',
    bookGroup: 'Vos adresses',
    defaultTag: 'Par défaut',
    otherGroup: 'Une autre adresse',
    street: 'Rue',
    streetPlaceholder: '12 rue du Coin Ferrand',
    postcode: 'Code postal',
    postcodePlaceholder: '73150',
    city: 'Ville',
    cityUnknown: 'Se déduit du code postal',
    outOfZone: 'Hors zone de livraison',
    outOfZoneNote: 'On ne descend pas encore jusque-là. Le retrait, lui, reste ouvert.',
    whoGroup: 'Qui reçoit',
    name: 'Nom',
    fromAccount: 'Compte',
    phone: 'Téléphone',
    edit: 'Modifier',
    whyPhone:
      'Prérempli depuis votre compte — le coursier appelle ce numéro s’il ne trouve pas la porte.',
    saveToBook: 'Enregistrer cette adresse au carnet',
    saveOn: 'On la retrouvera à la prochaine commande.',
    saveOff: 'Sinon, elle ne sert que pour cette commande.',
    cta: 'Choisir mon créneau · {fee} €',
    ctaBlocked: 'Choisissez une adresse',
  },
  slotStep: {
    pickupIntro: 'À retirer {place}. Le créneau vous garde la fournée.',
    deliveryIntro: 'Livré {place}. Le coursier part à l’ouverture du créneau.',
    amGroup: 'Matin · sortie de fournée',
    pmGroup: 'Après-ski · seconde fournée',
    firstBatch: 'sortie du four',
    free: 'disponible',
    full: 'complet',
    secondBatch: 'seconde fournée',
    laboOnly: 'Labo seulement',
    ctaIdle: 'Choisissez un créneau',
    cta: 'Remplir mon panier',
  },
  pro: {
    title: 'Intéressé par l’espace pro ?',
    bookedTitle: 'Rappel demandé',
    pitch:
      'Tarifs négociés, livraison en station, facturation mensuelle. On vous explique en deux minutes.',
    cta: 'Demander à être rappelé',
    booked: 'Rappel demandé · {slot}',
    at: 'Au',
    cancel: 'Annuler',
  },
};
