import type { ClientCopy } from './client-copy.model';

/** La langue de référence : c'est elle que la maquette écrit. */
export const FR: ClientCopy = {
  chrome: {
    back: 'Retour',
    menu: 'Menu',
    notifications: 'Notifications',
    lang: 'Langue',
    kickerWelcome: 'Bienvenue',
    kickerLogin: 'Connexion',
    kickerEntered: 'Compte créé',
    kickerRappel: 'Rappel',
    kickerCommande: 'Nouvelle commande',
    deskKicker: 'Val d’Isère · commande en ligne',
  },
  foot: {
    place: 'Le Labo · Route de la Balme, Val d’Isère',
    hours: 'Ouvert de 7 h à 19 h',
  },
  hero: {
    welcomeTitle: 'Votre commande en station, réservée en deux minutes.',
    welcomeIntro: 'Vous choisissez, nous préparons.',
    loginTitle: 'Content de vous revoir.',
    loginIntroAsk: 'Entrez votre e-mail, on vous envoie un lien.',
    loginIntroSent: 'Un lien de connexion vient de partir.',
    enteredTitle: 'Vous êtes connecté.',
    enteredIntro:
      'Compte créé sans mot de passe, sans formulaire d’entreprise. La commande commence maintenant.',
    rappelTitle: 'On vous rappelle quand ?',
    rappelIntro: 'On appelle depuis le fournil, jamais depuis un centre.',
  },
  aside: {
    proof: [
      'Inscription rapide.',
      'Votre espace évolue en fonction de vos besoins.',
      'Tarifs pro, livraison en station, facturation mensuelle sur demande.',
    ],
    address: 'Le Labo · Route de la Balme — ouvert de 7 h à 19 h.',
  },
  signup: {
    eyebrow: 'Première visite ? 3 infos et c’est parti',
    alreadyLead: 'Déjà client ?',
    alreadyLink: 'Se connecter en un lien',
    pitch:
      'Un prénom, un e-mail, un numéro. C’est tout — le reste attendra que vous en ayez besoin.',
    firstName: 'Prénom',
    firstNamePlaceholder: 'Votre prénom',
    tel: 'Téléphone',
    telPlaceholder: '06 00 00 00 00',
    telHint: 'Pour qu’un coursier qui cherche la porte puisse appeler.',
    email: 'E-mail',
    emailPlaceholder: 'vous@exemple.fr',
    open: 'S’inscrire',
    submit: 'Créer mon compte',
    fine: 'Pas de mot de passe : on vous envoie un lien à chaque connexion.',
    fineInline: 'Pas de mot de passe : un lien vous est envoyé à chaque connexion.',
    legal:
      'En créant un compte, vous acceptez nos conditions de vente. Aucun document d’entreprise n’est demandé à l’inscription.',
  },
  login: {
    email: 'Votre e-mail',
    emailPlaceholder: 'vous@exemple.fr',
    send: 'Recevoir mon lien',
    fine: 'Aucun mot de passe à retenir : le lien vous connecte directement.',
    sentTitle: 'Lien envoyé',
    sentBody: 'Ouvrez le message envoyé à {email} — le lien est valable une heure.',
    simulate: 'Simuler le clic sur le lien',
    resent: 'Un nouveau lien vient de partir.',
    resend: 'Renvoyer',
    editEmail: 'Changer d’adresse',
  },
  entered: {
    title: 'Compte actif',
    sub: 'Trois champs, aucun document. Le KBIS attendra que vous en ayez besoin.',
    next: 'La suite : retrait ou coursier, puis la boutique.',
    cta: 'Commander',
  },
  rappel: {
    asapGroup: 'Dès que possible',
    asapTitle: 'Dans les 15 minutes',
    asapSub: 'Le fournil décroche — c’est le plus rapide.',
    todayGroup: 'Aujourd’hui',
    note: 'Entre 12 h et 14 h on est au four : on ne prend pas d’appel, et on préfère le dire.',
    phone: 'On vous rappellera au {phone}.',
    ctaIdle: 'Choisissez un moment',
    ctaReady: 'Demander le rappel',
    slotFree: 'disponible',
    slotFull: 'complet',
    slotOven: 'au four',
  },
  doors: {
    or: 'ou',
    alreadyTitle: 'Déjà client ?',
    alreadySub: 'Se connecter en un lien',
    firstTitle: 'Première visite ?',
    firstSub: 'Prénom, e-mail, téléphone',
  },
  event: {
    badge: 'Traiteur',
    title: 'Un event,\non prépare tout.',
    pitch:
      'Séminaire, anniversaire, sortie de club : le nombre, l’heure, le lieu — on s’occupe du reste.',
    cta: 'Un devis ›',
    pending:
      'L’écran de demande de devis arrive au prochain lot — la carte est branchée, pas sa suite.',
  },
  commande: {
    title: 'Bonjour {name}.\nOn vous sert comment ?',
    intro: 'Vous choisissez, nous préparons.',
    sectionsLabel: 'Sections',
    newOrderTitle: 'Nouvelle commande',
    newOrderSub: 'Une seule question pour démarrer : vous venez, ou on vient ?',
    nowTitle: 'En ce moment',
    pickupBadge: 'Retrait',
    pickupTitle: 'Je passe\nle prendre',
    pickupDetail: 'Au Labo ou dans une boutique de station.',
    pickupNote: 'Prêt en 20 min',
    pickupDetailWide: 'Au Labo ou au village, demain à l’heure de mon choix.',
    pickupCta: 'Choisir un point de retrait',
    pickupNoteWide: 'Jusqu’à −10 %',
    deliveryBadge: 'Coursier',
    deliveryTitle: 'On vous\nl’apporte',
    deliveryDetail: 'Demain, au créneau que vous choisissez.',
    deliveryNote: 'Commandez avant 18 h',
    deliveryDetailWide: 'Demain, au créneau que vous choisissez. Deux adresses déjà enregistrées.',
    deliveryCta: 'Choisir une adresse',
    deliveryNoteWide: 'Avant 18 h',
    eventBadge: 'Noël',
    eventTitle: 'Noël se joue\nau fournil',
    eventDetail: 'Deux bûches, un calendrier, les papillotes.',
    eventNote: '72 h de délai · J-18',
    cateringBadge: 'Traiteur',
    cateringTitle: 'Un event,\non prépare tout',
    cateringDetail: 'Séminaire, anniversaire, sortie de club.',
    cateringNote: 'Réponse sous 24 h',
    browseTitle: 'Je visite la boutique',
    browseSub: 'Pour voir les produits et décider ensuite',
    againTitle: 'Comme samedi dernier ?',
    againSub: '2 traditions, 4 croissants, 1 ski praliné · retrait au Labo',
    againAction: 'Refaire',
    againLead: 'Ou reprenez',
    urgenceTitle: 'Une urgence, un ajout ?',
    urgencePitch:
      'Un oubli sur une commande en cours, une fournée à rallonger : ça se règle au téléphone. On dit rarement non.',
    urgenceCta: 'Être rappelé',
    pending:
      'La suite du parcours arrive au prochain lot — la carte est branchée, pas encore son écran.',
  },
  dialog: {
    close: 'Fermer',
  },
  pickupDialog: {
    kicker: 'Retrait',
    title: 'Vous venez où ?',
    lead: 'On aime vous recevoir : retirez au Labo et profitez d’une remise de {pct} % sur votre commande.',
    habit: 'votre habitude',
    readyFrom: 'Prêt dès {time}',
    discountTag: '−{pct} % sur tout',
    shopPrice: 'Prix boutique',
    cta: 'Choisir mon heure',
    ctaDiscount: 'Choisir mon heure · −{pct} %',
  },
  addressDialog: {
    kicker: 'Coursier',
    title: 'On livre où ?',
    bookGroup: 'Vos adresses',
    defaultTag: 'Par défaut',
    otherGroup: 'Une autre adresse',
    street: 'Rue',
    streetPlaceholder: '12 rue du Coin Ferrand',
    postcode: 'Code postal',
    postcodePlaceholder: '73150',
    city: 'Ville',
    cityUnknown: 'Se déduit du code postal',
    outOfZone: 'Hors zone de livraison',
    outOfZoneNote: 'On ne descend pas encore jusque-là. Le retrait, lui, reste ouvert.',
    whoGroup: 'Qui reçoit',
    name: 'Nom',
    fromAccount: 'Compte',
    phone: 'Téléphone',
    edit: 'Modifier',
    whyPhone:
      'Prérempli depuis votre compte — le coursier appelle ce numéro s’il ne trouve pas la porte.',
    saveToBook: 'Enregistrer cette adresse au carnet',
    saveOn: 'On la retrouvera à la prochaine commande.',
    saveOff: 'Sinon, elle ne sert que pour cette commande.',
    cta: 'Choisir mon créneau · {fee} €',
    ctaBlocked: 'Choisissez une adresse',
  },
  slotStep: {
    pickupIntro: 'À retirer {place}. Le créneau vous garde la fournée.',
    deliveryIntro: 'Livré {place}. Le coursier part à l’ouverture du créneau.',
    amGroup: 'Matin · sortie de fournée',
    pmGroup: 'Après-ski · seconde fournée',
    firstBatch: 'sortie du four',
    free: 'disponible',
    full: 'complet',
    secondBatch: 'seconde fournée',
    laboOnly: 'Labo seulement',
    ctaIdle: 'Choisissez un créneau',
    cta: 'Remplir mon panier',
  },
  pro: {
    title: 'Intéressé par l’espace pro ?',
    bookedTitle: 'Rappel demandé',
    pitch:
      'Tarifs négociés, livraison en station, facturation mensuelle. On vous explique en deux minutes.',
    cta: 'Demander à être rappelé',
    booked: 'Rappel demandé · {slot}',
    at: 'Au',
    cancel: 'Annuler',
  },
};
