import type { ClientCopy } from './client-copy.model';

/**
 * Italien. Val d'Isère est frontalière : la clientèle italienne n'est pas un
 * public de passage, c'est un public de saison.
 *
 * Deux partis pris de traduction : « fournil » devient *laboratorio* (le lieu,
 * pas le métier — c'est ainsi que la boutique se nomme, « Le Labo »), et
 * « coursier » devient *corriere*, qui dit la livraison en station sans laisser
 * croire à une messagerie.
 */
export const IT: ClientCopy = {
  chrome: {
    back: 'Indietro',
    menu: 'Menu',
    notifications: 'Notifiche',
    lang: 'Lingua',
    kickerWelcome: 'Benvenuto',
    kickerLogin: 'Accesso',
    kickerEntered: 'Account creato',
    kickerRappel: 'Richiamo',
    kickerCommande: 'Nuovo ordine',
    deskKicker: 'Val d’Isère · ordina online',
  },
  foot: {
    place: 'Le Labo · Route de la Balme, Val d’Isère',
    hours: 'Aperto dalle 7 alle 19',
  },
  hero: {
    welcomeTitle: 'Il tuo ordine in stazione, pronto in due minuti.',
    welcomeIntro: 'Tu scegli, noi prepariamo.',
    loginTitle: 'Bentornato.',
    loginIntroAsk: 'Inserisci la tua e-mail, ti mandiamo un link.',
    loginIntroSent: 'Il link di accesso è appena partito.',
    enteredTitle: 'Sei connesso.',
    enteredIntro:
      'Account creato senza password e senza moduli aziendali. L’ordine comincia adesso.',
    rappelTitle: 'Quando ti richiamiamo ?',
    rappelIntro: 'Chiamiamo dal laboratorio, mai da un call center.',
  },
  aside: {
    proof: [
      'Iscrizione rapida.',
      'Il tuo spazio cresce insieme alle tue esigenze.',
      'Prezzi professionali, consegna in stazione, fatturazione mensile su richiesta.',
    ],
    address: 'Le Labo · Route de la Balme — aperto dalle 7 alle 19.',
  },
  signup: {
    eyebrow: 'Prima volta ? 3 informazioni e si parte',
    alreadyLead: 'Sei già cliente ?',
    alreadyLink: 'Accedi con un link',
    pitch: 'Un nome, una e-mail, un numero. Tutto qui — il resto aspetterà che ti serva.',
    firstName: 'Nome',
    firstNamePlaceholder: 'Il tuo nome',
    tel: 'Telefono',
    telPlaceholder: '06 00 00 00 00',
    telHint: 'Perché un corriere che cerca la porta possa chiamarti.',
    email: 'E-mail',
    emailPlaceholder: 'tu@esempio.it',
    open: 'Iscriviti',
    submit: 'Crea il mio account',
    fine: 'Nessuna password : ti mandiamo un link a ogni accesso.',
    fineInline: 'Nessuna password : a ogni accesso ti arriva un link.',
    legal:
      'Creando un account accetti le nostre condizioni di vendita. All’iscrizione non chiediamo alcun documento aziendale.',
  },
  login: {
    email: 'La tua e-mail',
    emailPlaceholder: 'tu@esempio.it',
    send: 'Ricevi il mio link',
    fine: 'Nessuna password da ricordare : il link ti collega direttamente.',
    sentTitle: 'Link inviato',
    sentBody: 'Apri il messaggio inviato a {email} — il link vale un’ora.',
    simulate: 'Simula il clic sul link',
    resent: 'È appena partito un nuovo link.',
    resend: 'Rinvia',
    editEmail: 'Cambia indirizzo',
  },
  entered: {
    title: 'Account attivo',
    sub: 'Tre campi, nessun documento. La visura aspetterà che ti serva.',
    next: 'Poi : ritiro o corriere, e la bottega.',
    cta: 'Ordinare',
  },
  rappel: {
    asapGroup: 'Prima possibile',
    asapTitle: 'Entro 15 minuti',
    asapSub: 'Risponde il laboratorio — è la via più rapida.',
    todayGroup: 'Oggi',
    note: 'Tra le 12 e le 14 siamo al forno : non rispondiamo al telefono, e preferiamo dirlo.',
    phone: 'Ti richiamiamo al {phone}.',
    ctaIdle: 'Scegli un momento',
    ctaReady: 'Richiedi il richiamo',
    slotFree: 'disponibile',
    slotFull: 'esaurito',
    slotOven: 'al forno',
  },
  doors: {
    or: 'oppure',
    alreadyTitle: 'Sei già cliente ?',
    alreadySub: 'Accedi con un link',
    firstTitle: 'Prima volta ?',
    firstSub: 'Nome, e-mail, telefono',
  },
  event: {
    badge: 'Catering',
    title: 'Un evento,\npensiamo a tutto.',
    pitch:
      'Seminario, compleanno, uscita di club : il numero, l’ora, il luogo — al resto pensiamo noi.',
    cta: 'Un preventivo ›',
    pending:
      'La schermata di richiesta preventivo arriva nel prossimo lotto — la scheda è collegata, il seguito no.',
  },
  commande: {
    title: 'Buongiorno {name}.\nCome glielo serviamo ?',
    intro: 'Lei sceglie, noi prepariamo.',
    sectionsLabel: 'Sezioni',
    newOrderTitle: 'Nuovo ordine',
    newOrderSub: 'Una sola domanda per iniziare : viene lei, o veniamo noi ?',
    nowTitle: 'In questo momento',
    pickupBadge: 'Ritiro',
    pickupTitle: 'Passo io\na prenderlo',
    pickupDetail: 'Al Labo o in una delle botteghe della stazione.',
    pickupNote: 'Pronto in 20 min',
    pickupDetailWide: 'Al Labo o al villaggio, domani all’ora che scelgo io.',
    pickupCta: 'Scegliere un punto di ritiro',
    pickupNoteWide: 'Fino a −10 %',
    deliveryBadge: 'Corriere',
    deliveryTitle: 'Glielo\nportiamo noi',
    deliveryDetail: 'Domani, nella fascia oraria che sceglie lei.',
    deliveryNote: 'Ordini entro le 18',
    deliveryDetailWide: 'Domani, nella fascia che sceglie lei. Due indirizzi già salvati.',
    deliveryCta: 'Scegliere un indirizzo',
    deliveryNoteWide: 'Entro le 18',
    eventBadge: 'Natale',
    eventTitle: 'Il Natale si gioca\nal forno',
    eventDetail: 'Due tronchetti, un calendario, i papillotes.',
    eventNote: '72 h di preavviso · G-18',
    cateringBadge: 'Catering',
    cateringTitle: 'Un evento,\npensiamo a tutto',
    cateringDetail: 'Seminario, compleanno, uscita di club.',
    cateringNote: 'Risposta entro 24 h',
    browseTitle: 'Visito la bottega',
    browseSub: 'Per vedere i prodotti e decidere dopo',
    againTitle: 'Come sabato scorso ?',
    againSub: '2 traditions, 4 croissant, 1 ski al pralinato · ritiro al Labo',
    againAction: 'Rifare',
    againLead: 'Oppure riprenda',
    urgenceTitle: 'Un’urgenza, un’aggiunta ?',
    urgencePitch:
      'Una dimenticanza su un ordine in corso, una sfornata da allungare : si risolve al telefono. Diciamo di no di rado.',
    urgenceCta: 'Farsi richiamare',
    pending:
      'Il seguito del percorso arriva nel prossimo lotto — la scheda è collegata, la sua schermata no.',
  },
  dialog: {
    close: 'Chiudere',
  },
  pickupDialog: {
    kicker: 'Ritiro',
    title: 'Dove passa a prenderlo ?',
    lead: 'Ci fa piacere riceverla : ritiri al Labo e approfitti di uno sconto del {pct} % sull’ordine.',
    habit: 'la sua abitudine',
    readyFrom: 'Pronto dalle {time}',
    discountTag: '−{pct} % su tutto',
    shopPrice: 'Prezzo bottega',
    cta: 'Scegliere l’ora',
    ctaDiscount: 'Scegliere l’ora · −{pct} %',
  },
  addressDialog: {
    kicker: 'Corriere',
    title: 'Dove consegniamo ?',
    bookGroup: 'I suoi indirizzi',
    defaultTag: 'Predefinito',
    otherGroup: 'Un altro indirizzo',
    street: 'Via',
    streetPlaceholder: '12 rue du Coin Ferrand',
    postcode: 'Codice postale',
    postcodePlaceholder: '73150',
    city: 'Città',
    cityUnknown: 'Si deduce dal codice postale',
    outOfZone: 'Fuori zona di consegna',
    outOfZoneNote: 'Fin laggiù non scendiamo ancora. Il ritiro, invece, resta aperto.',
    whoGroup: 'Chi riceve',
    name: 'Nome',
    fromAccount: 'Account',
    phone: 'Telefono',
    edit: 'Modificare',
    whyPhone:
      'Precompilato dal suo account — il corriere chiama questo numero se non trova la porta.',
    saveToBook: 'Salvare questo indirizzo in rubrica',
    saveOn: 'Lo ritroveremo al prossimo ordine.',
    saveOff: 'Altrimenti serve solo per questo ordine.',
    cta: 'Scegliere la fascia · {fee} €',
    ctaBlocked: 'Scelga un indirizzo',
  },
  slotPanel: {
    pickupTitle: 'Quando passa ?',
    deliveryTitle: 'Domani, a che ora ?',
    pickupIntro: 'Da ritirare {place}. La fascia le tiene la sfornata.',
    deliveryIntro: 'Consegnato {place}. Il corriere parte all’apertura della fascia.',
    amGroup: 'Mattina · appena sfornato',
    pmGroup: 'Après-ski · seconda sfornata',
    firstBatch: 'appena sfornato',
    free: 'disponibile',
    full: 'al completo',
    secondBatch: 'seconda sfornata',
    laboOnly: 'Solo al Labo',
    ctaIdle: 'Scelga una fascia',
    cta: 'Tenere {slot}',
  },
  pro: {
    title: 'Ti interessa lo spazio professionale ?',
    bookedTitle: 'Richiamo richiesto',
    pitch:
      'Prezzi concordati, consegna in stazione, fatturazione mensile. Te lo spieghiamo in due minuti.',
    cta: 'Chiedi di essere richiamato',
    booked: 'Richiamo richiesto · {slot}',
    at: 'Al',
    cancel: 'Annulla',
  },
};
