import type { ClientCopy } from './client-copy.model';

/**
 * Italien. Val d'Isère est frontalière : la clientèle italienne n'est pas un
 * public de passage, c'est un public de saison.
 *
 * Deux partis pris de traduction : « fournil » devient *laboratorio* (le lieu,
 * pas le métier — c'est ainsi que la boutique se nomme, « Le Labo »), et
 * « coursier » devient *corriere*, qui dit la livraison en station sans laisser
 * croire à une messagerie.
 */
export const IT: ClientCopy = {
  chrome: {
    back: 'Indietro',
    menu: 'Menu',
    notifications: 'Notifiche',
    lang: 'Lingua',
    kickerWelcome: 'Benvenuto',
    kickerRappel: 'Richiamo',
    kickerCommande: 'Nuovo ordine',
    kickerShop: 'Bottega',
    kickerCart: 'Il carrello',
    kickerDone: 'Confermato',
    deskKicker: 'Val d’Isère · ordina online',
  },
  foot: {
    tagline: 'Panificio d’alta quota',
    pitch:
      'Pane a lievitazione naturale, viennoiserie al burro AOP e pasticceria di stazione, cotti ogni notte al Labo, route de la Balme. Consegnati in stazione prima dell’apertura degli impianti.',
    housesHead: 'Le case',
    houses: [
      {
        name: 'Le Labo',
        street: 'Route de la Balme',
        city: '73150 Val d’Isère',
        hours: '7 – 19, tutti i giorni',
      },
      {
        name: 'Le Village',
        street: '4 avenue Olympique',
        city: '73150 Val d’Isère',
        hours: '9 – 20, tutti i giorni',
      },
    ],
    orderHead: 'Ordinare',
    orderLinks: [
      'Ritiro al Labo o al Village',
      'Corriere in stazione',
      'Catering ed eventi',
      'Aprire un account pro',
      'I nostri banchi e i nostri metodi',
      'Operazioni Pasqua e Natale',
    ],
    helpHead: 'Aiuto e contatti',
    phoneHours: '7 – 19 · aggiunte fino alle 18',
    helpLinks: [
      'Fissare un appuntamento',
      'Seguire il mio ordine',
      'Domande frequenti',
      'Segnalare un problema',
    ],
    legalPay: 'Pagamento sicuro con carta e Apple Pay, bonifico per gli account pro.',
    legalVat: 'Prezzi IVA inclusa, 5,5 % o 10 % secondo i prodotti.',
    legalLinks: ['Note legali', 'Condizioni', 'Privacy', 'Cookie', 'Accessibilità'],
  },
  nav: {
    destinations: {
      espace: 'Il mio spazio',
      orders: 'Ordini',
      invoices: 'Fatture',
      baskets: 'Carrelli ricorrenti',
      account: 'Il mio account',
    },
    invoicesDue: '{n} da saldare',
    basketsCount: '{n} modelli',
    cart: 'Il mio carrello',
    soon: 'Presto',
    close: 'Chiudi il menu',
    newOrder: 'Nuovo ordine',
    newOrderSub: 'Ritiro o corriere, scegliete voi',
    house: 'La casa',
    houseLinks: [
      ['I nostri banchi e i nostri metodi', '6 schede'],
      ['Le Labo — orari e accesso', 'Aperto'],
      ['Un imprevisto, un’aggiunta?', 'Chiamaci'],
    ],
    logout: 'Esci',
    address: 'Le Labo · route de la Balme, Val d’Isère — 7 – 19',
    hello: 'Ciao {name}.',
    helloAnonymous: 'Ciao.',
  },
  espace: {
    today: ['Una cosa oggi.', 'Due cose oggi.', 'Tre cose oggi.'],
    todayNone: 'Non c’è nulla in sospeso.',
    lead: 'Ciò che richiede un’azione, e nient’altro.',
    leadNone: 'Tutto a posto. Si ricomincia quando volete.',
    eventCta: 'Vedere la collezione ›',
    wellTitle: 'Pronto per voi',
    wellNote: '— ciò che richiede un’azione, e nient’altro.',
    pickupTitle: 'Ritirare il mio ordine',
    pickupRef: 'Ordine {ref}',
    pickupWhen: 'Pronto {at}, dalle {slot}',
    pickupAction: 'Il mio QR',
    cartTitle: 'Carrello in attesa',
    cartBadge: 'Entro le 18',
    cartWhen: 'Iniziato ieri sera',
    cartAction: 'Concludere',
    invoiceTitle: 'Fattura di marzo',
    invoiceDue: 'Scadenza il 15 aprile',
    invoiceAction: 'Saldare',
    contactKicker: 'Rispondiamo',
    contactTitle: 'Una domanda,\nun imprevisto?',
    contactWho:
      'Camille e Malik, al Labo, dalle 7 alle 19. Un’aggiunta passa ancora per telefono fino alle 18.',
    call: 'Chiamare',
    write: 'Scrivere',
    habitsHead: 'Le vostre abitudini',
    proHead: 'Il vostro account pro',
    proDiscount: 'Sconto ritiro al Labo',
    proMonth: 'Esposizione del mese',
    proKbis: 'Verifica KBIS',
    proKbisState: 'In corso',
  },
  hero: {
    welcomeTitle: 'Il tuo ordine in stazione, pronto in due minuti.',
    welcomeIntro: 'Tu scegli, noi prepariamo.',
    rappelTitle: 'Quando ti richiamiamo ?',
    rappelIntro: 'Chiamiamo dal laboratorio, mai da un call center.',
  },
  aside: {
    proof: [
      'Iscrizione rapida.',
      'Il tuo spazio cresce insieme alle tue esigenze.',
      'Prezzi professionali, consegna in stazione, fatturazione mensile su richiesta.',
    ],
    address: 'Le Labo · Route de la Balme — aperto dalle 7 alle 19.',
  },
  signup: {
    eyebrow: 'Prima volta ? 3 informazioni e si parte',
    alreadyLead: 'Sei già cliente ?',
    alreadyLink: 'Accedere',
    pitch: 'Un nome, una e-mail, un numero. Tutto qui — il resto aspetterà che ti serva.',
    firstName: 'Nome',
    firstNamePlaceholder: 'Il tuo nome',
    tel: 'Telefono',
    telPlaceholder: '06 00 00 00 00',
    telHint: 'Perché un corriere che cerca la porta possa chiamarti.',
    email: 'E-mail',
    emailPlaceholder: 'tu@esempio.it',
    open: 'Iscriviti',
    submit: 'Crea il mio account',
    fine: 'Una password per aprire, poi il suo dispositivo la riconosce.',
    fineInline: 'Una password per aprire, poi il suo dispositivo la riconosce.',
    legal:
      'Creando un account accetti le nostre condizioni di vendita. All’iscrizione non chiediamo alcun documento aziendale.',
  },
  rappel: {
    asapGroup: 'Prima possibile',
    asapTitle: 'Entro 15 minuti',
    asapSub: 'Risponde il laboratorio — è la via più rapida.',
    todayGroup: 'Oggi',
    note: 'Tra le 12 e le 14 siamo al forno : non rispondiamo al telefono, e preferiamo dirlo.',
    phone: 'Ti richiamiamo al {phone}.',
    phoneUnknown: 'La richiamiamo al numero del suo account.',
    ctaIdle: 'Scegli un momento',
    ctaReady: 'Richiedi il richiamo',
    slotFree: 'disponibile',
    slotFull: 'esaurito',
    slotOven: 'al forno',
  },
  doors: {
    or: 'oppure',
    alreadyTitle: 'Sei già cliente ?',
    alreadySub: 'Password, o il suo dispositivo',
    firstTitle: 'Prima volta ?',
    firstSub: 'Nome, e-mail, telefono',
  },
  event: {
    badge: 'Catering',
    title: 'Un evento,\npensiamo a tutto.',
    pitch:
      'Seminario, compleanno, uscita di club : il numero, l’ora, il luogo — al resto pensiamo noi.',
    cta: 'Un preventivo ›',
    pending:
      'La schermata di richiesta preventivo arriva nel prossimo lotto — la scheda è collegata, il seguito no.',
  },
  commande: {
    title: 'Buongiorno {name}.\nCome glielo serviamo ?',
    titleAnonymous: 'Buongiorno.\nCome la serviamo?',
    intro: 'Lei sceglie, noi prepariamo.',
    sectionsLabel: 'Sezioni',
    newOrderTitle: 'Nuovo ordine',
    newOrderSub: 'Una sola domanda per iniziare : viene lei, o veniamo noi ?',
    nowTitle: 'In questo momento',
    pickupBadge: 'Ritiro',
    pickupTitle: 'Passo io\na prenderlo',
    pickupDetail: 'Al Labo o in una delle botteghe della stazione.',
    pickupNote: 'Domani dalle 6',
    pickupDetailWide: 'Al Labo o al villaggio, domani all’ora che scelgo io.',
    pickupCta: 'Scegliere un punto di ritiro',
    pickupNoteWide: 'Fino a −10 %',
    deliveryBadge: 'Corriere',
    deliveryTitle: 'Glielo\nportiamo noi',
    deliveryDetail: 'Domani, nella fascia oraria che sceglie lei.',
    deliveryNote: 'Ordini entro le 18',
    deliveryDetailWide: 'Domani, nella fascia che sceglie lei. Due indirizzi già salvati.',
    deliveryCta: 'Scegliere un indirizzo',
    deliveryNoteWide: 'Entro le 18',
    eventBadge: 'Natale',
    eventTitle: 'Il Natale si gioca\nal forno',
    eventDetail: 'Due tronchetti, un calendario, i papillotes.',
    eventNote: '72 h di preavviso · G-18',
    cateringBadge: 'Catering',
    cateringTitle: 'Un evento,\npensiamo a tutto',
    cateringDetail: 'Seminario, compleanno, uscita di club.',
    cateringNote: 'Risposta entro 24 h',
    browseTitle: 'Visito la bottega',
    browseSub: 'Per vedere i prodotti e decidere dopo',
    againTitle: 'Come sabato scorso ?',
    againSub: '2 traditions, 4 croissant, 1 ski al pralinato · ritiro al Labo',
    againAction: 'Rifare',
    againLead: 'Oppure riprenda',
    urgenceTitle: 'Un’urgenza, un’aggiunta ?',
    urgencePitch:
      'Una dimenticanza su un ordine in corso, una sfornata da allungare : si risolve al telefono. Diciamo di no di rado.',
    urgenceCta: 'Farsi richiamare',
    pending:
      'Il seguito del percorso arriva nel prossimo lotto — la scheda è collegata, la sua schermata no.',
  },
  shop: {
    changeService: 'Cambia',
    pickService: 'Dove viene servito?',
    pickServiceHint: 'Prezzo e orario dipendono da questo — lo dica prima di pagare.',
    searchPlaceholder: 'Cerca una baguette, un éclair…',
    clearSearch: 'Cancella la ricerca',
    allShelves: 'Tutto',
    allShelvesTitle: 'Tutto il banco',
    resultsFor: 'Risultati per « {query} »',
    pieces: '{count} pezzi',
    learnMore: 'Scopri di più',
    emptyTitle: 'Niente con questo nome.',
    emptyHint: 'Provi « pane », « torta », o tocchi un reparto.',
    shelvesGroup: 'I reparti',
    add: 'Aggiungi',
    addAria: 'Aggiungi {name}',
    removeAria: 'Togli {name}',
    cartBar: '{count} pezzi nel carrello',
    cartTitle: 'Il suo carrello',
    cartEmpty:
      'Carrello vuoto. L’infornata del mattino va via in fretta — lo sci al pralinato non arriva mai al pomeriggio.',
    upsell: '{name} insieme?',
    upsellLine: 'La golosità che si rimpiange di non aver preso.',
  },
  product: {
    signature: 'Firma',
    unitPrice: 'Prezzo unitario',
    oven: 'Uscita dal forno',
    pickupAt: 'Da ritirare',
    deliverTo: 'Consegnato',
    cta: 'Nel carrello · {price}',
  },
  cart: {
    kicker: 'Il carrello',
    title: 'Il suo ordine',
    intro: 'Rilegga, corregga, paghi. L’infornata segue la sua fascia oraria.',
    pickupGroup: 'Da ritirare',
    deliveryGroup: 'Da consegnare',
    slotNote: 'domani · fascia scelta',
    subtotal: 'Subtotale',
    discount: 'Sconto ritiro {at} −{pct} %',
    fee: 'Corriere',
    vat: 'di cui IVA {rate}',
    vatSweet: 'pane, viennoiseria, pasticceria',
    vatSale: 'salato, gastronomia',
    total: 'Totale',
    pay: 'Pago il mio ordine · {total}',
    payHint: 'Pagamento online. Mostri il QR al banco, non deve saldare nulla sul posto.',
    browse: 'Vedi il banco',
    back: 'Torna alla bottega',
  },
  done: {
    kicker: 'Confermato',
    title: 'È pagato.\nSi comincia alle 4.15.',
    intro: 'Il suo ordine entra nell’infornata di domani mattina.',
    mailTitle: 'Ricevuta inviata per e-mail',
    mailLine: 'A {email} — la fattura e il QR di ritiro sono lì dentro.',
    mailLineNoAddress:
      'All’indirizzo del suo account — la fattura e il QR di ritiro sono lì dentro.',
    recapPickup: 'Ritiro',
    recapDelivery: 'Consegna',
    recapContent: 'Contenuto',
    recapPieces: '{count} pezzi',
    paidOnline: 'Pagato online',
    qr: 'Vedi il mio QR di ritiro',
    edit: 'Modifica',
    cancel: 'Annulla',
    deadline: 'Modificabile fino alle 22 — rimborso immediato. Dopo, la pasta è impastata.',
    pending: 'Questa schermata arriva col prossimo lotto.',
  },
  dialog: {
    close: 'Chiudere',
  },
  pickupDialog: {
    kicker: 'Ritiro',
    title: 'Dove passa a prenderlo ?',
    lead: 'Ci fa piacere riceverla : ritiri al Labo e approfitti di uno sconto del {pct} % sull’ordine.',
    habit: 'la sua abitudine',
    readyFrom: 'Pronto dalle {time}',
    discountTag: '−{pct} % su tutto',
    shopPrice: 'Prezzo bottega',
    cta: 'Scegliere l’ora',
    ctaDiscount: 'Scegliere l’ora · −{pct} %',
  },
  addressDialog: {
    kicker: 'Corriere',
    title: 'Dove consegniamo ?',
    bookGroup: 'I suoi indirizzi',
    defaultTag: 'Predefinito',
    otherGroup: 'Un altro indirizzo',
    street: 'Via',
    streetPlaceholder: '12 rue du Coin Ferrand',
    postcode: 'Codice postale',
    postcodePlaceholder: '73150',
    city: 'Città',
    cityUnknown: 'Si deduce dal codice postale',
    outOfZone: 'Fuori zona di consegna',
    outOfZoneNote: 'Fin laggiù non scendiamo ancora. Il ritiro, invece, resta aperto.',
    whoGroup: 'Chi riceve',
    name: 'Nome',
    fromAccount: 'Account',
    phone: 'Telefono',
    edit: 'Modificare',
    whyPhone:
      'Precompilato dal suo account — il corriere chiama questo numero se non trova la porta.',
    saveToBook: 'Salvare questo indirizzo in rubrica',
    saveOn: 'Lo ritroveremo al prossimo ordine.',
    saveOff: 'Altrimenti serve solo per questo ordine.',
    cta: 'Scegliere la fascia · {fee} €',
    ctaBlocked: 'Scelga un indirizzo',
  },
  slotStep: {
    pickupIntro: 'Da ritirare {place}. La fascia le tiene la sfornata.',
    deliveryIntro: 'Consegnato {place}. Il corriere parte all’apertura della fascia.',
    amGroup: 'Mattina · appena sfornato',
    pmGroup: 'Après-ski · seconda sfornata',
    firstBatch: 'appena sfornato',
    free: 'disponibile',
    full: 'al completo',
    secondBatch: 'seconda sfornata',
    laboOnly: 'Solo al Labo',
    ctaIdle: 'Scelga una fascia',
    cta: 'Riempire il carrello',
  },
  pro: {
    title: 'Ti interessa lo spazio professionale ?',
    bookedTitle: 'Richiamo richiesto',
    pitch:
      'Prezzi concordati, consegna in stazione, fatturazione mensile. Te lo spieghiamo in due minuti.',
    cta: 'Chiedi di essere richiamato',
    booked: 'Richiamo richiesto · {slot}',
    at: 'Al',
    cancel: 'Annulla',
  },
};
