
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  SkuRegistry: 'SkuRegistry',
  Category: 'Category',
  TvaRegime: 'TvaRegime',
  Emplacement: 'Emplacement',
  EmplacementTable: 'EmplacementTable',
  Product: 'Product',
  ProductVariant: 'ProductVariant',
  ShopifySettings: 'ShopifySettings',
  ShopifyProductBinding: 'ShopifyProductBinding',
  ShopifyPushSnapshot: 'ShopifyPushSnapshot',
  ShopifyVariantBinding: 'ShopifyVariantBinding',
  NutritionDeclaration: 'NutritionDeclaration',
  ProductEditorial: 'ProductEditorial',
  MediaAsset: 'MediaAsset',
  ProductMedia: 'ProductMedia',
  B2bChannelBinding: 'B2bChannelBinding'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const SkuRegistryScalarFieldEnum = {
  value: 'value',
  ownerType: 'ownerType',
  ownerId: 'ownerId'
} as const

export type SkuRegistryScalarFieldEnum = (typeof SkuRegistryScalarFieldEnum)[keyof typeof SkuRegistryScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  parentId: 'parentId',
  position: 'position',
  isArchived: 'isArchived',
  channelPreset: 'channelPreset',
  emporterTvaId: 'emporterTvaId',
  surPlaceTvaId: 'surPlaceTvaId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const TvaRegimeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  percent: 'percent',
  tag: 'tag',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TvaRegimeScalarFieldEnum = (typeof TvaRegimeScalarFieldEnum)[keyof typeof TvaRegimeScalarFieldEnum]


export const EmplacementScalarFieldEnum = {
  id: 'id',
  name: 'name',
  clickCollect: 'clickCollect',
  surPlace: 'surPlace',
  baseUrl: 'baseUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EmplacementScalarFieldEnum = (typeof EmplacementScalarFieldEnum)[keyof typeof EmplacementScalarFieldEnum]


export const EmplacementTableScalarFieldEnum = {
  emplacementId: 'emplacementId',
  number: 'number',
  qrCreated: 'qrCreated',
  token: 'token'
} as const

export type EmplacementTableScalarFieldEnum = (typeof EmplacementTableScalarFieldEnum)[keyof typeof EmplacementTableScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  sku: 'sku',
  slug: 'slug',
  kind: 'kind',
  name: 'name',
  categoryId: 'categoryId',
  status: 'status',
  attributes: 'attributes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const ProductVariantScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  sku: 'sku',
  name: 'name',
  options: 'options',
  isDefault: 'isDefault',
  isDiscontinued: 'isDiscontinued',
  position: 'position',
  attributes: 'attributes',
  priceCents: 'priceCents',
  weightGrams: 'weightGrams',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  updatedBy: 'updatedBy'
} as const

export type ProductVariantScalarFieldEnum = (typeof ProductVariantScalarFieldEnum)[keyof typeof ProductVariantScalarFieldEnum]


export const ShopifySettingsScalarFieldEnum = {
  id: 'id',
  shopDomain: 'shopDomain',
  apiVersion: 'apiVersion',
  isEnabled: 'isEnabled',
  updatedAt: 'updatedAt'
} as const

export type ShopifySettingsScalarFieldEnum = (typeof ShopifySettingsScalarFieldEnum)[keyof typeof ShopifySettingsScalarFieldEnum]


export const ShopifyProductBindingScalarFieldEnum = {
  productId: 'productId',
  shopifyProductGid: 'shopifyProductGid',
  lastPushedHash: 'lastPushedHash',
  lastPushedAt: 'lastPushedAt',
  syncStatus: 'syncStatus',
  lastError: 'lastError',
  headSnapshotId: 'headSnapshotId'
} as const

export type ShopifyProductBindingScalarFieldEnum = (typeof ShopifyProductBindingScalarFieldEnum)[keyof typeof ShopifyProductBindingScalarFieldEnum]


export const ShopifyPushSnapshotScalarFieldEnum = {
  id: 'id',
  handle: 'handle',
  productId: 'productId',
  version: 'version',
  hash: 'hash',
  payload: 'payload',
  mode: 'mode',
  outcome: 'outcome',
  pushedAt: 'pushedAt'
} as const

export type ShopifyPushSnapshotScalarFieldEnum = (typeof ShopifyPushSnapshotScalarFieldEnum)[keyof typeof ShopifyPushSnapshotScalarFieldEnum]


export const ShopifyVariantBindingScalarFieldEnum = {
  variantId: 'variantId',
  channelReference: 'channelReference',
  shopifyVariantGid: 'shopifyVariantGid'
} as const

export type ShopifyVariantBindingScalarFieldEnum = (typeof ShopifyVariantBindingScalarFieldEnum)[keyof typeof ShopifyVariantBindingScalarFieldEnum]


export const NutritionDeclarationScalarFieldEnum = {
  variantId: 'variantId',
  allergens: 'allergens',
  mayContain: 'mayContain',
  energyKcal: 'energyKcal',
  carbsG: 'carbsG',
  fatG: 'fatG',
  proteinG: 'proteinG',
  glycemicIndex: 'glycemicIndex',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NutritionDeclarationScalarFieldEnum = (typeof NutritionDeclarationScalarFieldEnum)[keyof typeof NutritionDeclarationScalarFieldEnum]


export const ProductEditorialScalarFieldEnum = {
  productId: 'productId',
  descriptionShort: 'descriptionShort',
  descriptionLong: 'descriptionLong',
  story: 'story',
  pairing: 'pairing',
  brand: 'brand',
  seoTitle: 'seoTitle',
  seoDescription: 'seoDescription',
  updatedAt: 'updatedAt'
} as const

export type ProductEditorialScalarFieldEnum = (typeof ProductEditorialScalarFieldEnum)[keyof typeof ProductEditorialScalarFieldEnum]


export const MediaAssetScalarFieldEnum = {
  id: 'id',
  url: 'url',
  alt: 'alt',
  focalX: 'focalX',
  focalY: 'focalY',
  createdAt: 'createdAt'
} as const

export type MediaAssetScalarFieldEnum = (typeof MediaAssetScalarFieldEnum)[keyof typeof MediaAssetScalarFieldEnum]


export const ProductMediaScalarFieldEnum = {
  productId: 'productId',
  mediaId: 'mediaId',
  role: 'role',
  position: 'position'
} as const

export type ProductMediaScalarFieldEnum = (typeof ProductMediaScalarFieldEnum)[keyof typeof ProductMediaScalarFieldEnum]


export const B2bChannelBindingScalarFieldEnum = {
  productId: 'productId',
  publishedAt: 'publishedAt',
  publishedBy: 'publishedBy',
  lastPushedAt: 'lastPushedAt'
} as const

export type B2bChannelBindingScalarFieldEnum = (typeof B2bChannelBindingScalarFieldEnum)[keyof typeof B2bChannelBindingScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

